### ISSUE TITLE
All good working, my wallet 0x45d5a2b6c9578aEFbb1A9b9CA1AEC05b18a9577b

### ISSUE THREAD

**Issue by qqcomposernet** [taikoxyz/taiko-mono#10261]
### Discussed in https://github.com/orgs/taikoxyz/discussions/335

<div type='discussions-op-text'>

<sup>Originally posted by **d1onys1us** November 24, 2022</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by cyberhorsey** [comment]
Thanks!
