### ISSUE TITLE
fix: TRANSACTION IS IN PENDING 

### ISSUE THREAD

**Issue by qwardit** [taikoxyz/taiko-mono#10800]
### Describe the bug

I had tried to transfer my ETH from Ethereum A1 to Taiko A1 but the money is stuck.

### Steps to reproduce

1. Do bridge $ETH from Ethereum A1 to Taiko A1
2. Click on the "claim" button 

### Additional context

<img width="1440" alt="Screenshot 2023-01-06 at 02 39 43" src="https://user-images.githubusercontent.com/111157197/210906374-75a4b896-3801-423c-ac74-d3df72358c21.png">

**Comment by cyberhorsey** [comment]
@qwardit Taiko network was slow this day as we had a very large transaction count. Should be claimable, sorry for the issue.
