### ISSUE TITLE
fix(bridge): max amount leads to insufficient gas

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#11147]
### Describe the bug

When choosing the max to bridge I get an error message `insuffienct funds for gas` where I then would have to manually deduct the gas needed. Ideally the bridge would automatically deduct the gas needed from the amount, as close as possible.

![image](https://user-images.githubusercontent.com/60930264/211023103-b88b0776-2e6a-4a85-ad4e-b0134809bdcc.png)

### Steps to reproduce

Go to the bridge and click max.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
@shadab-taiko this should be a good one to work on as priority. Can make add a "estimateGas" option in the domain bridge opts and if it's true, don't send the tx but just estimate the gas instead. And we can subtract that amount from the Max balance when button clicked.
