### ISSUE TITLE
fix(bridge): clearing cache removes all transactions

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#11184]
### Describe the bug

After clearing cookies/cache all transactions are removed, even after connecting again.

### Steps to reproduce

1. connect to bridge
2. make transaction(s)
3. clear cookies/cache
4. connect again

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
For testnet transactions are only stored in local storage. For next testnet they will be pulled from blockchain state.
