### ISSUE TITLE
fix: POAP bot not working on other repositories

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#11631]
### Describe the bug

The current POAP bot only works on taiko-mono and not yet on [simple-taiko-node](https://github.com/taikoxyz/simple-taiko-node)
cc: @d1onys1us 

### Steps to reproduce

[Example](https://github.com/taikoxyz/simple-taiko-node/pull/27)

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
Good catch, simple-taiko-node has been added now.

**Comment by wolfderechter** [comment]
Making the POAP bot leave comments on other taiko repositories is currently missing afaik @d1onys1us 
[example bot comment
](https://github.com/taikoxyz/taiko-mono/pull/12557#issuecomment-1378179159)
[example missing bot comment](https://github.com/taikoxyz/simple-taiko-node/pull/28)

**Comment by d1onys1us** [comment]
> Making the POAP bot leave comments on other taiko repositories is currently missing afaik @d1onys1us [example bot comment ](https://github.com/taikoxyz/taiko-mono/pull/12557#issuecomment-1378179159) [example missing bot comment](https://github.com/taikoxyz/simple-taiko-node/pull/28)

@wolfderechter this is because initially simple-taiko-node was not added to the list for the gitpoap-bot to automatically reward the GitPOAP. that is why it posted the GitPOAP in the more recent PR, after it was added.
