### ISSUE TITLE
feat: automatically publish latest blog posts to website

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#12277]
## summary
on our website homepage we show the latest 3 blog posts. right now, this is a manual process that we have to update the homepage with the latest blog posts. it would be much better if we could automate this process.

currently, it does not look like mirror.xyz has an API. however one could probably use something like CURL or fetch, etc. to get the latest blog posts dynamically from https://mirror.xyz/labs.taiko.eth . Or use this: https://dev.mirror.xyz/GjssNdA6XK7VYynkvwDem3KYwPACSU9nDWpR5rei3hw

## acceptance criteria
- new taiko blog posts on mirror.xyz automatically update the "recent blog posts" on taiko.xyz

**Comment by Jaapiehetaapie** [comment]
Hi there, i'm able to get some of the information dynamically. However i'm not sure how to get the image from imgix (i do have an imgURI). I also can't retrieve the direct author name, but i could set up a dictonary (manualy) storing some author and then using the one corresponding with the address. Would love to hear any suggestions.

**Comment by Jaapiehetaapie** [comment]
I'm now getting the images by fetching the mirror site. But for this im using cors-anywhere.herokuapp.com, is this going to cause any problems in deployment and if so how could otherwise implement it?
