### ISSUE TITLE
feat: webset auto-refreshes the recent posts

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#12318]
### Describe the feature request

We shall use API to query the most recent N posts from the website instead of manually refreshing.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
@dantaik is this a duplicate of https://github.com/taikoxyz/taiko-mono/issues/12277 by chance? Giving it a few more days to see if community members wants to pick it up

**Comment by d1onys1us** [comment]
closing as duplicate.
