### ISSUE TITLE
chore(bridge): add comments explaining entries in .default.env

### ISSUE THREAD

**Issue by shadab-taiko** [taikoxyz/taiko-mono#12391]
Our README for bride-ui mentions some environment variables here https://github.com/taikoxyz/taiko-mono/blob/main/packages/bridge-ui/README.md#environment-variables. The same are also present in `.default.env` file (without actual values).  We should add some comments explaining why we need each of the environment variables and where they are used.

**Comment by dantaik** [comment]
@shadab-taiko could you please add more info about this PR. I'm not sure what it's about.
