### ISSUE TITLE
It's really cool that Taiko's idea is the ZK-Rollup, the equivalent of Ethereum. Taiko allows Ethereum to scale by supporting all EVM opcodes in a Layer-2 architecture that is decentralized and secure. But there are still a lot of unsolved problems and fails with transactions and errors, we need to work on it

### ISSUE THREAD

**Issue by DiForss** [taikoxyz/taiko-mono#12433]
It's really cool that Taiko's idea is the ZK-Rollup, the equivalent of Ethereum. Taiko allows Ethereum to scale by supporting all EVM opcodes in a Layer-2 architecture that is decentralized and secure. But there are still a lot of unsolved problems and fails with transactions and errors, we need to work on it 
0x76fb696413C657a9FEDc14F2d664b700440ABb18

_Originally posted by @DiForss in https://github.com/taikoxyz/taiko-mono/discussions/12432_

**Comment by d1onys1us** [comment]
Folks, please do not use GitHub issues for feedback. These should be for specific feature requests and bug reports. Thank you.
