### ISSUE TITLE
feat(status-page): add amount of nodes currently running

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#12697]
### Describe the feature request

Since geth tends to limit the amount of peers to 16, grafana can't display the amount of nodes live accurately.
Perhaps the status page can display this information, if possible? Would be cool to see

Edit: extended the feature request with proposers and provers

- [ ] Keep track of all nodes
- [ ] Keep track of proposers
- [ ] Keep track of provers

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

These stats should show the amount of currently running nodes/proposers/provers.

**Comment by davidtaikocha** [comment]
I think the approach should be very similar to L1 ethereum, however, it seems not a very simple job, looks like we need to implement and maintain a network crawler to show this number: https://ethereum.stackexchange.com/questions/198/how-many-nodes-are-there-on-the-ethereum-network

**Comment by dantaik** [comment]
This is not something we should do for now.
