### ISSUE TITLE
feat: provide developer documentation for our signal service and Bridge contracts

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#12941]
### Describe the feature request

We have documentation for users to use the Bridge, but we do not have sufficient technical documentation for dApp developers who wants to use our Bridge and the new ISignalService. @d1onys1us correct me if I'm wrong.

BTW, the IServiceSignal will be added (refactored) later this month.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by SupaDupafly2** [comment]
dddd

**Comment by d1onys1us** [comment]
finished most documentation here. added a separate issue for next sprint, which is a dapp building tutorial: https://github.com/taikoxyz/taiko-mono/issues/13148
