### ISSUE TITLE
Feedback for “❓ Get help”

### ISSUE THREAD

**Issue by 0CY0** [taikoxyz/taiko-mono#12958]
Claim will fail from Ethereum A1 to Taiko A1 sometimes.

**Comment by Vmr95** [comment]
I have the same problem

**Comment by dantaik** [comment]
I'd appreciate if you guys can share us the failed transaction IDs.

**Comment by cyberhorsey** [comment]
As testnet is down, they will be unable to report on this. Closing as stale.
