### ISSUE TITLE
Deploy rogers forkdiff to vercel

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#12963]
this would be similar to / inspired by https://op-geth.optimism.io/

**Comment by wolfderechter** [comment]
Op-geth uses [Forkdiff](https://github.com/protolambda/forkdiff) under the hood

**Comment by dantaik** [comment]
@RogerLamTd Are you still working on this? It doesn't seem to be a very challenging task!

**Comment by RogerLamTd** [comment]
> 

I've been focusing on other tasks, I can get back on this though!

**Comment by RogerLamTd** [comment]
Rudimentary one done, Dave's helping me put it up on the repo now! We can update it as we go, but it's all done manually currently.
