### ISSUE TITLE
Adapt the new Signal Service in Bridge UI/Backend

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#12960]
Now the MK proof for signals/message are stored in the SignalService address, not the Bridge contract address. We need to change the bridge relayer logics to adapt this change.

**Comment by dantaik** [comment]
This can be done once we have an alpha-2 devnet

**Comment by shadab-taiko** [comment]
Completed in https://github.com/taikoxyz/taiko-mono/pull/13170
