### ISSUE TITLE
Taiko Testnet Feedback

### ISSUE THREAD

**Issue by Formendo** [taikoxyz/taiko-mono#12972]
The testnet was fantastic to navigate but the transactions took longer time to change status from pending status.
0x87e04A9DfceC01D7cFd4Bcb0A3aAc5a695773185.

**Comment by MitchDBI** [comment]
Ethereum A1 to Taiko A1 (Metamask 0x87c83A84698282b5aFAc2168f1525d392dF4F0ed) bridge: The 0.4ETH transaction passed without significant delays or errors. Claim also passed with the first time and without errors.
Taiko A1 to Ethereum A1 bridge (Metamask 0x87c83A84698282b5aFAc2168f1525d392dF4F0ed): transaction 0.4ETH showed up as "pending" for a very long time
Transfer from 0x87c83A84698282b5aFAc2168f1525d392dF4F0ed to 0x8399cA7ff6F69E784fD9BAaF462652966c671474 in Taiko A1 network: 0.4ETH was sent, transaction passed without significant delays and no errors, funds were received within about 1 minute. 
The testnet was fantastic to navigate but the transactions took longer time to change status from pending status.
