### ISSUE TITLE
fix: LibBridge... should be contracts and not libraries

### ISSUE THREAD

**Issue by bxmmm1** [taikoxyz/taiko-mono#13007]
### Describe the bug

Rethink the design of Bridge and Library contracts.

With the current design, there are some issues:
1.  Libs are supposed to be used by various smart contracts deployed on the chain, and these functionalities are bridge specific, no other contracts will ever use them.
2. (Bug) Currently libs arent emitting events, for example: `retryMessage`, `processMessage` should emit events
3. In this example we have a lib that is emitting an event, but the code is not clean (see file`LibBridgeData.sol`)
```
// Note: These events must match the ones defined in Bridge.sol.
event MessageSent(bytes32 indexed msgHash, IBridge.Message message);
```

Possible solution:
- Add events to IBridge
- Create BridgeBase.sol and add `state` as an internal variable
- Change libs to contracts with internal functions
- `Bridge.sol` is inheriting functionality and emitting appropriate events, calling internal functions from BridgeData.sol... etc..

**Comment by dantaik** [comment]
The bridge contract code are split into multiple libraries to get around the code-too-large error. This is the best solution we have found. You can test your ideas to see if the code can still be deployable, if so, we will consider your approach.
