### ISSUE TITLE
The problem with the officially stated specifications for running a node.

### ISSUE THREAD

**Issue by igorizuchaetcrypty** [taikoxyz/taiko-mono#13026]
### Describe the bug

There is a common problem that many people encounter when installing a node.

This problem is caused by the fact that the declared specifications are not enough to synchronize the node. Namely 2 CPU 4 RAM 50 MEMORY.

Node just crashes and stops working. Many people have written about this problem in chat.

### Steps to reproduce

To solve the problem people need to move the node at the time of synchronization to 3 CPU 5 RAM 5 MEMORY. With these specifications everything works fine.

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
Thanks for submitting the issue, we've already seen some feedbacks from the community that a VPS with 2 CPU 4 Gb Memory sometime can not work well, as our chain head is still increasing. Since our alpha-1 testnet will be deprecated in Feb 15th. We will update the hardware requirement in our next testnet node's documentation :)

**Comment by igorizuchaetcrypty** [comment]
Does finding this bug count as a GitHub contribution? Can I get a role in discord? igorizuchaetcrypty#2322
________________________________
От: David ***@***.***>
Отправлено: 13 февраля 2023 г. 12:11
Кому: taikoxyz/taiko-mono ***@***.***>
Копия: igorizuchaetcrypty ***@***.***>; Author ***@***.***>
Тема: Re: [taikoxyz/taiko-mono] The problem with the officially stated specifications for running a node. (Issue #13026)


Thanks for submitting the issue, we've already seen some feedbacks from the community that a VPS with 2 CPU 4 Gb Memory sometime can not work well, as our chain head is still increasing. Since our alpha-1 testnet will be deprecated in Feb 15th. We will update the hardware requirement in our next testnet node's documentation :)

**Comment by davidtaikocha** [comment]
I think according to the rule in https://www.gitpoap.io/ , to become a Github contributor, u need to contribute some actual code in this `taiko-mono` repo :)

**Comment by igorizuchaetcrypty** [comment]
Not all current contributors wrote actual code. There are enough of those guys who just described bugs in the testnet or on the website. There are plenty of examples, such as this: 

https://github.com/taikoxyz/taiko-mono/issues/13095

All the same, I also looked into Node where there is actual code to detect this problem and offered solutions to users in chats, which helped a lot.

**Comment by davidtaikocha** [comment]
emm OK i believe @d1onys1us can give a more accurate answer about the GitHub contribution :) since i'm not involved a lot in gitpoap / discord role related things.
