### ISSUE TITLE
fix: workflow runs / autorelease bot on forks 

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#13037]
### Describe the bug

There are now workflow runs and the autorelease bot active on forks of taiko-mono. Is this expected behaviour?

[example release pr](https://github.com/wolfderechter/taiko-mono/pull/1)
![image](https://user-images.githubusercontent.com/60930264/214273785-1239fba1-716e-4426-b651-3da2155f9deb.png)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by kshyun28** [comment]
Hello, is this still a valid issue? (was looking at the list of good first issues).

I have recently forked the repo and GitHub Actions is auto-disabled on forks it seems.
![GitHub Actions on forking](https://github.com/taikoxyz/taiko-mono/assets/56709653/c7def72c-7625-461d-8da7-88a66d7d25b6)

**Comment by wolfderechter** [comment]
Thanks for letting me now, will close in that case

**Comment by kshyun28** [comment]
Just a heads up. 

For some reason, when I synced my fork to the latest version on main, GitHub workflows were running. 
![Workflow runs](https://github.com/taikoxyz/taiko-mono/assets/56709653/37fe55b2-c567-4468-a342-8d2ba8831e39)

Fix would be to manually [disable workflows](https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow).
![Disabled workflow](https://github.com/taikoxyz/taiko-mono/assets/56709653/d97aba25-a1f6-45b9-a190-94022c9da1be)

**Comment by Lukay-gsm22** [comment]
The way the site intergration process is mapped isn't user friendly I followed Taiko on Twitter and it didn't redirect as expected once a task is completed which is a huge concern
