### ISSUE TITLE
Lots of transaction out are occurring!

### ISSUE THREAD

**Issue by nekokoban-kasoutuu** [taikoxyz/taiko-mono#13038]
### Describe the bug

Yesterday, I activated taiko node anew. It was fine during the testnet period, but I experienced a lot of transaction errors.
like this.
https://l1explorer.a1.taiko.xyz/tx/0xf106733e554d0811a2c67b26252a3b7a043ee6624afb1c85d939b7f7111c257a

I am looking at the logs on linux and there do not seem to be any glaring errors.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
that's normal if you are running as a proposer, lots of proposers are competing limited available L2 block slots, not all of them can propose successfully each time, so those execution reverted errors are expected, and if you read your proposer image's log, there should be some corresponding `L1:tooMany` errors.

**Comment by nekokoban-kasoutuu** [comment]
ah, yeah, I found it.

ERROR[01-24|12:48:58.655] Proposing operation error                error="failed to propose transactions: execution reverted: L1:tooMany"

Some of  my friends said the same thing, so I did a report. Sorry for asking such a simple question.
