### ISSUE TITLE
fix: Transaction status not updated

### ISSUE THREAD

**Issue by cmiller008** [taikoxyz/taiko-mono#13033]
### Describe the bug

Transaction has successfully completed but still showing as pending
![Screen Shot 2023-01-24 at 6 38 39 pm](https://user-images.githubusercontent.com/122761046/214236261-aa890896-7a8e-4f28-94f5-7bd51ca8f4b7.png)
https://l2explorer.a1.taiko.xyz/tx/0xb7a8cab06c0de90fd3c53b24cfd6777757c015eea0f1e228bce250de1ed09917

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
It takes time for L2 => L1 transfers, not instant like L1 => L2. This testnet is now closed, I am closing this issue.
