### ISSUE TITLE
fix: claim error with bridge

### ISSUE THREAD

**Issue by PH2026** [taikoxyz/taiko-mono#13040]
### Describe the bug

message error with a claim transaction for 2 eth, all transactions are well passes.

### Steps to reproduce

Steps to reproduce here. five trying, same result.

### Additional context

Additional context here.
<img width="1480" alt="Capture d’écran 2023-01-24 à 21 50 35" src="https://user-images.githubusercontent.com/107720748/214410718-44dd9904-f6db-47cf-b491-9eae113b6491.png">

**Comment by dantaik** [comment]
@shadab-taiko please take a look at this as well.

**Comment by shadab-taiko** [comment]
Hi @PH2026 could you please share the wallet address for which this failure occured?

**Comment by PH2026** [comment]
Hi, its ok now.i will continue thé testnet.
Thanks
Best

Le jeu. 2 févr. 2023, 14:42, shadab-taiko ***@***.***> a
écrit :
