### ISSUE TITLE
feat(protocol): Change require strings to custom errors

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#13057]
### Describe the feature request

Custom Errors are significantly lower on gas and bytes, and would reduce the size and gas costs of our deployments and contract calls by quite a bit.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
@dantaik do you agree?

**Comment by dantaik** [comment]
[This PR](https://github.com/taikoxyz/taiko-mono/pull/13086) is the first one to use custom errors. We need another one for Bridge related contracts. @RogerLamTd could you please review the first PR and continue with the second oen?

**Comment by dantaik** [comment]
> [This PR](https://github.com/taikoxyz/taiko-mono/pull/13086) is the first one to use custom errors. We need another one for Bridge related contracts. @RogerLamTd could you please review the first PR and continue with the second oen?

The bridge part is also done in my PR.

**Comment by dantaik** [comment]
@cyberhorsey ,with [this PR](https://github.com/taikoxyz/taiko-mono/pull/13143), maybe we can quickly change all string-based errors to custom errors.

**Comment by dantaik** [comment]
With https://github.com/taikoxyz/taiko-mono/pull/13146, the outstanding work is changing Bridge contracts to use custom errors.

**Comment by dantaik** [comment]
Update: now only the bridge related files have string-based error messages.
