### ISSUE TITLE
A new occasional `test:integration` error

### ISSUE THREAD

**Issue by davidtaikocha** [taikoxyz/taiko-mono#13055]
link: https://github.com/taikoxyz/taiko-mono/actions/runs/4006544300/jobs/6878203013

**Comment by dantaik** [comment]
@davidtaikocha do you still see such errors?

**Comment by davidtaikocha** [comment]
dont see such errors these days, but im not sure if this is investigated and got fixed? or just close this issue and re-open it when we see these errors in action again?

**Comment by davidtaikocha** [comment]
newly observed: https://github.com/taikoxyz/taiko-mono/actions/runs/4095470363/jobs/7062474045

**Comment by cyberhorsey** [comment]
closed by https://github.com/taikoxyz/taiko-mono/pull/13155 
after investigation, it was TokenVault contract which approached 24.5kb max size.
