### ISSUE TITLE
 bridging from Taiko A1 to Ethereum A1 its display pending all along

### ISSUE THREAD

**Issue by Mathman14** [taikoxyz/taiko-mono#13077]
### Describe the bug

Description of the bug here.

 1: the bridging speed between swaping from L2 and L1 is slow hope thats could be improved
 2: was unable to claim my transactions after bridging from Taiko A1 to Ethereum A1 its display pending all along

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.
the address used to test thats out is 
                                      
                                     0x8B81A7af6b49C4FeaC73157E89430C50553AABF1

**Comment by dantaik** [comment]
@shadab-taiko could you please take a look at this issue?

**Comment by shadab-taiko** [comment]
Hi @Mathman14 the bridging process is slower for L2 to L1, as is also mentioned in the status explainer tooltip on the bridge UI (screenshot attached).
![Screenshot 2023-02-03 at 12 47 30 PM](https://user-images.githubusercontent.com/108871478/216536542-ded73b1e-ca46-4fa9-90fa-2e6330e0cbad.png)
This is expected as per protocol design.

The bridge UI displays the transaction as `Pending` till it becomes claimable. Can you confirm whether you are still not able to claim and if so whether you are getting some error?

**Comment by cyberhorsey** [comment]
Closing this issue as stale.
