### ISSUE TITLE
Could only see 2 made transactions while done more then 10

### ISSUE THREAD

**Issue by ZalmBruin** [taikoxyz/taiko-mono#13073]
Could only see 2 made transactions while done more then 10 transactions.

Done multiple bridge transactions with HORSE
(0xd839d428dac12177c94f45dabcaa49624fbe1c4ae98596d6306bf8427ecf8881)

But it is not available to see in past transactions. But metamask gives a notification that it was succesfull.

**Comment by dantaik** [comment]
@shadab-taiko please also follow up on this one?

**Comment by wolfderechter** [comment]
Maybe you used a different device or cleared the cache. The current testnet uses the browser cache to display transactions and doesn't display everything else, will be implemented in the future AFAIK.

**Comment by shadab-taiko** [comment]
Hi @ZalmBruin 
It looks like you have only `Approved` ERC20 tokens but not actually bridged them. The UI only shows `Bridge` transactions and not `Approved` or `Claim` transactions for now.

 Here's a step by step along with some screenshots to help you bridge ERC20 tokens:
- Enter the amount in the field and `Approve` the bridge contract to be able transfer the ERC20 tokens. Metamask (or whichever wallet you are using) pops up and asks you to submit a transaction.
![Screenshot 2023-02-08 at 6 22 22 PM](https://user-images.githubusercontent.com/108871478/217535665-f11d7af9-5606-4948-a545-c0dc32362824.png)


- The button on the UI now changes to `Bridge`. Clicking on it will again pop up your wallet to send a second transaction.
![Screenshot 2023-02-08 at 6 22 53 PM](https://user-images.githubusercontent.com/108871478/217535703-f5a3a635-765a-4a10-89db-fa8b28614616.png)


- After the above transaction is confirmed you can see the transaction in the transactions tab
![Screenshot 2023-02-08 at 6 24 03 PM](https://user-images.githubusercontent.com/108871478/217535734-9c3cc18a-0ba2-4f46-bf83-1e520a9b64ed.png)

- You will have to wait some time before the tokens can be claimed on the destination chain. Once you see the `Claim` button and click on it, depending on which chain you wallet is currently pointed to:
     - If bridging from L2 to L1 and you are on L2, the wallet will first pop up and ask you to confirm switching the chain to L1 
       and then pop up to ask you submit the `Claim` transaction. If the wallet doesn't ask you to switch the chain you can 
       first change the chain manually in the wallet and then come back to the UI and click on `Claim` again.
     - If bridging from L2 to L1 and you are on L1 the wallet will straightaway pop up to ask you submit the `Claim` 
        transaction.
