### ISSUE TITLE
fix: 'TAIKO' name on taiko.xyz appears black on dark mode (mobile)

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/taiko-mono#13088]
### Describe the bug

Device: iPhone 14 Pro Max
Browser: Safari   (Brave does not have this problem)

When navigating to taiko.xyz, the TAIKO name appears black while in dark mode. Additional information:

1. If I refresh the page, it will occasionally correct itself and change to white
2. If I tap the extension icon in URL and tap 'Turn off Content Blockers' it will also correct to white

### Steps to reproduce

1. Navigate to taiko.xyz via mobile device (iPhone + Safari).
2. Attempt to refresh the page.
3. Attempt to disable content blockers.

### Additional context

@d1onys1us - I saved a video but it's too long to send here. But I can toss it in a Google Drive if it helps.

![image](https://user-images.githubusercontent.com/104391159/216500021-8b797eba-9756-4069-94f8-3d06647b176b.png)

**Comment by d1onys1us** [comment]
Great bug report, thank you. Will take a look this sprint.
