### ISSUE TITLE
fix: Transaction History Keep Disappear

### ISSUE THREAD

**Issue by AndraSKUI** [taikoxyz/taiko-mono#13091]
### Describe the bug

Transaction History Keep Missing and Gone in the UI/UX Taiko, i dont know it is bug or no but when im trying to delete all the history in the browser, then when im trying to open Taiko and testing the testnet again, All the previous transaction in transaction history is gone. its not saved to taiko database or it is saved to my browser? because its happening when im deleting my history browser and taiko history transaction in the ui also gone.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by wolfderechter** [comment]
It's normal behaviour, the current testnet uses the browser cache to display transactions and doesn't display everything else, it will be implemented in the future the previous transactions from a wallet in the future AFAIK.

**Comment by Voron23** [comment]
same problem

**Comment by dantaik** [comment]
This is being worked in and have another issue that tracks it.
