### ISSUE TITLE
You cannot send a Horse from Etherium(A1) to Taiko(1) if th the sum is greater than or equal to 1000 and divisible by 500 without a remainder. For example 1000, 1500, 2000 etc.

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13095]
### Describe the bug

You cannot send a Horse from Etherium(A1) to Taiko(1) if th the sum is greater than or equal to 1000 and divisible by 500 without a remainder. For example 1000, 1500, 2000 etc.

For example, this is my transaction:
https://l1explorer.a1.taiko.xyz/tx/0xd0c62e98d8e74a61597b3a95ce76b519dbfc8095e12f8008a5721016d77dc234
As you can see, when 1000 HORSE tokens are sent, the blockchain does not see them as 1000, it recognizes them as just a token, and you can see a large number of users who send such amounts and they do not receive them -
https://l1explorer.a1.taiko.xyz/address/0x3E3a3416DbCc5cb4448B6b171fF15f9Da35Ab72d

For example two good transactions with amount, not multiple of 1000 and less that 1000.
https://l1explorer.a1.taiko.xyz/tx/0xa8cdced85aa83a222e52b9a2b8991d52b36c1d18169fc8af937b90e6d3871c0f 241HORSE
https://l1explorer.a1.taiko.xyz/tx/0xfbcfbf9e371be3c233ad65f9b38ecd55efef64729c1dadf6cc0883ea66a1e4ea

Saw some issues on taiko GitHab related to this problem before

Hope this gets fixed soon. Author: WhiteGod#8401

**Comment by cyberhorsey** [comment]
I am a bit confused.
The link in question provides not a transfer call, but `approve` call.
https://l1explorer.a1.taiko.xyz/tx/0xd0c62e98d8e74a61597b3a95ce76b519dbfc8095e12f8008a5721016d77dc234

Where as the one for 241 is an actual `transfer` call.
https://l1explorer.a1.taiko.xyz/tx/0xa8cdced85aa83a222e52b9a2b8991d52b36c1d18169fc8af937b90e6d3871c0f 

Is this user simply confused about ERC20 approval method?
@dantaik

**Comment by shadab-taiko** [comment]
Works fine for me both ways:
L1 to L2:
Approve: https://l1explorer.a1.taiko.xyz/tx/0x66e7936240d84472730170047d7100543c51a33e8a9ebab440eb45050291bcad

Bridge: https://l1explorer.a1.taiko.xyz/tx/0xae2af6b1f80f4ddf98a07f2837d9ca34009b52594473dd3d38c55d90b1515417

Claim on L2: https://l2explorer.a1.taiko.xyz/tx/0x191a22c899acbf2ad7a1fa46166a9a554209588fd005377832f30f0ec0c18a47


L2 to L1:
Approve: https://l2explorer.a1.taiko.xyz/tx/0xdc6d88c528b3b7be9ff8aeef4f128e093c44fdef63e41b5d4dcdc159bbe80b2a

Bridge: https://l2explorer.a1.taiko.xyz/tx/0xd5a54ca8530ea639cf585762343bbcf7b33ee5c1a206f1ebfe1eee7b6f555709

Claim on L1: https://l1explorer.a1.taiko.xyz/tx/0x2839e90da5745630675c63a95d66ea14d44743121a5e2fef34203b59fdd2dc76
