### ISSUE TITLE
fix: TRANSACTION_HISTORY

### ISSUE THREAD

**Issue by seektruth-cs** [taikoxyz/taiko-mono#13090]
### Describe the bug

Description of the bug here. I did several transactions on mobile phone.  Then with same wallet, ON DESKTOP, di more transactions.  The transaction history of the bridge only shows the history of the desktop session's transactions, rather than all the history associated with the wallet including mobile, which would be more useful.  Great job guys, this would be polish on the lambo!

### Steps to reproduce

Do a few bridge swaps on mobile device, dont claim, or claim.  With same wallet, do transactions on DESKTOP, check bridge history - no mobile bridge history, mobile history is gone.  

### Additional context

Additional context here. I think you understand what I mean, bridge history is not cumulative with mobile & desktop.  Thanks guys and like I said - great job!  Interface looks clean and is easy to use - kudos!!

**Comment by wolfderechter** [comment]
It's normal behaviour, the current testnet uses the browser cache to display transactions and doesn't display everything else, it will be implemented in the future the previous transactions from a wallet in the future AFAIK.

**Comment by stefanio112** [comment]
what about made taiko on 50 percent anonymous ?

**Comment by dantaik** [comment]
Tracked by another pr
