### ISSUE TITLE
fix: Bridge page, the link to the faucet doesn't work 

### ISSUE THREAD

**Issue by Synopt1c** [taikoxyz/taiko-mono#13111]
### Describe the bug

On the bridge page, in the site header "Receive some tokens for bridging with our faucet." when you click on "faucet", it says "404 This page could not be found."
Bridge page header
<img width="1440" alt="Снимок экрана 2023-02-07 в 22 06 40" src="https://user-images.githubusercontent.com/90967630/217342721-1657e64e-a7d6-448f-b62d-b47b4a258ff8.png">
Faucet 
<img width="1414" alt="Снимок экрана 2023-02-07 в 22 06 56" src="https://user-images.githubusercontent.com/90967630/217342758-e36c82f1-c2aa-4693-9b22-0a4c048e19ea.png">

### Steps to reproduce

Steps to reproduce here..

### Additional context

Additional context here.

**Comment by Andy-Kushtan** [comment]
I think you just need to change wrong link to one of those:
https://l1faucet.a1.taiko.xyz/
https://l2faucet.a1.taiko.xyz/

**Comment by davidtaikocha** [comment]
fixed in https://github.com/taikoxyz/taiko-mono/pull/13112
