### ISSUE TITLE
Testing failure handling of in Bridge message processing

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13125]
### Describe the feature request

We can change Horse token to have a likelihood of 50 to fail when transfer tokens. Then it will enable us to test the source/destination bridge's error handling with the Bridge UI.

- [x] Daniel, an ERC20 token is added for testing purpose: https://github.com/taikoxyz/taiko-mono/pull/13130
- [x] David, could you please make sure this ERC20 token is deployed on our devnet (we will not deploy it on public testnet) https://github.com/taikoxyz/taiko-mono/pull/13132
- [ ] Jeff, could you please enable this token in our bridge config?

**Comment by davidtaikocha** [comment]
will do it today, created an issue: https://github.com/taikoxyz/k8s-configs/issues/58

**Comment by davidtaikocha** [comment]
Deployed and verified: https://l1explorer.internal.taiko.xyz/address/0x1B5Ccd66cc2408A0084047720167F6234Dc5498A

**Comment by dantaik** [comment]
I don't see any bridge test failing, close this one for now.

**Comment by davidtaikocha** [comment]
> I don't see any bridge test failing, close this one for now.

Does it mean BullToken can be removed from our codebase?
