### ISSUE TITLE
feat: Specify which technologies used

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#13136]
### Describe the feature request

I think it would be beneficial to specify which technologies/frameworks are used in each package to make it clear for outsiders.

For example:
- bridge-ui: svelte application
- website: next.js application(?)
- ...

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by wolfderechter** [comment]
cc: @d1onys1us

**Comment by d1onys1us** [comment]
Hmm I'm not sure if I agree. Because I think the monorepo README should describe what kind of things are inside it and not really the details of the technology used. Maybe in the README inside the subpackage it is a better abstraction layer to put the technologies used. But I could be wrong, if you have a good idea for it please feel free to open a PR, thanks.

**Comment by wolfderechter** [comment]
> Hmm I'm not sure if I agree. Because I think the monorepo README should describe what kind of things are inside it and not really the details of the technology used. Maybe in the README inside the subpackage it is a better abstraction layer to put the technologies used. But I could be wrong, if you have a good idea for it please feel free to open a PR, thanks. @wolfderechter

Yeah just a quick introduction in each package with tech used would be perfect. I'll look around and give it a shot.

**Comment by d1onys1us** [comment]
i have made sure that we include a README in each sub-package of the monorepo, and we also have a README in the root of the monorepo describing the packages. so I believe we can close this for now. (ref: https://github.com/taikoxyz/taiko-mono/tree/main#documentation )
