### ISSUE TITLE
Positive impression

### ISSUE THREAD

**Issue by Boomax22** [taikoxyz/taiko-mono#13149]
I've done some simple interactions and transfers. it was quite slow at some moment especially when transacting horses but very cheap fees, less than other layer 2.

**Comment by salar191** [comment]
this is really good platform. low fee, high speed transaction and good user interface. i wait for mainnet 👌

**Comment by ariaboy** [comment]
Your website lacks user-friendliness, which can cause confusion for visitors. Unfortunately, both the website pages and educational materials do not have the best quality and instruction. It would be beneficial to incorporate more graphics to enhance the user experience.

As someone who teaches and develops for the cryptocurrency industry, I recommend considering these suggestions to ensure that your platform provides top-notch education and resources to the community.

Thank you for your attention and consideration

**Comment by cyberhorsey** [comment]
Thank you for the feedback.
