### ISSUE TITLE
fix: transaction claiming slow

### ISSUE THREAD

**Issue by Kanhaiya82** [taikoxyz/taiko-mono#13140]
### Describe the bug

Description of the bug here.
![Screenshot_20230211_203000_MetaMask](https://user-images.githubusercontent.com/86355860/218266112-816c642e-f5ed-4b20-8302-3bb854a426b3.png)

Many time testnet completed, generally no issue found but, sometimes its a bit slow it

might be RPC related or network problem.

0x408FC152eD2c8180e389D7759A5e48cd5431CE1D

### Steps to reproduce

0x408FC152eD2c8180e389D7759A5e48cd5431CE1D

### Additional context

Additional context here.

**Comment by Vidi-byte** [comment]
Good

**Comment by cyberhorsey** [comment]
L2 => L1 has to wait for block header to sync between chains, is not nearly instant like L1 => L2.
