### ISSUE TITLE
fix: horse contract overflow

### ISSUE THREAD

**Issue by xalexec** [taikoxyz/taiko-mono#13158]
### Describe the bug

https://l1explorer.a1.taiko.xyz/address/0xEcB55A56360ecaD5ae94bb5f3C7f7f5244E90453

to bridge 0xD0dfd5baCf160B97C8eE3ecb463F18c08673160c 

And recurrent

https://l1explorer.a1.taiko.xyz/address/0x6242EAC133Ca4e022d904eD5C8c0C8092C252a8A/token-transfers#address-tabs

My Discord ID:alexec#9021
if have some debug,dev role plz give me

### Steps to reproduce

Steps to reproduce here.

Mint 1000
-500
-500
-500
overflow

### Additional context

Additional context here.

**Comment by dantaik** [comment]
@davidtaikocha @cyberhorsey maybe we should check in a horse token contract in our github.
