### ISSUE TITLE
feat: Reward the provers with some random mechanism to promote decentralization

### ISSUE THREAD

**Issue by hugo-blue** [taikoxyz/taiko-mono#13154]
### Describe the feature request

According to Taiko's current L1 contract, the earlier the proof is submitted, the higher the reward. And for each block, a maximum of 5 provers will be rewarded.

The potential problem is that, assuming I have a batch of the highest performing provers sufficient to submit the proof on time for all the proposed blocks, I will get all the rewards.  Other lower-performing provers will not have a chance to receive rewards, and they will quit forever. This is not necessarily desirable for decentralization of provers.

One possible solution is to provide a random mechanism for selecting provers, as described below: 
1. Set a time window in which all provers can submit proofs. For example, the number of forkchoices can be 100 or more. 
2. Randomly select 5 or more provers to grant a reward. 
3. Allow the provers of the same address to submit multiple proofs. A nonce value may be required to distinguish the proofs.

The advantages of this solution: 
1. Provers with lower performance have a chance to get a reward and they can join. This makes the network of provers more decentralized. 
2. The high-performing prover has a greater chance of receiving a reward because it can submit multiple times and is more easily selected.

The disadvantages of this solution: 
1. The average time to finalize the block might be some longer.

In fact, a similar mechanism is used in POW. We will not use POW here, but we can still introduce a random mechanism to achieve more decentralization.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by hugo-blue** [comment]
Additional Information: In the current Taiko contract, the same Prover can only submit once for the same block, others are denied, like the codes below:
```
            for (uint256 i = 0; i < fc.provers.length; ++i) {
                require(fc.provers[i] != prover, "L1:prover:dup");
            }

```

As a prover, there is a scenario to consider: a prover operator can control several, even hundreds of prover machines (as in a mining pool), and all these provers share the same address that receives all the rewards. In this case, it is not practical to have too many wallet addresses for different prover machines.

This is another reason to support this feature:
 "Allow the provers of the same address to submit multiple proofs. A nonce value may be required to distinguish the proofs."

**Comment by dantaik** [comment]
The `prover` address serves as the nonce in the ZKP. If an actual prover entity can simply use multiple addresses then the problem is already solved. The protocol should be *as simple as possible* by dropping nice-to-have features.

**Comment by dantaik** [comment]
I think our engineer @cyberhorsey  likes the idea of randomize the prover reward but still want to keep the early proofs to have bigger odds of receiving the larger rewards.  We just need to make sure the math is simple.

**Comment by hugo-blue** [comment]
> The `prover` address serves as the nonce in the ZKP. If an actual prover entity can simply use multiple addresses then the problem is already solved. The protocol should be _as simple as possible_ by dropping nice-to-have features.

OK.  Since the proof for the same block is differentiated by address and the reward goes to the address within the proof, the high-performance prover must manage the different private keys of the different addresses. This involves some management overhead, but it can be handled well.

**Comment by dantaik** [comment]
@hugo-blue https://github.com/taikoxyz/taiko-mono/pull/13200 will support multiple proofs from the same address per block

**Comment by hugo-blue** [comment]
> @hugo-blue #13200 will support multiple proofs from the same address per block

LGTM. Thx.

**Comment by dantaik** [comment]
I think now we are in favor of this feature https://github.com/taikoxyz/taiko-mono/issues/258 (draft impl https://github.com/taikoxyz/taiko-mono/pull/13205) in alpha-3, thus [PR](https://github.com/taikoxyz/taiko-mono/pull/13200) doesn't have to be merged at all.

**Comment by hugo-blue** [comment]
Got it. I'm going to follow up and look at it.
