### ISSUE TITLE
fix: alpha-1 faucets and explorer redirects

### ISSUE THREAD

**Issue by odesium** [taikoxyz/taiko-mono#13167]
### Describe the bug

The following sites need to be redirected to the Taiko main website as they are currently showing the site is unreachable.

https://l1faucet.a1.taiko.xyz/
https://l2faucet.a1.taiko.xyz/
https://l1explorer.a1.taiko.xyz/
https://l2explorer.a1.taiko.xyz/

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
<img width="1018" alt="Screenshot 2023-02-16 at 21 35 14" src="https://user-images.githubusercontent.com/99078276/219379193-ba6754dd-fb06-4a6d-8e1b-88b1b382727b.png">


Not sure what went wrong on GoDaddy, but I did create those CNAME redirects.

**Comment by dantaik** [comment]
<img width="916" alt="Screenshot 2023-02-16 at 21 46 50" src="https://user-images.githubusercontent.com/99078276/219381807-f7cc8cca-c2c3-4e6a-afe0-afb770ebc96a.png">
Should have been fixed.

**Comment by odesium** [comment]
Not sure if this is website or redirect issue. All 4 sites are showing this similar error. "This site can't be reached ... took too long to respond"

<img width="818" alt="image" src="https://user-images.githubusercontent.com/56487762/219428873-7f7136a9-2d78-4c3d-8f8a-06e60bffa131.png">

**Comment by wolfderechter** [comment]
> Not sure if this is website or redirect issue. All 4 sites are showing this similar error. "This site can't be reached ... took too long to respond"
> 
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/56487762/219428873-7f7136a9-2d78-4c3d-8f8a-06e60bffa131.png">
only http is redirecting successfully http://l1faucet.a1.taiko.xyz/ 
https://l1faucet.a1.taiko.xyz/ is unreachable indeed

**Comment by Kenitas2** [comment]
I went through this tesnet several times and got everything right, but my address is not in your list, please check  0x11b183eB85562eE448161fB57AB3De8d8b23644C
