### ISSUE TITLE
feat: Bridge proof optimization ideas

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/taiko-mono#13180]
### Describe the feature request

- A bridge Merkle proof consists of two smaller proofs: the account proof and the storage proof. The account proof proves that a contract has some state hash at some point. Bridging transactions can re-use the same state hash as long as their bridging transaction happened before or including that state. And so if that state hash is cached in the smart contract (which costs 20k gas) future bridging transactions can then simply only submit the storage proof against this cached state hash when it's available, which should save around 33% in gas for most bridging transactions, probably more.
- I believe if the specific L1/L2 block hash is still available, it is also possible to verify the bridging transaction using an event in the receipts tree instead of the state tree. The receipts tree should normally be cheaper to traverse than the state tree.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Good suggestions in general.

1, I think we can simply hash the SignalService's account state *for the last N L1/L2 block that has at least one claim operation* using a ring-buffer. Then after N sstore, the extra cost will be low.
2. We can change the protocol to persist all cross-chain headers then we can use receipt tree.

I think I'll implement both to do some comparisons.

**Comment by cyberhorsey** [comment]
There were some obvious gas improvements I've made in a draft PR as well, like making the Library methods internal instead of external. That PR has an ether bridge tx down from 800-900k to about 550k.

I will finish that PR as is and then try your account proof cache here next probably?

**Comment by dantaik** [comment]
As of now, the bridge uses a partial Merkle proof, so the design decision has already been made.

The next step will be **optimizing the solidity proof library.**
