### ISSUE TITLE
feat: automatic update of taiko-client bindings when protocol changes

### ISSUE THREAD

**Issue by alexshliu** [taikoxyz/taiko-mono#13201]
### Describe the feature request

Automatic update of bindings via GitHub action when the protocol changes, which in turn triggers an update of other project code (e.g., taiko-client/taiko-hive).

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
If you do this, can you please update the bindings in the relayer package in this repository as well?

**Comment by davidtaikocha** [comment]
Not sure whether we can do it automatically, since some protocol changes (like changing some field names in a struct) will also lead to some manual updates in Go code.

**Comment by Ejiniemmanuel** [comment]
kindly update

**Comment by alexshliu** [comment]
This is just an idea I had and a todo item, at the moment there are still parts that need to be changed manually after abigen generates the golang binding, this may require a change to the taiko-mono code to decouple it, I will deal with this when I have time.
