### ISSUE TITLE
fix: maybe should use rlp-encode instead of abi-encode for proposeBlock's first param `meta`

### ISSUE THREAD

**Issue by johntaiko** [taikoxyz/taiko-mono#13219]
### Describe the bug

now we use abi-encode for proposeBlock's first param, but it's inefficient and wasteful
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/25055590/221499958-f24fa134-594b-4958-9b8b-f0979996a7d8.png">
from above picture, the meta's length is longer than txlist's length(encoding txlist with rlp)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
You mean using RLP in solidity contracts?

**Comment by Brechtpd** [comment]
This data is read in the smart contract, and decoding the RLP encoded data in the smart contract will be a more expensive to just having some more zero bytes in the calldata (just 4 gas/byte) and will also be more complex. Closing for now, please re-open if you disagree.
