### ISSUE TITLE
Bridge ETH/tokens between Ethereum A1 and Taiko A1

### ISSUE THREAD

**Issue by Gushynu** [taikoxyz/taiko-mono#13255]
### Describe the bug

The site can't be reached

### Steps to reproduce

Just trying to connector, but the page cannot be reached

### Additional context

Just trying to connector, but the page cannot be reached

**Comment by cyberhorsey** [comment]
We don't have a public bridge until our next testnet is live.

**Comment by Gushynu** [comment]
hi,

when the next testnet will be live?

thanks!

În sâm., 4 mar. 2023 la 22:42, jeff ***@***.***> a scris:
