### ISSUE TITLE
Does poap need to be claimed? or  will still be airdropped directly to the wallet

### ISSUE THREAD

**Issue by maggiemaggiezz** [taikoxyz/taiko-mono#13269]
### Describe the feature request

How do users participating in the first round of testnet claim their POAP? where to claim

### Describe alternatives you've considered

How do users participating in the first round of testnet claim their POAP? where to claim

**Comment by d1onys1us** [comment]
we will share information about this as soon as possible and we have not forgotten about it. thanks for your patience and participation in alpha-1
