### ISSUE TITLE
feat: optimize keyForName method in AddressResolver.sol

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13290]
### Describe the feature request

Changing AddressResolver's key generation from
```solidity
string memory key = string.concat(Strings.toString(chainId), ".", name);
```
to

```solidity
string memory key = string(bytes.concat(bytes32(chainId), bytes(name)));
```

will reduce 2360 gas for proveBlock tx. But it will break many hardhat tests.

| Deployment Cost                                | Deployment Size |        |        |        |         |
|------------------------------------------------|-----------------|--------|--------|--------|---------|
| proveBlock                                     | 49861           | 56789  | 49861  | 126161 | 49      |
| resolve(string,bool)(address)                  | 4329            | 4544   | 4554   | 10829  | 100     |
| resolve(uint256,string,bool)(address)          | 4232            | 4272   | 4232   | 6232   | 49      |

| Deployment Cost                                | Deployment Size |        |        |        |         |
|------------------------------------------------|-----------------|--------|--------|--------|---------|
| proveBlock                                     | 47501           | 54429  | 47501  | 123801 | 49      |
| resolve(string,bool)(address)                  | 3496            | 3709   | 3718   | 9996   | 100     |
| resolve(uint256,string,bool)(address)          | 3541            | 3581   | 3541   | 5541   | 49      |

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

You can work on top of this [draft PR](https://github.com/taikoxyz/taiko-mono/pull/13285) to do comparison by running:

```
forge test --gas-report -vvv
```

**Comment by jscriptcoder** [comment]
Created a branch for this issue [here](https://github.com/taikoxyz/taiko-mono/tree/13290-optimize-keyforname-method-in-addressresolver)

**Comment by dantaik** [comment]
We should probably avoid using string at all. A better way to do `resolve` is to map a string into a public constant bytes32, then always use it to resolve to an address. For example

```solidity
bytes32 public constant KEY_SIGNAL_SERVICE = keccack256(bytes("signal_service"));

function resolve(uint chainId, bytes32 key) public view returns(address) {
    bytes32 actualkey;
    assembly {
       actualKey := mul(key, chainId)
   }
  return theMap[actualKey];
}
```

**Comment by dantaik** [comment]
Implemented in https://github.com/taikoxyz/taiko-mono/pull/13557

**Comment by d1onys1us** [comment]
@dantaik can we close this issue?
