### ISSUE TITLE
feat(taiko.xyz): Add Roadmap and Link

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/taiko-mono#13294]
### Describe the feature request

Consider adding the Official Roadmap to the taiko.xyz site. Then add as a link under “Learn more about Taiko” on this page: `https://taiko.xyz/docs`

For reference, the roadmap discussed is the one on the Medium Article:

![IMG_1864](https://user-images.githubusercontent.com/104391159/224549554-ade4bc92-24af-4c7e-971d-33e363a97fe1.jpeg)

**Comment by zeecnla** [comment]
I can add this if no one has done it yet.
