### ISSUE TITLE
fix: whitepaper Rc is not defined

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13314]
### Describe the bug

![image](https://user-images.githubusercontent.com/13951458/225007994-58d5626f-d187-48ab-adbb-757b1bf8ac44.png)

In this image from the whitepaper I do not see where R_c is defined. Also, the last AND statement has a <= comparison but nothing to compare to.

@dantaik do you know what R_c refers to and also if there should be a value it is <= to?

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dong77** [comment]
<img width="444" alt="Screenshot 2023-03-16 at 11 01 20" src="https://user-images.githubusercontent.com/1710087/225500329-e2fd52ca-e412-494d-ad99-530296d72825.png">

In a previous version, R_c is defined in section 5.5.1, but I don't know why it is missing now.

BTW, I'll create a PR to completely remove commit-and-reveal scheme from the whitepaper.

**Comment by dong77** [comment]
https://github.com/taikoxyz/taiko-mono/pull/13331 created, but will be merge a few days later.
