### ISSUE TITLE
fix: Protocol.Yml

### ISSUE THREAD

**Issue by Roro5555** [taikoxyz/taiko-mono#13343]
### Describe the bug

 this protocol.yml :
name: Protocol

on:
  push:
    branches: [main]
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: protocol - Unit Tests
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm test

      - name: protocol - Integration Tests
        working-directory: ./packages/protocol
        run: pnpm test:integration

      - name: protocol - Tokenomics Tests
        working-directory: ./packages/protocol
        run: pnpm test:tokenomics

      - name: protocol - Bridge Tests
        working-directory: ./packages/protocol
        run: pnpm test:bridge

      - name: protocol - Test Coverage
        working-directory: ./packages/protocol
        run: pnpm test:coverage

      - name: protocol - Generate Genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      - name: protocol - Export ABIs
        working-directory: ./packages/protocol
        run: pnpm export:abi

      - name: protocol - Deploy L1 Contracts
        working-directory: ./packages/protocol
        run: pnpm deploy:hardhat

      - name: protocol - Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/protocol/coverage
          flags: protocol

  post-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up protocol
        uses: ./.github/actions/set-up-protocol

      - name: Run the command to update the documentation
        run: pnpm -F protocol export:docs

      - name: Stage all modified and untracked files
        run: git add .

      - name: Exit if there are no changes
        run: git diff --exit-code --cached

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "docs(protocol): auto-update protocol documentation"
          commit-message: "docs(protocol): auto-update protocol documentation"
          branch: update-docs-${{ github.sha }}
          delete-branch: true

### Steps to reproduce

The YAML syntax for the provided protocol.yml file appears to be valid. However, there are a few things that can be improved or optimized in the workflow:

The Cancel previous runs step is using a third-party GitHub Action styfle/cancel-workflow-action@0.11.0 to cancel previous workflow runs. This step is optional and can be removed if it is not necessary for the workflow.

The Checkout repository step is repeated twice in the workflow, once in the build job and once in the post-merge job. It is better to move this step to the top of the workflow so that it is only executed once.

The Set up protocol step in the post-merge job is using a custom action ./.github/actions/set-up-protocol. This action should be reviewed and verified to ensure that it is necessary and safe to use.

The Exit if there are no changes step in the post-merge job is redundant and can be removed as the create-pull-request action will only create a pull request if there are changes.

The delete-branch option in the create-pull-request action is set to true, which means that the branch created for the pull request will be deleted after the pull request is merged. This may not be desirable in some cases, so the option should be reviewed and adjusted if necessary.

### Additional context

Additional context here.

**Comment by Roro5555** [comment]
Here is the updated protocol.yml file with the suggested changes:

name: Protocol

on:
  push:
    branches:
      - main
    paths:
      - "packages/protocol/**"
  pull_request:
    paths:
      - "packages/protocol/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm dependencies
        uses: ./.github/actions/install-pnpm-dependencies

      - name: protocol - Unit Tests
        working-directory: ./packages/protocol
        run: pnpm clean && pnpm test

      - name: protocol - Integration Tests
        working-directory: ./packages/protocol
        run: pnpm test:integration

      - name: protocol - Tokenomics Tests
        working-directory: ./packages/protocol
        run: pnpm test:tokenomics

      - name: protocol - Bridge Tests
        working-directory: ./packages/protocol
        run: pnpm test:bridge

      - name: protocol - Test Coverage
        working-directory: ./packages/protocol
        run: pnpm test:coverage

      - name: protocol - Generate Genesis
        working-directory: ./packages/protocol
        run: pnpm test:genesis

      - name: protocol - Export ABIs
        working-directory: ./packages/protocol
        run: pnpm export:abi

      - name: protocol - Deploy L1 Contracts
        working-directory: ./packages/protocol
        run: pnpm deploy:hardhat

      - name: protocol - Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./packages/protocol/coverage
          flags: protocol

  post-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up protocol
        uses: ./.github/actions/set-up-protocol

      - name: Run the command to update the documentation
        run: pnpm -F protocol

**Comment by dantaik** [comment]
Could you please open a PR for these changes (and these changes only?)

**Comment by d1onys1us** [comment]
hello @Roro5555 would you mind opening a PR for this? just bumping the thread, thanks.

**Comment by d1onys1us** [comment]
i am closing this issue for now as it seems stale, please re-open if needed
