### ISSUE TITLE
Add linting for mdx and md on build / PR for docs website

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13411]
### Describe the feature request

Description of the feature request here.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by developerkunal** [comment]
@d1onys1us 
## Description:
This feature request aims to improve the quality and consistency of documentation websites by adding linting for MDX and MD files. Linting is a process of analyzing code or text for potential errors, stylistic issues, or other problems. In the context of documentation, linting can help catch common mistakes like broken links, spelling errors, inconsistent formatting, or unclear language.

By adding linting for MDX and MD files, documentation website maintainers can ensure that all content meets a certain standard, regardless of who wrote it or when. Linting can also help automate the review process, freeing up time and resources for more critical tasks.

## Alternatives considered:

Manual review: Documentation website maintainers can manually review all content to ensure it meets a certain standard. However, this process is time-consuming and prone to errors or biases.

## Additional context:
Adding linting for MDX and MD files can be done using various tools and plugins, such as remark, markdownlint, or textlint. The configuration of the linter can be tailored to the specific needs and preferences of the documentation website, and can be integrated with popular CI/CD tools like GitHub Actions or CircleCI. By running the linter on build or pull request, documentation website maintainers can catch issues early on and provide feedback to content contributors in a timely manner.

**Comment by seunbayo** [comment]
@d1onys1us  more details about this

**Comment by d1onys1us** [comment]
yes @seunbayo basically we don't do a prettier lint for the documentation, i dont think. i think we can include this as part of lint-staged. i created this issue because in vscode one time i saved the .mdx file (difference from .md), and it formatted the bullet points in a bad way (changed the way the document was rendered). so i mainly want to prevent that. perhaps there is a suggested formatter as well we can include in the README of the website sub-package for vscode users and/or include a linter.

**Comment by d1onys1us** [comment]
mdx with prettier has issues, instead let's just be careful on PR review and disable in ~/.vscode/settings.json. will open a PR for that.
