### ISSUE TITLE
feat: approve contributor workflows for deploying preview builds or skip preview builds on fork PR

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13419]
### Describe the feature

- contributors have to get their workflows approved for deploying preview builds (we should allow by default for the website)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by ram200009** [comment]
their no issue, smooth working ,great project

**Comment by rainymind** [comment]
It works well and no problems were observed.
that was perfect

**Comment by bardiasani** [comment]
this is a cool idea

**Comment by Sator13** [comment]
works consistently good project

**Comment by Froegge** [comment]
Absolutely smooth and no problems

**Comment by Dodiekurniawan** [comment]
No error good testnet

**Comment by hamzacheema9** [comment]
satisfied

**Comment by LevelerDad** [comment]
No error in testnet

**Comment by thuccoin** [comment]
Great

**Comment by jiaojinqian** [comment]
nice

**Comment by kostiiik** [comment]
спробував

**Comment by zhangfan0599** [comment]
非常好的一个项目

**Comment by ferox-glitch** [comment]
works smooth

**Comment by Pitcher75** [comment]
It works well, smooth, good project!

**Comment by plast73** [comment]
Great project! I hope we have a great future!

**Comment by Uzan666** [comment]
ok done

**Comment by kkwdk** [comment]
Great

**Comment by LIZ369** [comment]
Até o momento sem problemas, trabalho tranquilo, ótimo projeto lets go.

**Comment by sangamxi** [comment]
It working properly!

**Comment by jitakuasobi117** [comment]
No error in testnet

**Comment by bagatov** [comment]
awesome

**Comment by Sator13** [comment]
работает стабильно

**Comment by Jarwo8680** [comment]
works flawlessly no issue found yet

**Comment by ZM2109** [comment]
Very good!

**Comment by wizeone1** [comment]
amazing stuff

**Comment by LIZ369** [comment]
experiência maravilhosa

**Comment by Mystical89** [comment]
It works well and smooth.

**Comment by azharimad** [comment]
good, flawless

**Comment by redowanahsan** [comment]
Good plan

**Comment by locvalucha** [comment]
I would prefer to choose the first one, approve contributor workflows for deplying the preview builds.

**Comment by pucedoteth** [comment]
it works without ERRORS welldone

**Comment by Lovander** [comment]
No error good testnet

**Comment by Aztercrew** [comment]
Nice

**Comment by jacekdk1972** [comment]
i found no errors or faults, testnet going good . I still try to find something to report

**Comment by kidochukwu** [comment]
i'm finding it difficult to launch a contract

**Comment by HiddenHead** [comment]
works well

**Comment by LIZ369** [comment]
No error , very good testenet .  ok

**Comment by thenextbigbull** [comment]
No error working good

**Comment by ynhstick** [comment]
> ### Describe the feature
> * contributors have to get their workflows approved for deploying preview builds (we should allow by default for the website)
> 
> ### Steps to reproduce
> Steps to reproduce here.
> 
> ### Additional context
> Additional context here.

it so smooth bro, taiko is a good project

**Comment by applepie493** [comment]
エラーはなく正常に動作しています
