### ISSUE TITLE
feat(bridge-ui): show estimated receive amount

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13431]
Would be great if we could show an estimation for the amount the user will receive on the other side when bridging. Many other bridges already do this, providing with better experience.

Some examples

Celer cBridge:
<img src="https://user-images.githubusercontent.com/613724/227213819-256544d2-438d-4586-a484-0be0d110cfd9.png" width="400" />

Synapse:
<img width="400" alt="Screenshot 2023-03-23 at 14 17 18" src="https://user-images.githubusercontent.com/613724/227216064-99b95434-5b18-4165-840e-1c2407e971a2.png">

**Comment by dong77** [comment]
I think we should have this feature.

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
