### ISSUE TITLE
feat(bridge-ui): filter transactions

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13437]
Pending transactions could be considered more important to the user than the rest of transactions, and therefore we might want to separate them into their own tab, or having a filter set by default. We might want to also have different type of filters or tabs to differentiate where the token has been bridged to, etc...

Other bridges have this idea in mind

Polygon:
<img width="400" alt="Screenshot 2023-03-23 at 19 57 33" src="https://user-images.githubusercontent.com/613724/227325370-e29cbb6f-8f87-458b-b38a-15f83bbff7e2.png">

Arbitrum:
<img width="400" alt="Screenshot 2023-03-23 at 19 57 55" src="https://user-images.githubusercontent.com/613724/227325837-7ef3c2c0-90bf-43b2-a88b-b660a022660e.png">

**Comment by dong77** [comment]
We need to define "pending":

1.  On the source chain, if the bridge transaction is pending a confirmation, it is "pending"
1.  Once the source tx is confirmed, the claim transaction on the destination chain may also "pending" the signal root to be available, this is also a kind of "pending"
1.  Once the claim transaction is fired on the destination chain but has not been confirmed yet (in mempool), it is also "pending". This is the same type of "pending" as 1.

1 and 3 can be displayed as "pending confirmation", and 2 can be "pending bridging"

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
