### ISSUE TITLE
feat(bridge-ui): view wallet in explorer

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13432]
How about providing with a link to view the wallet address in Etherscan? Some bridges show this link or make the wallet address clickable to redirect the user to the explorer. The benefit would be to give the user a quick access to more details about their wallet address.

Some examples

Cross-Chain Bridge:
<img width="320" alt="Screenshot 2023-03-23 at 14 25 38" src="https://user-images.githubusercontent.com/613724/227218311-bb1c536d-7de9-4c31-ae60-6d98af49f4ad.png">

Multichain:
<img width="320" alt="Screenshot 2023-03-23 at 14 27 20" src="https://user-images.githubusercontent.com/613724/227218648-18bf1e49-9dc1-411e-a4e8-a672eb51aad9.png">

**Comment by dong77** [comment]
We should also have this feature.

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
