### ISSUE TITLE
feat(bridge-ui): show instant feedback when insufficient balance

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13433]
A better user experience would be to show instant feedback if their balance is lower than  what's intended to be transferred (including estimated fees). We currently disable the transfer bridge button, but the user might not realize the reason why the button remains disabled... Other bridges inform the user right away either as they enter the amount or blur out of the textbox.

Some examples

Optimism:
<img width="400" alt="Screenshot 2023-03-23 at 14 43 00" src="https://user-images.githubusercontent.com/613724/227222553-7303e306-ee6b-4cd3-9eb0-e483d139012c.png">

Hop:
<img width="400" alt="Screenshot 2023-03-23 at 14 44 06" src="https://user-images.githubusercontent.com/613724/227222787-f9ddf7e1-e80b-4b80-8cac-9c41e5908d3e.png">

**Comment by dong77** [comment]
Definitely need this feature.

**Comment by 2manslkh** [comment]
@jscriptcoder Are we still going ahead with this enchantment?

**Comment by 2manslkh** [comment]
Closing, will include feature in Bridge V2
