### ISSUE TITLE
fix: Link error in the Gitbook 

### ISSUE THREAD

**Issue by Aanostra** [taikoxyz/taiko-mono#13458]
### Describe the bug

There is a link error in your gitbook 
In the "Hello" section then > Contribute to Taiko > "contributing guide" link
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/106231459/227725449-5af2d58b-14c5-4a3c-a321-5632d9029b1b.png">

### Steps to reproduce

Go in the "Hello" section on the Gitbook
then > Contribute to Taiko
then click on > "contributing guide" link

it displays an error 404

**Comment by d1onys1us** [comment]
this is fixed now, thank you
