### ISSUE TITLE
Metamask and Taiko dashboard unmatch

### ISSUE THREAD

**Issue by Wolgebel** [taikoxyz/taiko-mono#13460]
### Describe the bug

waiting for a very long time for a response from the Taiko Dashboard, even though the transaction on metamask is already in an approved condition, but the Taiko dashboard is still buffering
![Screenshot_20230326_104817_Kiwi Browser](https://user-images.githubusercontent.com/128950383/227754318-d1643580-5cab-4936-a499-08ce10943c36.jpg)
![Screenshot_20230326_104826_Kiwi Browser](https://user-images.githubusercontent.com/128950383/227754320-abf86288-0203-478c-a904-e6c3e6d22fbe.jpg)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Maybe need more speed the platform capacity

**Comment by d1onys1us** [comment]
thank you for the feedback, @Wolgebel . i believe the reason you faced this issue is because of the network congestion of the mempool, which we are looking into currently. i will close the issue for now and if it comes up again we can re-open it, thanks.
