### ISSUE TITLE
"killed" in node logs.

### ISSUE THREAD

**Issue by Perf89** [taikoxyz/taiko-mono#13469]
### Describe the bug

"killed" in node logs. 
How to fix it?

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.
![Снимок экрана (1131)](https://user-images.githubusercontent.com/120090929/227904545-1f3d2885-b0ce-4e7b-bf6c-994bb96a1c27.png)

**Comment by d1onys1us** [comment]
@Perf89 are you still afcing this issue? did trying to restart the node fix it or the trouble shooting guides here: https://taiko.xyz/docs/guides/run-a-node#troubleshooting?

**Comment by Perf89** [comment]
@d1onys1us I think this question can be closed, I ran the prover on a more powerful VPS, I did not encounter such a problem again. Thank you
