### ISSUE TITLE
fix: Visual bugs when using the bridge + sending two transactions instead of one

### ISSUE THREAD

**Issue by PurpleM0ney** [taikoxyz/taiko-mono#13465]
### Describe the bug

Hello! 

1. When using the bridge, after a successful transaction, the site still won't let me send a new transaction through the bridge (as if the past transaction didn't end).
![Screenshot_122](https://user-images.githubusercontent.com/108991469/227790961-3fa32ad9-ad5d-4775-a81b-156884792ad6.png)

As you can see, in MetaMask the transaction passed, but still not on the site. And so for a very long time after the transaction in MM.

2.  After sending the transaction I wanted to speed it up, so I have visually generated two different transactions 
![Screenshot_123](https://user-images.githubusercontent.com/108991469/227791051-067f805b-0465-4716-9c9a-aba5cee4a859.png)

As you can see, I have two transactions of 0.05 ETH, but I sent only one.

Tx of the transactions is also backed up, but one of them doesn't work.

Tx of a normal transaction: 0x513cd2d896965dece18b1a9519f87703a8eb048941387fa4bbae86f2a1e3c087
Tx of the repeated transaction: 0x24b3e3fa5adea07831ab5a4c19d861072638a8aa0ee6ea7eadf562ec1f8be5e5 
(explorer does not find it, but it is nevertheless displayed in the bridge interface)

**Comment by d1onys1us** [comment]
cc @shadab-taiko wonder if this is still an issue? we did make a fix for it, so maybe you found an edge case here.

**Comment by PurpleM0ney** [comment]
> cc @shadab-taiko wonder if this is still an issue? we did make a fix for it, so maybe you found an edge case here. we can also close this if we are doing the bridge-overhaul, it may no longer be relevant. but tagging you for visibility

If necessary, I can try to repeat the same errors and test their reappearance

**Comment by dantaik** [comment]
@jscriptcoder could you triage this issue?

**Comment by jscriptcoder** [comment]
After some polishing on the bridge and better error handling, I can no longer reproduce this issues.
