### ISSUE TITLE
feat: shorten_steps

### ISSUE THREAD

**Issue by bardiasani** [taikoxyz/taiko-mono#13467]
### Describe the feature request

Is it possible that after bridge , it does not need to claim in the destination chain?
( no claim & transaction on the destination)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
this is a design feature because we want users to be able to claim transactions on their own without needing to rely on any intermediary (such as the relayer), so it's not really possible. i will close the issue for now but can re-open it if you still have questions and/or a feature request.
