### ISSUE TITLE
improve taiko nodes documentation

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13472]
taiko nodes is too long: https://taiko.xyz/docs/concepts/taiko-nodes

we need to take the sub-sections and "separate" it out a bit. i believe it would make sense for the following sections:
- overview
- taiko geth
- taiko client
- driver, proposer, prover (separate sections, possibly, to taiko client, or perhaps just within taiko client, whichever is more clear)

lastly, we should normalize the "quote" blocks where we say like:
> NOTE... blah blah blah

and use the callout component: https://nextra.site/docs/docs-theme/built-ins/callout , also, there should be links to the whitepaper to click on (less preferred) or direct links to the documentation on the website (more preferred, but as whitepaper docs are in-progress, they might not exist yet)

**Comment by d1onys1us** [comment]
@umededoteth i just discovered, i think i can assign this issue to you if you comment on it. can you leave a dummy comment :)

**Comment by umededoteth** [comment]
@d1onys1us dummy comment :)

**Comment by lolsmackdown11** [comment]
good idea man :> +1
