### ISSUE TITLE
Create remix deployment tutorial

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13491]

**Comment by sgpkey35** [comment]
perfeclt

**Comment by developerkunal** [comment]
@d1onys1us can i work on this?

**Comment by d1onys1us** [comment]
@developerkunal yes, i will assign it to you, thanks! 

i would suggest you create a draft idea of the walkthrough and gain some peer review before creating the tutorial or if you plan on doing a video walkthrough, i would be happy to help with review. you can check some ideas here: https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md#creating-content 

either a text guide with screenshots or a video would be the best, in my opinion. the former is probably more maintainable and more likely to make it as a core "guide" on taiko.xyz, the latter will likely be listed as a bullet point under a heading "resources" in the "deploy a contract" guide.

**Comment by developerkunal** [comment]
@d1onys1us for sure i will create a draft and sent it here

**Comment by developerkunal** [comment]
@d1onys1us for this I would like to create a blog post that gonna include the images for step by step guide to deploying the smart contract using remix, we can deploy the getter and setter contract in it. which will be easy to understand.

**Comment by d1onys1us** [comment]
> @d1onys1us for this I would like to create a blog post that gonna include the images for step by step guide to deploying the smart contract using remix, we can deploy the getter and setter contract in it. which will be easy to understand.

any reason why a blog post versus doing the step-by-step and images in a guide on taiko.xyz? i only say that because a blog post will be an outgoing link, which will lose the context of the documentation site.

**Comment by developerkunal** [comment]
@d1onys1us i want to create a blog post on taiko instead of creating outside I don't wanna give outbound links or anything like that.

**Comment by developerkunal** [comment]
## DRAFT

Title: How to Deploy a Smart Contract Using Remix

Introduction:
Remix is an open-source web and desktop application used for creating and deploying smart contracts. In this tutorial, we will show you how to deploy a smart contract using Remix, step-by-step.

Step 1: Create a Smart Contract
To create a smart contract, go to remix.ethereum.org and select the "contracts" folder. Choose a Solidity file from the File Explorers pane or create a new one. Review the smart contract code and make any necessary changes. Once you are satisfied with your changes, save the final version by pressing Command/Ctrl + S.

Step 2: Compile the Contract
Choose the Solidity Compiler icon on the left side menu. Check that your compiler version is compatible with the version specified in the pragma solidity statement. Then, select the "Compile" button to compile your smart contract.

Step 3: Deploy the Contract
Click on the "Deploy and Run Transactions" icon on the left side menu. Choose your desired environment such as Injected Web3 or JavaScript VM. If using Injected Web3, connect your wallet to the chain and verify that the environment reads as the network you want to deploy the contract on. Click "Deploy" and select "Confirm" in the wallet notification window to pay for the transaction.

Step 4: Interacting with the Contract
Select the dropdown on the newly deployed contract at the bottom of the left panel. View the deployed contract's functions using the "Deployed Contracts" window. You can read or write on the network using the function inputs as needed. Confirm write transactions in the wallet notification window to pay the transaction's gas fee.

Step 5: View Contract Details
Copy the contract address from the "Deployed Contracts" window on the left panel. Navigate to a block explorer for the network you deployed the contract on and use the contract address to search for your contract. Explore the details of your deployed smart contract and learn more about the explorer there.

Conclusion:
Deploying a smart contract using Remix is a straightforward process. By following this tutorial, you can create and deploy your own smart contract using Remix and interact with it on any network of your choice.

**Comment by developerkunal** [comment]
@d1onys1us look at draft please

**Comment by developerkunal** [comment]
@d1onys1us  Any update on this

**Comment by byru17** [comment]
Nice draft sir

**Comment by d1onys1us** [comment]
hey @developerkunal thanks for the draft! it looks great. for now, we can hold off on adding it while the alpha-2 testnet is deprecated. we can work on getting this draft as a guide once we come with the alpha-3 testnet

**Comment by developerkunal** [comment]
@d1onys1us thanks for update sure we can do that.

**Comment by mpshimul** [comment]
> ## DRAFT
> Title: How to Deploy a Smart Contract Using Remix
> 
> Introduction: Remix is an open-source web and desktop application used for creating and deploying smart contracts. In this tutorial, we will show you how to deploy a smart contract using Remix, step-by-step.
> 
> Step 1: Create a Smart Contract To create a smart contract, go to remix.ethereum.org and select the "contracts" folder. Choose a Solidity file from the File Explorers pane or create a new one. Review the smart contract code and make any necessary changes. Once you are satisfied with your changes, save the final version by pressing Command/Ctrl + S.
> 
> Step 2: Compile the Contract Choose the Solidity Compiler icon on the left side menu. Check that your compiler version is compatible with the version specified in the pragma solidity statement. Then, select the "Compile" button to compile your smart contract.
> 
> Step 3: Deploy the Contract Click on the "Deploy and Run Transactions" icon on the left side menu. Choose your desired environment such as Injected Web3 or JavaScript VM. If using Injected Web3, connect your wallet to the chain and verify that the environment reads as the network you want to deploy the contract on. Click "Deploy" and select "Confirm" in the wallet notification window to pay for the transaction.
> 
> Step 4: Interacting with the Contract Select the dropdown on the newly deployed contract at the bottom of the left panel. View the deployed contract's functions using the "Deployed Contracts" window. You can read or write on the network using the function inputs as needed. Confirm write transactions in the wallet notification window to pay the transaction's gas fee.
> 
> Step 5: View Contract Details Copy the contract address from the "Deployed Contracts" window on the left panel. Navigate to a block explorer for the network you deployed the contract on and use the contract address to search for your contract. Explore the details of your deployed smart contract and learn more about the explorer there.
> 
> Conclusion: Deploying a smart contract using Remix is a straightforward process. By following this tutorial, you can create and deploy your own smart contract using Remix and interact with it on any network of your choice.

Nice Draft sir, I am gonna try this, waiting for the alpha-3 testnet!

**Comment by RadekBit** [comment]
Thank you for this draft Sir!

**Comment by d1onys1us** [comment]
hey @developerkunal ! sorry for taking a while to get back. we have included this guide in our alpha-3 testnet docs, and think it would be better to keep this guide on the core documentation website instead of a separate blog post.

please feel free to edit the remix deployment guide if you see any issues once the alpha-3 docs are released, and also feel free to create any individual blog post to help developers out!

i'll close this issue for now because anyone can now just open a PR if they want to edit the docs once alpha-3 is released. thank you!
