### ISSUE TITLE
fix (status-pagr): Latest Proof Tile Shows Wed Dec 31 1969

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/taiko-mono#13503]
### Describe the bug

Watching the Taiko Status page (<https://status.a2.taiko.xyz/>), occasionally the `Latest Proof` date/time shows:

<img width="379" alt="Screenshot 2023-03-30 at 8 39 09 AM" src="https://user-images.githubusercontent.com/104391159/228854416-8d0541ef-5506-4797-8231-21fcd5e5451d.png">

### Steps to reproduce

Head over to <https://status.a2.taiko.xyz/> and watch the Latest Proof tile.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
cc @cyberhorsey

**Comment by Perf89** [comment]
![Снимок экрана (1177)](https://user-images.githubusercontent.com/120090929/229048190-059de518-d4e2-4b1d-9b9f-690af5b8dec4.png)
