### ISSUE TITLE
allow the possibility to cancel pending transaction

### ISSUE THREAD

**Issue by Aanostra** [taikoxyz/taiko-mono#13529]
### Describe the feature request

These transaction are pending for more than 1 week now, maybe you can allow the possibility to cancel them
It seems that the token are freezed because I can't not bridge them again anymore

when users have lot of transaction, it can be useful 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/106231459/229581729-504eae86-7f44-4064-86cc-fdfe32562bf9.png">

### Describe alternatives you've considered

Suggestion : add color for the transactions status 
claim : pink
claimed : green
pending : red or orange

**Comment by 2manslkh** [comment]
Is it possible to cancel a transaction when the token is already deposited? I don't think it is possible as the job might be already accepted on the destination chain. Adding a cancel feature might cause some sort of doubling of assets on both chains?? @d1onys1us

**Comment by dantaik** [comment]
@jscriptcoder The bridge UI, in the future, should allow users to do the claiming on the target chain (as the msg.sender) without the relayer initiating the claim transaction. The contract should not be changed.
