### ISSUE TITLE
Create an ARM Docker image

### ISSUE THREAD

**Issue by dimazhornyk** [taikoxyz/taiko-mono#13523]
### Describe the feature request

Currently, the only platform that can run zkevm-chain-prover-rpcd(gcr.io/evmchain/askja-proverd) is `linux/amd64`
Could you please add there an image built for `linux/arm64`

### Describe alternatives you've considered

As an alternative, you can just point me to the Dockerfile used to build the image, so I could build it by myself

**Comment by d1onys1us** [comment]
cc @davidtaikocha

**Comment by davidtaikocha** [comment]
Closed this issue since we wont use `zkevm-chain-prover-rpcd` for alpha-3 testnet.
