### ISSUE TITLE
change loading spinner to more meaningful text on bridge

### ISSUE THREAD

**Issue by GONY7** [taikoxyz/taiko-mono#13531]
### Describe the feature request

![image](https://user-images.githubusercontent.com/83521556/229592464-43895568-9903-4792-96c9-d85590c2900a.png)

I'd like you to text me about the progress.

### Describe alternatives you've considered

-

### Additional context

-

**Comment by chiragbadhe** [comment]
@GONY7 progress in the sense of loading, bridging like that?

**Comment by GONY7** [comment]
> 

Yes, I think it would be better than a simple circle. : )

**Comment by d1onys1us** [comment]
pasting @jscriptcoder here, would tag Jane but not sure her github username

**Comment by jscriptcoder** [comment]
We're working on a re-design for the Bridge. These are very valuable feedbacks we'll definitely take into consideration. Assigning this issue to me to keep track of it.

**Comment by thibault-ketterer** [comment]
why not "synchronization" on oribter they use "Send"
![image](https://github.com/taikoxyz/taiko-mono/assets/4283686/e83b0881-3778-40c6-957f-5dfc99d37827)

**Comment by 2manslkh** [comment]
![Image](https://github.com/taikoxyz/taiko-mono/assets/23635326/48578f39-4222-4a45-903a-070191120168)

UI was updated to have "Bridging..." text

@GONY7 Thank you for your feedback :)
