### ISSUE TITLE
fix(bridge-ui): no transaction shown when bridging BLL and HORSE

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13532]
There is an issue when bridging Bull and Horse tokens. Transaction doesn't seem to be recorded in UI

**Comment by jscriptcoder** [comment]
There is an issue when bridging Bull and Horse token. Transaction doesn't seem to be recorded in the UI

**Comment by jscriptcoder** [comment]
What's happening here is that we're not adding the transaction to the storage when bridging tokens: https://github.com/taikoxyz/taiko-mono/blob/main/packages/bridge-ui/src/components/form/BridgeForm.svelte#L161. 

We do so when bridging ETH: https://github.com/taikoxyz/taiko-mono/blob/main/packages/bridge-ui/src/components/form/BridgeForm.svelte#L293

**Comment by jscriptcoder** [comment]
Actually, the above is not correct. As explained by @cyberhorsey: "To allow the bridge to transfer tokens on your behalf, ERC20 has an approval/allowance mechanism. All tokens implement this, and the same logic/button/flow appears on say, Uniswap"... So it seems to be a UX issue, where the users are not well aware of these two steps, where if allowance if required, we need to first approve it. Second step is to bridge... Seems to though the second step is not really working. Investigating the issue

**Comment by dantaik** [comment]
Should we then close this issue?
