### ISSUE TITLE
need an interface that shows the node is running

### ISSUE THREAD

**Issue by AlperenCvs** [taikoxyz/taiko-mono#13554]
### Describe the feature request

When the node is built, we can't follow the occurrences and performance, we need an interface that shows the node is running

https://taiko.xyz/docs/guides/run-a-node There are commands and directions in the manual, I installed them I don't know if it works, but it can be understood from the blockchain, not everyone may know it

### Describe alternatives you've considered

need an interface that shows the node is running

### Additional context

Additional context here.

**Comment by wolfderechter** [comment]
There is a grafana dashboard that you can check to see if things are working but I agree a simple status page would be beneficial. I thought about it and came up with the following specs/requirements, feel free to add or criticize it.

Create a localhost HTML status page that shows some basic info with a clean/simple UI
- the current node status (syncing/running/failure?)
- the type of node (node/proposer/prover)
	-> each type could show additional info/metrics
	-> proposer: how many blocks proposed, earnings, how much ETH is left on L1
	-> prover: amount of proofs generated, your (average?) proving time, earnings, how much ETH is left on L1
- how long it has been running
- basic resource usage: how much storage, memory and CPU is used

Why?
- Have a clear and concise way to monitor the node/proposer/prover with relevant and useful metrics.

Why not the existing grafana board?
-> The current grafana board contains some good metrics but it's not as readable/accessible to newcomers and less tech-savvy

How?
- I'm thinking about a HTML status page that gets deployed with the simple-taiko-node docker package, most of the metrics should be able to be pulled from grafana. In addition a few metrics need to be calculated within the page
- Alternatively a grafana template could be used but I

**Comment by AlperenCvs** [comment]
Thank you, my English and node knowledge is insufficient, you explained everything very well, congratulations :)

**Comment by Eleleth77** [comment]
coming back to this with some layout ideas. Fully support the movement Wolfez. Let's build a great Taiko community NODE dapp

**Comment by cyberhorsey** [comment]
I could easily fork the general status page into something for this.

**Comment by AlperenCvs** [comment]
> Bunun için genel durum sayfasını kolayca bir şeye ayırabilirim. Tabii ki, tasarım çok basit, çünkü ben bir UI/UX uzmanı değilim, sadece 5 dakikada uydurdum. Ama buna benzeyen ve bazı yerel bilgilere sahip bir araç istiyorsanız, yapabilirim

Are the admins making the pull request?

**Comment by Eleleth77** [comment]
here is a mock-up of what Wolfer and I had been talking about. @cyberhorsey we are wondering whats the best way for us all to work together. Wolf has more programming knowledge, I have design. The preview you showed earlier today looked pretty good. Curious if you just want to make the whole thing, or if there is anything we can help with it.

Let us know what's best (also available to make a thread in DC and chat)

![Taiko Node GUI V1](https://user-images.githubusercontent.com/109436304/232350499-0095811d-9a74-414c-9183-a0890d19a38b.png)

**Comment by d1onys1us** [comment]
@cyberhorsey is this something you have the bandwidth to take for alpha-3 or should we see if a community member is interested to help?

**Comment by d1onys1us** [comment]
going to link this issue: https://github.com/taikoxyz/taiko-geth/issues/36 , i'm not too familiar with dappnode but I wonder if it exposes an extensible interface that we can get some things for free and then also add to it for our specific desires.

**Comment by davidtaikocha** [comment]
and if i remember correctly, @cyberhorsey was working on a status page which can be integrated into `simple-taiko-node`'s docker-compose yaml?

**Comment by mehdibouzit** [comment]
Hello,
I've been working on some dashboard using Panel and Holoviz (a Python library for creating dashboards). This is a WIP but would this kind of thing be interesting ?

![example](https://github.com/mehdibouzit/taiko-client-dashboard/blob/089e268a1035d95dc3cfa855dc6f5a92cf0f5392/app/doc/screenshots/node.PNG)

You can find the source code in my [repos](https://github.com/mehdibouzit/taiko-client-dashboard).

**Comment by wolfderechter** [comment]
Can be closed now with the release of https://github.com/wolfderechter/taiko-node-dashboard? :)
