### ISSUE TITLE
Remove x/y scaling in EIP1559 calculation

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13556]
### Describe the feature request

From Brecht:
> The `exp` implementation has as input and output values in 10**18 fixed format notation, so `exp(0) == 10**18`. Let's say that's 1 wei (so plenty of precision). The `exp` function also works with inputs up till `~135`, which will return an enormous number: `log10(exp(135)) == 58`. The total ETH supply is ~100,000,000 ETH, and 10*18 wei/ETH, so `log10(100,000,000*(10**18)) == 26`, much smaller than the max value returned by `exp`.

**Comment by dantaik** [comment]
I don't think it has something to do with value boundaries or accuracy, it's about finding the parameters to shape the curve's slope to ensure that at the initial best-guess price, the 2x/1x basefee ratio is as expected.

I tried but didn't find a way to just use one scaling factor to make it work.

**Comment by Brechtpd** [comment]
I think the y scaling can be avoided (I haven't done the math, so take with a grain of salt). To target `p` you would pick some `ADJUSTMENT_QUOTIENT` (total x scaling is done with `TARGET * ADJUSTMENT_QUOTIENT`). Then to get `gasExcess` to target some initial fee, you would just do the inverse basefee calculation:

```
initial_basefee = 10**8
gasExcess = (TARGET * ADJUSTMENT_QUOTIENT) * math.log(initial_basefee * (TARGET * ADJUSTMENT_QUOTIENT))
```

**Comment by dantaik** [comment]
I suggest that we keep it as-is to reduce risk. Removing y-scale still ends up with the same number of storage slots that we have to write (1 for now), the only small downside is that we have an extra DIV opcode to be optimized away, it's too small of a gain I think.
