### ISSUE TITLE
node setups wallet issue

### ISSUE THREAD

**Issue by AlperenCvs** [taikoxyz/taiko-mono#13553]
### Describe the bug

when installing node 
 cp .env.sample .env
After the sudo nano .env command, it didn't ask us to enter the wallet key and address, but it only wants the wallet key

the right one
![TAIKO1](https://user-images.githubusercontent.com/129639795/230260025-c94ed711-d898-434c-b9a4-1e59994bc2fa.png)
the problem experienced
![TAIKO](https://user-images.githubusercontent.com/129639795/230260091-25d7bcbd-39dd-4283-8e13-f136fc3164c3.png)

### Steps to reproduce

this line should be written in the missing place manually
L2_SUGGESTED_FEE_RECIPIENT=wallet adress

### Additional context

Additional context here.

**Comment by AlperenCvs** [comment]
feat(scope): description of feature

**Comment by AlperenCvs** [comment]
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]

**Comment by Mr-Cansky** [comment]
Can I use a different wallet for the SUGGESTED_FEE?

Example
L1_PROVER_PRIVATE_KEY= Wallet A
L2_SUGGESTED_FEE_RECIPIENT= Wallet B

**Comment by AlperenCvs** [comment]
no, it must be the same wallet address and key

**Comment by davidtaikocha** [comment]
> Can I use a different wallet for the SUGGESTED_FEE?
> 
> Example L1_PROVER_PRIVATE_KEY= Wallet A L2_SUGGESTED_FEE_RECIPIENT= Wallet B

I believe the answer is yes u can :)
