### ISSUE TITLE
feat: add private key guidance for running a node guide

### ISSUE THREAD

**Issue by Mr-Cansky** [taikoxyz/taiko-mono#13563]
### Describe the feature request

Could you please add a feature with details on how to securely enter or register wallet/private keys for operator nodes?

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by AlperenCvs** [comment]
Hello, you are setting up a new node, do you have this problem, there is no line to write the wallet address

https://github.com/taikoxyz/taiko-mono/issues/13553

**Comment by davidtaikocha** [comment]
Closed this since https://github.com/taikoxyz/taiko-mono/issues/13553 was closed.
