### ISSUE TITLE
fix: "Retry" When Bridge BLL

### ISSUE THREAD

**Issue by maltipoolabs** [taikoxyz/taiko-mono#13585]
### Describe the bug

![image](https://user-images.githubusercontent.com/107974770/230877799-55e94f40-4e3a-4505-9d31-32f9d866ad14.png)
Retry but on the TxHash it confirm and success
https://l2explorer.a2.taiko.xyz/tx/0x8d95b0590d1fa7895ceab74975d79c23e382f700a9c38add1bb241e47cc776da

### Steps to reproduce

Please fix this bug

### Additional context

When I try to click retry, its dasn't work.

**Comment by d1onys1us** [comment]
@jscriptcoder adding you. we can try testing this once the bridge is deployed on alpha-3. we can close it once we confirm that it works correctly.

**Comment by maltipoolabs** [comment]
Hi, thanks now brigde on taiko more better than before.
But, I lost my sepolia testnet before I swap again can you please send my sepolia testing
Thanks
Address
0xf3bad3aAabbDfb791DbcD2d3788D6Ac8EDD6bf8e
