### ISSUE TITLE
feat(swap): add % of total asset in swap page

### ISSUE THREAD

**Issue by ThanhLoc47** [taikoxyz/taiko-mono#13589]
### Describe the feature request

Having % of the total assets for the user will be convenient to select when swapping.

### Describe alternatives you've considered

<img width="471" alt="Screenshot 2023-04-10 at 11 23 02 PM" src="https://user-images.githubusercontent.com/35883152/230945204-e3f0ed13-886a-4054-bfb4-4e8495f43a64.png">
Provider % total asset like the picture above

**Comment by dantaik** [comment]
@je4nt0nic Assigned to you for evaluation.

**Comment by dantaik** [comment]
We'll launch Uniswap v3 UI.
