### ISSUE TITLE
block explorer update is not timely

### ISSUE THREAD

**Issue by guang123** [taikoxyz/taiko-mono#13584]
### Describe the bug

Browser data update is not timely

### Steps to reproduce

Browser data update is not timely

### Additional context

https://explorer.a2.taiko.xyz/address/0xbc7498F962a7824db42daC2CA6A5b3421EDe4aA8/internal-transactions#address-tabs 
<img width="925" alt="截屏2023-04-10 09 30 22" src="https://user-images.githubusercontent.com/7297098/230808328-20bc0fb3-9fe1-419c-a613-83c7a6cbdb79.png">

**Comment by d1onys1us** [comment]
adding this to the checklist of things to make sure are smooth on alpha-3, thanks!

**Comment by d1onys1us** [comment]
update: i tried this and i'm about to get the same issue. thank you very much for sharing. we might not be able to get this in for alpha-3 based on priority, but will definitely get it in as soon as we can.

here are the steps to reproduce for anyone checking this issue:
1. use an account with 0 transfers, and bridge some sepolia ETH on taiko
2. try to send some sepolia ETH to any address
3. enter the account address into block explorer and you should see transactions does not update


![Image](https://github.com/taikoxyz/taiko-mono/assets/13951458/785bd447-9b6f-4471-92c1-a8ed65f277e6)
