### ISSUE TITLE
Add liquid pool and staking 

### ISSUE THREAD

**Issue by hmz9742** [taikoxyz/taiko-mono#13588]
### Describe the feature request

If you can add liquidity pool and staking features to make a stress test

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
we did have the swap dapp deployed, and will continue to have that on the alpha-3 testnet release. if that's not what you mean, i can re-open the issue. thanks for the feedback!
