### ISSUE TITLE
Please allow me to turn several POOL

### ISSUE THREAD

**Issue by Chihyunpark1** [taikoxyz/taiko-mono#13595]
### Describe the feature request

Please allow me to spin several pools at the same time.

I want to spin more, but I can only spin one thing.

It allows you to turn several grasses.

It's not about expanding the area of the stable.

ETH - HORSE
ETH - BULL
We need a way to turn it around at the same time.

HORSE - ETH
HORSE - BULL

Right now, if we do one thing

The other one shuts down.

### Describe alternatives you've considered

I think you can allow it.

### Additional context

![767676](https://user-images.githubusercontent.com/130653226/231720301-83af54de-5ba2-4fda-b670-e10b858e6257.jpg)

**Comment by d1onys1us** [comment]
i am going to close this issue because we will re-deploy swap for alpha-3. also, i don't fully understand the issue. if you still face the problem in alpha-3, please open another issue. thanks for the feedback
