### ISSUE TITLE
fix: the ability of a transaction to be submitted even with insufficient balance

### ISSUE THREAD

**Issue by alhajincrypto** [taikoxyz/taiko-mono#13590]
### Describe the bug

while bridging from taiko A2 to sepolia network, i initiated a transaction to bridge 0.4 eth instead of 0.04. the transaction went through and was submitted as a pending transaction even when my eth balance was not sufficient. now i cant perform any other transaction as they all have to queue behind the pending transaction which has been up for a couple of hours. i expect the taiko team to tackle this issue by making sure transaction with insufficient balance are canceled and not sent to pending transactions. also users should be able to cancel pending transactions that are not going through.
![taiko issue](https://user-images.githubusercontent.com/123172224/231007620-fddce421-ec61-46c1-b56b-35d4e9b4a7cf.PNG)
![taiko issue 2](https://user-images.githubusercontent.com/123172224/231007884-cadbd9bc-cc04-4c31-8b22-7c1a4fc15090.PNG)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
cc @jscriptcoder @cyberhorsey

**Comment by jscriptcoder** [comment]
I take care of this one @d1onys1us ... Thanks @alhajincrypto for reporting.

**Comment by 2manslkh** [comment]
Fixed. Users can no longer click on the bridge button when they have insufficient ETH
