### ISSUE TITLE
fix(bridge-ui): pending claiming leaves the button enabled

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13607]
We have an issue when claiming tokens on the other chain: the button remains enabled while the transaction is ongoing

<img width="994" alt="Screenshot 2023-04-15 at 23 05 43" src="https://user-images.githubusercontent.com/613724/232229523-60e16cd7-3039-4e2a-b1aa-5a0e21772880.png">

**Comment by 2manslkh** [comment]
Issue has been fixed

<img width="1027" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/d3e215a9-c870-4a34-8507-bd8e69630772">
