### ISSUE TITLE
feat(bridge-ui): loading state for transactions

### ISSUE THREAD

**Issue by jscriptcoder** [taikoxyz/taiko-mono#13604]
Currently we don't show any loading state while waiting for transactions to arrive. It's a horrible experience.

<img width="383" alt="Screenshot 2023-04-15 at 15 21 03" src="https://user-images.githubusercontent.com/613724/232190297-486f6c06-da5a-4e89-a668-c8d120846dcf.png">

**Comment by 2manslkh** [comment]
![Image](https://github.com/taikoxyz/taiko-mono/assets/23635326/70e22f93-e24e-4db2-b7fc-a2038488a7be)


Bridge UI has been update ith this feature request.
