### ISSUE TITLE
fix: <Claim Bridge Transaction Waiting for Relayer>

### ISSUE THREAD

**Issue by DjangoBlockStar** [taikoxyz/taiko-mono#13612]
### Describe the bug

Can´t Claim. Waiting for Relayers infinite bug. Metamask don´t show acept transaction to complete the bridge

### Steps to reproduce

Realize a ETH bridge sepolia->Taiko A2.

### Additional context

Additional context here.

**Comment by Brzo1983** [comment]
Hi, it's working correct...i realized ETH bridge sepolia -> Taiko A2 10min ago. Try to change your processing fee and make higher then recommended ;)

**Comment by miront** [comment]
Hello,

I have an issue with the bridge.taiko.xyz.
The transaction is not claimed by the relayer for 50 hours and I can not claim it manually due to the recipient address is an exchange.

Any suggestions?
