### ISSUE TITLE
fix: <insert descriptive title here>

### ISSUE THREAD

**Issue by JSimon03** [taikoxyz/taiko-mono#13615]
### Describe the bug

High gas fees. The gas fees are way to high to claim tokens from the bridge from sepolia to taiko, hard to do much especially when the faucets are not giving much room to wiggle and claim those bridged assets.

### Steps to reproduce

Either give more test eth in the faucets or lower the gas fees for the transactions to be more smoother.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
the tx fees were very high during the last testnet due to the issues of the large mempool, alpha-3 testnet is coming soon which should address these issues, thanks for the feedback
