### ISSUE TITLE
feat: Bridge more than 1 hour has not been completed

### ISSUE THREAD

**Issue by rubyru17** [taikoxyz/taiko-mono#13614]
### Describe the feature request

I understand because this is still testing and still needs a lot of improvement, but it would be better if the team could add a realtime estimate of a transaction.  So that users can get more accurate estimates and don't need to check transactions repeatedly
![Screenshot_2023-04-16-14-21-54-442_site mises browser](https://user-images.githubusercontent.com/118650740/232280415-22973e77-feec-4c6f-bc91-88885b14178e.jpg)
![Screenshot_2023-04-16-14-21-29-165_site mises browser](https://user-images.githubusercontent.com/118650740/232280423-3844beff-f828-46cf-bdf3-b3dd0123809b.jpg)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by rubyru17** [comment]
8 hours have passed and still have to wait
![Screenshot_2023-04-16-21-15-28-856_site mises browser](https://user-images.githubusercontent.com/118650740/232319167-3c15edce-740b-4181-8b25-80be2951ddf2.jpg)
![Screenshot_2023-04-16-21-15-41-919_site mises browser](https://user-images.githubusercontent.com/118650740/232319178-ea71065e-2752-4c92-a48e-d57efdec3606.jpg)

**Comment by d1onys1us** [comment]
we are going to redesign the bridge and have read this feedback, thanks. if you find the issue again in alpha-3, please feel free to re-open an issue.
