### ISSUE TITLE
Upgrade alpha-3 testnet to use static AddressManager

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13669]
See https://github.com/taikoxyz/taiko-mono/pull/13668

**Comment by adaki2004** [comment]
Reminder (mainly to myself): When all the contracts are deployed we need to have a list of needed contracts (to be resolved), put them into a StaticAddressManager, deploy it.
Then re-deploy L1 with the new static contract address.

**Comment by davidtaikocha** [comment]
https://github.com/taikoxyz/taiko-mono/pull/13846
