### ISSUE TITLE
Merge status pages into blockscout clone 

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13682]
### Describe the feature request

As of now we have a status-page frontend (as a sub package of this project). Ideally, we can clone Blockscout and merge the status page into the landing page of the Blockscout explorer.

This is a nice project to start with if you are interested in contributing to Taiko as a frontend developer.

**Comment by d1onys1us** [comment]
this is a cool idea. i will tentatively triage this into `meta.alpha-4`, for now.

**Comment by sheenhx** [comment]
Just a friendly advice from MXC here, blockscout current version is not modifiable as the exlir is integrated with JS, we requested the V2 which separated the frontend to react, and we integrated Taiko status page here already : https://wannsee-explorer.mxc.com/

**Comment by dantaik** [comment]
@sheenhx We have gain access to BlockScout's V2 frontend code, what do you think is the best way to open source the dashboard you built for Taiko?

**Comment by cyberhorsey** [comment]
> @sheenhx We have gain access to BlockScout's[ V2 frontend](https://github.com/blockscout/frontend) code, what do you think is the best way to open source the dashboard you built for Taiko?

I don't have access to this URL yet. It would be helpful if MXC open source their changes, as we have added some new status changes as well since, and perhaps we could maintain it ongoing as we add new metrics as well

**Comment by miguelmagalhaes02** [comment]
Someone have access to the first version of the Taiko testnet block explorer? I've made some txs months ago and I can't check them on block explorer

**Comment by dscorpionking** [comment]
I think this will be a great move
