### ISSUE TITLE
Create an example to use foundry to deploy contracts onto Taiko

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13696]
We should create an example (people can simply copy) to deploy their contracts to Taiko using foundry and/or hardhat. Ideally we also create a Youtube video so people can follow and learn.

**Comment by d1onys1us** [comment]
closing this because i'm including it in my alpha-3 docs PR. Also, created a separate issue for youtube videos: https://github.com/taikoxyz/taiko-mono/issues/13766
