### ISSUE TITLE
Improve SignalService

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13694]
### Describe the bug

Because this contract is now kind of built into the protocol, it'd be kind of nice to make it as simple as possible. I think the contract could be as simple as:
```
mapping(address addr => mapping (bytes32 key => bytes32 value)) public data;

function store(bytes32 key, bytes32 value) public {
  data[msg.sender][key] = value;
}
```
All other functionality could be implemented using a library on top of this. That makes it much easier to update and also provides some extra flexibility (like being able to store data directly in the value which allows a smart contract on the source chain to still have access to the data directly instead of having to store it both on L1 and send a signal to get it to the other chain as well).

**Comment by dantaik** [comment]
This will break existing tests, so lets be cautious and do it only when necessary.

**Comment by Brechtpd** [comment]
I think not done? I still think this would be a significant improvement that also makes sure we won't ever have to worry having to upgrade this contract.
