### ISSUE TITLE
Developer dapp challenges

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13697]
I steal this idea from Marcus Wentz.
Lets create a list of dapp challenges so developers can submit and earn a reward. The difficulty shall increase over time.

**Comment by d1onys1us** [comment]
i'm not sure if we can make this into alpha-3 but we'll try to and keep it triaged here.

also wanted to share this (possibly related), optimism quests: https://app.optimism.io/quests . maybe these dapp challenges are a form of a "quest"

**Comment by 2manslkh** [comment]
Possibly move this to the grants repo? @dantaik @d1onys1us
