### ISSUE TITLE
feat(protocol): basic multi-prover with SGX

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/taiko-mono#13693]
https://ethresear.ch/t/2fa-zk-rollups-using-sgx/14462

While nobody is a fan of SGX, it only really adds to the security of the rollup without any real downside, while being very simple (compared to a whole new proving system).

This also significantly reduces the importance of the oracle prover and cooldown period, especially while the zk coverage is incomplete.

**Comment by dantaik** [comment]
See https://github.com/taikoxyz/taiko-mono/pull/14851
