### ISSUE TITLE
Adjust code to 18 decimals of TKO

### ISSUE THREAD

**Issue by adaki2004** [taikoxyz/taiko-mono#13706]
Currenlty the tests and code is designed for 8 decimals of TKO. Now the main branch has 18 so need to add support to that (in testing and possibly checking side effects if any within the code. (underflow, overflow ?))

**Comment by dantaik** [comment]
After reading [this post](https://www.reddit.com/r/ethdev/comments/7nowxv/using_more_or_less_than_18_decimals_please_dont/), I no longer believe we have to change the decimals from 8 to 18. I'm open to discuession.
