### ISSUE TITLE
Combine status page and block explorer

### ISSUE THREAD

**Issue by DAOmindbreaker** [taikoxyz/taiko-mono#13710]
Status page, separate explore makes it less efficient. As well as adding the revoke feature will be better in future transactions.

**Comment by dantaik** [comment]
<img width="1221" alt="Screenshot 2023-05-20 at 14 25 47" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/f8fb63b7-c07d-408a-82f3-2fc3b9a6425b">

A project called MXC has actually built a dashboard into BlockScout's latest React-based UI. We just need to wait for the new UI to be open-sourced and do something similar.

**Comment by DAOmindbreaker** [comment]
Okay sir

Pada tanggal Sab, 20 Mei 2023 14.14, Daniel Wang ***@***.***>
menulis:
