### ISSUE TITLE
feat(node): implement another Taiko client

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13717]
The current Taiko client is based on GoEthereum, we may want to implement another client as the first step for client diversity.

<img width="712" alt="Screenshot 2023-05-08 at 13 27 17" src="https://user-images.githubusercontent.com/99078276/236742066-e080b525-bcb5-4c15-a2a9-c9a611b5960b.png">

According to [Ethereum's client diversity status](https://ethereum.org/en/developers/docs/nodes-and-clients/client-diversity/):

- Open Ethereum: deprecated
- [Erigon](https://github.com/ledgerwatch/erigon)  uses golang
-  [Nethermind](https://github.com/NethermindEth/nethermind) uses C#

Since we do not have C# experience, maybe we should go with Erigon?

**Comment by wolfderechter** [comment]
I love this idea! I'm not sure about the priority on this but perhaps https://github.com/paradigmxyz/reth could be worth it, if the team has some rust experience of course. It's still in early stage though
