### ISSUE TITLE
Stuck at compiling when deploy contracts using foundry

### ISSUE THREAD

**Issue by wangtsiao** [taikoxyz/taiko-mono#13718]
Currently, taiko uses `forge` to deploy contracts, as we can see from [here](https://github.com/taikoxyz/taiko-mono/blob/main/packages/protocol/script/test_deploy_on_l1.sh#L16).

When I try to deploy contracts using the following command
```
pnpm deploy:foundry
```

It became frozen at compiling.

```
base ❯ pnpm deploy:foundry

> @taiko/protocol@0.6.1 deploy:foundry /Users/tsiao/Desktop/windranger-labs/taiko-mono/packages/protocol
> ./script/download_solc.sh && ./script/test_deploy_on_l1.sh

[⠔] Compiling...
[⠑] Compiling 165 files with 0.8.18
```

When I remove flag `--via-ir`, run the following command
```
base ❯ forge script script/DeployOnL1.s.sol:DeployOnL1 --fork-url http://localhost:8545 --broadcast --ffi -vvvv         
[⠃] Compiling...
No files changed, compilation skipped
Error: 
Failed to deploy script:
Execution reverted: EvmError: Revert (gas: 1550653)
```

**Comment by cyberhorsey** [comment]
This was an issue with the new plonk verifier, created a PR:
https://github.com/taikoxyz/taiko-mono/pull/13740

thanks for reporting!
