### ISSUE TITLE
feat(bridge-ui): add info on other layers and link to other bridge

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/taiko-mono#13733]
### Describe the feature request

With alpha-3, we will have multiple bridge sites in which a user will need to navigate to in order to bridge assets between layers. It may help users better navigate and understand where funds are at (which layer) if we include more information on the bridge sites. For example:

1.  Show the wallet address's funds on each Layer
- If user selects XXX as the bridged token, we should display the amount of XXX on each Layer

2. A button/link that directs the user to the other bridge site for easy navigation

Thanks for the consideration.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Hi @ablankstory, could you explain what you mean by multiple bridge sites? Currently, we will only have 1 bridge site: https://bridge.test.taiko.xyz/ to bridge from L1 Sepolia <> Taiko A3 testnet.

**Comment by 2manslkh** [comment]
Perhaps it is also good to show the balance on all chains on one page instead of having to switch between chains to view the  balance on the other chain

**Comment by 2manslkh** [comment]
We are currently revamping on our bridge ui so that the user experience is closer to what you have mentioned.

<img width="635" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/9e3fbcce-9b29-482a-9cf0-d1cd70de2679">
