### ISSUE TITLE
feat(protocol): Token vault can not handle ERC20s behind proxy's

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#13739]
### Describe the feature request

TokenVault should be able to handle ERC20s behind proxies, or at least determine if it is behind a proxy and fail gracefully.

**Comment by dantaik** [comment]
Jeff, ERC20 proxies shall be transparent to function callers, or did I miss something?

**Comment by davidtaikocha** [comment]
Closed due to TTKO works on A3 tokenVault
