### ISSUE TITLE
Block fee in internal devnet keeps increasing exponentially

### ISSUE THREAD

**Issue by davidtaikocha** [taikoxyz/taiko-mono#13765]
Block fee in internal devnet keeps increasing exponentially, in last ~14 hrs:
<img width="812" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/104078303/386110f0-b229-4739-9055-6166f55371fa">

Latest protocol status:

<img width="455" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/104078303/560cccf9-0df6-4bb9-bb18-2ebdd259989b">

The average block time is ~30s:

<img width="1327" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/104078303/ee267bc5-8a06-4271-bd36-c001b6f35851">

Will add more detailed info later on, plz correct me if i mis-configured anything.

**Comment by davidtaikocha** [comment]
> As discussed in DMs, here are my notes:
> 
> * If proof time (averages out) always above the proofTimeTarget the fees will be ever increasing
> * If proof time (averages out) always below the proofTimeTarget the fees will be ever decreasing
> * This way proofTimeTarget should be a healthy / pre calculated limit and transparently communicated towards stakeholders, to know and adjust their behaviour so in case proof reward are not covering their costs, simply keep proving more slowly
> * Hard to test on testnet if they have no real costs and reasonable thinking but the intention is to prove ASAP
> * The update mechanism (of the contract) is complex therefore modifying the target with a setProofTimeTarget() could have been easier (for testnet).

Yep after the discussion with Dani, i believe the reason is the proof submission time of each block in internal devnet is all above the `proofTimeTarget` a bit, which leads to the fee to be ever increasing. But since the `proofTimeTarget` is a fixed value, seems its hard to "hardcode" this to a right value beforehand. And also since provers will keep improving their circuits during the testnet, which means we may need to keep changing the fixed `proofTimeTarget` value during the testnet by replacing the proxy implementation.

**Comment by Brechtpd** [comment]
> And also since provers will keep improving their circuits during the testnet, which means we may need to keep changing the fixed proofTimeTarget value during the testnet by replacing the proxy implementation.

The target is not meant to track the actual prover time closely, it's important that it's a reasonable value that is significantly larger than the expected proof time.

> So conclusion: once we change the proofTimeTarget we need to adjust also the initProofTimeIssued as well - which we could not do ATM. I will open a new PR to change proofTimeTarget to state var, and being able to change together with the proofTimeIssued.

This will indeed be helpful when we update the circuits and the proof generation time increases drastically.

> How do we incentivize provers to act 'responsibly' AKA submit proofs as they were cost them something ? Because i see provers trying to rush to submit them ASAP - not really caring about a target. On mainnet this would not be an issue, if proofs actually costs money, but here is just a race of 'do i get something as a reward' (if im the first prover) or not. No real incentives tied to it. Maybe we can reward provers somehow tied to the TKO acquired by proving - and correlating with the amount as well.. ? Otherwise it will be just a race who submits first.. ?

On testnet it's Proof of Speculation. :)

**Comment by davidtaikocha** [comment]
> The target is not meant to track the actual prover time closely, it's important that it's a reasonable value that is significantly larger than the expected proof time.

![image](https://github.com/taikoxyz/taiko-mono/assets/104078303/b94874dc-dd5c-47fd-86a3-023d94f3969e)

hmm another fact observed after i changed the target proof time to a value (200 seconds) which is significantly larger than the expected proof time (80 seconds), so the block fee started decreasing, and at this point its `0`, so proposing should be free in current internal devnet right now (proposing fee is equal to `blockFee` right now)... which is also not what we want?

**Comment by Brechtpd** [comment]
Provers decide on their expected prover fee when they submit their proof compared to the proof target time (which is why the proof target needs to be high enough so even "slow" provers can "vote" on the fee, because we prefer cheaper proofs over more expensive and faster proofs). Provers should _not_ submit the proof as soon as they have it. Most of the time provers should just submit their proof at the proof target time (which will make the prover fee remain the same). Provers should only submit the proof faster than the proof target time if they are okay with a lower fee (and they would only do so to out compete other provers).

**Comment by cyberhorsey** [comment]
> Provers decide on their expected prover fee when they submit their proof compared to the proof target time (which is why the proof target needs to be high enough so even "slow" provers can "vote" on the fee, because we prefer cheaper proofs over more expensive and faster proofs). Provers should _not_ submit the proof as soon as they have it. Most of the time provers should just submit their proof at the proof target time (which will make the prover fee remain the same). Provers should only submit the proof faster than the proof target time if they are okay with a lower fee (and they would only do so to out compete other provers).

If they race to the bottom competing each other doesn't it go to 0 and the baseFee is also the fee for proposing so proposing is also free and they can spam the network?

**Comment by Brechtpd** [comment]
Proposing has a separate EIP 1559 style fee that is only related to the proposing, basically the same how it works in Ethereum. The target is in gas/s. So if the amount of work proposed in blocks is higher than that target then the proposing fee goes up. This is fully separate from the proving fee.

Because this proposing fee can raise very quickly, this should even work on testnet.

**Comment by dantaik** [comment]
@d1onys1us Please note that we need to explain this to potential provers in our testnet. Previously, provers submit proofs ASAP but if they do that with this tokenomics, eventually reward goes to 0.
