### ISSUE TITLE
Separate Taiko L1 multi-prover logic into a separate verifier contract

### ISSUE THREAD

**Issue by adaki2004** [taikoxyz/taiko-mono#13777]
### Describe the feature request

Separating the current multi-prover (L1/libs/proofTypes/*.*) logic into a new verifier contract.

Protocol would be simplified and changes in the proving logic like: skipping N proofs, accepting super signatures would have nothing to do with the protocol and not imply protocol re-deployments.

### Additional context

Issues's dependency is that this https://github.com/taikoxyz/taiko-mono/pull/13745  PR is done.

**Comment by dantaik** [comment]
I would suggest this to be a low priority and lets get the tokenomics fully figured out before moving to multiproof support.

**Comment by dantaik** [comment]
This is done already.
