### ISSUE TITLE
feat: Separate Tokenomics from Core Protocol to a Controller Contract

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13791]
Currently, tokenomics is tightly integrated with the core protocol. I suggest decoupling the tokenomics code into a distinct contract. This division would:

1. Streamline the core protocol, improving testability.
2. Promote codebase reusability, enabling others to employ it independently of our tokenomics.
3. Simplify tokenomics testing by eliminating the need for proposing/proving actual blocks.
4. Allow concurrent tokenomics deployment across different L3 testnets without altering the core protocol.
5. Facilitate safer upgradability, leaving the core protocol undisturbed when tokenomics updates are necessary.

This decoupling, however, might inflate gas costs.

Certain implementation precautions are necessary:

1. The tokenomics contract should not hold custody of user-deposited TaikoTokens; this role should remain with the core protocol to prevent token migration during a tokenomics switch or we should simply avoid user-deposited TaikoTokens (see below). 
2. To minimize gas costs, a single call to the tokenomics contract should be implemented when multiple blocks are verified.
3. If **_tokenomics_** lookup resolves to '0x0', it signifies the absence of tokenomics (the core protocol shall still work as a permissionless rollup)

It may be beneficial to rename 'tokenomics' to a more representative term like **_controller_**. This contract could whitelist proposer/prover addresses without token or tokenomics involvement. For example, a company could create a simple **_controller_** contract for deploying a centralized, permissioned Taiko rollup without a token.

Considering the core protocol may not require a token, we might want to remove `taikoTokenBalances` and associated functions from the core protocol. The controller contract could then undertake token minting/burning operations if tokens are introduced.

**Comment by Brechtpd** [comment]
With tokenomics you mean the proposer selection/prover selection/fee system right? (I think that goes well above what people would normally understand under tokenomics so just making sure).

Yes I think we should do this, same with the verifier contracts this will otherwise get too messy if we want to make this more flexible/modular.

> This decoupling, however, might inflate gas costs.
> To minimize gas costs, a single call to the tokenomics contract should be implemented when multiple blocks are verified.

If it makes things significantly simpler I think it should be fine to call for each block. With how current gas costs are set up to make warm storage reads/writes very cheap compared to cold ones (even true for calls), the gas savings probably won't be that significant while the complexity of batching things could be high (and also costs gas).

> The tokenomics contract should not hold custody of user-deposited TaikoTokens; this role should remain with the core protocol to prevent token migration during a tokenomics switch or we should simply avoid user-deposited TaikoTokens (see below).
> Considering the core protocol may not require a token, we might want to remove taikoTokenBalances and associated functions from the core protocol. The controller contract could then undertake token minting/burning operations if tokens are introduced.

There could still be a shared independent smart contract where funds could be stored that could be used by multiple Taiko instances (sure, costs some extra gas), it'll be up to the specific instance to use that or not, but could make sense depending on how the selection mechanism works.

**Comment by dantaik** [comment]
Brecht, appreciate your insights. Contemplating on this issue and Dani's PR, which isolates verifier logic into a separate contract, I still want to advocate for cost-optimization over composability. In the long run, any third party utilizing our code will inevitably modify it to minimize gas costs and eliminate inter-contract calls, nullifying the benefit of contract division.

I propose leveraging inheritance. The core protocol could simply define empty virtual functions, allowing derived contracts to override these with bespoke logic.

**Comment by dantaik** [comment]
FYI, the extra cost of using independent contracts is roughly 4600.

**Comment by Brechtpd** [comment]
I would actually argue for the opposite, too much focus on gas costs at this point. It's very easy to optimize things once we're happy with the functionality and design (in this case: just replace the external contract call by an internal library call and you're done). Optimizing each step towards that final design is just wasted effort I feel. 

I agree that we don't want to be more flexible than needed and so don't want to add functions/APIs that we don't need at this point.

**Comment by Brechtpd** [comment]
So a bit more on why I think optimizing at this point is early: things will still change, pretty significantly as far as I currently know, and who knows what else will come up in the next months. And even the things we know that still have to change aren't fully figured out yet.

- One with a very big impact on gas costs is block aggregation: https://github.com/taikoxyz/zkevm-circuits/issues/85. Depending on how this is implemented, this will very likely impact how blocks are proven and how the prover fee system works
- Once that's figured out I think we can look at the prover system again: auction, the proving system that shall not be named, ... So potentially many changes to how blocks are proven and paid for.
- SGX prover: https://github.com/taikoxyz/taiko-mono/issues/13693: Still to be fully figured out, but unlikely to work with a single ECDSA signature if we want to do it in a decentralized way with multiple provers being able to run their own SGX provers. (They'll have to prove that what they are running is genuine, and then they can generate their own proofs using their own keys will need some additional smart contract support which will very likely make sense to do in its own contract). Also multiple nodes in SGX, different TEE support, etc...
- Unprovable blocks: https://github.com/taikoxyz/taiko-mono/issues/13724. Likely only minor changes necessary to the smart contracts/circuits, most of the changes should be on the node level
- Different testnet/L3 setups that is just throw away code and ideally should not touch the actual core contracts at all
- More that I forgot or we simply don't know yet

Implementing these and making sure they work: not so easy.
Optimizing code that works and is tested: pretty easy I think.

**Comment by Brechtpd** [comment]
Honestly I'm probably also somewhere in the middle!

My main point is simply that for me it seems we should optimize for simplicity and ease of changing things. We're not planning on using the protocol on mainnet very soon so why worry so much about gas costs? Realistically we're gonna go through a couple of iterations before we get something we'll actually want to deploy on mainnet, so I don't see a reason we should try and optimize each iteration as much as possible and then throw it away anyway.
