### ISSUE TITLE
feat: skip checking withdrawalsRoot in circuits and client

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#13795]
As of now,  the `withdrawalsRoot` in Taiko blockheader is the hash of a list of EthDeposits from L1 to L2. In both circuits and client, we check this value is correctly calculated and matches the actual EthDepoisits.

To simpify the code is to enforce `withdrawalsRoot` to have the value of the **empty MPT withdrawals root** (not `0x0`) . In the circuits, verify the hash of the list of EthDeposits actually match the value used by the protocol to calculate the right metahash.

<img width="766" alt="Screenshot 2023-05-22 at 22 41 52" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/6b195665-7255-4d71-929e-e7c15013fce0">

**Comment by Brechtpd** [comment]
> To simpify the code is to enforce withdrawalsRoot to have the value of 0x1 (not 0x0) 

If we set it to some constant value, I think better to use the empty MPT withdrawals root as the constant because then the block header still looks like a standard Ethereum one.

**Comment by dantaik** [comment]
An updated diagram based on the above idea is here: https://github.com/taikoxyz/taiko-mono/blob/prover_req_diagram_depositsRoot/packages/protocol/docs/how_taiko_proves_blocks.md

**Comment by davidtaikocha** [comment]
> FYI right now the empty hash for the withdrawals is the empty code hash, not empty MPT withdrawals hash. #13795

yep its because the empty code hash is equal to `keccak256(zero bytes)` which is the current protocol implementation, if we don't want do the `keccak256` hash for the withdrawals anymore in protocol, we need to change back to the empty MPT withdrawals hash.

**Comment by dantaik** [comment]
I think we can just leave the implementation as-is?
