### ISSUE TITLE
Zonic NFT Testnet Support

### ISSUE THREAD

**Issue by sami1811** [taikoxyz/taiko-mono#13797]
### Describe the feature request

It would be great if Taiko has Zonic NFT testnet support so developer can test multiple NFT functions after deployment. Functions like minting, unrevealing, burning and whitelisting would be easy for developers to test.

### Describe alternatives you've considered

Taiko can come up with its own Testnet NFT marketplace and that would be much better as Zonic is quite slow atm coz of multiple chain support.

### Additional context

Additional context here.

**Comment by mfinestone** [comment]
Hi @sami1811 , thanks for the issue. Are you a developer/contributor for the Zonic marketplace? It would be nice to have Taiko testnet support in there!

If not, are you interested in trying to build the alternative you mention? I think that would indeed be great if you are up for it.

**Comment by sami1811** [comment]
I'm a developer at beginner level and not yet a contributor but im willing to help always. I can share the idea with zonic team, still waiting for the response. We also need Taiko's own NFT marketplace as im learning frontend i can help with that too.

**Comment by sami1811** [comment]
> Hi @sami1811 , thanks for the issue. Are you a developer/contributor for the Zonic marketplace? It would be nice to have Taiko testnet support in there!
> 
> If not, are you interested in trying to build the alternative you mention? I think that would indeed be great if you are up for it.



> Hi @sami1811 , thanks for the issue. Are you a developer/contributor for the Zonic marketplace? It would be nice to have Taiko testnet support in there!
> 
> If not, are you interested in trying to build the alternative you mention? I think that would indeed be great if you are up for it.

I'm a developer at beginner level and not yet a contributor but im willing to help always. I have shared the idea with zonic team, still waiting for the response. We also need Taiko's own NFT marketplace as im learning frontend i can help with that too.

**Comment by 2manslkh** [comment]
Hi @sami1811 would you like to help to get Zonic to deploy their contracts on Taiko A3 testnet?

**Comment by theCast91** [comment]
I think it's a good idea.

**Comment by MykolaIW** [comment]
nice

**Comment by sami1811** [comment]
> Hi @sami1811 would you like to help to get Zonic to deploy their contracts on Taiko A3 testnet?

I contacted Zonic team they said the team hava listed Taiko and working on it.

**Comment by d1onys1us** [comment]
> > Hi @sami1811 would you like to help to get Zonic to deploy their contracts on Taiko A3 testnet?
> 
> I contacted Zonic team they said the team hava listed Taiko and working on it.

thanks sami! can you please ask the Zonic team to open an issue here once it is integrated: https://github.com/taikoxyz/taiko-mono/issues/new?assignees=&labels=category.enhancement%2Cstatus.needs-triage&projects=&template=add_project.yml

they can also follow the integration guide here: https://taiko.xyz/docs/resources/integration-guide

**Comment by 2manslkh** [comment]
@sami1811 Any updates on this?
