### ISSUE TITLE
feat(protocol): add an event for each block's reward for a3

### ISSUE THREAD

**Issue by hatark** [taikoxyz/taiko-mono#13807]
### Describe the feature request

Each time when a block is verified, we can emit an event to tell how much the block's proving reward is (also proposing reward if there is any). I think it's better to make this data clear for provers (and maybe proposers) and helpful to show it in dashboard like [this](https://data.zkpool.io/public/dashboards/JHDtVb3J6E2v1crgDAMkcE0xKqAzDSluJXUufWqe?org_slug=default&p_w59_time_range=Last%204%20Hours&p_w60_time_range=Last%204%20Hours&p_w61_time_range=Last%207%20Days) for a3.

Now we have no way to check how much the block-wise reward is. `function getProofReward(uint64 proofTime) public view returns (uint64)` since this function is non-deterministic so we can't use it to get this data.

**Comment by cyberhorsey** [comment]
Closed by #13808
