### ISSUE TITLE
Update configs in `TaikoConfig.sol` \ `EIP1559Params` for Alpha 3 testnet

### ISSUE THREAD

**Issue by davidtaikocha** [taikoxyz/taiko-mono#13802]
Current config (we will change `chainId` for sure, and what else?):
```solidity
library TaikoConfig {
    function getConfig() internal pure returns (TaikoData.Config memory) {
        return TaikoData.Config({
            chainId: 167,
            // Two weeks if avg block time is 10 seconds
            maxNumProposedBlocks: 120960,
            ringBufferSize: 120960 + 10,
            // Each time one more block is verified, there will be ~20k
            // more gas cost.
            maxVerificationsPerTx: 10,
            // Set it to 6M, since its the upper limit of the Alpha-2
            // testnet's circuits.
            blockMaxGasLimit: 6000000,
            // Set it to 79  (+1 TaikoL2.anchor transaction = 80),
            // and 80 is the upper limit of the Alpha-2 testnet's circuits.
            maxTransactionsPerBlock: 79,
            minEthDepositsPerBlock: 8,
            maxEthDepositsPerBlock: 32,
            maxEthDepositAmount: 10000 ether,
            minEthDepositAmount: 1 ether,
            // Set it to 120KB, since 128KB is the upper size limit
            // of a geth transaction, so using 120KB for the proposed
            // transactions list calldata, 8K for the remaining tx fields.
            maxBytesPerTxList: 120000,
            proofCooldownPeriod: 30 minutes,
            systemProofCooldownPeriod: 15 minutes,
            // Only need 1 real zkp per 10 blocks.
            // If block number is N, then only when N % 10 == 0, the real ZKP
            // is needed. For mainnet, this must be 0 or 1.
            realProofSkipSize: 10,
            ethDepositGas: 21000,
            ethDepositMaxFee: 1 ether / 10,
            txListCacheExpiry: 0,
            adjustmentQuotient: 16,
            relaySignalRoot: false
        });
    }
}
```

And we also need to create a `EIP1559Params` for the testnet:

```solidity
struct EIP1559Params {
        uint64 basefee;
        uint64 gasIssuedPerSecond;
        uint64 gasExcessMax;
        uint64 gasTarget;
        uint64 ratio2x1x;
}
```

**Comment by Brechtpd** [comment]
Do Sepolia faucets give users >= 1 ETH (to be able to test ETH deposits, `minEthDepositAmount`)?

In general looking at these ETH deposit parameters, the UX for ETH deposits is gonna be very challenging with the current system/values I think.

**Comment by davidtaikocha** [comment]
> Do Sepolia faucets give users >= 1 ETH (to be able to test ETH deposits, `minEthDepositAmount`)?
> 
> In general looking at these ETH deposit parameters, the UX for ETH deposits is gonna be very challenging with the current system/values I think.

i believe some of them can give users >= 1 ETH, like the PoW one, but not sure the actual percentage, cc @d1onys1us . and hmm actually this feature is not supported in current bridge UI, so users have to do this by calling the `TaikoL1.depositEtherToL2()` manually, also not sure how many of them will use it.

**Comment by d1onys1us** [comment]
> > Do Sepolia faucets give users >= 1 ETH (to be able to test ETH deposits, `minEthDepositAmount`)?
> > In general looking at these ETH deposit parameters, the UX for ETH deposits is gonna be very challenging with the current system/values I think.
> 
> i believe some of them can give users >= 1 ETH, like the PoW one, but not sure the actual percentage, cc @d1onys1us . and hmm actually this feature is not supported in current bridge UI, so users have to do this by calling the `TaikoL1.depositEtherToL2()` manually, also not sure how many of them will use it.

Yes it is possible for this faucet to give 1 ETH eventually but it is not easy, the user will need to wait for a period of time to get the 1 ETH. By the time they have to wait... they might lose interest. If we can do 0.1 ETH it will definitely be better from the perspective of the users.

**Comment by dantaik** [comment]
Smaller value shall be fine as long as it covers the fee. So I guess even 0.01 Ether will work.
