### ISSUE TITLE
Broken Website Link

### ISSUE THREAD

**Issue by spachib** [taikoxyz/taiko-mono#13826]
### Describe the bug

There's a broken link on the Docs homepage. The page code in repo is [here](https://github.com/taikoxyz/taiko-mono/blob/7ed816d8db7ac75468faa235c09f147db5009034/packages/website/pages/docs/index.mdx?plain=1#L11). I would have filed a pull request but it seems the link is correct in the code.

### Steps to reproduce

From taiko.xyz homepage click on the Docs link in the header bar, then scroll down and observe the contribution guide link is broken , it's missing the .md extension.

### Additional context

Additional context here.
![image](https://github.com/taikoxyz/taiko-mono/assets/34748551/83cebf05-e483-4f7b-9cdf-a39494ef0375)

**Comment by spachib** [comment]
Another broken link [here](https://github.com/taikoxyz/taiko-mono/blob/7ed816d8db7ac75468faa235c09f147db5009034/packages/website/pages/docs/concepts/proving-taiko-blocks/provers.mdx?plain=1#L1)

**Comment by spachib** [comment]
At https://taiko.xyz/docs/reference on the live site the RPC Configuration header link and the Contract Addresses header link are broken

**Comment by spachib** [comment]
At https://taiko.xyz/docs/resources on the live site the Presentations link is broken

**Comment by dantaik** [comment]
This should have been fixed by https://github.com/taikoxyz/taiko-mono/pull/13840
