### ISSUE TITLE
LibBridgeRetry backward gasLimit check comments vs code

### ISSUE THREAD

**Issue by zobront** [taikoxyz/taiko-mono#13833]
### Describe the bug

In the `retryMessage()` function in [LibBridgeRetry.sol](https://github.com/taikoxyz/taiko-mono/blob/main/packages/protocol/contracts/bridge/libs/LibBridgeRetry.sol), the check for situation in which the owner must be the caller is backwards from what's specified in the comments.

```
// If the gasLimit is not set to 0 or isLastAttempt is true, the
// address calling this function must be message.owner.
if (message.gasLimit == 0 || isLastAttempt) {
    if (msg.sender != message.owner) revert B_DENIED();
}
```

### Steps to reproduce

N/A

### Additional context

I _think_ the code is correct and the comment is backwards (it would make more sense to me that `gasLimit = 0` would denote owner only), but not positive, so wanted to submit just in case.

**Comment by dantaik** [comment]
Fixed in https://github.com/taikoxyz/taiko-mono/pull/13829. It will be nice for you to double check my change.

**Comment by zobront** [comment]
Looks good to me, but as I mentioned, that’s with the assumption that the
code was right and comment was wrong.

That seems logical to me, but I don’t know the complete system well enough
to be sure of that fact.
