### ISSUE TITLE
feat(docs): provide info about prover/proposer simple tokenomics

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#13869]
### Describe the feature request

Provide some info about the tokenomics for the provers
 -  have eth on L1 and receive TKO(?) for blocks proved on L1

and proposers:
 - have eth on L1 and receive eth on L2
 - info about that we can change the L2_SUGGESTED_FEE_RECIPIENT for proposers 

Just some quick and easy to understand tokenomics for the node types would be useful so people know how to prepare and how it works

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
As mentioned in our Discord we should describe the formula for proposer rewards

**Comment by nollie0107** [comment]
@d1onys1us 

Where is the official mention of the reward in the DISCODE about this?

**Comment by nollie0107** [comment]
https://taiko.mirror.xyz/wD7yN8Y5RttbP7kzdtX22GbMg6i18a-Xwet2sshpt48

I found it. I will try as soon as I have time.

**Comment by dantaik** [comment]
I'll talk to our content team to come up a new article to explain our alpha-5 tokenomics.
