### ISSUE TITLE
feat(website): add back auto-generated documentation

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/taiko-mono#13923]
## Summary

We removed auto-generated documentation because there are multiple versions of code in our repo supporting multiple testnets. We have the main branch, alpha-4 branch, and alpha-3 branch.

Thus, it was not clear: to what testnet is this auto-generated documentation referring to?

## Definition of done

1. Add back auto-generated documentation
2. Make sure it is clear what this documentation is referring to (which testnet)

## Additional ideas

Keep in mind on the blockscout explorers it is possible to view the full code for the smart contracts. Is it better to parse the natspec, or would it be better to just link to these core protocol contracts where users can see the full / complete code?

The user is interested in not just generated output / descriptions of contracts, but what set of contracts are deployed for our bridge, core rollup protocol, etc. Can take a look at the domain/config inside the packages/website and DeployOnL1.s.sol (L1 contract deployment script) for inspiration on what are the interesting contract for users to explore.

**Comment by Yang-Jiaxin-Jim** [comment]
Newbie here, but trying to work on Update contracts with natspec.

**Comment by d1onys1us** [comment]
updated the issue description / title as a few of these were completed.

**Comment by dantaik** [comment]
@d1onys1us do you think now it's a good time to add these auto-gen docs back, given that the big protocol PR has been merged?
