### ISSUE TITLE
feat(bridge-ui): add checks for sufficient ETH on destination chain when selecting "None" option for Processing Fee

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/taiko-mono#13936]
The bridge app on the destination chain will show a "Waiting for Relayer" error although the "None" option is selected for Processing Fee.

**Steps to replicate issue:**

1. Create new wallet address with 0 ETH on destination & source chain.
2. Get some ETH on source chain
3. Bridge any amount of ETH and select the "None" option for Processing Fee
4. While having 0 ETH on the source chain, click on claim under the transaction tab
5. See error popup

![Image](https://github.com/taikoxyz/taiko-mono/assets/23635326/ef60a7e7-e1a4-4400-a744-98d5bd0e1ef5)

6. Top up some ETH on the destination chain, enough to claim the ETH. Error should go away.

**Suggestion**

Check the balance of ETH on the destination chain before allowing the user to select the "None" option under Processing Fee

**Comment by cyberhorsey** [comment]
The bridge is being redesigned so this probably won't get done for current bridge. @jscriptcoder this is a good idea if it's not currently in bridge v2.

**Comment by jscriptcoder** [comment]
... and this is actually an excellent timing. I'm right now working on the Processing Fee part of the bridge, https://github.com/taikoxyz/taiko-mono/pull/14170. I'll include this
cc: @cyberhorsey @2manslkh

**Comment by dantaik** [comment]
@jscriptcoder
