### ISSUE TITLE
NATIVE TAIKO POWERED AMM (AUTOMATED MARKET MAKER) ON TESTNET

### ISSUE THREAD

**Issue by Scottlouis8** [taikoxyz/taiko-mono#13958]
### Describe the feature request

TAIKO IS AN EVM BASED PROJECT AND AS SUCH EARLY STRESS TESTS IN FORM OF THE DIFFERENT SERIES OF TESTNETS ARE NEEDED. WE HAVE SEEN THE PREVIOUS TESTNET EVENTS FOCUS ON BRDIGING, INTER-WALLET TRANSFERS, CONTRACT DEPLOYMENT AND RUNNING OF NODE. I THINK IT IS HIGH TIME TO INCLUDE AN TAIKO POWERED AMM TO TEST SWAP FEATURES, LP STAKING, ETC. I BELIEVE IT IS AN IMPORTANT AND CRUCIAL ASPECT OF THE TESTNET ESPECIALLY AS WE ARE FAST APPROACHING MAINNET. 

### Describe alternatives you've considered

SINCE WE ARE STILL AT THE INCEPTION OF THIS ALPHA-3 TESTNET, I AM MAKING A PROPOSAL TO ADD A DEX (AMM) TASK AS PART OF THE TESTNET, WE COULD EVEN USE THE UNISWAP FRONT-END

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
we do have the swap dapp which you can see on our ecosystem page: https://taiko.xyz/ecosystem

**Comment by Scottlouis8** [comment]
Pls could I get access to the Contributor POAP? Would appreciate it
