### ISSUE TITLE
Pending Transactions.

### ISSUE THREAD

**Issue by Varibido** [taikoxyz/taiko-mono#13950]
### Describe the feature request

Pending transactions are not displayed on the transactions Bar.

### Describe alternatives you've considered

Pending transactions should be displayed alongside confirmed transactions on the Transactions Bar.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
A transaction on the bridge will only reflect on the bridge when the transaction on the L1 is **confirmed**.

The **Pending** status refers to the state where the asset is in between the L1 and L2 and **awaiting confirmation on the destination chain**.

@Varibido Please check if this issue still exists.

**Comment by Varibido** [comment]
Issue fixed. Thanks
