### ISSUE TITLE
Isn't the test ETH coming to the Taiko network?

### ISSUE THREAD

**Issue by Adalett5** [taikoxyz/taiko-mono#13960]
### Describe the bug

Friends, I sent a test ETH from the sepolia network to the Taiko network, but it still hasn't arrived. I'm waiting.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
any update on this issue @Adalett5 after trying what @Peepeth7 has suggested? any additional details will be helpful.

**Comment by cyberhorsey** [comment]
Closing this as it's been a week without a response and most likely user just needed to add to metamask.
