### ISSUE TITLE
Problems with bridge notifications

### ISSUE THREAD

**Issue by theCast91** [taikoxyz/taiko-mono#13979]
### Describe the bug

I'm running into a small bug when trying to move BLL from Sepolia to Taiko.

It turns out that the interface always returns an error, but the token transfer is finishing successfully both on the blockchain and on Metamask.

I attach a photo of the error returned by Taiko's website:

![cap](https://github.com/taikoxyz/taiko-mono/assets/116200748/5c814b37-979a-49de-834c-4bb6c713b1c2)

Metamask TX: https://sepolia.etherscan.io/tx/0x44d2ddbbcd03b023f917e81f3d5bbe8703a98a45f2b02522ee2169b876698058
Taiko GUI TX: https://sepolia.etherscan.io//tx/0xd77b7de4a5a6731d2f20a94f81eef8cc8c94ea6d5e99da5722621af4fd7dc759

### Steps to reproduce

1. Connect in Sepolia network
2. Bridge BLL from Sepolia to Taiko.
3. Tokens transfere success, but GUI show a error (screenshot) 

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
This is an expected behavior as 50% of all BLL transactions are meant to fail.
[[source]](https://taiko.xyz/docs/guides/use-the-bridge)
