### ISSUE TITLE
Add Orally, decetralised oracles, to ecosystem page

### ISSUE THREAD

**Issue by verkhohliad** [taikoxyz/taiko-mono#13989]
### Title of your project

Orally

### Short (1-2 sentence) description of your project

Orally is a decentralized oracle and automation service, leveraging Internet Computer Protocol (ICP) to fetch, verify, and deliver real-world data to multiple blockchain networks. This empowers developers to create more dynamic dApps by incorporating external data and automated operations.

### Link to your project

https://orally.network/

### Upload a quality logo to your project

![logo-circle 2](https://github.com/taikoxyz/taiko-mono/assets/23651458/8d362e03-0a61-4e5b-9a7c-1eb6da6a1de2)

**Comment by d1onys1us** [comment]
hello @verkhohliad can you confirm with some evidence that this is integrated to work with Taiko? thanks!

**Comment by verkhohliad** [comment]
> hello @verkhohliad can you confirm with some evidence that this is integrated to work with Taiko? thanks!

We've deployed our data verifier contract from Sybil. This contract allows the attachment of Sybil price feeds (one of our offerings) to a transaction interacting with a specific contract on the Taiko chain. By leveraging our contract, the integrity of the data can be verified, ensuring it remains uncompromised. You can find more information in our documentation: https://docs.orally.network/getting-started/sybil-price-feeds. 

Verifier: 0xCFf00E5f685cCE94Dfc6d1a18200c764f9BCca1f. 
Verifier Interface: https://github.com/orally-network/evm-oracle/blob/main/contracts/interfaces/IOrallyVerifierOracle.sol

<img width="819" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23651458/a753360d-0b39-4e36-b986-ff326862ab52">

Additionally, once our automation product Pythia has undergone internal testing and is officially launched, we plan to incorporate the Taiko chain into its services. With Pythia, developers will have the ability to automate price feed updates, perform other types of updates, and even deliver randomness to their projects.
