### ISSUE TITLE
update node troubleshooting for windows

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#13984]
### Describe the feature request

leppaludi posted this nice thing helping windows users on the Discord:
```
If you're on Windows:

You can either:

docker compose down -v
cd scripts
dos2unix start-zkevm-chain-rpcd.sh
dos2unix start-prover-relayer.sh
cd ..
docker compose up 

or

1)
Open Notepad++
Go to: File -> Open -> Locate start-prover-relayer.sh file and open it
Go to: Edit -> EOL Conversion -> Unix
Go to: File -> Save
Close the file

2)
Do the same for start-zkevm-chain-rpcd.sh

3)
Then go back to command line and do
docker compose down -v
docker compose up
```

we should enshrine this in our docs / troubleshooting

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by ikaika1** [comment]
Hello, I am trying to become a contributor and am currently reviewing the list of "good first problems". Is this problem the same as run-a-node.mdx ## simple-taiko-node-taiko_client_prover_relayer-1 | /bin/sh:/script/start-prover-relayer.sh: not found?

On Windows, this error is caused by a control character (in this case a newline), so create three tabs (mac, linux, windows) in           Clone simple-taiko-node in run-a-node.mdx,
Adding the following line to the windows tab seems to solve the problem.

### clone simple-taiko-node.
```sh
git config --global core.autocrlf false.
git clone https://github.com/taikoxyz/simple-taiko-node.git
cd simple-taiko-node
```


Also, if necessary, I can add the following content to troubleshooting.

```
If you're on Windows:

. . . .
```

**Comment by alexanderblv** [comment]
Hey! 

I have compiled a detailed intsruction to solve this problem. I think there is an opportunity to get involved in digitized Taiko documents!

The provided instructions suggest two alternatives for Windows users to perform certain actions and resolve formatting issues. Here's an overview of the instructions:

**Alternative 1:**

1. Execute the command docker compose down -v to stop and remove Docker containers along with associated volumes.
2. Change the directory to scripts.
3. Use the command dos2unix start-zkevm-chain-rpcd.sh to convert the formatting of the start-zkevm-chain-rpcd.sh file from DOS/Windows format to Unix format.
4. Use the command dos2unix start-prover-relayer.sh to convert the formatting of the start-prover-relayer.sh file from DOS/Windows format to Unix format.
5. Go back to the previous directory.
6. Execute the command docker compose up to start the Docker containers.

**Alternative 2:**

1. Open Notepad++ text editor.
2. Navigate to the menu options: File -> Open -> Locate the start-prover-relayer.sh file and open it.
3. Navigate to the menu options: Edit -> EOL Conversion -> Unix to convert the file's formatting to Unix format.
4. Navigate to the menu options: File -> Save to save the changes.
5. Close the start-prover-relayer.sh file.
6. Repeat the above steps for the start-zkevm-chain-rpcd.sh file.
7. Return to the command line and execute the commands docker compose down -v and docker compose up to stop and start the Docker containers, respectively.

The suggestion is to document and include these instructions in their documentation or troubleshooting guides to provide users with a clear resolution for the specific issue they might encounter.

**Comment by shnmld** [comment]
Hello i want to contribute in this ecosystem

**Comment by panditdhamdhere** [comment]
hello I want to contribute

**Comment by K-tang-mkv** [comment]
Use vscode to open those scripts, and change CRLF to LF, and then everything will be all good
