### ISSUE TITLE
Add ZKSynth to Taiko ecosystem

### ISSUE THREAD

**Issue by prasad-kumkar** [taikoxyz/taiko-mono#13999]
### Title of your project

ZKSynth

### Short (1-2 sentence) description of your project

zkSynth allows you to create and trade synthetic assets that track the price of any real-world asset, such as stocks, commodities, currencies, and more.

### Link to your project

https://zksynth.com/

### Upload a quality logo to your project

![image](https://github.com/taikoxyz/taiko-mono/assets/43164022/66a958f8-3c8a-4d1e-a50c-c486f8fd3eed)

**Comment by d1onys1us** [comment]
hello @prasad-kumkar thanks for the PR, however I do not see the Taiko integration here:

<img width="1512" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/13951458/07f7d480-90eb-43d8-85dc-b4673b7d18a1">

If you want to integrate Taiko, please take a look at our integration guide: https://taikoxyz.notion.site/Taiko-integration-guide-d47ceef15f8b46818c6d922a603b4295

**Comment by 2manslkh** [comment]
@prasad-kumkar bump

**Comment by prasad-kumkar** [comment]
hi @d1onys1us, have texted you for a few queries on integration

**Comment by 2manslkh** [comment]
@prasad-kumkar bump

**Comment by MarcusWentz** [comment]
@prasad-kumkar bump
