### ISSUE TITLE
Node Dashboard

### ISSUE THREAD

**Issue by Eleleth77** [taikoxyz/taiko-mono#13990]
### Title of your project

Taiko Node Dashboard

### Short (1-2 sentence) description of your project

a user friendly, easy to read, and visually pleasing dashboard for those running a Node/Proposer/Prover

### Link to your project

https://github.com/wolfderechter/taiko-node-dashboard-docker/tree/main

### Upload a quality logo to your project

![Cover Image Thumbnail](https://github.com/taikoxyz/taiko-mono/assets/109436304/92b46a77-f3b8-48f4-9369-bb00fecdafbe)

**Comment by Eleleth77** [comment]
Led by Wolfez + Helios

**Comment by wolfderechter** [comment]
I like the description `The Taiko node dashboard is aimed to provide quick and digestible insights into your Taiko node.`
