### ISSUE TITLE
Add KEKKAI to Taiko ecosystem

### ISSUE THREAD

**Issue by ZZZDAD** [taikoxyz/taiko-mono#14011]
### Title of your project

KEKKAI

### Short (1-2 sentence) description of your project

KEKKAI is a product that protects the security of web3 user assets. It can help users get the result of asset flow in advance and analyze its risks when interacting with wallets.

### Link to your project

https://kekkai.io

### Upload a quality logo to your project

<img width="292" alt="black_img+name(square)" src="https://github.com/taikoxyz/taiko-mono/assets/26974615/ad578cb3-8525-46fd-aaa9-78173f19b978">
<img width="292" alt="black_img" src="https://github.com/taikoxyz/taiko-mono/assets/26974615/9c604aab-e374-454b-8929-fd0e1c282e69">

**Comment by 2manslkh** [comment]
Hello @ZZZDAD, could you provide some proof of Taiko's integration with some screenshots / video demonstration? That would be greatly appreciated. thank you!

**Comment by 2manslkh** [comment]
@ZZZDAD bump

**Comment by ZZZDAD** [comment]
With great honor, the following is the video of KEKKAI working in taiko bridge.
https://github.com/taikoxyz/taiko-mono/assets/26974615/0af84029-04ab-4625-8eee-dddbbf7f381d

**Comment by ZZZDAD** [comment]
![image](https://github.com/taikoxyz/taiko-mono/assets/26974615/10fed3d1-2ea4-4313-917c-739cc85cb80b)
For better cooperation and better user experience, KEKKAI added Taiko bridge to the certification list.

**Comment by 2manslkh** [comment]
@ZZZDAD The logo has a bit too much white space, so the icon looks small 

**Example**

<img width="830" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/ee192d52-95b7-4754-875f-d14d747cceff">

**Comment by ZZZDAD** [comment]
<img width="160" alt="20230627-100615" src="https://github.com/taikoxyz/taiko-mono/assets/26974615/8bb50a8c-e383-4203-9f99-f5713a7633e8">
Thank you very much, this is our newly uploaded logo.
