### ISSUE TITLE
website for TTKO deposits 

### ISSUE THREAD

**Issue by toglokkoplak** [taikoxyz/taiko-mono#14012]
### Describe the feature request

for now we can only deposit on contracts using the traditional method, we have to manually open a scan and deposit with 8 decimal places at the end, that's very common for some people, I want there to be a special website for deposits to contracts according to the TTKO balance without adding decimals 

### Describe alternatives you've considered

![Screenshot_20230618_141102_Chrome](https://github.com/taikoxyz/taiko-mono/assets/52659369/f94b61b3-460e-4cf5-89e8-8658a0a9f59a)
we can only deposit here, can you make a special website for TTKO deposits 

### Additional context

Additional context here.

**Comment by IniestaChidozie** [comment]
Traditional method of deposit is the best, but if ttko can provide a new deposit website, it will be awesome

**Comment by toglokkoplak** [comment]
now that's what I mean, a special website from the official for deposits to contracts

**Comment by 2manslkh** [comment]
@jscriptcoder Possible to add this to bridge-ui-v2?
