### ISSUE TITLE
Missing transactions on the bridge website if refreshing

### ISSUE THREAD

**Issue by BlankerL** [taikoxyz/taiko-mono#14017]
### Describe the bug

When I transfer ETH from Taiko to Sepolia, if I refresh the page right after clicking "Sign Transaction" on MetaMask, the transactions will not be stored and shown on ["Transaction" tab](https://bridge.test.taiko.xyz/#/transactions).

### Steps to reproduce

1. Go to ["Bridge" tab](https://bridge.test.taiko.xyz/#/), choose to end ETH from Taiko to Sepolia,
2. Once MetaMask popup, send the transaction,
3. Refresh the website immediately after signing the tx,
4. Go the ["Transaction" tab](https://bridge.test.taiko.xyz/#/transactions), the transactions will not show there

### Additional context

N/A

**Comment by BlankerL** [comment]
I had a discussion with @jscriptcoder on Discord, and it appears to be a bug related to the transaction recording mechanism in[Bridge UI](https://github.com/taikoxyz/taiko-mono/blob/ebcca680ac1d20b27ac2afd4fd6f6f79bbb522af/packages/bridge-ui/src/components/BridgeForm/BridgeForm.svelte#L366).

**Comment by cyberhorsey** [comment]
This has been fixed by a redeploy of the L2 to L1 relayer, which was lagging behind due to not creating transactions with the correct baseFeePerGas, and the request context did not have a timeout so it would hang forever and failed to move on to the next block. Closed by #14019 and #14024
