### ISSUE TITLE
Error When Claim Bridge

### ISSUE THREAD

**Issue by maltipoolabs** [taikoxyz/taiko-mono#14022]
### Describe the bug

Dear Support

Error when claim bridge, but I receive ETH
![image](https://github.com/taikoxyz/taiko-mono/assets/107974770/56d50f08-9a39-46e9-ab56-cb47e1999845)
https://test.taikoscan.io//tx/0x98ba462de60b14f14ef44fb713fa3ca514019d796ffa64297364d09637c881e0

My Address: 0xf3bad3aAabbDfb791DbcD2d3788D6Ac8EDD6bf8e

Thanks

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
@maltipoolabs Are you still facing this issue?

**Comment by maltipoolabs** [comment]
no, its okay now. Thanks
