### ISSUE TITLE
Add [PROJECT_NAME] to the ecosystem.

### ISSUE THREAD

**Issue by iammsb** [taikoxyz/taiko-mono#14038]
### Title of your project

domain.taiko (unique identifiers)

### Short (1-2 sentence) description of your project

These will help filter users and help the ecosystem fight bots

### Link to your project

not yet

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

no yet

**Comment by 2manslkh** [comment]
Hi @iammsb this template is for adding new projects to the Taiko ecosystem.
