### ISSUE TITLE
UI/UX user experience swap function

### ISSUE THREAD

**Issue by iammsb** [taikoxyz/taiko-mono#14039]
### Describe the bug

I suggest shouldn't the swap function be integrated on the main taiko website page, this will help everything organized in one ecosystem for the users to interact easily, too much links have been spread around especially when it has to be with such a project that stands out from the bunch, bad actors will always want to implement trap codes and lure in users to use the links.

*The swap https://swap.test.taiko.xyz/#/swap should be integrated on the main Taiko testnet page / the bridge page

### Steps to reproduce

*The swap https://swap.test.taiko.xyz/#/swap should be integrated on the main Taiko testnet page / the bridge page
* A nice user friendly interface 

### Additional context

So far the interaction has improved  and we are excited to see more improvements

**Comment by 2manslkh** [comment]
Duplicate #14040
