### ISSUE TITLE
Feat(Bridge): allows the bridge to add more assets, especially stable coins(ex: USDC,USDT,DAI,...)

### ISSUE THREAD

**Issue by ThanhLoc47** [taikoxyz/taiko-mono#14048]
### Describe the feature request

- Diversify asset classes when bridge assets from Sepolia chain to Taiko Chain

**Comment by 2manslkh** [comment]
Currently, we only want to allow the bridging of HORSE, BULL, and TTKO tokens. However, more tokens may be added in the future :)
