### ISSUE TITLE
Swap Function be integrated on the main bridge page

### ISSUE THREAD

**Issue by iammsb** [taikoxyz/taiko-mono#14040]
### Describe the feature request

We hope to expect more function implementation,
the swap function page should be integrated on the bridge page so users can easily interact instead of clicking on links that might not be safe.

these days there too many bots on the ecosystem and we humans we battle with them to try to interact with your products  .

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Coupling bridge and a swap app is not a good idea.
