### ISSUE TITLE
feat(protocol): horizontal scaling (multiple L2s/contract)

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/taiko-mono#14044]
### Describe the feature request

Because Taiko is a based rollup, all Taiko L2s blocks are already proposed by the currently selected Ethereum validator, so Taiko chains always form a network with a "shared sequencer". This is very useful for cross-L2/... transactions. However, there are still inefficiencies with deploying multiple L2s:
- Blocks need to be proposed to separate smart contracts, with each proposed block needing to store some data in the smart contract. (When multiple blocks are proposed per L2 we could already batch those together per L2).
- Blocks need to get verified separately for each L2, there is no built-in proof verification batching that provers can use. And even if that would be the case, the provers for each L2 may not overlap.

To make an efficient, highly scalable network of identical L2s we can solve these efficiencies by allowing multiple L2s within the same smart contract. This makes it possible to store a constant amount of data when proposing blocks for multiple L2s at the same time. It also allows blocks of multiple L2s to share the same provers, so blocks of different L2s can automatically be proven together, reducing verification costs and/or proof verification delays.

Conceptually this is quite similar to having identical L3s on top of the same L2. However, this does away with some of the complexities of having multiple layers, which are introduced to be able to solve some of the efficiencies of running multiple (identical) L2s on L1. This also makes cross-layer transactions more straight forward because everything is now just an L2.

This will also be interesting to enforce mechanisms like this: https://www.umbraresearch.xyz/writings/shared-validity-sequencing

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
This approach has some downsides:
1. Multiple L2s supported by the same contract are tightly coupled, it's not easier to upgrade one L2 without upgrading all other L2s.
2. The code is more complicated and error prone.

**Comment by Brechtpd** [comment]
1. This is a feature! Why would you not update all of them together though? If you would upgrade Ethereum, would you choose to only update smart contracts at odd addresses first and at even addresses later? If people want to have their own independent L2 they can, but then it's not the main Taiko chain consisting of interconnected L2s.
2. It is indeed more complicated (though also not that much I feel, all per chain things are now just an array and you hash things together). But you also get a lot in return! Atomic cross layer transactions are big. It makes it possible to increase the throughput of the chain in a way that is standardized for all participants in the main Taiko chain (RPC providers can just look at the contract and spin a new node up when a new L2 is added, proposers/provers create blocks for the same chain no matter the number of L2s in it, ...). It's also transparent for users, they don't have to care about all kinds of different L2s on all kinds of different versions that are live. If they are on the main Taiko chain it will behave like a single chain with the same security properties.

**Comment by Brechtpd** [comment]
Closing this in factor of https://github.com/taikoxyz/taiko-mono/issues/14659
