### ISSUE TITLE
Project board update proposal

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/taiko-mono#14053]
## Overview

The project board can be improved to enhance internal workflow and transparency for this open-source project.

### 1. Project Roadmap Addition

Example:
![Project Roadmap](https://github.com/taikoxyz/taiko-mono/assets/23635326/aaa66c1b-586d-4147-acca-b93b0d9335cf)

**Purpose:** Provide a clear and transparent view of the project's progress on each component.

**Solution (for discussion):**
- Utilize Epics to outline the key goals of the project, such as:
  - "Full Decentralization"
  - "Type 1 ZK Rollup"
  - "Tokenomics"
  - "dApp Ecosystem"

    *Full Decentralization* is an epic that encompasses features leading to the eventual decentralization of the Taiko Protocol.

    *Type 1 ZK Rollup* is an epic that encompasses features making Taiko a Type 1 ZK-Rollup.

    *Tokenomics* is an epic that encompasses features enabling Taiko with sustainable tokenomics.

    *Developer Ecosystem* is an epic that encompasses features fostering the growth of Taiko's dApp ecosystem (bridges, DEXes, DeFi, NFT Marketplace).

Adapted from Jira management methodology:

- **Epic:** Epics serve as the highest level of the hierarchy, representing large bodies of work that can be broken down into smaller units. Epics are long-term initiatives or major features spanning multiple sprints or releases. They provide an overarching theme or goal for the work being done.

- **Feature:** Features are derived from Epics and represent focused units of work. They reflect customer-centric functionality or improvements contributing to the Epic. Features are smaller and more tangible than Epics, making them easier to plan, implement, and track. Features can be further broken down into smaller units of work, such as stories.

- **Story:** Stories are the smallest actionable units of work within the hierarchy. They represent specific user requirements, functionality, or improvements contributing to a Feature. Stories are typically written from a user's perspective, describing the desired outcome or behavior. Each story should be independent and deliver value to the end-user.

### 2. Milestone Usage for Future Testnet(s) and Mainnet Launch Dates

![Milestones](https://github.com/taikoxyz/taiko-mono/assets/23635326/c8de5757-3552-431b-b5e3-0cdcb6cb67b3)

**Purpose:** Mark milestone end dates on the project roadmap to indicate launch dates for future testnets and mainnet.

**Comment by dantaik** [comment]
@d1onys1us we do need to keep our project page up-to-date.
