### ISSUE TITLE
Provers could prove same block multiple times

### ISSUE THREAD

**Issue by BlankerL** [taikoxyz/taiko-mono#14050]
### Describe the bug

I have been using a prover client for the Alpha-3 testnet, and everything was going smoothly until recently (possibly yesterday or today). I noticed that my prover successfully proved the same block at the same time as other provers. You can find the details of the transactions below:

Transaction 1: https://sepolia.etherscan.io/tx/0xf8d43b8b2e50895c98482e42d02f3e08bcaacd23d8909a2a4560fa6094e691b2

Transaction 2: https://sepolia.etherscan.io/tx/0x0cb54a3deb648129097acf7085c72a86acbadcb3ffd7275586c2c65cc402d0ec

Both of these transactions successfully proved block "367390." Generally, when a previous unsuccessful transaction occurs, it should be reverted. However, in this case, both of these transactions were not reverted.

### Steps to reproduce

N/A

It is just my observation, I don't know how to reproduce it. 

### Additional context

N/A

**Comment by cyberhorsey** [comment]
I think you are proving a fork. You should try to resync your nodes, and see if that rectifies the issue.

**Comment by BlankerL** [comment]
Thanks, I will have a try, but won't the node know it's on a fork?

**Comment by BlankerL** [comment]
Resyncing the node fixed the problem, thanks a lot! 

But I suppose the node should know it's on a fork and self-correct if it's connected to the peers correctly?

Also, shouldn't the layer 1 smart contract prevent multiple prover proves the same block? Otherwise in the production environment provers might burn the real cash to prove a fork. In my cases, I burned 400 Sepolia ETH a night proving the fork.

**Comment by cyberhorsey** [comment]
> Resyncing the node fixed the problem, thanks a lot!
> 
> But I suppose the node should know it's on a fork and self-correct if it's connected to the peers correctly?
> 
> Also, shouldn't the layer 1 smart contract prevent multiple prover proves the same block? Otherwise in the production environment provers might burn the real cash to prove a fork. In my case, I burned 400 Sepolia ETH a night proving the fork.

Contra t doesn't know which proof is correct until the previous one is verified, we allow multiple proofs for different fork choices.

**Comment by BlankerL** [comment]
Is that also the reason why the L2 client won't correct themselves and discard the forked chain?

**Comment by cyberhorsey** [comment]
> Is that also the reason why the L2 client won't correct themselves and discard the forked chain?

That's something we have to look in to. It's the geth node that became out of sync following the fork most likely, the client is just reacting to the node.

**Comment by BlankerL** [comment]
Also, if multiple proofs for different forks are accepted, why some proof will failed but others won't?

Failed transaction example: https://sepolia.etherscan.io/tx/0x15178b38c64931dfc124ca293790a2d925c4cf2dc232183cffc511b3889ccc35

**Comment by cyberhorsey** [comment]
> Also, if "multiple proofs for different forks" are accepted, why some proof will failed but others won't?
> 
> Failed transaction example: https://sepolia.etherscan.io/tx/0x15178b38c64931dfc124ca293790a2d925c4cf2dc232183cffc511b3889ccc35

Because a proof was already submitted for this fork, there are many cases it can revert.

**Comment by cyberhorsey** [comment]
Closing this issue as it's resolved in taiko-client not taiko-mono.
