### ISSUE TITLE
Add domain/name service

### ISSUE THREAD

**Issue by Fomonofomo** [taikoxyz/taiko-mono#14054]
### Describe the feature request

I would like to request a possibility to test domains/name registration.
Simple description, but a more detailed description can be added on a later moment.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
i don't understand what you mean @Fomonofomo, could you please add more details?

**Comment by alexanderblv** [comment]
@d1onys1us I think he is requesting resources or support to create something like ENS on the Taiko network

**Comment by Fomonofomo** [comment]
> @d1onys1us I think he is requesting resources or support to create something like ENS on the Taiko network

Sorry for the slow response, was a bit busy.

You are definitely right there and was supporting to create something like ENS on the network.

**Comment by d1onys1us** [comment]
> > @d1onys1us I think he is requesting resources or support to create something like ENS on the Taiko network
> 
> Sorry for the slow response, was a bit busy.
> 
> You are definitely right there and was supporting to create something like ENS on the network.

yes we are planning on doing that! we will close this issue for now, and possibly add another with more details. thank you for the idea :)
