### ISSUE TITLE
Add Particle to the ecosystem

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/taiko-mono#14076]
### Title of your project

Particle Network

### Short (1-2 sentence) description of your project

The Full-Stack Infrastructure To Simplify Web3

### Link to your project

https://particle.network/

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

https://cdn.discordapp.com/attachments/1115270137193431110/1124194531273887846/telegram-cloud-photo-size-5-6120616245964420685-x.jpg

### Upload a quality logo to your project

![512](https://github.com/taikoxyz/taiko-mono/assets/23635326/f4eda1dd-6035-487b-a5cc-52ec143950f1)

**Comment by Saru94** [comment]
good preject L2
