### ISSUE TITLE
Check old transactions

### ISSUE THREAD

**Issue by miguelmagalhaes02** [taikoxyz/taiko-mono#14086]
### Describe the bug

Someone have access to the first version of the Taiko testnet block explorer? I've made some txs months ago and I can't check them on block explorer

### Steps to reproduce

1. acess to block explorer
2. check the old transactions (more than 3 months)

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
If the tx is made a few months ago, the transaction may have been made in testnet A2 and would not be included in A3
