### ISSUE TITLE
feat (bridge-ui): Upgrade WalletConnect integration to v2

### ISSUE THREAD

**Issue by ablankstory** [taikoxyz/taiko-mono#14091]
### Describe the feature request

The bridge site is still using WCv1 to connect wallets. v1 is deprecated and no longer works. DApps need to upgrade to v2 in order for wallets to connect using WC.

Until v2 is supported, any wallet that requires WalletConnect to connect to the bridge site will be unable to. This poses an issue for Loopring Wallet since that is the only way for the wallet to connect. 

### Describe alternatives you've considered

only workaround is to use a wallet that doesn’t require WC to connect to the dapp.

**Comment by jscriptcoder** [comment]
This is already done
