### ISSUE TITLE
MXC

### ISSUE THREAD

**Issue by sheenhx** [taikoxyz/taiko-mono#14107]
### Title of your project

MXC

### Short (1-2 sentence) description of your project

Layer3 IoT app chain

### Link to your project

https://wannsee.mxc.com/docs/intro

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

in the docs

### Upload a quality logo to your project

https://uploads-ssl.webflow.com/6253d5b96f29fe54ae351282/6287440e15c1ce566364ee5c_mxc-mini-version%20(1).svg

**Comment by MarcusWentz** [comment]
Which part of the documentation proves Taiko integration? 

Please provide a link and screenshot.

Thank you.
