### ISSUE TITLE
Add zkDELX to Taiko ecosystem 

### ISSUE THREAD

**Issue by tsubasakong** [taikoxyz/taiko-mono#14119]
### Title of your project

zkDELX

### Short (1-2 sentence) description of your project

zkDELX is a decentralized electricity exchange market based on zkEVM to facilitate the electrical vehicles and renewable energy industries. 

### Link to your project

https://zkdelx-front-1.vercel.app/

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

On Ethglobal Scaling ETH Hackathon, we deployed our contract on Taiko testnet (Deployer: 0xb72D7383D233697B74c672BAa0B0BfeCAAc10B99 Deployed to: 0x258FF931ce6A7DC9391a649E8a7A84fC17717c76 Transaction hash: 0x707be16258be9ea9af34e3ba011f81980c7d6afa2bf9c28406099a71d388e6b5), and we plan to continue develop our project on Taiko. 

### Upload a quality logo to your project

![zldelx-logo](https://github.com/taikoxyz/taiko-mono/assets/97429702/17ac8bd1-24e0-4517-83ad-cde8fcfafb27)

**Comment by d1onys1us** [comment]
hello @tsubasakong apologies for the change in RPC (this shouldn't happen in the future). we would need to add / integrate this with the latest alpha-3 testnet to land on our ecosystem page, so that people can use it!

would you be able to add it in? let us know if we can help.

**Comment by tsubasakong** [comment]
> hello @tsubasakong apologies for the change in RPC (this shouldn't happen in the future). we would need to add / integrate this with the latest alpha-3 testnet to land on our ecosystem page, so that people can use it! you can find the new RPC here: https://taiko.xyz/docs/reference/rpc-configuration
> 
> would you be able to add it in? let us know if we can help.

Thanks for let us know about this! 
1. We have update to the latest alpha-3 testnet RPC setup.
2. This setup is used in our new website: https://zkdelx-front.vercel.app/.





O
