### ISSUE TITLE
Aggregator Finance for TAIKO

### ISSUE THREAD

**Issue by heatherrai** [taikoxyz/taiko-mono#14120]
### Title of your project

RAI Finance

### Short (1-2 sentence) description of your project

User can easily compare and swap multiple chains on top of the Taiko blockchain. A service that links multiple swaps and organizes multiple tokens. 

### Link to your project

https://app.rai.finance/#/aggregateSwap

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

https://youtu.be/WO5J9NZayCw

### Upload a quality logo to your project

![RAI finance Logo_VF_icon logo_dark](https://github.com/taikoxyz/taiko-mono/assets/138840431/2e13eb65-1da3-4c43-a0fa-909656f77ead)

**Comment by d1onys1us** [comment]
> https://app.rai.finance/#/aggregateSwap

do you have a square image by any chance? (like 1:1 dimension) perhaps just the logo would be good? otherwise it shrinks. if not, we can update the code to try to make it look nicer.

ref:
![image](https://github.com/taikoxyz/taiko-mono/assets/13951458/377b999f-9caf-4c9f-b6ea-5d045382f21b)

**Comment by boz6336** [comment]
yessßss

**Comment by d1onys1us** [comment]
> User can easily compare and swap multiple chains on top of the Tyco blockchain. A service that links multiple swaps and organizes multiple tokens.

@heatherrai also, is this description correct? Do you mean "Taiko" instead of "Tyco". Please let us know if you'd want to update it. thanks

**Comment by heatherrai** [comment]
> 

I've completed the update, thank you. ;)
