### ISSUE TITLE
Add [taiko-One-click-installation-node] to the ecosystem

### ISSUE THREAD

**Issue by mgcnb666** [taikoxyz/taiko-mono#14132]
### Title of your project

taiko-One-click-installation-node

### Short (1-2 sentence) description of your project

taiko-One-click-installation-node

### Link to your project

https://github.com/mgcnb666/taiko-One-click-installation-node

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

https://github.com/mgcnb666?tab=repositories

**Comment by d1onys1us** [comment]
thanks for your contribution but what is the difference between this and simple-taiko-node? i think we will hold off on adding this for now because of the similarity, feel free to comment if you feel otherwise.
