### ISSUE TITLE
node running friction log

### ISSUE THREAD

**Issue by LayerRadio** [taikoxyz/taiko-mono#14139]
### Describe the bug

Viewpoint: I ran Taiko Alpha-1 and helped with Docs, I wasn't able to run Taiko Alpha-2 due to time constraints, but I am currently working on getting a node up to run Taiko Alpha-3.

This ticket is aimed to point out potential frictions and ideas on where the gaps can be filled to help new and returning with users wanting to contribute and learn in future Alphas and Betas.   

- Flow at the beginning of the Docs should briefly mention why the user is running the steps. For someone new or in my case returning, there felt to be a gap in the flow from skipping Alpha-2. This may be able to be quickly addressed by a short intro containing, why someone wants to set this up, what they need for a bare minimum to get started, and what they may or may not want to do (ie run a proposer or prover). In addition to bare minimum, explicitly stating the more advanced setups. Some of this can also be solved by tweaking hierarchy. (Also, thinking about target audience for running the nodes both currently and for the future, will help dictate the best way to rework the flow). 

- If certain steps take a bit of time on average (may be worth mentioning what takes time and where the user should wait, this could help reduce repeat questions on Discord. I think this and making adjustments on flow will also help people to not stopping before even trying to ask a question on Discord)

- State sepETH and TTKO minimum requirements (when they are needed)

- Does both Prover and Proposer need to be synced? (state sync time)

- Can a Prover and Proposer be ran at the same time? I'm pretty sure I saw somewhere on discord this can't\shouldn't happen, so may be worth putting in to clear up any misconception. What happens if a user puts true to both, etc

- Why set up Sepolia node? (There wasn't any context to this, but I think a brief sentence or 2 would be sufficent to address this)

- Setting up Sepolia node was not straight forward (wasn't sure what to select for minimal requirements in the terminal config), I stopped with this approach due to the hardening and didn't want to unknowing open a vulnerability on my system). Note: Infura free account hit the daily limit really quick (within a few hours), currently syncing with Alchemy (haven't hit monthly limit yet, hoping that I can get synced and try to prove before I do, but is looking like it will be tight). In future releases, Taiko may want to have a tutorial in doing this (separate from the guide section, on how to safely and easily set up the minimum required archive node)

- with BLL (should note in the docs that it's designed to fail for testing purposes)

- I do want to mention that the issues I ran into with pending transactions and a question I had on local node config were both addressed very quickly on discord. 

- Overall, the docs are very good and think most of the things I mentioned can be addressed with a few added or reworded sentences. 

- In the future, Taiko may want to considered packaging this in a PPA (or Flatpak). This could be a really good way to make it much more straight forward for users running linux or linux vms. 

Another way to help newcomers (and veteran users alike) could be to set up forums, which can have a more organized navigational structure than discord for questions, discussion and guides. This may also be a good way to introduce things such as community guides. 

Hope the above helps, and happy to expand on any of the points I above. 

### Steps to reproduce

Alpha-3 node friction log

### Additional context

Opened per request of team member. If any questions, please let me know.

**Comment by rosedwik1** [comment]
First time to try

**Comment by spachib** [comment]
re:last paragraph, Taiko has a forum at community.taiko.xyz
