### ISSUE TITLE
除了官方跨链桥之外，1、建议增加交易所的充值通道；2、SWAP里增加OTC出入金合作方。

### ISSUE THREAD

**Issue by wengxinzhuang** [taikoxyz/taiko-mono#14131]
### Describe the feature request

De.scription of the feature request here.
除了官方跨链桥之外，为保证资金安全
1、建议增加交易所的充值通道；
2、SWAP里增加OTC出入金合作方。

### Describe alternatives you've considered

Description of the alternatives you've considered here.
类似UNISAWP上也有OTC出入金的合作通道，增强社区的资金安全。

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
Could u repoen this issue when an English description?
