### ISSUE TITLE
Apply for adding Taikoverse to Taiko's ecosystem

### ISSUE THREAD

**Issue by hatark** [taikoxyz/taiko-mono#14158]
### Title of your project

Taikoverse

### Short (1-2 sentence) description of your project

Play Minecraft on Taiko. An infinite and unstoppable world running on Taiko's stack.

### Link to your project

https://linktr.ee/taikoverse

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

https://github.com/taikoverse

### Upload a quality logo to your project
![Group 51taikoverse (12)](https://github.com/taikoxyz/taiko-mono/assets/124481232/2ce403f0-70e8-4871-9e7d-ea35b59c5507)

**Comment by d1onys1us** [comment]
hello @hatark is it okay if i rename this to "running on Taiko's stack" instead of inception layer? because technically we are referring to an inception layer as L3. we haven't come up with a name yet for "Taiko's stack" (we are thinking maybe "Tempo"), but for now, I think running on Taiko's stack is fine.

**Comment by hatark** [comment]
> hello @hatark is it okay if i rename this to "running on Taiko's stack" instead of inception layer? because technically we are referring to an inception layer as L3. we haven't come up with a name yet for "Taiko's stack" (we are thinking maybe "Tempo"), but for now, I think running on Taiko's stack is fine.


Both Taiko's stack and Tempo are OK to me. I'm thinking deploying to Taiko L3 later, because it's very cool.

**Comment by spy625** [comment]
I think so..  Taiko L3 will be awesome..

**Comment by hatark** [comment]
Updated the logo and the short description to make it introduces better. Hope it does not take much time to update in the next ecosystem webpage update :) thanks  @d1onys1us @2manslkh @MarcusWentz

**Comment by MarcusWentz** [comment]
Added in this pull request:

https://github.com/taikoxyz/taiko-mono/pull/14162
