### ISSUE TITLE
Add BNSD to the ecosystem

### ISSUE THREAD

**Issue by hipexjain** [taikoxyz/taiko-mono#14177]
### Title of your project

Add BNSD Defi Project

### Short (1-2 sentence) description of your project

BNSD is multichain defi project

### Link to your project

https://bns.finance/

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

It is not integrated currently

### Upload a quality logo to your project

BNSD is a multi chain defi project of BNS ecosystem. Having multichain laucnhpads, prediction utility, etc.

**Comment by d1onys1us** [comment]
you can open this issue again once the project is integrated, thanks.
