### ISSUE TITLE
Add Polyhedra Network to Taiko's Ecosystem

### ISSUE THREAD

**Issue by AntPoly** [taikoxyz/taiko-mono#14176]
### Title of your project

Polyhedra Network

### Short (1-2 sentence) description of your project

Polyhedra Network is building the infrastructure for Web3 interoperability with efficient zero-knowledge proof protocols. Polyhedra Network designs and implements zkBridge, providing trustless and efficient cross-chain infrastructures for layer-1 and layer-2 interoperability.

### Link to your project

https://polyhedra.network/ & https://zkbridge.com/

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

Contracts we deployed on Taiko: https://docs.google.com/document/d/18SBQSFXJ6T_HUMijiVqZrpoztODVNf61IwZv0TDijvw/edit?usp=sharing

### Upload a quality logo to your project

[Polyhedra Logo Assets.zip](https://github.com/taikoxyz/taiko-mono/files/12061064/Polyhedra.Logo.Assets.zip)

**Comment by d1onys1us** [comment]
@AntPoly i was trying this out and did not see Taiko in the network dropdown. Has it been added to the UI? see screenshot below:

![image](https://github.com/taikoxyz/taiko-mono/assets/13951458/2e8e8c63-36c2-4ad6-9704-23b086ac7ed1)

**Comment by 2manslkh** [comment]
@AntPoly Bump

**Comment by AntPoly** [comment]
We have the bridge deployed at https://zkbridge.com/zknft
You may try out BSC Testnet -> Taiko Testnet

**Comment by MarcusWentz** [comment]
I do not see support for Taiko on 

-https://zkbridge.com/zkmessenger 
-https://zkbridge.com/zknft

yet.

After adding Taiko, take screenshots with the network added.

**Comment by Inna78spb** [comment]
Я пробовал мост, развернутый в https://zkbridge.com/zknft , создал нфт в бск тестнет, и сделал бридж в сеть Taiko
![Screenshot (93)](https://github.com/taikoxyz/taiko-mono/assets/138746165/cfab97f6-664a-4473-a5a7-0e510d4225a4)
![Uploading Screenshot (92).png…]()

**Comment by Inna78spb** [comment]
![Screenshot (93)](https://github.com/taikoxyz/taiko-mono/assets/138746165/1f74de6a-8725-472a-bb81-bcc1acb49e94)

**Comment by Inna78spb** [comment]
![Screenshot (92)](https://github.com/taikoxyz/taiko-mono/assets/138746165/b376c731-a35c-40af-9e8a-e591d75709f4)
