### ISSUE TITLE
add TTKO to metamask

### ISSUE THREAD

**Issue by rasatustra** [taikoxyz/taiko-mono#14171]
### Describe the feature request

It would make testers´life easier if you added TTK0 to metamask in order to make testing more fluent and efficient. 

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by xudawen12138** [comment]
good idea

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/14227
