### ISSUE TITLE
Add Pizzap to the ecosystem

### ISSUE THREAD

**Issue by Pizzap-io** [taikoxyz/taiko-mono#14185]
### Title of your project

Pizzap

### Short (1-2 sentence) description of your project

Pizzap is a user-benefit-oriented and mass-adopted AI ecosystem. Members  can create, show and trade NFTs in this community , as well as build personal art brand in MetaVerse. VoiceNFT is a kind of main work form in Pizzap for members  to create with.

### Link to your project

​https://pizzap.io

### Please provide evidence here that your project is integrated with Taiko for us to easily check.

Under development, coming soon.

### Upload a quality logo to your project

![512logo](https://github.com/taikoxyz/taiko-mono/assets/84441043/a6934383-c1a1-4087-aea2-60e9bfbc5f15)

**Comment by 2manslkh** [comment]
Only projects that have completed integration of Taiko will be added to the ecosystem page

**Comment by 2manslkh** [comment]
Please Rrise a new issue when the project is integrated
