### ISSUE TITLE
Proses

### ISSUE THREAD

**Issue by Gustishodik0** [taikoxyz/taiko-mono#14180]
### Describe the bug

Open
Automate the process of publishing blog posts
#13870
d1onys1us opened this issue on Jun 4 · 1 comment
Labels
area.developer-experience
area.website
meta.alpha-4
Comments
d1onys1us commented on Jun 4 • 
Summary
We have attempted this before by querying ARWeave. Please see:

https://support.mirror.xyz/hc/en-us/articles/7112432091284-Does-Mirror-have-an-API-
feat(website): automatically publish latest blog posts to website #13027
The reason we reverted this change was because it was taking way too long to load the mirror blog posts. It caused the first-page-load to be a very subpar experience as it made the API calls.

Definition of done
option 1
not significantly impact the initial page load
update the website homepage within a 24 hour window of publishing a blog post
option 2
implementing an approach that deprecates the need for this
Some ideas:

Have a cron schedule / nightly that queries the API and rebuilds the blog posts locally, perhaps a sed replace over the file BlogSection.tsx, and re-publishes the website.
Completely move to another blogging platform -> this would warrant discussion with the team and some clear arguments of why the change could be beneficial
Some reasons it could be beneficial: improvement in SEO on our site, could look more official having the blog on a proper taiko.xyz domain
Chat with @je4nt0nic / team to see if we even need blog posts on the home page or if we should put something else there.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Spam
