### ISSUE TITLE
Feedback for “Run a Taiko node”

### ISSUE THREAD

**Issue by Azazel020** [taikoxyz/taiko-mono#14194]
In the docs is an Alchemy example how to use Alchemy/Infura for the Sepiola L1 RPC. For the new L3 Eldfell node it is mentioned that we have to use an Grimsvotn L2 RPC instead but not clear how and where to get it. 

It should be a great addition to add some more content here.

![Taiko](https://github.com/taikoxyz/taiko-mono/assets/44430967/a01cc7ab-7644-48fe-984e-a4134248ba47)

**Comment by xudawen12138** [comment]
good idea

**Comment by 2manslkh** [comment]
@Azazel020 
It is mentioned in the docs that you need a fully synced Grimsvotn Node in order to run the L3

This means you need to be running an L2 node before an L3.
