### ISSUE TITLE
BRIDGE L1 - L2 - L3 and 'claim button error'

### ISSUE THREAD

**Issue by Uzan666** [taikoxyz/taiko-mono#14198]
### Describe the bug

when I started the bridge from L1 TO L2 AND L3, everything went normally, there were no problems that I experienced, but I was confused by the process of having a claim button in transaction history, and when I clicked on that button, there was a tx crow, 
for example:

https://explorer.test.taiko.xyz/tx/0x3638d9c72b84c550a301405feb5edf22a43eb3ccbfd023bce3c3181d5a58ca33

and for swap , add liquidity, there is no problem from l1,l2,l3 everything runs normally

### Steps to reproduce

My Address : 0x80F603c33AeB5d504beF9a0809383Ca1bc589b67

### Additional context

https://postimg.cc/SnR19HtR

https://postimg.cc/fSbqvFT8

https://postimg.cc/SjpMz8tz

**Comment by nazarov1ch** [comment]
Its not necessary to click on claim button just wait until status will be claimed automatically ( as i see on ur screenshots)
