### ISSUE TITLE
BLL token 

### ISSUE THREAD

**Issue by zakariamaarafi** [taikoxyz/taiko-mono#14192]
### Describe the bug

BLL token bridging from sepolia to taiko testnet fail almost every time

### Steps to reproduce

1 - entre amount of bll to transfer from sepolia to taiko testnet
2- approve bll 
3- bridging

### Additional context

Additional context here.
![Screenshot 2023-07-18 030515](https://github.com/taikoxyz/taiko-mono/assets/135147363/0589fd5a-b8dd-4664-8539-1f0404bcddcc)

**Comment by 2manslkh** [comment]
<img width="866" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/4ac3b802-a636-4651-b1ea-367732f3c8d0">

https://taiko.xyz/docs/guides/build-on-taiko/bridge-tokens
