### ISSUE TITLE
There is a bug that the transaction cannot be completed in the testnet interaction

### ISSUE THREAD

**Issue by concepteros** [taikoxyz/taiko-mono#14219]
### Describe the bug

There is a bug that the transaction cannot be completed in the testnet interaction

### Steps to reproduce

When executing ETH/bull swap, the transaction cannot be completed immediately

**Comment by iamenochlee** [comment]
please provide more information.
If you meant that executing ETH/BULL swap, this is intentionally as it is expected to fail 50% of time
