### ISSUE TITLE
Claiming token failure

### ISSUE THREAD

**Issue by nbgoku** [taikoxyz/taiko-mono#14214]
### Describe the bug

On Taiko (Alpha-4 Testnet) I got a failed metamask alert of claim attempt of bill tokens, but website indicates its succesful

Recent failed attempt: 
https://explorer.l3test.taiko.xyz/tx/0x0eb15b2f3b5e54d82745f35921232f6b1f32be5fe4ebfc497ae8ed435cc0bf82

Odd though because the https://bridge.l3test.taiko.xyz/#/transactions website is telling me the claim is succesful and I can see them in my wallet, so not sure why I transaction is showing as failed in the taiko explorer and metmask

![image](https://github.com/taikoxyz/taiko-mono/assets/32963749/ef08f723-97cb-4605-be35-361505459ef0)

![image](https://github.com/taikoxyz/taiko-mono/assets/32963749/f04eafe2-1305-4c70-a4d0-c24b2cb9141d)
![image](https://github.com/taikoxyz/taiko-mono/assets/32963749/e5de0f96-f8ff-4348-bfd3-50f7604b90f3)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
@jscriptcoder

**Comment by LIZ369** [comment]
Também tive esse mesmo bug mas agora esta normal.

**Comment by nbgoku** [comment]
@jscriptcoder just happened again

![image](https://github.com/taikoxyz/taiko-mono/assets/32963749/c56d2f51-4d5d-4041-a99d-cfa3ee8f2f53)

https://explorer.test.taiko.xyz/tx/0x1181f8636d3304b619fa6d8b99097f9e244c2b0a0acb076e50b198e9991fed8b

really strange how it claims succesfully, but metamask says it failed and the website says its succesful and failed

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
