### ISSUE TITLE
"Error: execution reverted" Bug transaction in the testnet swap interaction

### ISSUE THREAD

**Issue by Freda46** [taikoxyz/taiko-mono#14226]
### Describe the bug

Bug transaction in the testnet swap interaction
**Error: execution reverted**

### Steps to reproduce

Transaction cannot be completed immediately ETH/HORSE swap

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Could you check if you used enough gas for the transaction?

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
