### ISSUE TITLE
Add more features like staking or provide liquidity pool.

### ISSUE THREAD

**Issue by rho777** [taikoxyz/taiko-mono#14237]
### Describe the feature request

There should be also a feature like this. Since it is crucial to everyone and also a beneficial to everybody who uses the platform. I hope in the future this could come true.

### Describe alternatives you've considered

Liquidity pool and staking

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Currently, users can provide liquidity on our swap page https://swap.test.taiko.xyz/#/pool.

However, it would be cool to see a **liquidity incentivisation protocol** using some staking mechanism developed by a protocol

**Comment by MwitahJob** [comment]
Hello, please if you don't mind could you provide more information about the issue.

**Comment by agustinusang** [comment]
i tried make token on L2, and bridge to L3, when i claim my token its requested fee about $9 in eth but i rejected it, and i still can claim my token in my wallet on L3. is it a bug?

**Comment by Clarssss** [comment]
More information specific within the issue thank you

**Comment by selymyst** [comment]
Kindly provide more info about this issue

**Comment by panditdhamdhere** [comment]
confusing 
more info please

**Comment by Ionanspt** [comment]
this is a good featura

**Comment by nhasuh** [comment]
I'm glad I could try it

**Comment by Nitinrao123** [comment]
yes please take a note of it .staking and liquidity pools are really important nowadays.it will create a positive impact both for taico and the users.

**Comment by burhanhussain13** [comment]
how do you even contribute

**Comment by pucedoteth** [comment]
provide Liquidity is available at: https://swap.l3test.taiko.xyz/#/pool , but i don't know about Staking Program.

**Comment by abidex0z** [comment]
I believe it is a gradual process and the subject and feature  mentioned above will be added as time goes on because we are still on the testnet.

**Comment by kidochukwu** [comment]
Hello, please if you don't mind could you provide more information about the issue.

**Comment by Web3metahunter** [comment]
provide Liquidity is available at: https://swap.l3test.taiko.xyz/#/pool , but i don't know about Staking Program.

**Comment by vijayrajreddy** [comment]
Yes, staking feature can also be tested before Mainnet...

**Comment by Abycrpt01** [comment]
Liquidity pool is already on at https://swap.l3test.taiko.xyz/#/pool

**Comment by Auwamuu** [comment]
Add more features like staking

**Comment by Nitinrao123** [comment]
Please add the staking feature also

**Comment by Vandayzm** [comment]
Is not working on extension
