### ISSUE TITLE
Add a button to view transactions carried out on a specific network

### ISSUE THREAD

**Issue by mateuzrib** [taikoxyz/taiko-mono#14242]
### Describe the feature request

Add a button to view only the transactions from a network A or from a network B. In the image below the transactions are shown in the order in which they were executed. But what if it were possible to see only the transactions from the Sepolia network to Taiko? Or just transactions from Taiko to Sepolia? It would be a cool feature. The button could have two options: "From Sepolia Only" and "From Taiko Only".
![image](https://github.com/taikoxyz/taiko-mono/assets/116719237/6d9bbb44-d2a1-45b4-95a6-3325f1d22c85)

In this case the user selected the option From Taiko Only:

![image](https://github.com/taikoxyz/taiko-mono/assets/116719237/6cf3e64b-7877-46ae-b220-08f341e6ff3e)

Or the user could select From Sepolia Only:
![image](https://github.com/taikoxyz/taiko-mono/assets/116719237/90a87a6a-a348-4af9-b5c8-896b0ca2b0e4)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by pierreneter** [comment]
I can create that filter. Hey @ d1onys1us, that is a good idea so I can do it right away.

**Comment by 2manslkh** [comment]
@pierreneter go ahead and create the PR :)

**Comment by 2manslkh** [comment]
@jscriptcoder @cyberhorsey Is this included in the bridge v2?

**Comment by pierreneter** [comment]
I also implement the idea from #13437 too. If that doesn't have in bridge v2

**Comment by pierreneter** [comment]
1 PR for #14242 and #13437 soon

**Comment by 2manslkh** [comment]
Legend

**Comment by M0izes** [comment]
This is a good feature

**Comment by Lovander** [comment]
not bad i like it

**Comment by pucedoteth** [comment]
nice feature if they added

**Comment by pierreneter** [comment]
sorry for delaying it 1 week, I'm implementing it and will push it tomorrow

**Comment by mateuzrib** [comment]
🔥

**Comment by d1onys1us** [comment]
closing this issue as we are working on a new bridge UI. cc @KorbinianK @jscriptcoder
