### ISSUE TITLE
Multichain Cross Swap Feature

### ISSUE THREAD

**Issue by piethor** [taikoxyz/taiko-mono#14252]
### Describe the feature request

As in Alpha- III we can only Bridge Eth from Sepolia to Taiko. 
It would be great to have multiple network support rather than just eth mainnet

### Describe alternatives you've considered

Some Multiple Networks i've considered : 
• Arbitrum
• Optimism
• zkSync
• Linea
• Matic

### Additional context

Using all the type of L1 L2 And L3 Test networks in Taiko will be great help in upcoming mainnet to get bugs and and more updates. 
thank you

**Comment by lacosteiro088ce** [comment]
Ok

**Comment by dantaik** [comment]
There are many Bridge projects, I'd leave these opportunities to them while Taiko can focus on the core challanges.
