### ISSUE TITLE
Switch networks

### ISSUE THREAD

**Issue by Eizy0125** [taikoxyz/taiko-mono#14250]
### Describe the bug

If you open the L1 ⇔ L2 and L2 ⇒ L3 bridges at the same time and switch the network. there is a pattern where the switching does not go well. The same is true when switching wallet networks.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by pucedoteth** [comment]
if you want to open both on same time, i suggest you to open each bridge on different browser cuz each bridge requires different chain.

**Comment by dantaik** [comment]
Bridge dapp v1 has been depreciated.
