### ISSUE TITLE
una red bastante rapida

### ISSUE THREAD

**Issue by afgajeno1** [taikoxyz/taiko-mono#14257]
### Describe the feature request

una red bastante rapida deben mejorar los tiempos de respuesta y de confirmaciones, en mi pc adicionalmente no me esta dejando ingresar a la pagina de swap y bridge reportando pishing en la url : 
![image](https://github.com/taikoxyz/taiko-mono/assets/138340621/bce8f4a0-a12d-47e5-8873-a2ba3fe4f1ca)

### Describe alternatives you've considered

revisar como resolver este tema pues varias personas se estan quedando sin poder terminar las tareas de galxe por esto. yo tengo el antivirus de avast no si si tenga algo que ver seria positivo mostrarn una solucion para esto

### Additional context

tareas en galxe error por pishing como solucionar eso??
![image](https://github.com/taikoxyz/taiko-mono/assets/138340621/863136d1-8b0e-4607-a14a-33167a6c6bd3)
detectado por escudo web

**Comment by lacosteiro088ce** [comment]
Ok

**Comment by 2manslkh** [comment]
https://swap.l3test.taiko.xyz/

should be the correct l3 swap
