### ISSUE TITLE
direccion de contratos de token

### ISSUE THREAD

**Issue by llombetu** [taikoxyz/taiko-mono#14264]
### Describe the feature request

I don't see the search for token contracts as intuitive.
Maybe a section where all the contracts come. When I went to the network, I have not been able to find the horse token to add it to my metamask wallet in the latest version

### Describe alternatives you've considered

a search tab by name of token addresses to add to metamask

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
@llombetu thanks for the feedback. you are referring to the search on the documentation site right?

**Comment by llombetu** [comment]
that is

**Comment by dantaik** [comment]
I don't understand this feature request, is it about our documentation or the bridge UI?

**Comment by dantaik** [comment]
Let me close this issue but feel free to reopen it with additional info.
