### ISSUE TITLE
Add support for internationalization (i18n)

### ISSUE THREAD

**Issue by animal81** [taikoxyz/taiko-mono#14271]
### Describe the feature request

Description of the feature request hereDescription: The taiko-mono application currently only supports English, but we want to make it accessible to users who speak other languages. We need to add support for internationalization (i18n) so that the application can be easily translated into other languages.

### Describe alternatives you've considered

Description of the alternatives you've considered here. Implement the custom i18n solution throughout the application to enable language switching and translation of all text.

### Additional context

Additional context hereSkills needed: Familiarity with web development, experience with i18n libraries/frameworks.

To work on this issue, you could:

Research i18n libraries/frameworks that are compatible with the taiko-mono application and choose the one that best fits our needs.
Add the chosen i18n library/framework to the taiko-mono application.
Create language files for each language that we want to support, containing translations for all of the text in the application.
Implement the i18n library/framework throughout the application to enable language switching and translation of all text.
Test the application thoroughly to ensure that all text is translated correctly and that the language switching functionality works as expected.
Create a pull request from your forked repository to the main taiko-mono repository.
Wait for feedback and iterate on your changes as necessary.

**Comment by dantaik** [comment]
Localizing something too early is really a bad idea. I'd wait until Taiko core tech is ready for mess-addoption.
