### ISSUE TITLE
Function to enter the swap amount as a percentage

### ISSUE THREAD

**Issue by tikitikijiu** [taikoxyz/taiko-mono#14289]
### Describe the feature request

I would like the MAX button to be converted to a percentage input option. Most people do not swap their entire wallet of tokens, so having the ability to input a percentage would be convenient.

### Describe alternatives you've considered

Add % or slider instead of MAX button

**Comment by Inna78spb** [comment]
поддерживаю предложение предыдущего https://github.com/tikitikijiu Я хотел бы, чтобы кнопка MAX была преобразована в опцию процентного ввода. Большинство людей не обменивают весь свой кошелек жетонов, поэтому было бы удобно иметь возможность вводить процент.

**Comment by dantaik** [comment]
The swap UI is based on Uniswap's UI, and I don't think we are in the position to change it. BTW, we'll launch a new UI for Uniswap v3 on the next testnet.
