### ISSUE TITLE
feat(website): ecosystem page enhancements

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/taiko-mono#14281]
### Describe the feature request

The viewing experience for users on the [ecosystem page](https://taiko.xyz/ecosystem) could be made better with the following features:

- [ ] Add ecosystem integration status
- "live on A3 testnet" "live on A4 testnet" "live on mainnet" "no tag"

e.g. on zk sync

<img width="240" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/f6ff44f9-3990-4923-8319-f271e2d86a71">

- [ ] Add project tags and filters

<img width="240" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/8aaf4b6e-b744-40e4-9ef0-1eca90646349">

<img width="240" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/1976df6b-0336-4bdb-807f-5fbd48ded734">

- [ ] Optimize images

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
@d1onys1us anyone working on this?

**Comment by je4nt0nic** [comment]
This has been integrated onto [ecosystem page](https://taiko.xyz/ecosystem) on our site.
