### ISSUE TITLE
Broken Job Board link in Mirror Blog Posts

### ISSUE THREAD

**Issue by spachib** [taikoxyz/taiko-mono#14292]
Hey, I noticed the Job Board link at the end of the recent mirror [post](https://taiko.mirror.xyz/JMR41gK1TcTWa0NpwLfchJ-IJTtEX6RajqHF-A9qsZo) seems broken. It is currently https://taiko.mirror.xyz/828fd7232d2c4150a11e10c8baa910a2 and the working link is [here](https://taikoxyz.notion.site/Taiko-Jobs-828fd7232d2c4150a11e10c8baa910a2) you can find through the pink Explore Positions button on the Taiko homepage
I think similar links are broken in some of the past Mirror posts
Cheers

**Comment by 2manslkh** [comment]
Fixed. Thanks!
