### ISSUE TITLE
IDE / ETH

### ISSUE THREAD

**Issue by Avitron3174** [taikoxyz/taiko-mono#14294]
### Describe the bug

Hello,

The amount on metamask is in IDE on the other hand the same amount on swap.test.taiko.xyz is in ETH (the upper right corner)

Kind regards;

Avitron

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Bridge UI v1 has been deprecated.
