### ISSUE TITLE
Add Chaindrop Faucet to the ecosystem

### ISSUE THREAD

**Issue by ApoorvaUniLend** [taikoxyz/taiko-mono#14305]
### Title of your project

Chaindrop Faucet

### Short (1-2 sentence) description of your project

ChainDrop offers an effortless way to access Web3 test tokens. With just one click, you can receive free Web3 test tokens directly into your wallet.

### Link to your project

chaindrop.org

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://chaindrop.org/?chainid=167005&token=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

### Upload a quality logo to your project

<img width="2560" alt="Logo" src="https://github.com/taikoxyz/taiko-mono/assets/109734643/1f9b9069-6451-4ce2-83d6-3a66e0a20469">

**Comment by 2manslkh** [comment]
Could you provide a square logo? otherwise the logo would look like that on our ecosystem page:

<img width="321" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/f67a4660-0887-432f-9317-c6374e32fbe4">

**Comment by MarcusWentz** [comment]
Square logo:

![63cada285d04fb4e50ea9a1a_Q7dnrZGcc0gy6CcWtSn6rrclelWc5CX6oEwyJmjmOL4](https://github.com/taikoxyz/taiko-mono/assets/52706599/7bc06461-4aef-4271-be09-73ca20139944)
