### ISSUE TITLE
feat(bridge): combine swap and bridge in one app.

### ISSUE THREAD

**Issue by pucedoteth** [taikoxyz/taiko-mono#14318]
### Describe the feature request

combine **Swap** and **Bridge** in one app will make it visible for users. you can add a tap for **Bridge** and can easily navigated to **Bridge** of Taiko by clicking on it. Also do the same and insert **Swap** tap in **Bridge** interface. so users can move between **Swap** and **Bridge** without need to looking for swap and url. 

<img width="1131" alt="Screenshot 2023-07-30 at 5 39 44 PM" src="https://github.com/taikoxyz/taiko-mono/assets/119044801/418014d2-cd40-4246-8880-67cd1b35a8bf">

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by x520074** [comment]
hhhh

**Comment by Adriano0509** [comment]
Hello puyg

**Comment by d1onys1us** [comment]
we are working on this now by having one portal for bridge and swap. @jscriptcoder should we keep this issue open for tracking or not needed?

**Comment by dantaik** [comment]
@d1onys1us with Uniswap v3 UI to be launched, I don't think we are going to have one portal for bridge and swap, yes?

**Comment by d1onys1us** [comment]
yeah i don't think we should ever "combine them". perhaps in jane's website redesign we will improve the navigation bar links and/or add some easy tiles to link out to bridge/swap. zksync does have a "portal" here: https://portal.zksync.io/ but this combines things, which I think we should avoid.
