### ISSUE TITLE
Adding node errors on Taiko Docs page

### ISSUE THREAD

**Issue by zakk15** [taikoxyz/taiko-mono#14314]
### Describe the feature request

Many errors occur when running Prove/Proposer on Taiko's Testnet. The following link has various error indications, but there are errors that occur frequently in Discord, including mine

[](https://taiko.xyz/docs/reference/node-troubleshooting)

when run a node by mistake, the error display is "error="initialize rpc clients error" repeatedly.
This is an error caused by incorrect L2 or L3 RPC. 

### Describe alternatives you've considered

It is preferable to add specific examples of errors to the Docs.
A description of how to fix the error is as follows:

"The RPC in your config is wrong.
You have to set the ENDPOINT correctly.
Please refer to the following page to set the correct RPC
https://taiko.xyz/docs/guides/run-a-node/run-a-taiko-node"

### Additional context

Additional context here.

**Comment by KriptaHi** [comment]
No problem

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/14231 , https://github.com/taikoxyz/taiko-mono/pull/14316 , and will keep updating this page.
