### ISSUE TITLE
YouTube SEO Enhancement

### ISSUE THREAD

**Issue by vijayrajreddy** [taikoxyz/taiko-mono#14328]
### Describe the feature request

I saw Taiko YouTube video's have good values, but title and description is not optimized which leads to exposure to lesser audience + low views.

For example: https://www.youtube.com/watch?v=FCerB2PhLZI

**Problem**: Title with less words + no description and links

**Solution**: You can use title as "_TUTORIAL: How To Run a Taiko L3 Node in Few Steps_" _instead of "Run a Taiko L3 node_". You can add some nice description (around 100 words) and add links to setup the node directly in the description + use some hashtags. You can also add a custom thumbnail so that developers get to know what is the video about.

![Image1](https://github.com/taikoxyz/taiko-mono/assets/10988904/d746bc70-3c01-499c-92fb-45d62dd78786)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
@d1onys1us @MarcusWentz We should take note of this :)

**Comment by dantaik** [comment]
Good suggestion, I've forward it to Lisa and RJ on the team.
