### ISSUE TITLE
feat(bridge-ui-v2): add good humor and wisdom after each transaction

### ISSUE THREAD

**Issue by Peace92** [taikoxyz/taiko-mono#14321]
### Describe the feature request

The idea is to create something unique of its kind :

Add a data base with some Wisdom quote from enlightened masters about life, wisdom, love, meditation ...
Add a random feature.

So every user when they make a bridge transaction completed or a swap or whatever they see a nice quote that put a smile on their face :)  and are happy to use Taiko fonctionnalities.

Well being is primordial for every single human being ,
Love & light ♥

you can contact me in discord : mindfulness92

### Describe alternatives you've considered

an alternative may be to see a quote while waiting for a transaction or a waiting time ( instead of seing a hourglass or something like that a user can see a quote or 2 or maybe 3 while waiting)   :)

### Additional context

Some exempes for the Quotes :   

" If you truly loved yourself, you could never hurt another. "
- Buddha

"Peace comes from within. Do not seek it without. "
- Buddha
 
"We are shaped by our thoughts; we become what we think. When the mind is pure, joy follows like a shadow that never leaves."
- Buddha
 
“Just as a mother would protect her only child with her life, even so let one cultivate a boundless love towards all beings.” 
- Buddha 

"Your visions will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes. "
- Carl Jung

“The happiness of your life depends upon the quality of your thoughts.” 
Marcus Aurelius

**Comment by vijayrajreddy** [comment]
Instead of humor and wisdom, you can also add basic information about Taiko (like 1 liners, etc...) so that people get to know more about Taiko while waiting for the transaction to complete.

**Comment by Peace92** [comment]
My option is about well being and good humor , but Yes, this is also an option for the team, Love & light ♥

**Comment by sathmali** [comment]
is there anyone working on this . i would love to contribute

**Comment by segwizy** [comment]
i think more interesting info on taiko should be let out to build the community instead of humour and wisdom

**Comment by Decub** [comment]
I agree with wisdom talks or investment strategies that are not too lengthy at the end of any transaction. Reason is not far fetched and probably because personally, I have had cause to visit a 'wisdom quote' site every morning just to ensure I start up the day with something motivating and at the same time, enlightening.

**Comment by Earthgod96** [comment]
This is a welcome development. It's a beautiful ideal.

**Comment by Giri-Aayush** [comment]
Is someone working in this? Or can I take up this feature to work on?

**Comment by kakha2992** [comment]
good idea..make tx looks colorfull (make optional)

**Comment by alexandermacedonian** [comment]
what is the relation of this to the project

**Comment by paun88** [comment]
nice!

**Comment by dantaik** [comment]
I like this idea very much. The [new bridge UI (v2)](https://github.com/taikoxyz/taiko-mono/tree/main/packages/bridge-ui-v2) are being worked on, I welcome people to submit PR to add this feature.

**Comment by rabiyass1** [comment]
i would love to contribute

**Comment by Danubio-L** [comment]
I confess that I find this a bit crazy, but it is interesting nonetheless.

**Comment by 0xAshook** [comment]
It is very good for the user to see a philosophical, emotional, etc. sentence after each transaction and while waiting for its confirmation. But in my opinion, instead of this case, we can show **the most important points of excellence of this project** and **its competitive advantages** to the audience in the form of sentences or short paragraphs.
It will have a greater effect on _attracting the audience for future use_ and will also help strengthen this project scientifically.

**Comment by Jadavjanu** [comment]
Good

**Comment by 0xRoyalty1** [comment]
A good idea!
I personally think a "waiting time" for trx completion is better...like user get to know howlong their trx gonna take before successful completion.

**Comment by ayhan444** [comment]
nice

**Comment by DaDy75** [comment]
not bad at all

**Comment by Cucla321** [comment]
Good

**Comment by Stacker142069** [comment]
Mixing education, humour and wisdom could be interesting. Eg. Estimated bridge time followed by witty quotes.
"Don't rush the process. Good things take time".

**Comment by JI-NU** [comment]
The function of every user when they make a bridge transaction completed or a swap or whatever they see a wisdom quote from enlightened masters is great.
But taiko will be used by people all over the world.
Some people may not be able to read English.
Therefore, it would be a good idea to also display a diagram representing the randomly introduced quotes!
I think you can use AI to dynamically generate illustrations, or add illustrations to the database in advance.

**Comment by rubensher** [comment]
Good quotes, specially Buddha frases.

**Comment by AlpaniaRahman** [comment]
Fungsi setiap pengguna ketika mereka menyelesaikan transaksi jembatan atau pertukaran .ini sangat bagus dsn membantu untuk jembatan masa depan.

**Comment by aahr0707** [comment]
nice!
