### ISSUE TITLE
Amount of digits after dot

### ISSUE THREAD

**Issue by S7anislav** [taikoxyz/taiko-mono#14333]
### Describe the bug

Throuth my working with test net. if i'm trying to put max Eth on bridge and there is a lot of digits after dot Transaction doesn't work. It's msging "Failed to bridge founds. Try again later"

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by s7anly** [comment]
> Amount of digits after dot #14333 please
17 and more

**Comment by s7anly** [comment]
![IMG_20230803_211356](https://github.com/taikoxyz/taiko-mono/assets/141305733/19a8ca7b-7186-4960-9956-07edb50c2655)

**Comment by dantaik** [comment]
Bridge dapp v1 has been deprecated. See our new bridge app (v2) soon.
