### ISSUE TITLE
Suggestion Add RPC provider site link and change description position

### ISSUE THREAD

**Issue by nollie0107** [taikoxyz/taiko-mono#14334]
### Describe the feature request

As of 2023/08/01, there seems to be a scattered increase in demand due to request limits in the discord.
To increase the importance of this one, I will move the error description up and add a reference site.

### Reference Site

https://auth.alchemy.com/
https://www.infura.io/

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by Mdrislams** [comment]
Suggestion Add RPC provider site link and change description position #14334
