### ISSUE TITLE
swapping issue

### ISSUE THREAD

**Issue by LeidiAnn23** [taikoxyz/taiko-mono#14342]
### Describe the bug

many attempts to swap eth - bull or vise versa but can't go through

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
What do you mean by not being able to swap? Does the transaction hang at pending?

**Comment by dantaik** [comment]
Closing this issue due to lack of response from the issue author.
