### ISSUE TITLE
NFT tasks, Stake to earn (TTKO maybe)

### ISSUE THREAD

**Issue by Paschal695** [taikoxyz/taiko-mono#14343]
### Describe the feature request

I suggest we add a feature that allows NFT Staking to earn TTKO,bridge NFT, List NFT on marketplace place,buy NFT ,Sell NFT and so on.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
We can create a NFT borrowing and lending platform on Taiko :)

**Comment by kidochukwu** [comment]
i support this

**Comment by Web3metahunter** [comment]
Lending and borrowing would be nice

**Comment by Nghiavu0709** [comment]
good farming

**Comment by Vandayzm** [comment]
Imagine to bridging NFT

**Comment by dennyloureiro13** [comment]
I really agree with the suggestions given. nft is something that is hype right now

**Comment by dantaik** [comment]
:) Nope sorry.

**Comment by Paschal695** [comment]
😭😭😭
