### ISSUE TITLE
Transactions stuck/slow on metamask.

### ISSUE THREAD

**Issue by abidex0z** [taikoxyz/taiko-mono#14354]
### Describe the bug

I have been trying to do different transactions on taiko testnet through metamask, and i noticed it takes time before it will eventually  go through and sometimes it will get stuck and i hope the team will attend to this issue in order to enhance a smooth transaction.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by kareem-89** [comment]
The problem is from matamask, you need to always click approve before any transaction can go through
