### ISSUE TITLE
Develop a dashboard to monitor Eldfell L3

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/taiko-mono#14352]
### Describe the feature request

I found a great tool not long ago to monitor my node on Grimsvotn L2 but it's doesn't work for Eldfell L3.

### Describe alternatives you've considered

It would be cool to upgrade wolfderechter dashboard

### Additional context

Additional context here.

**Comment by spachib** [comment]
Wolf's Taiko Node Dashboard is a community project, you can find it and provide feedback here https://github.com/wolfderechter/taiko-node-dashboard
