### ISSUE TITLE
Galxe taiko task approve bug

### ISSUE THREAD

**Issue by Aztercrew** [taikoxyz/taiko-mono#14351]
### Describe the feature request

I am contributtor in galxe taiko task
Can you fix the task in galxe because every page open or back to page must approve in metamask
i have to agree a lot on the metamask or the taiko task page on the galxe not updating

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
we can send this feedback to the galaxe team, but unfortunately it's outside of our domain.
