### ISSUE TITLE
The swap window shifts when switching between tabs

### ISSUE THREAD

**Issue by Mazhula** [taikoxyz/taiko-mono#14355]
### Describe the bug

When switching between the 'Swap' and 'Pool' tabs on Grimsvotn or on Eldfell, there is a minor graphical bug where the window shifts slightly to the left when clicking on 'Pool' compared to 'Swap.' This bug occurs at resolutions: 1455 x 712, 1600 x 783.
It's a visual issue that doesn't affect the overall process.

### Steps to reproduce

1. Open Google Chrome
2. Change window resizer to 1455 x 712 or 1600 x 783
3. Join https://swap.test.taiko.xyz/
4. Сlick on the button "Pool"

### Additional context

![5](https://github.com/taikoxyz/taiko-mono/assets/1078060/7bb9e7b5-3d23-401a-be36-a25bf5afafbc)

**Comment by gaganoo** [comment]
just fine, it doesn't affect the overall process at all, and maybe the bug is coming from the window resizer 
extensions

**Comment by yasineylul** [comment]
Nice job

**Comment by Web3metahunter** [comment]
It's just fine

**Comment by Reza28Trade** [comment]
it's look fine already /sir

**Comment by lamvu1994** [comment]
I'm interested in working on

**Comment by Sparspae** [comment]
This is fine already

**Comment by rainman420** [comment]
I'm interested in working on

**Comment by dantaik** [comment]
We'll deploy uniswap v3 UI for the next testnet.
