### ISSUE TITLE
The grimsvotn  to Eldfell L3 is very buggy. And inconsistent.

### ISSUE THREAD

**Issue by Adelbah** [taikoxyz/taiko-mono#14360]
### Describe the bug

Whenever I'm bridging to Eldfell L3 from grimstone I find it to be very laggy and very rarely it achieve the  approval and bridging in less than 5 min

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Do you mean that the transaction stays pending for a long time when trying to bridge from L2 to L3?
