### ISSUE TITLE
optimize code

### ISSUE THREAD

**Issue by dc4finance** [taikoxyz/taiko-mono#14361]
### Describe the feature request

Greetings and regards to the project developers.  The speed of transactions can be improved by making some modifications and styling in the codes.  In the ui-ux part, it has been done well, but the place of notifications needs changes.  Sometimes they do not perform well during transactions, which can become a more serious problem with the increase in network traffic and simultaneous transactions.  With respect

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
thank you for your feedback. we are going to deploy a new version of the bridge-ui which should have better notifications.
