### ISSUE TITLE
Multiple failed HORSE and ETH bridge transactions from L2 to L3 

### ISSUE THREAD

**Issue by Cryptographix-Designs** [taikoxyz/taiko-mono#14372]
### Describe the bug

There were multiple failed transactions in a row when attempting to bridge HORSE and ETH from L2 to L3. I ultimately had to force quit browser and re-enter the bridge several times before achieving a successful transaction.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
What do you mean by failed transactions? Do they show a failure message or are they stuck in pending?

**Comment by dantaik** [comment]
Closing this issue due to lack of response.
