### ISSUE TITLE
Little bug (ide/eth)

### ISSUE THREAD

**Issue by VLDNSP** [taikoxyz/taiko-mono#14379]
### Describe the bug

Greetings,

The balance displayed on metamask is denominated in IDE tokens, whereas the exact same balance on swap.test.taiko.xyz is in ETH tokens (located in the upper right corner).

Best regards

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
This has to do with your metamask settings
