### ISSUE TITLE
Check the balance of ttko,ttkeoe that I deposited in explorer.

### ISSUE THREAD

**Issue by tukimi666** [taikoxyz/taiko-mono#14389]
### Describe the feature request

Deposit in explorer is required to run Propose.If the Propose is successful, the balance will be reduced.So I thought it would be useful to have a place where I could check how much more I have left in my balance.I found it inconvenient that I could not check my balance.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
You can add the token to your metamask and view your TTKO balance there.


Click on the "Add Sepolia Tokens" button to easily add TTKO token to your metamask:
https://taiko.xyz/docs/guides/build-on-taiko/setup-your-wallet

**Comment by tukimi666** [comment]
Not metamasku, I'm talking about currency deposited directly in Explorer.

2023年8月7日(月) 11:26 Kenk ***@***.***>:

**Comment by 2manslkh** [comment]
Ah so you would want a dashboard to see TTKO / TTKOe in your wallet as well as TTKO / TTKOe deposited in the TaikoL1 contract

**Comment by d1onys1us** [comment]
you can check the balance on the TaikoL1 contract. i will close the issue for now.
