### ISSUE TITLE
feat(website): add check TTKO balance / withdraw TTKO guidance on website

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#14382]
### Describe the feature request

I think we need to edit the claim prover rewards guide to more generically be for withdrawing taiko token. that's because you should be able to withdraw Taiko token also after you deposit some (not necessarily from prover rewards).

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Dave, can people do it by interacting with our verified contracts through Blockscout's UI?
