### ISSUE TITLE
Feedback for “Bridge tokens”

### ISSUE THREAD

**Issue by Turgskaya** [taikoxyz/taiko-mono#14387]
When using the bridge, the bridge button does not turn on time without selecting the maximum amount. I have to select max. first and then enter the amount I want. Is it normal? Thank you.

**Comment by 2manslkh** [comment]
What do you mean by "does not turn on time" ?

To bridge tokens:

1.

**Comment by Turgskaya** [comment]
sorry to poor english. I mean sometimes when i enter the amount that i want to brigde, bridge button doesn't show up, then i click to max to solve the problem. after that i enter the amount that i want to bridge. maybe it's an issue with my internet connection, i don't know.

**Comment by dantaik** [comment]
Bridge UI v1 has been deprecated, please try v2 with the next testnet.
