### ISSUE TITLE
Morkie

### ISSUE THREAD

**Issue by mazzwell** [taikoxyz/taiko-mono#14396]
### Title of your project

Morkie

### Short (1-2 sentence) description of your project

Morkie aims to create an immersive oasis for NFT enthusiasts and collectors, offering them a unique space to not only showcase their digital assets but also to earn rewards for their loyalty and participation in the ecosystem. Our vision is to foster a thriving community that embraces the potential of NFTs beyond static ownership.

### Link to your project

https://www.morkie.xyz/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://www.morkie.xyz/

### Upload a quality logo to your project
![morkiexyz](https://github.com/taikoxyz/taiko-mono/assets/137079218/da8aa5fa-d365-4ec9-8036-ff10d66ae143)

**Comment by 2manslkh** [comment]
@mazzwell Could you provide a square logo for your dapp :)

**Comment by mazzwell** [comment]
yes. sorry I forgot

**Comment by 2manslkh** [comment]
thanks bro
