### ISSUE TITLE
Transaction stuck up swap in ttko

### ISSUE THREAD

**Issue by jeffreyplumber** [taikoxyz/taiko-mono#14392]
### Describe the bug

swaping ttko always stuck up when using normal gas fee.
need to use speed up and x30 gas fee.
 team need to fix the gas problem.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Seems to be some congestion.

@cyberhorsey @davidtaikocha Any advice on this?

**Comment by davidtaikocha** [comment]
Like in current Ethereum, if there are some congestion, the only solution is increasing gas fee too.
