### ISSUE TITLE
Access permission signature incl date and time in addition to amount

### ISSUE THREAD

**Issue by FFicey** [taikoxyz/taiko-mono#14391]
### Describe the feature request

worst of many scams is they initially rely on the permission that the user grants. Even scarier is some contract being altered after gaining permission and abusing the end-users permission signature. Adding max pain to the damage caused to end-users severely deminishing the user experience.

### Describe alternatives you've considered

A possibility to add a time-frame next to llimiting the amount of funds a signature grants access to a contract would imho greatly increase safety for the  enduser and atleast limit scammers.

### Additional context

If web3 wants to grow it will also need to facillitate the less skilled populus.

**Comment by 2manslkh** [comment]
@FFicey Which contract are you referring to?

**Comment by FFicey** [comment]
any permission to withdraw assets from any adress wether tokens or NFTs. should not only have an option to limit the amount but also the timeframe. I can't think of any contract that really needs permission signatures to stay valid forever or until revoked. revoking is also a gas consuming transaction.

**Comment by 2manslkh** [comment]
This would require a modification to the ERC20 / ERC721 / any asset class tokens. You can implement this in your own token smart contract logic :). But existing tokens most likely will not implement this logic

**Comment by FFicey** [comment]
thx for explaining its impossible. I expected a new layer to have more flexibillity.
please remember me to fix this when i launch my own chain. Just drop an issue in the repository ;) 

Until then i'll just stick to sharing feedback and ideas in the dedicated sections. as requested.
