### ISSUE TITLE
Correction of node documentation

### ISSUE THREAD

**Issue by tukimi666** [taikoxyz/taiko-mono#14398]
### Describe the bug

https://taiko.xyz/docs/guides/run-a-node/run-a-taiko-node
Step 3 on this page.
・L2_ENDPOINT_HTTP
・L2_ENDPOINT_WS
If it were written the way it is now, I would mistakenly think that the L3 setting should be the same URL as the L2.
Shouldn't it be noted in the L3 that an INTERNAL PORT is required as a precaution?
L3 Copying and pasting Alchemy's APIKEY as is did not work.
For example
L2_ENDPOINT_HTTP=http://l2_execution_engine:8545/
L2_ENDPOINT_WS=ws://l2_execution_engine:8546 worked fine.
I don't think the explanation of the L3 configuration is sufficient.

Second.
https://taiko.xyz/docs/guides/run-a-node/enable-a-prover
1step
You should write that it is nano .env.l3 nano .env.
env alone is not sufficient.It is hard to understand if you don't write down to nano.
Thank you for your consideration.

**Comment by 2manslkh** [comment]
Thanks for highlighting this. Will make the changes ser

**Comment by tukimi666** [comment]
Glad I was helpful! I would like a POAP

**Comment by 2manslkh** [comment]
Check out #14400

**Comment by tukimi666** [comment]
check done. Thanks for writing the pull request!
 can I get a GitPOAP?

**Comment by tukimi666** [comment]
I was able to check, and would appreciate it if you could link me to this page.
Can I get a gitpoap?
