### ISSUE TITLE
MORE ETH FOR TESTNET 

### ISSUE THREAD

**Issue by issammassi** [taikoxyz/taiko-mono#14393]
### Describe the bug

Description of the bugHY EVERYBODY IS THERE A SOLUTION TO GET MORE TESNET TOKEN AND ETH 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
You can get more testnet ETH by bridging ETH from sepolia to Taiko.

1. Get some sepolia eth from the list of sepolia faucets [here](https://taiko.xyz/docs/guides/build-on-taiko/receive-tokens#receive-sepolia-eth) 
2. Bridge your sepolia eth to taiko [here](https://bridge.test.taiko.xyz/)

@issammassi 

Closing the issue as it does not require any changes
