### ISSUE TITLE
Bug in staking dashboard for Eldfell L3 provers

### ISSUE THREAD

**Issue by Tsubasa-Kasuga** [taikoxyz/taiko-mono#14394]
### Describe the bug

There was a bug in the staking dashboard for Eldfell L3 provers.
This staking dashboard was supposed to be for Grimsvotn L2, but Eldfell L3 was also able to connect to it. And when connected to Eldfell L3 and the staking button is pressed, a transaction can be sent.
I think we should originally be prompted to change the network and go to Grimsvotn L2 to prompt the transaction to send the transaction.

### Steps to reproduce

1. Connect the meta mask with Grimsvotn L2.
2. Switch to Eldfell L3 with Metamask
3. I get a warning "Not on the right network" on the dashboard.
4. When I press the "Grimsvotn L2" button on the popup, I get a message that the chain switch was successful, but it is still connected to the Eldfell L3 chain.
5. Press the STAKE button in this state.
6. Transaction gets issued on Eldfell L3 network. This is also a problem because the top right corner of the dashboard shows Grimsvotn L2.

### Additional context

■staking dashboard
https://staking.l3test.taiko.xyz/

■Corresponding part of the manual
https://taiko.xyz/docs/guides/run-a-node/enable-a-prover#stake-your-ttkoe-eldfell-l3-provers-only

**Comment by 2manslkh** [comment]
Can you show the transaction on L3?

**Comment by Tsubasa-Kasuga** [comment]
This transaction.
https://explorer.l3test.taiko.xyz/tx/0x20fea6fde36847bb8d35c771275fba0a2de7b7d4d9c783f36df9a40f40614ae0

<img width="1713" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/69389755/fbe7a2ac-2020-4507-95dd-69b996cdcd1a">

**Comment by 2manslkh** [comment]
Seems like 0xC95... is the contract address for the [prover pool on L2](https://explorer.l3test.taiko.xyz/address/0xC9580414A4372BDdBd8e19e01854DC0B2b1390Cf) and that there have been a few others who have accidentally transferred eth there

I managed to reproduce the error.

**Possible solution:**

Check chainId again before allowing user to click on Stake button

cc: @cyberhorsey @davidtaikocha

**Comment by cyberhorsey** [comment]
Will do, thanka for the bug report

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/14447
