### ISSUE TITLE
Add neuron 🧠 to Taiko ecosystem

### ISSUE THREAD

**Issue by goneuronxyz** [taikoxyz/taiko-mono#14405]
### Title of your project

neuron 🧠

### Short (1-2 sentence) description of your project

neuron is a blazing fast privacy focused cross-chain bridge for transferring Ethereum native assets quickly and privately between chains faster than L1 native bridges cheaply. 

### Link to your project

goneuron.xyz

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

Listing of testnet contract in documentation https://docs.goneuron.xyz/details/contracts

### Upload a quality logo to your project

https://pbs.twimg.com/profile_images/1680516268854595584/t1PJ5Amj_400x400.jpg

![neuron_large](https://github.com/taikoxyz/taiko-mono/assets/141687054/ba59f5a1-a113-4823-8688-7500c4120598)

**Comment by 2manslkh** [comment]
Can you add a square logo? It will look better on the ecosystem page

**Comment by goneuronxyz** [comment]
Could you use the circular one linked above please?
