### ISSUE TITLE
Financial Incentives for Closing GitHub Issues

### ISSUE THREAD

**Issue by pavlovcik** [taikoxyz/taiko-mono#14413]
I stumbled upon your org/repos when checking out some of our community contributors' other repositories they worked on. 

We made a GitHub bot to financially incentivize open source development on GitHub. It currently does payouts in DAI and WXDAI all via decentralized wallets and GitHub comments. It boosts developer engagement and would help you guys close out issues faster. We are also looking for beta testing partners.

It is designed for proper git flow: with filing issues, associating pull requests, and closing those issues (as you guys currently do.) The bot allows people register their wallet inside of GitHub comments (e.g. `/wallet 0x0000`) and then it allows them to claim the reward when the issue is closed as completed. 

- Overview from developer perspective: https://dao.ubq.fi/devpool-flow
- A real issue example: https://github.com/ubiquity/ubiquibot/issues/546

Does it sound interesting to try?

**Comment by dantaik** [comment]
Instead of setting up a reward explicitly to incentivize contributors, we'd rather reward tokens after people have contributed something to our repo.

**Comment by pavlovcik** [comment]
Yes the rewards are paid out when you mark the issue as completed. Generally this means a pull request is linked to an issue, reviewed, and merged. Once it's merged, they have contributed something to your repo.
