### ISSUE TITLE
Add cool visual for processing transactions (swapping or bridging)

### ISSUE THREAD

**Issue by Bitmage77** [taikoxyz/taiko-mono#14439]
### Describe the feature request

A visualization for the transaction status would be nice. Established DEX's have that as well (e.g. Orbiter or Stargate). A percentage display or an estimated time would be great. In my opinion, the pending signal in the top right corner could be improved.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
There will be visual improvements in the v2 bridge ui
