### ISSUE TITLE
Is it possible to have a feature like transfer from L1 to L3 directly

### ISSUE THREAD

**Issue by CZSOUL21** [taikoxyz/taiko-mono#14433]
### Describe the feature request

Bridging from L1 to L3 directly without switching to L2 first and then bridge to L3

### Describe alternatives you've considered

It is more practical to transfer your assets to L3.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
We have a new bridge coming which will support this. Stay tuned!
