### ISSUE TITLE
Make contributions and GitPoap reward a GALXE task

### ISSUE THREAD

**Issue by foxxjhony** [taikoxyz/taiko-mono#14445]
### Describe the feature request

It would be nice to have contributions and suggestions a galxe task, as this will give it more publicity and traffic. We would have more people contributing if we do.

Thanks

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by Iamjustified** [comment]
This is a very nice Idea, it will be easily accessible for all

**Comment by goblokID** [comment]
nice idea but gitpoap for contributions at github only no others.
