### ISSUE TITLE
Considering to make taiko nft play & earn

### ISSUE THREAD

**Issue by Immar24** [taikoxyz/taiko-mono#14449]
### Describe the feature request

Will be a cool feature if we can have our costume nft that can we stake on taiko

### Describe alternatives you've considered

We can learning from another crypto project like defi kingdom or axie projects that introduce nft play and earn

### Additional context

Context : added an nft feature that can we manually costume our nft

**Comment by dantaik** [comment]
Thank you for the idea, we'll think about it:)
