### ISSUE TITLE
See the price ratio earlier

### ISSUE THREAD

**Issue by anti185** [taikoxyz/taiko-mono#14442]
### Describe the feature request

Now that we choose two tokens to exchange them, we don't see their relationship with each other. We will only see this when we enter the value of one of them. Why can't we see this ratio at once when we chose two tokens? That would be logical. I could immediately understand the value and quantity to exchange. Now I have to guess with the first attempt to understand how many tokens I need

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

now - https://ibb.co/C7M5dxD
will see price after we enter the value of one of them - https://ibb.co/cXrFp38
should be - https://ibb.co/p0gpFLL

**Comment by dantaik** [comment]
We will deploy uniswap v3 UI for our next testnet. But even if there are room for improvements in the UI, I don't think we are in the position to enhance it.
