### ISSUE TITLE
Bug while approving liquidity. 

### ISSUE THREAD

**Issue by Bitmage77** [taikoxyz/taiko-mono#14440]
### Describe the bug

In the pending image (https://swap.l3test.taiko.xyz/#/add/ETH/0x804FADE1e0F9b1F5Af6bEF6c615c9af3Af823336), it can be observed that the transaction is still pending, but the swap (which is the subsequent step) is already marked with a green checkmark. Shouldn't this only happen once the approve transaction is completed? Please see the attached screenshot.
![Screenshot 2023-08-10 115807](https://github.com/taikoxyz/taiko-mono/assets/116085817/9f4880d7-93d8-4c6e-9b00-22b3b7802a78)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Lets wait to see how the Uniswap v3 UI perform on Taiko's next testnet.
