### ISSUE TITLE
feat(bridge-ui-v2): auto-refresh wallet balance

### ISSUE THREAD

**Issue by fernandoparks** [taikoxyz/taiko-mono#14456]
### Describe the feature request

You can add autorefresh wallet balance, or add a reload button for it
Because it shows real balance only after reloading the page

### Describe alternatives you've considered

-

### Additional context

-

**Comment by dantaik** [comment]
@KorbinianK @xiaodino when we bridge something, the balance should be refreshed. Please test the new UI.

**Comment by KorbinianK** [comment]
fixed in https://github.com/taikoxyz/taiko-mono/pull/14539 for v2
