### ISSUE TITLE
feat(bridge-ui-v2): Transaction Auto Refresh

### ISSUE THREAD

**Issue by robcrypt25** [taikoxyz/taiko-mono#14454]
### Describe the bug

Screen continues to show Tx pending even when completed - auto refresh notification would be helpful and more user friendly

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
@KorbinianK @xiaodino I guess this is about subscribing to certain events from within the app?

**Comment by KorbinianK** [comment]
This is coming soon with v2. Stay tuned!
