### ISSUE TITLE
Changing a Layer 2 wallet to Layer 3 wallet or vice versa when the bridge is very long and error makes transcactions longer and difficult.

### ISSUE THREAD

**Issue by ichsnrmdni** [taikoxyz/taiko-mono#14464]
### Describe the bug

When the L2 to L3 bridge is active https://bridge.test.taiko.xyz/ and the connection on metasmask is smooth, but when we are still connected to the wallet at https://bridge.test.taiko.xyz/ and we will access the bridge at https://bridge.l3test.taiko.xyz/ for the L3 to L2 bridge and changing the wallet connection, this causes an error so the ETH in the wallet is not read clearly.
and it makes us have to close the web bridge first and start reconnecting the wallet, this makes transactions longer and more difficult.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Are the L2 and L3 bridges combined in the bridge-ui v2? @jscriptcoder

**Comment by Smart-Q-s** [comment]
ye!   bro, You have solved my problem. When using L1 for swap, you need to close the L2-L3 swap webpage first, otherwise the L1 swap page will have a bug where the account amount cannot be read.

**Comment by jscriptcoder** [comment]
@2manslkh V2 will support L2 and L3
