### ISSUE TITLE
Token approval stuck on pending

### ISSUE THREAD

**Issue by adrinaticaret** [taikoxyz/taiko-mono#14465]
### Describe the bug

when you want to add liquidity , you need to approve horse , ttkoe and bll.
did all and done but testnet still processing firs one ( HORSE ) 
![image](https://github.com/taikoxyz/taiko-mono/assets/136897992/1097adb2-5e6f-485b-b456-7f06533d1784)
you can see HORSE already approved and added to the pool but it shows pending and also direct to empty Tx

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Please wait for abit as the network may be a little congested :)

**Comment by adrinaticaret** [comment]
doing task was not an issue , approving process was done , the transaction shows still pending !
