### ISSUE TITLE
bridge BLL from L2 to L3

### ISSUE THREAD

**Issue by achiepatricia** [taikoxyz/taiko-mono#14460]
### Describe the bug

Can't bridge BLL , Horse , from Grimsvotn L2 to Eldfell L3, Tx pending. and get failed.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by Vandayzm** [comment]
No coment

**Comment by anamtheblue** [comment]
Thx

**Comment by 2manslkh** [comment]
Can you provide the tx hashes?

**Comment by Uzzairedrix** [comment]
It's working smoothly now. Go and try

**Comment by davidtaikocha** [comment]
> It's working smoothly now. Go and try

Thank you for feedbacks.
