### ISSUE TITLE
Navigation Logo is missing at Swap Page

### ISSUE THREAD

**Issue by lamvu1994** [taikoxyz/taiko-mono#14467]
### Describe the bug

**Issues statement:**
At Swap Page is now missing logo TAIKO navigation to Main Page. 
You can see at the Bridge Page have Logo TAIKO but at the Swap Page missing Logo TAIKO on the top left of page.

### Steps to reproduce

**You can check issue with this process:**
1. go to mainpage: https://taiko.xyz/
2. go to tab swap at mainpage: https://swap.test.taiko.xyz/#/
3. See on the top left page => missing Logo TAIKO navigation

### Additional context

**At Swap Page missing Logo TAIKO:**
![3](https://github.com/taikoxyz/taiko-mono/assets/134614657/653c66bc-509a-45a2-9d19-2f8044c51ad5)

Here is Bridge Page:
![4](https://github.com/taikoxyz/taiko-mono/assets/134614657/b032e343-3a94-417d-8c67-7ad16e8f2ae1)

Here is Main Page:
![5](https://github.com/taikoxyz/taiko-mono/assets/134614657/96757c61-e7dc-414a-bbd6-fc9461cd9b85)

**Comment by melihaltin** [comment]
if you want i can fix this problem

**Comment by lamvu1994** [comment]
I think Logo navigation very importance, user easy to go back mainpage or open new tab can click it.
@melihaltin yes, keep it up sir!

**Comment by KoxyG** [comment]
i am interested in working on this issue

**Comment by lamvu1994** [comment]
> i am interested in working on this issue

This is a important issue need fix as soon as possible sir.

**Comment by dantaik** [comment]
This UI is deprecated, we'll deploy Uniswap V3 UI on our next testnet.

**Comment by lamvu1994** [comment]
> This UI is deprecated, we'll deploy Uniswap V3 UI on our next testnet.

good job sir!
