### ISSUE TITLE
using the --remove-orphans flag 

### ISSUE THREAD

**Issue by AlexSHuk** [taikoxyz/taiko-mono#14475]
### Describe the bug

the documentation states the following
<img width="861" alt="Снимок экрана 2023-08-13 в 22 38 08" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/0f6f9d6c-184e-42a2-b7b1-a836a77c7048">
however, given the directory structure when cloning the repository 
<img width="603" alt="Снимок экрана 2023-08-13 в 22 40 05" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/0f132264-faaa-47cf-b218-e93b022ca088">
the user will encounter a problem, namely: 
- when L3 containers starts, all L2 containers will be destroyed. 
Example:
1. Running L2 containers
<img width="1438" alt="Снимок экрана 2023-08-13 в 22 43 02" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/ac54641f-b18d-430d-b0a2-1130c8ba00f1">
2. Running L3 containers
<img width="1438" alt="Снимок экрана 2023-08-13 в 22 44 38" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/9c1714b3-cd9d-41e7-b8db-1aa7be7d2802">
You can see that all L2 containers were killed by the flag --remove-orphans

### Steps to reproduce

**Solution**
use 2 different directories for L2 and L3 , for examples : 
<img width="587" alt="Снимок экрана 2023-08-13 в 22 52 08" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/4e64404c-70cb-4e5b-96f7-ebb81983ee78">
in this case, when L3 starts with --remove-orphans flag  , the L2 containers remain untouched
<img width="1436" alt="Снимок экрана 2023-08-13 в 22 50 45" src="https://github.com/taikoxyz/taiko-mono/assets/44318764/860585f0-0639-4238-90bc-0fecb81d98dc">

### Additional context

The --remove-orphans flag applies to all containers running within the Docker Compose project, regardless of the configuration file used to start them. Therefore, if there are other docker-compose.yml or docker-compose.*.yml files in the same directory, all containers not associated with any of these configuration files will be considered orphaned and will be removed when the --remove-orphans flag is used.

**Comment by AlexSHuk** [comment]
@d1onys1us  d1onys1us check please my issue .

**Comment by d1onys1us** [comment]
@gitpoap-bot please give @AlexSHuk a gitpoap
