### ISSUE TITLE
docs(website): small changes

### ISSUE THREAD

**Issue by brachsterX** [taikoxyz/taiko-mono#14476]
### Describe the feature request

# Minor changes

* `cp` is not recognized in Windows. Might be helpful to add a Windows compatible option
  - [2. Enable archive node](https://taiko.xyz/docs/guides/run-a-node/run-a-sepolia-node)
  - [2. Copy the sample .env files](https://taiko.xyz/docs/guides/run-a-node/run-a-taiko-node)
*  `sudo` is not recognized in Windows. Might be helpful to add a Windows compatible option
   - [4. Complete the eth-docker quickstart](https://taiko.xyz/docs/guides/run-a-node/run-a-sepolia-node)
   - [4. Start a node](https://taiko.xyz/docs/guides/run-a-node/run-a-taiko-node)
   - [5. Verify node is running](https://taiko.xyz/docs/guides/run-a-node/run-a-taiko-node)
*   `nano` is not recognized in Windows. Might be helpful to add a Windows compatible option
    - [5. Open .env file in simple-taiko-node](https://taiko.xyz/docs/guides/run-a-node/enable-a-proposer)
    - [1. Open the .env file in simple-taiko-node](https://taiko.xyz/docs/guides/run-a-node/enable-a-prover)
* `docker` is not recognized in Windows. Might be helpful to add a Windows compatible option
  - [3. Verify prover logs](https://taiko.xyz/docs/guides/run-a-node/enable-a-prover)
 
 ## Reword Claim prover rewards steps
* Step 1
  - From: Go to the TaikoL1 _**contract read**_ page... and input your prover address...
  - To: Go to the TaikoL1 _**Read Proxy**_ page... and input your prover address _**in `10.  getTaikoTokenBalance`**_ 
* Step 2
  - From: Switch to the _**contract write**_....
  - To: Switch to the _**Write Proxy**_

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by brachsterX** [comment]
Wen poap @d1onys1us (:

**Comment by d1onys1us** [comment]
> Wen poap @d1onys1us (:

@gitpoap-bot please reward @brachsterX
