### ISSUE TITLE
ChainPray is still in constant iteration, hoping to get the support of Taiko

### ISSUE THREAD

**Issue by zerochl007** [taikoxyz/taiko-mono#14480]
### Title of your project

ChainPray

### Short (1-2 sentence) description of your project

The mission of ChainPray is to provide spiritual assistance to ordinary users in the cryptocurrency community who have been affected by hackers, bad actors, liquidation, and other harmful events. ChainPray ingeniously combines traditional prayer with blockchain technology. Here, every user has the right to claim a "PrayLuck" (PrayLuck Coin) daily for free, which can be used to activate the daily prayer function and receive blessings from the blockchain, ushering in a positive and uplifting day.

### Link to your project

https://chainpray.com

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://test.taikoscan.io/address/0x41C100E9BB4571D51AA421De0E9152735E9698Fc

### Upload a quality logo to your project

![cosmos-big](https://github.com/taikoxyz/taiko-mono/assets/11828255/d10deacd-b7cb-4b23-a44e-18fef36d69d6)

**Comment by thanhduoc200597** [comment]
Tế

**Comment by zerochl007** [comment]
@thanhduoc200597 what?
