### ISSUE TITLE
Failed to faucet token testnet

### ISSUE THREAD

**Issue by ynhstick** [taikoxyz/taiko-mono#14487]
### Title of your project

Failed to faucet token testnet

### Short (1-2 sentence) description of your project

Failed to faucet token testnet

### Link to your project

https://bridge.test.taiko.xyz/#/faucet

### Live on Testnet

Yes (default)

### Upload a quality logo to your project

i couldn't faucet token testnet

**Comment by MarcusWentz** [comment]
1. Which token?
2. What is your wallet address?
3. Do you have a screenshot for an exact error you saw?

**Comment by dantaik** [comment]
Closing this as there is no response from @ynhstick
