### ISSUE TITLE
Failed to add liquidity

### ISSUE THREAD

**Issue by cala111982** [taikoxyz/taiko-mono#14485]
### Describe the bug

Two failed try to add liquidity on Eldfell (L3)

![taiko](https://github.com/taikoxyz/taiko-mono/assets/132839895/dec6091a-cc55-4ded-b8ed-5b8733712ca1)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by thanhduoc200597** [comment]
Oh

**Comment by dantaik** [comment]
This UI will be deprecated soon.
