### ISSUE TITLE
Approve/Swap transactions loading

### ISSUE THREAD

**Issue by AXES-SPEC** [taikoxyz/taiko-mono#14507]
### Describe the bug

Description of the bug here.The approve transaction tap on taiko l3test site takes too long to be approved and after approval the Swap tap takes too long to pop out

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Lets wait to see how the Uniswap v3 UI perform on Taiko's next testnet.
