### ISSUE TITLE
Feedback for “Swap tokens”

### ISSUE THREAD

**Issue by IgorStarchenko** [taikoxyz/taiko-mono#14509]
0x83895c0A43AD7008f9619aF702Cb271f36BbE9b4

I have a problem, I have 2 taiko networks and one has no funds, but all the time it transfers to the one that is empty
![Снимок 2023-08-15 10 40 32](https://github.com/taikoxyz/taiko-mono/assets/140015536/3081ad76-01ce-4315-9c56-e0b434a42488)
![MetaMask Notification 2023-08-15 10 39 35](https://github.com/taikoxyz/taiko-mono/assets/140015536/c24c00ec-65c9-401d-8d8b-f8fd66a3ae6f)
![Bridge - Google Chrome 2023-08-15 10 39 14](https://github.com/taikoxyz/taiko-mono/assets/140015536/3a1cf639-21c4-4a22-89d3-347e84dad974)

**Comment by dantaik** [comment]
Bridge dapp v1 has been deprecated.
