### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by FPniMAT** [taikoxyz/taiko-mono#14506]
### Describe the feature request

Upon opening Swap and upon clickiing "Connect Wallet" maybe you add the speciefic wallet like the other DEX instead of the feature "New to Etherium? Learn more about wallet.
![Screenshot_20230815-124457_Kiwi Browser](https://github.com/taikoxyz/taiko-mono/assets/78898754/cce5f4e5-a5a6-4183-bace-dcd6ea1d73bd)

### Describe alternatives you've considered

Suggetions only, I knew that this would be a great project soon.

### Additional context

Additional context here.
![Screenshot_20230815-124457_Kiwi Browser](https://github.com/taikoxyz/taiko-mono/assets/78898754/171691dc-3cd5-4d42-8205-38743b8c34ae)

**Comment by dantaik** [comment]
We'll launch a Uniswap v3 UI for the next testnet.
