### ISSUE TITLE
add pool issue

### ISSUE THREAD

**Issue by BiChou999** [taikoxyz/taiko-mono#14505]
### Describe the bug

Can not access add liquid pool.

### Steps to reproduce

 Just refresh page and increase gas fee.

### Additional context

![add pool failed](https://github.com/taikoxyz/taiko-mono/assets/116357634/880b7a0b-4868-42d8-9de0-fd546807d103)
![add pool 1](https://github.com/taikoxyz/taiko-mono/assets/116357634/f481973f-2753-4738-bab2-ac5883124560)
![edit gas fee - aggressive](https://github.com/taikoxyz/taiko-mono/assets/116357634/8273e8ab-9493-48c5-a6d6-d5d0f3ec1a05)

**Comment by BiChou999** [comment]
please check

**Comment by MaksymOsmakov** [comment]
check

**Comment by dantaik** [comment]
We'll launch a Uniswap v3 UI for the next testnet.
