### ISSUE TITLE
Selection by tab entry on the select token screen is not possible.

### ISSUE THREAD

**Issue by applepie493** [taikoxyz/taiko-mono#14513]
### Describe the bug

The UI is inconvenient for those who do not operate with a mouse.
Also, the ability to move tabs would reduce operation time.

### Steps to reproduce

1. Open the SWAP screen.
2. select a token
3. When I try to move tabs, only "Serch name or pasteaddress" and "change" can be selected.

### Additional context

![kakou](https://github.com/taikoxyz/taiko-mono/assets/112812104/9fceeb51-b4d9-42d3-a739-9c35b8c36ac9)

**Comment by dantaik** [comment]
Bridge dapp v1 has been deprecated.
