### ISSUE TITLE
Phalcon Explorer - Powerful Transaction Explorer Designed For DeFi Community 

### ISSUE THREAD

**Issue by aleaxu** [taikoxyz/taiko-mono#14523]
### Title of your project

Phalcon Explorer

### Short (1-2 sentence) description of your project

Designed specifically for the DeFi community, Phalcon Explorer empowers developers, traders, and security researchers to delve deep into transactions. As of now, Phalcon Explorer boasts over 20,000 monthly active users, analyzing approximately 10,000 transactions daily across 160+ countries. Notably, 75% of our user base hails from major countries including the US, China, and the UK.

### Link to your project

https://explorer.phalcon.xyz/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

By now, Phalcon Explorer supports ETH, BSC, Arbitrum, OP, Polygon, Fantom, Avalanche

### Upload a quality logo to your project

![Phalcon logo](https://github.com/taikoxyz/taiko-mono/assets/19487594/a93bdcda-edc1-4c94-8b0c-123eb1222853)

**Comment by 2manslkh** [comment]
@aleaxu When can we expect Phalcon to be live on Taiko testnet? :)
