### ISSUE TITLE
feat(relayer): bridge relayer messaging queue

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#14528]
### Describe the feature request

Relayer should be split up into two subcommands, indexer and processor. Indexer indexes the chain and adds messages to a queue (rabbit, Kafka, etc). Processor reads from the queue.  
  
This will enable high fault tolerance and persistence, especially when the chain is backed up and blocks take a very long time to verify.

A refactor should accompany this to use the same urfave cli package as taiko-client, to make it easier to work across both projects, and similiar subcommand/config pattern.

**Comment by dantaik** [comment]
@cyberhorsey could you provide an ETA for this? I hope to launch alpha-5 ASAP.

**Comment by cyberhorsey** [comment]
@dantaik this is not something urgent, and can be deployed during alpha-5 if we choose to go down this path. Do not consider it a blocker.
