### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by Lannn45** [taikoxyz/taiko-mono#14538]
### Describe the bug

Description of the bug here.

When I bridge the Horse token from Grimsvotn L2 to Eldfell L3, the status should be claimed after clicking "Claim." However, I received a notification saying "Failed," even though the status shows as "claimed." Interestingly, the Horse token has been successfully deposited into my wallet.

![eror](https://github.com/taikoxyz/taiko-mono/assets/117993673/38a80af5-82c2-4a93-824a-302ad69ddee7)

![eror1](https://github.com/taikoxyz/taiko-mono/assets/117993673/e5ba15c3-5e1a-4cb8-81b9-4fc4f37fa247)

![Screenshot 2023-08-19 011238](https://github.com/taikoxyz/taiko-mono/assets/117993673/e18231dc-6aff-4ad6-a358-d9468c894c42)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Bridge dapp v1 has been deprecated
