### ISSUE TITLE
Bitget Wallet

### ISSUE THREAD

**Issue by Chickkkkkk** [taikoxyz/taiko-mono#14534]
### Title of your project

Bitget Wallet

### Short (1-2 sentence) description of your project

Faster Trading, Better Assets Bitget Wallet, Your Web3 Trading Wallet of the Future

### Link to your project

https://web3.bitget.com/

### Live on Testnet

Yes (default)

### Upload a quality logo to your project

![Bitget LOGO V1的副本](https://github.com/taikoxyz/taiko-mono/assets/80138302/59fb4ee6-d0e9-411f-a225-039db6682a52)

**Comment by MarcusWentz** [comment]
`If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).`
Info on this?

**Comment by Chickkkkkk** [comment]
Marcus Wentz ***@***.***>于2023年8月17日 周四23:58写道：

**Comment by Chickkkkkk** [comment]
> 

![Taiko Testnet](https://github.com/taikoxyz/taiko-mono/assets/80138302/2b195edc-d946-4b9c-b6e9-dceb3754ec6b)
