### ISSUE TITLE
liquidity error

### ISSUE THREAD

**Issue by daotunglam239099** [taikoxyz/taiko-mono#14542]
### Describe the bug

I have added liquidity for BLL and HORSE pairs, the wallet has confirmed the completion of the transaction but when I check the liquidity pool again, they don't appear.

### Steps to reproduce

Steps to reproduce here.

### Additional context
![1](https://github.com/taikoxyz/taiko-mono/assets/99623770/557b46a2-c041-4075-a98a-0aa8d24607dc)
![2](https://github.com/taikoxyz/taiko-mono/assets/99623770/3f866b32-4aa2-48ae-835b-7aba3ca23dad)

Additional context here.

**Comment by TTorricobr** [comment]
Hello, how are you? Were you able to resolve your issue? Generally, errors like these occur due to communication failures between the blocks or even connection errors. However, to precisely understand what happened, we need more information, such as the transaction ID.

I'm here to help, my friend!!!

**Comment by daotunglam239099** [comment]
Hello,
Here are my 2 transaction ids getting error about adding liquidity as
mentioned in github:
My 1st trade (August-19-2023 10:36:12 PM +7 UTC) is add 0.05 HORSE and
about 0.014 BLL with transaction ID:
"0x574c8ba41b20e4ce632fdccd44a5b838e241b1a6669cbd4c528b36454e3f56c6"
My second trade(August-19-2023 10:36:12 PM +7 UTC) is adding about 0.01
HORSE and about 0.003 BLL  with transaction ID:
"0xf95be683c0fc186374deb4d317770d1a117a9f04639cd5fa73b2d61a4d9ee7ac"
Thank you!.


Vào CN, 20 thg 8, 2023 vào lúc 09:20 TTorricobr ***@***.***>
đã viết:

**Comment by daotunglam239099** [comment]
> Hello, how are you? Were you able to resolve your issue? Generally, errors like these occur due to communication failures between the blocks or even connection errors. However, to precisely understand what happened, we need more information, such as the transaction ID.
> 
> I'm here to help, my friend!!!

Here are my 2 transaction ids getting error about adding liquidity as mentioned in github: 
My 1st trade (August-19-2023 10:36:12 PM +7 UTC) is add 0.05 HORSE and about 0.014 BLL with transaction ID: "0x574c8ba41b20e4ce632fdccd44a5b838e241b1a6669cbd4c528b36454e3f56c6"
My second trade(August-19-2023 10:36:12 PM +7 UTC) is adding about 0.01 HORSE and about 0.003 BLL  with transaction ID: "0xf95be683c0fc186374deb4d317770d1a117a9f04639cd5fa73b2d61a4d9ee7ac"

**Comment by dantaik** [comment]
Bridge dapp v1 has been deprecated.
