### ISSUE TITLE
No list of tokes

### ISSUE THREAD

**Issue by felipegargal** [taikoxyz/taiko-mono#14559]
### Describe the bug

When trying a swap, no tokens appears in the list, so you cannot make the swap

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by CryMin** [comment]
Select a token -> Choose a list -> Taiko Testnet Tokens -> Select and tokens will appear.

**Comment by y2ky2** [comment]
yes it take a little sec for token to appear but sometime it depend on wallet connection make sure you close other web3 site and use only one tab to swap it

hope it will help your issue
