### ISSUE TITLE
Fuzzing test plan for circuits

### ISSUE THREAD

**Issue by CeciliaZ030** [taikoxyz/taiko-mono#14556]
Creating fuzzer for each circuits as part of the testing infrastructure. @krzysztofpaliga

**Comment by dantaik** [comment]
@CeciliaZ030 does it make sense to move this issue to the zkevm repo?

**Comment by CeciliaZ030** [comment]
> @CeciliaZ030 does it make sense to move this issue to the zkevm repo?

Yea sorry I meant open this in zkevm repo, but choose the wrong one 😅
