### ISSUE TITLE
bridge from L3 to L2

### ISSUE THREAD

**Issue by AlpaniaRahman** [taikoxyz/taiko-mono#14555]
### Describe the bug

the bridge from L3 to L2 takes quite a long time (pending).
![Screenshot_20230822_193911](https://github.com/taikoxyz/taiko-mono/assets/136436791/0a04713d-9008-46c5-89c3-69ef54c0d1f7)

### Additional context

Additional context here.

**Comment by Vandayzm** [comment]
Same issue

**Comment by alexandermacedonian** [comment]
i have the same issue

**Comment by Sparspae** [comment]
I have the same issue

**Comment by dantaik** [comment]
This is indeed being worked on right now. Hopefully it will be ready for the next testnets.

**Comment by AlpaniaRahman** [comment]
Semoga tidak ada bug" yang parah
