### ISSUE TITLE
Eldfell(Taiko L3) token bug

### ISSUE THREAD

**Issue by Sparspae** [taikoxyz/taiko-mono#14568]
### Describe the bug

I was unable to add the Eldfell (Tiako L3) token automatically, I had to add it manually by inputting the contract address for each token.⬇️
![Screenshot_20230823-165838](https://github.com/taikoxyz/taiko-mono/assets/140791184/ca63e020-7152-4416-af9c-0993d950bf3d)

### Steps to reproduce

1.Go to Edlfell L3 swap 
2.Click on swap, it will display only Ethereum
3.Click on add token
4.Go to Taiko doc guild to copy the contract address for each token
5.Add manually
6.Then proceed to swap

### Additional context

Additional context here.

**Comment by dantaik** [comment]
This bridge dapp (v1) has been deprecated, lets see if the problem still exists on our new bridge app (the v2).

**Comment by Sparspae** [comment]
Okay done
