### ISSUE TITLE
Taiko wallet

### ISSUE THREAD

**Issue by maul37** [taikoxyz/taiko-mono#14566]
### Describe the feature request

does taiko not plan to make his own digital wallet ? 

### Describe alternatives you've considered

through an application or web browser extension.

### Additional context

Additional context here.

**Comment by jaeeswitch** [comment]
That's a nice suggestion, I very much support this. It will be good if Taiko has its own unique wallet.
This can increase the amount of users who find it difficult to engage with other protocols in the taiko ecosystem

**Comment by maul37** [comment]
Exactly

**Comment by dantaik** [comment]
We try to be lean and only work on something innovative or at least different. Repeating other teams' work won't help Taiko succeed.
