### ISSUE TITLE
Requesting Taiko testnet faucet within parent Taiko discord server

### ISSUE THREAD

**Issue by y2ky2** [taikoxyz/taiko-mono#14560]
### Describe the feature request

many good project in this space have a faucet feature in their dicord channel

i hope team will consider a faucet to use bridge to and from Taiko 

by placing faucet in taiko discord 

many ppl can easily get testnet token to use and contribute to Taiko

many builders also need certain amount of test token to build their project on Taiko 

so i am requesting faucet on our Taiko Discord channel❤️

As a newbie in this space i have no idea how to contribute for coding related issue on Taiko but i am trying to contribute to Taiko 
because i love using Taiko 💜

### Describe alternatives you've considered

Description of the alternatives you've considered here.

**Comment by d1onys1us** [comment]
we have considered this and will consider it in the future. we have to keep in mind the risks it has to network congestion.
