### ISSUE TITLE
Incorrect gas limit at L3 Staking Dashboard 

### ISSUE THREAD

**Issue by CryMin** [taikoxyz/taiko-mono#14569]
### Describe the bug

L3 Staking Dashboard estimates Gas limit for transactions incorrectly. When for example I tried to stake using Dashboard the Transaction had been generated with Gas limit: 214,269 and it was reverted (failed because out of gas):
[https://explorer.test.taiko.xyz/tx/0xb968ffe2e7ec70ad063b636de1035e765206f4d9375ab143947d9af7ca05b5f0](url) 

 When I tried to stake to staking contract directly (without Dashboard) a new Transaction had Gas limit: 321,403 and it was confirmed:
[https://explorer.test.taiko.xyz/tx/0x82bd77217376a93c9559918b09d636a1b139c276d4481ebab19c343b3cbebe51](url) 

![Transaction-0xb968ffe2e7ec70ad063b636de1035e765206f4d9375ab143947d9af7ca05b5f0-Alpha-3-L2-Explorer](https://github.com/taikoxyz/taiko-mono/assets/142942494/54b28e13-b033-46b1-a19f-94ff6c4b0f3f)
![Transaction-0x82bd77217376a93c9559918b09d636a1b139c276d4481ebab19c343b3cbebe51-Alpha-3-L2-Explorer](https://github.com/taikoxyz/taiko-mono/assets/142942494/355301eb-2406-4ce3-8a8e-2046c1ebc473)

The same situation is with Withdraw and Deposit functions.

It's possible to use Dashboard now, but for transaction, sent using it, to be confirmed, the Gas limit should be increased manually.

### Steps to reproduce

1. Visit L3 Staking Dashboard at [https://staking.l3test.taiko.xyz](url)
2. Connect Wallet
3. Go to Stake tab
4. Fill in Amount per Capacity, RewardPerGas, Capacity fields
5. Click Stake button
6. Click Confirm button in pop-up wallet extension 

### Additional context

Until the 21th of August, 2023 functions of Dashboard had worked fine, so the bug may be caused by some recent changes in its code or by blockchain's congestion, when more gas is needed for transaction to be Confirmed.

**Comment by dantaik** [comment]
The ProverPool contract has bee deprecated.
