### ISSUE TITLE
feat(deployment): uniswap v3 fork deployment

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#14562]
## Definition of done
1. Fork of Uniswap v3 is deployed on one of our testnets.
2. All Uniswap branding is removed and/or a notice is posted to make it clear that it is a fork (unofficial).  

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Done
