### ISSUE TITLE
feat(protocol): hybrid Optimistic-ZK Rollup

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#14574]
### Describe the feature request

In the existing design,  ZKPs (Zero-Knowledge Proof) will eventually prove every block. We might consider incorporating ideas from OP to only prove blocks requiring ZK proofs. Below is the concept.

For each block, the protocol accepts assertions provided by participants. An assertion is a tuple consisting of `<parentBlockHash, parentGasUsed, blockHash, gasUsed>`. To accept an assertion, a substantial deposit of tokens must be burned.

When a parent block is verified, the current block can be verified under specific conditions:
- If the parent block's `<blockHash, gasUsed>` aligns with exactly one assertion of the current block, and that matching assertion is at least x hours old, then the current block can be verified as long its parent is verified. The block hash and gas used are obtained from the matching assertion.
- If there are multiple matching assertions, a ZKP must be provided to prove which one of the matching assertions is correct, or if a new assertion is the right one.
- If no assertion aligns with the parent's selected assertion, it will be necessary to wait for new assertions or a ZKP.

For the assertion that verifies a block, the deposit is refunded, and new tokens are minted as a block reward.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by Brechtpd** [comment]
This is an optimistic rollup with a zk fraud proof, in this case the fraud proof is requiring someone to put valid block meta data on-chain and proving its validity. But by doing this you don't really get the main benefit of using zk, just some small benefit of potentially optimizing the fraud proving itself. Multi step fraud proofs do increase the acceptable finalization time so Optimism was also looking into using zk to make this a single step I believe, but in the end it's still an optimistic rollup with onchain finalization times very far removed from zk rollups.

**Comment by dantaik** [comment]
I agree (and I think we talked about this previously). Assume the ZK proof is very expensive which may be the case in the near term, if we have a way to allow a configurable percentage of blocks to be optimistic with zk fraud proof, and the rest to require ZK proofs. Then we can tune this percentage from a large number (so the block is initially more of an OpRollup) to a smaller number (so the block will eventually become a ZKRollup), and eventually 0.

**Comment by dantaik** [comment]
Over the weekend, I've considered this hybrid Optimistic + ZK Rollup idea. It's challenging to persuade people, but I still want to document it and propose it to the team.

## Recap of the current v5 testnet

In our latest codebase, here's how a block goes through the proposing, proving, and verification steps:

- The proposer, Alice, proposes a block with Bob assigned as the prover.
- The protocol verifies that Bob has authorized this *prover assignment* with a valid signature.
- Assuming Alice sends 0.01ETH, these funds are immediately transferred to Bob as a non-refundable proving fee.
- Bob also deposits 10,000 Taiko tokens as a *bond* in the same transaction.

Bob has a one-hour window to be the exclusive prover for this block. Once he submits a valid zk proof or the hour passes, the block becomes *open* for other provers. Bob's bond is returned if his fork choice finalizes the block; otherwise, he loses the bond.

## Be Optimistic

How can we incorporate an optimistic rollup with ZK as a fraud-proof mechanism? Here are my ideas:

- Alice proposes a block and still assigns Bob as the prover.
- Alice deposits 0.01ETH as the proving fee, and Bob also transfers 10,000 Taiko tokens as a bond.

Post-*proposeBlock* transaction, anyone can submit fork choices without ZK proofs. For example, let's say Cindy, Dave, and Fred submit the following fork choices:

1. Cindy: p1 → h1
2. Dave: p1 → h2
3. Fred: p2 → h3

A 4-hour challenge window is set if multiple fork choices mature after this period and share the same parent hash, a ZK proof from Bob is required.

### How are they rewarded?

1. If Cindy's fork choice is proven by Bob, then Dave and Fred lose their bond, and Bob and Cindy get their bonds back and share half of the bonds from Dave and Fred. Bob also gets the 0.01ETH proving fee.
2. If Cindy's choice is proven by someone else, Bob loses his bond, the actual prover gets other fees and rewards that would otherwise go to Bob.
3. If Fred's choice is correct and there's no conflict, Cindy and Dave lose their bond, Bob gets his bond back with 0.005 ETH as the standby fee, and Alice receives a 0.005 ETH refund. Bob and Fred share half of the bond from Cindy and Dave.

Only contradicting fork choices need a ZK proof, and incorrect submissions result in a loss of bonds.

## Put them together

We could use a random selection mechanism: 99% of blocks are optimistic, and 1% require proactive ZK proofs. This ensures a small, active pool of provers. Only 1% of blocks would incur proving fees, making the system more efficient.

**Comment by dantaik** [comment]
> I have some questions:
> 
> * Is this hybrid solution you propose because of proof costs or security (circuit coverage) ? If former, it might be fine (i have less clue about the costs associated with off-chain proof generation but it may result in community 'backlash' of the narrative, see below), but if latter isn't why we go for SGX as a backup/fallback ?

Proof of cost, especially if we adopt zkVM for future proving. It will be more expensive than a type-1 zkEVM approach. Also L3s may expect the proof cost per block to be even cheaper.

> * This model would introduce some heavy changes to the protocol, (fork choice proving/handling), resulting in additional complexities, for what cost ? If the whole network would benefit from it -> Woth it imo, if not, maybe not.

It will certainly make our implementation more complicated. Those benefits come with a price.

> * Does not it deviates significantly from our original plan / narrative of the "First Type-1 zkEVM" ? Again, if something which makes sense from technological point of view because of X or Y, it is ok but it is related to question 1. Are we optimizing for cost ? Even at the cost of giving up on the "first Type-1 zkEVM ? If this is because of security, i'd assume we are safe bc. of SGX.

Eventually we can change the config to make it 100% zk-Rollup, but such a hybrid idea may be a very good experiment for the first couple of years where zk proofs are still costly.

**Comment by Brechtpd** [comment]
I'm not sure I'd agree that zk rollups are more expensive than optimistic rollups because of the hidden costs for optimistic rollups like:
- Fewer data availability/compression options (no path to transition to state deltas for example)
- 7 day withdrawal delays add a lot of capital inefficiency to the system that will be indirectly paid by users
- Requires higher bonds/staking because now required for the security of the rollup 

The complexity of using a fraud proof approach also has far reaching consequences on how the protocol should work: https://medium.com/offchainlabs/bold-permissionless-validation-for-arbitrum-chains-9934eb5328cc

With zk getting easier by the day, and proof generation costs getting down fast, I don't really see fraud proofs sticking around much longer. I think optimistic rollups will be more complex and more expensive than zk rollups.

**Comment by dantaik** [comment]
Update: After discussion with Brecht, we've decided not to pursue this concept for the following reasons:

1. We believe zkRollups are the future, and even Optimistic Rollups are likely to adopt ZK technology.
2. The high costs associated with ZK proofs in the short to mid-term are expected to decrease rapidly. We're optimistic about this.
3. Our priority should be to concentrate on refining our core protocol design/implementation and narrowing our focus.

It's possible that other developers, such as those working on app-chains or layer 3s, may take this idea and change our core protocol code into a _**ZK-Optimistic Rollup protocol**_ (all blocks are optimistic but invalid state transactions are corrected by ZK validity proofs) or a _**Hybrid Rollup protocol**_ (with both optimistic blocks and ZK blocks). We're open to discussions and willing to assist.

**Comment by dantaik** [comment]
Update again: After another discussion with Brecht, we agree that we should try the hybrid rollup idea with some improvements.

The following diagram may be capture the [idea above](https://github.com/taikoxyz/taiko-mono/issues/14574#issuecomment-1694408754). 


<img width="809" alt="Screenshot 2023-09-07 at 10 11 57" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/8867cf15-f7c6-45dc-a073-ec9f0ea1a937">

If an *optimistic state transition assertion* or (optimistic transition) is challenged by a different transition of the same type, the protocol enforces the challenged transition to be proven by more trustworthy transition, in this case, one proven by a  PSE-zkEVM proof

But we can generalize the idea with even more types of different transitions. We can put them on a x-axil based on their trustworthness.

<img width="1018" alt="Screenshot 2023-09-07 at 10 11 35" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/6d743e85-0d3e-4ab3-810e-c089704391a4">


For each block, the protocol always accepts transition from the left end, and only elevate the transition type up to 1 level to the right once the transition is challenged.

**Comment by dantaik** [comment]
This is considered done in [this PR](https://github.com/taikoxyz/taiko-mono/pull/14705).
