### ISSUE TITLE
TIME TO FINALITY

### ISSUE THREAD

**Issue by paltechphones** [taikoxyz/taiko-mono#14576]
### Describe the bug

The time to finalize the bridging between Grimsvotn L2 - Eldfell L3 bridge need to be worked on for a faster and easier bridging

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
This is indeed being worked on right now. Hopefully it will be ready for the next testnets.
