### ISSUE TITLE
Taiko Alpha-1 Testnet

### ISSUE THREAD

**Issue by alexandermacedonian** [taikoxyz/taiko-mono#14575]
### Describe the bug

Taiko Alpha-1 Testnet is not working for me and when I enter the link I get 404 error

### Steps to reproduce

Steps to reproduce here.

### Additional context

can anyone help?

**Comment by CryMin** [comment]
Taiko Alpha-1 Testnet was finished some months ago. Now Alpha-3 (Grimsvotn L2) and Alpha-4 (Eldfell L3) testnets are available for testing.
