### ISSUE TITLE
feat(node): notify Node Operators about updates

### ISSUE THREAD

**Issue by Bajankenrom** [taikoxyz/taiko-mono#14579]
### Describe the feature request

Whenever a node operator is view this logs for his L2\L3 via the following command:

Grimsvotn L2:

`docker compose logs -f
`
Eldfell L3:

`docker compose -f ./docker-compose.l3.yml --env-file .env.l3 logs -f
`

There should be a text broadcasting a message saying the following:

There is a new update out `version:  x.x.x` Please update your node.

### Describe alternatives you've considered

Make a dedicated ANN channel in discord for node updates etc...

### Additional context

Additional context here.

**Comment by dantaik** [comment]
I like it, but I'm not sure if it is absolutely needed.

**Comment by Bajankenrom** [comment]
> I like it, but I'm not sure if it is absolutely needed.

ok np....just thought about after finding out a new update came out and myslef and others werent aware of it..

**Comment by DaDy75** [comment]
test

**Comment by AlpaniaRahman** [comment]
Nice

**Comment by wolfderechter** [comment]
I don't think it's the best idea to put it in the logs, but a discord channel with a bot could be a good idea. Note there already exists a few tools to know about latest docker images ([watchtower](https://github.com/containrrr/watchtower), [diun](https://github.com/crazy-max/diun), [dockcheck](https://github.com/mag37/dockcheck)...)

**Comment by Bajankenrom** [comment]
> I don't think it's the best idea to put it in the logs, but a discord channel with a bot could be a good idea. Note there already exists a few tools to know about latest docker images ([watchtower](https://github.com/containrrr/watchtower), [diun](https://github.com/crazy-max/diun), [dockcheck](https://github.com/mag37/dockcheck)...)

hence why i said a discord ANN channel or in the logs every couple of seconds which is the norm for other blockchain nodes.

**Comment by d1onys1us** [comment]
> > I don't think it's the best idea to put it in the logs, but a discord channel with a bot could be a good idea. Note there already exists a few tools to know about latest docker images ([watchtower](https://github.com/containrrr/watchtower), [diun](https://github.com/crazy-max/diun), [dockcheck](https://github.com/mag37/dockcheck)...)
> 
> hence why i said a discord ANN channel or in the logs every couple of seconds which is the norm for other blockchain nodes.

yeah i also like this idea. i feel like it would be best if we had both, but i don't know the scope of the change on the client side. if it's too difficult, the discord bot seems fairly straightforward to do as a first step.

**Comment by Cryptoastt** [comment]
The idea is good, but it's not the need of an hour

**Comment by szymcio32** [comment]
I created a discord bot that gives the information about the latest docker images. Here's an example of the output:

![image](https://github.com/taikoxyz/taiko-mono/assets/32844693/4a1223b8-937b-40e9-bb88-b2e34cdde353)

Let me know what you think about it. Is it something that'd be useful?

**Comment by szymcio32** [comment]
@dantaik the above output is from my test environment. The bot still needs to be deployed and configured with Taiko discord by the admin of the discord server.
