### ISSUE TITLE
Faucet Error

### ISSUE THREAD

**Issue by kutjhing** [taikoxyz/taiko-mono#14585]
### Describe the bug

i can't get the faucet token 
![IMG_9716](https://github.com/taikoxyz/taiko-mono/assets/139467347/85db2783-281a-4797-a3c1-276febe8fc30)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
select a token from the dropdown.
