### ISSUE TITLE
Rubic

### ISSUE THREAD

**Issue by IlyaStor** [taikoxyz/taiko-mono#14584]
### Title of your project

Rubic 

### Short (1-2 sentence) description of your project

Rubic enhances interoperability through network bridging and cross-chain dev tools for omnichain dApps. Users access diverse assets via varied DEXs under a unified interface with optimized cross-chain transactions.

### Link to your project

https://rubic.exchange/

### Live on Testnet

No

### Upload a quality logo to your project

![11](https://github.com/taikoxyz/taiko-mono/assets/102148545/91da9f3d-f0e8-4361-9f72-b596705804e0)

**Comment by Koljash** [comment]
Vero
