### ISSUE TITLE
Coinscope. Coinlisting platform that offers a majority of tools and supports many chains

### ISSUE THREAD

**Issue by AndreasCyberscope** [taikoxyz/taiko-mono#14599]
### Title of your project

Coinscope

### Short (1-2 sentence) description of your project

Coinscope is a comprehensive platform for early coin listings, interactive voting, and crypto insights.

### Link to your project

https://www.coinscope.co/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

no It's a multichain dapp 

### Upload a quality logo to your project

![Coinscope Logo (512 × 512 px)](https://github.com/taikoxyz/taiko-mono/assets/143086760/a29be9aa-dfa1-42d5-a28d-6fc5fe79e65d)

**Comment by 2manslkh** [comment]
@AndreasCyberscope if there is no integration with Taiko at all, the project will not be included in the ecosystem.
