### ISSUE TITLE
Add Alphamint to Taiko's ecosystem

### ISSUE THREAD

**Issue by Visiok09** [taikoxyz/taiko-mono#14629]
### Title of your project

Alphamint

### Short (1-2 sentence) description of your project

Multichain NFT marketplace to create, sell and buy ERC-721 tokens.

### Link to your project

https://www.alphamint.online/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://test.taikoscan.io/address/0x2E18e4385aDAb5A8a63B5930114DF57252f5366f

### Upload a quality logo to your project

![android-chrome-512x512](https://github.com/taikoxyz/taiko-mono/assets/94221061/33917570-50ce-4a28-9bdf-6db701a68b32)

**Comment by MarcusWentz** [comment]
I see the outdated Taiko testnet is supported.

Please migrate to Taiko Jolnir testnet next.

**Comment by Visiok09** [comment]
Updated, thanks for accepting!
