### ISSUE TITLE
Request MoveChess to the Taiko Explorer

### ISSUE THREAD

**Issue by movechess-labor** [taikoxyz/taiko-mono#14656]
### Title of your project

MoveChess - Brilliant Moves on Taiko

### Short (1-2 sentence) description of your project

MoveChess is a chess project currently under development by the MoveLabs team. Its primary goal is to provide a platform for chess enthusiasts within the Taiko community and offer various activities related to NFT rewards on the MoveChess platform.

### Link to your project

https://movechess.com

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

MoveChess is currently deploying its landing page and developing the smart contract. We will provide any necessary evidence for the team and users very soon

### Upload a quality logo to your project

![Group 174](https://github.com/taikoxyz/taiko-mono/assets/143335690/542ee1ee-809e-4e8b-ba89-1c019f4ba09d)

**Comment by 2manslkh** [comment]
Hey @movechess-labor,

When can we expect the app to be deployed?

**Comment by movechess-labor** [comment]
From MoveChess, 

our primary focus is on developing our game engine. In addition to that, we have completed our landing page, which is currently in the staging phase. We plan to deploy the landing page next week.

**Comment by movechess-labor** [comment]
> Hey @movechess-labor,
> 
> When can we expect the app to be deployed?


From MoveChess,

our primary focus is on developing our game engine. In addition to that, we have completed our landing page, which is currently in the staging phase. We plan to deploy the landing page next week.
