### ISSUE TITLE
Adding Sendtokens to Taiko Ecosystem

### ISSUE THREAD

**Issue by defiboyszn** [taikoxyz/taiko-mono#14664]
### Title of your project

Sendtokens

### Short (1-2 sentence) description of your project

Sendtokens is a self custody wallet with super powers

### Link to your project

https://sendtokens.xyz

### Live on Testnet

No

### Upload a quality logo to your project

![Sendtokens512x512](https://github.com/taikoxyz/taiko-mono/assets/61181645/a39b6392-b7d7-4b5d-860c-b807f9c878a0)

**Comment by Tobithedev** [comment]
@d1onys1us  we support it already but the wallet isn't live for public usage yet

**Comment by Tobithedev** [comment]
Hi @d1onys1us, any updates about the listing

**Comment by MarcusWentz** [comment]
@Tobithedev when will the wallet be live for public usage?

**Comment by MarcusWentz** [comment]
@Tobithedev sounds good. Let us know when it goes live. Thank you.

**Comment by defiboyszn** [comment]
Hi our beta is live, we'd love to integrate Taiko
