### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by yanbili666** [taikoxyz/taiko-mono#14694]
### Describe the feature request

How can i support making a Spanish translation of the documentation to make it more approachable for LATAM people

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
thank you for your comment. at the moment we don't support multiple language dropdowns for our documentation, but keep an eye out because it's something we are considering supporting in the future.
