### ISSUE TITLE
rest api on jolnir explorer 

### ISSUE THREAD

**Issue by Ghonghito** [taikoxyz/taiko-mono#14760]
### Describe the feature request

Please add rest api on jolnir explorer 

![1](https://github.com/taikoxyz/taiko-mono/assets/73051326/efa56f43-9be2-42f7-94a7-5a239ab05653)

**Comment by adnockamran** [comment]
Great project

**Comment by Ghonghito** [comment]
> Great project

good projectors

**Comment by DRISS75-LAB** [comment]
Great project
