### ISSUE TITLE
Going to bridge fiat and more users to Taiko ecosystem

### ISSUE THREAD

**Issue by kurokiiangie** [taikoxyz/taiko-mono#14774]
### Title of your project

Alchemy Pay

### Short (1-2 sentence) description of your project

Alchemy Pay is bridging the fiat to cryptocurrency all around the world 

### Link to your project

https://alchemypay.org/

### Live on Testnet

No

**Comment by kurokiiangie** [comment]
![Uploading alchemy-pay-logo.png…]()

**Comment by d1onys1us** [comment]
closing as won't do because there is no integration or plans for integration. please feel free to re-open if there is a plan to integrate, thanks!
