### ISSUE TITLE
Different balance displayed on Swap

### ISSUE THREAD

**Issue by Lannn45** [taikoxyz/taiko-mono#14796]
### Describe the feature request

![issue](https://github.com/taikoxyz/taiko-mono/assets/117993673/9ba1bfb9-082b-49db-a82b-8e537f11d74e)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
wont fix as we updated to uniswap v3
