### ISSUE TITLE
Add AIT Protocol to Taiko's ecosystem

### ISSUE THREAD

**Issue by AITProtocol** [taikoxyz/taiko-mono#14794]
### Title of your project

AIT Protocol

### Short (1-2 sentence) description of your project

AIT Protocol is the first’s Web3 data infrastructure focusing on AI data annotations, leverages blockchain technology to deliver a trustless and cross-border labor market being strategically incentivized by crypto economics and having instant cross-nation payment settlements.

### Link to your project

https://ait.tech/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

https://explorer.jolnir.taiko.xyz/address/0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5

### Upload a quality logo to your project

https://drive.google.com/file/d/1qWzB_BO6b7t3_KGcKWl2ORDqMocu2bjO/view

**Comment by fahimMuhamma** [comment]
Good going

**Comment by MarcusWentz** [comment]
On 

https://testnet.ait.tech/

I don't see Taiko listed

![ait](https://github.com/taikoxyz/taiko-mono/assets/52706599/8e82a366-d9b0-4295-9780-16bdfc1e0388)

Also the contract at 

https://explorer.jolnir.taiko.xyz/address/0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5

is not verified. GitHub link to the deployed contract? Are you able to verify the contract on the explorer?

**Comment by AITProtocol** [comment]
Hi. This is the internal testnet for OG user on discord. We limited to 200 users only. There is a new public testnet coming out in October that will open the omnichain feature, supporting 5 chains: BNB, OKTC, Zksync, BASE, Taiko and Tomochain.

**Comment by AITProtocol** [comment]
Hi. We have successfully verified the contract.
https://explorer.jolnir.taiko.xyz/address/0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5?tab=contract

**Comment by MarcusWentz** [comment]
Let us know when the public testnet comes out in October.

**Comment by MarcusWentz** [comment]
> Hi. This is the internal testnet for OG user on discord. We limited to 200 users only. There is a new public testnet coming out in October that will open the omnichain feature, supporting 5 chains: BNB, OKTC, Zksync, BASE, Taiko and Tomochain.

Let us know when the public testnet comes out in October.



> Hi. We have successfully verified the contract. https://explorer.jolnir.taiko.xyz/address/0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5?tab=contract

Thank you.

**Comment by AITProtocol** [comment]
Sure. We will be inviting our partners to co-host a panel on Twitter Space. For the announcement on Taiko's discord, is there anything else needed? 

We have announced on our end: https://x.com/AITProtocol/status/1706543806114578446?s=20

**Comment by AITProtocol** [comment]
Sure. We will be inviting our partners to co-host a panel on Twitter Space. For the announcement on Taiko's discord, is there anything else needed? 

We have announced on our end: https://x.com/AITProtocol/status/1706543806114578446?s=20

**Comment by AITProtocol** [comment]
Hi, can you approve us to list on https://taiko.xyz/ecosystem? https://taiko.xyz/ecosystem Ben ***@***.***) from the Taiko team is waiting for that to draft the announcement. Thank you.

**Comment by 2manslkh** [comment]
Can you verify these contracts as well and integrate them with your frontend?

AIT Token: 0x802e73F54D092D2F3f237bC5Dba74fFF7cF89BE5
Pool Reward: 0x469828686D8F24ba71093c0696a0C1f58034F439
AITONFT: 0xd686194da724b82E33fCD30152a7A6201dA2aBF9
Claim: 0x3233003f9B241e1CD0f8A922BdF69A1160643EAf

It would be best if there were actual successful integration before announcing anything so as to not confuse the users.
