### ISSUE TITLE
Please add spheron network, web3 infra solution

### ISSUE THREAD

**Issue by hipiyushhere** [taikoxyz/taiko-mono#14808]
### Title of your project

Spheron Network

### Short (1-2 sentence) description of your project

Deploy, manage & scale your applications using Web3 Infrastructure

### Link to your project

https://spheron.network/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots).

Its chain agnotic solution

### Upload a quality logo to your project

![Spheron_icon_512x512](https://github.com/taikoxyz/taiko-mono/assets/70137264/7c395a09-686f-435e-8e99-c141b8fa1f8c)

**Comment by 2manslkh** [comment]
Project has no integration with Taiko. Closing.
