### ISSUE TITLE
X7 Finance

### ISSUE THREAD

**Issue by mohit-321** [taikoxyz/taiko-mono#14832]
### Title of your project

Xchange

### Short (1-2 sentence) description of your project

Launch your project on Xchange with 10-1000x the initial liquidity into the Ethereum ecosystem where anyone can Swap, Borrow and Lend!

### Link to your project

https://x7.finance/

### Live on Testnet

No

### Upload a quality logo to your project

![brunHCql_400x400](https://github.com/taikoxyz/taiko-mono/assets/128371531/95fb0d6b-22f8-4902-8190-2b0b394ad130)

**Comment by d1onys1us** [comment]
@mohit-321 if there are no plans to integrate Taiko, then we will have to close this issue. please update that section of the submission, thanks

**Comment by 2manslkh** [comment]
Closing as stale
