### ISSUE TITLE
Prover market registration page enhancement 

### ISSUE THREAD

**Issue by cyberpunk9932** [taikoxyz/taiko-mono#14837]
### Describe the feature request

The thing is that at the moment [Prover market registration page](https://taiko.xyz/docs/reference/prover-market-page) has a static representation, and current proposers may not be confident in the uninterrupted work of a certain API endpoint. 

For example in my observation this one "Web3Cript 1 | http://taiko.web3cript.xyz:9876" works only several hours at night (UTC+5)

Current list:
![image](https://github.com/taikoxyz/taiko-mono/assets/70695776/ee066e81-92c8-4629-ad5f-3f0a4131f7a3)

### Describe alternatives you've considered

I propose to make the same list but on Github, so that each user can make suggestions for editing this sheet or so that provers have the opportunity to indicate in what time periods they work.

Proposed list:
![photo_2023-09-27_14-38-03](https://github.com/taikoxyz/taiko-mono/assets/70695776/23b8a62b-aed5-4bfb-b641-da37dceb9317)

This way, proposers will know the latest information about Prover market.

And I would also like to note the need to correct the guide for running a proposer, since it is not noted there that it is necessary to change the PROVER_ENDPOINTS if you do not run the prover yourself.

**Comment by 2manslkh** [comment]
I think it would be difficult to maintain a fresh update for working hours for each prover endpoint

Noted on the PROVER_ENDPOINTS

**Comment by Jonesjr1** [comment]
Yes it would be difficult

**Comment by dantaik** [comment]
In future releases, this list should only include endpoints from trusted and verified parties. Any ad-hoc endpoints should be promoted on our Discourse forum instead.
