### ISSUE TITLE
Make proposer rewards distribution more fair

### ISSUE THREAD

**Issue by adaki2004** [taikoxyz/taiko-mono#14881]
### Describe the feature request

Currently the first proposer within an L1 block gets the TKO compensation which does lead (at least on testnet definitely) to 'gas war' situations which fuels by speculation that TKO might worth something on mainnet. 
On the other hand the design is what it makes it doable, so maybe best to change it for example like:

1. Accumulate the "rewards" by every seconds (kind of same as now, but not reset to 0 at all.)
2. Give 1/3 of the accumulated rewards to each every proposers

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Given the discussion with Brecht yesterday, lets postpone this improvement.

**Comment by adaki2004** [comment]
> Given the discussion with Brecht yesterday, lets postpone this improvement.

I understand it may be out of interest for now, but was already half cooked, so i just leave it as is. We can close that PR then.
https://github.com/taikoxyz/taiko-mono/pull/14888

**Comment by dantaik** [comment]
Fixed
