### ISSUE TITLE
Taiko Early Creator Access

### ISSUE THREAD

**Issue by GeneralChaos999** [taikoxyz/taiko-mono#14890]
### Describe the bug

Cant seem to find my minted nft on mintpad after creating nft. Theres no transaction history to search on for thats why if you click on mint button it always says youre not allowed to mint.

### Steps to reproduce

At least make a transaction history bar or history page.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
This should be raised on the mintpad discord or via their email [support@mintpad.co](mailto:support@mintpad.co).
