### ISSUE TITLE
Adding some testnet link for bridging on the website will be useful

### ISSUE THREAD

**Issue by entrepreneurlibre** [taikoxyz/taiko-mono#14891]
### Describe the feature request

A more user-friendly interface will be welcome and some testnet link for bridging will be useful

**Comment by Crypto-Chucky** [comment]
I agree

**Comment by 2manslkh** [comment]
Hi @entrepreneurlibre, could you provide more details on how to improve the [current user interface](https://bridge.jolnir.taiko.xyz/)?

**Comment by entrepreneurlibre** [comment]
Since you are in testnet, it would be better to add a testnet menu which will redirect users to the link for the distribution of eth sopolia in testnet. This keeps users on the page and it makes the interface less difficult to understand. You will see a menu like this:


**Bridge**

**Faucet**

**Transactions**

**Explore**

**Get testnet tokens** (new)

Guide


This remains exhaustive but the idea is to have everything in one without going to do research elsewhere

**Comment by TiMeDoctorDre** [comment]
Good
