### ISSUE TITLE
Bash script node installer

### ISSUE THREAD

**Issue by tudorpintea999** [taikoxyz/taiko-mono#14918]
### Describe the feature request

a bash script that contains all the commands from the tutorial

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by tudorpintea999** [comment]
Hello, i made this pr for the issue, https://github.com/taikoxyz/simple-taiko-node/pull/141

**Comment by tudorpintea999** [comment]
Hello again, currently i m working on the script to install the utils as git, docker if they are not installed, choose between prover and proposer (or both) the make the required changes in .env file. Note that the pr above works for the moment only for prover. I will submit a new pr once the full script is working as expected.

**Comment by tudorpintea999** [comment]
new pr , the node installation (plus docker, git and the utils) is now fully automated, the users can choose to instal a Prover, Proposer or both https://github.com/taikoxyz/simple-taiko-node/pull/142

**Comment by d1onys1us** [comment]
left a small comment on the PR @tudorpintea999 , thanks!

**Comment by 2manslkh** [comment]
@tudorpintea999 bump

**Comment by tudorpintea999** [comment]
@2manslkh check my last comment on the pr

**Comment by tudorpintea999** [comment]
hello @d1onys1us is my script used somewhere? thanks
