### ISSUE TITLE
feat: Private ETH/token transfers

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/taiko-mono#14917]
### Describe the feature request

We can allow private ETH/token transfers using the mechanism described here: https://eips.ethereum.org/EIPS/eip-7503

Unlike on L1, we don't need any changes to the protocol/EVM itself, because we can already mint ETH/tokens on L2. So the only change necessary for us to support this is to also allow the smart contract that verifies the ZKP that implements the burn checking to mint new ETH. Basically this is just a special ETH bridging contract.

It should be able to do this withing a single L2 but also across L2s that share the same L1 bridge contract.

### Describe alternatives you've considered

Other mixers have some more downsides than the method above.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Interesting idea. However, to implement this idea without a new built-in Ether minting opcode, the L2 EtherVault must grant permission to a dedicated contract that verifies ZKPs then transfer Ether out of EtherVault to users. Granting such permission is done by us which makes us a target like the Tonado cash team.

Also, I didn't totally get it: the EIP claim "zero smart-contract interactions", but there will at least be a smart contarct to verify ZKPs, no?

**Comment by Brechtpd** [comment]
> Interesting idea. However, to implement this idea without a new built-in Ether minting opcode, the L2 EtherVault must grant permission to a dedicated contract that verifies ZKPs then transfer Ether out of EtherVault to users. Granting such permission is done by us which makes us a target like the Tonado cash team.

Doesn't have to be us, any Taiko L2 can choose to add it to the whitelisted addresses for ETH. So this could even be a standalone L2 just for this that people could bridge too. And each token smart contract would be able to decide this on their own.

> Also, I didn't totally get it: the EIP claim "zero smart-contract interactions", but there will at least be a smart contarct to verify ZKPs, no?

Yeah in our case the minting would require a smart contract. Still, the burning step does not require any smart contract interaction, so the sender address cannot be banned for interacting with any blacklisted smart contract. The minting is always something special (even in the EIP) so it cannot be hidden that that ETH was mixed.

**Comment by keyvank** [comment]
Wondering if you guys are still considering this? :)
