### ISSUE TITLE
AICOO - A Decentralized AI co-create Platfrom

### ISSUE THREAD

**Issue by mydoto** [taikoxyz/taiko-mono#14920]
### Title of your project

AICOO

### Short (1-2 sentence) description of your project

AICOO is a decentralized AI co-create platfrom. Anyone can initial a new collection and set conditions for who can paticipate. All participants co-created used AI tool and share the royalty of the collection. 

### Link to your project

https://www.aicoo.xyz/

### Live on Testnet

Yes

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

<img width="1409" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/30818067/d1e2e6dd-bc8e-4ad8-9fb1-cbbfada43154">
### Upload a quality logo to your project

![aicoo](https://github.com/taikoxyz/taiko-mono/assets/30818067/b65f0d5e-625a-4a6b-9d26-c692051b4d60)

![logo-black](https://www.aicoo.xyz/_next/static/media/logo.db461150.svg)

**Comment by 2manslkh** [comment]
Hi @mydoto, what are the integration plans for Taiko? e.g. the integration timeline and how it will be integrated.

**Comment by mydoto** [comment]
@2manslkh We will complete the operation of existing functions on Taiko network in 2 weeks.

**Comment by 2manslkh** [comment]
@mydoto any updates?

**Comment by mydoto** [comment]
@2manslkh Yes, AICOO has been updated and now supports Taiko on the Jolnir testnet.  You can have a try. For stable access, we deployed the graph of Taiko ourselves.
And, Please add our project on the Ecosystem page.
