### ISSUE TITLE
XEX 

### ISSUE THREAD

**Issue by babyface001** [taikoxyz/taiko-mono#14931]
### Title of your project

XEX

### Short (1-2 sentence) description of your project

Xex is an orderbook DEX on Taiko, enabling Users creating tradepair witout permission,and adding liquidity is not needed.

### Link to your project

https://taiko.xex.fi/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://twitter.com/xextrade/status/1711641617449521227/photo/1

### Upload a quality logo to your project

![logoX_副本](https://github.com/taikoxyz/taiko-mono/assets/34022395/563d2830-6293-47f6-be8f-b95f8de779c6)

**Comment by 2manslkh** [comment]
<img width="1406" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/23635326/8e1e442b-4355-4761-a7a6-bab430c329fd">

Impossible to test as we do not have any of the tokens.

also, lots of spelling errors

**Comment by 2manslkh** [comment]
Closing as stale
