### ISSUE TITLE
Algebra

### ISSUE THREAD

**Issue by Adamsuto** [taikoxyz/taiko-mono#14939]
### Title of your project

Algebra

### Short (1-2 sentence) description of your project

Empowering DEXes with Concentrated Liquidity (V3 and V4)

### Link to your project

https://algebra.finance/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

AlgebraPoolDeployer to: 0x59a662Ed724F19AD019307126CbEBdcF4b57d6B1  AlgebraFactory deployed to: 0x805488DaA81c1b9e7C5cE3f1DCeA28F21448EC6A  PluginFactory to: 0x95E325A85B9E6cB4DeA2ccd96218e5F8365E0B0F  TickLens deployed to: 0xd265f57c36AC60d3F7931eC5c7396966F0C246A7  Quoter deployed to: 0xFe3BEcd788320465ab649015F34F7771220A88b2  SwapRouter deployed to: 0x8C97D1566eD686249b6E818E664aCe873ccfE442  NonfungibleTokenPositionDescriptor deployed to: 0x0BFaCE9a5c9F884a4f09fadB83b69e81EA41424B  NonfungiblePositionManager deployed to: 0x13fcE0acbe6Fb11641ab753212550574CaD31415  AlgebraInterfaceMulticall deployed to: 0xa77aD9f635a3FB3bCCC5E6d1A87cB269746Aba17  AlgebraEternalFarming deployed to: 0x50FCbF85d23aF7C91f94842FeCd83d16665d27bA  FarmingCenter deployed to: 0x658E287E9C820484f5808f687dC4863B552de37D

### Upload a quality logo to your project

![Logo](https://github.com/taikoxyz/taiko-mono/assets/114906692/0759889f-701b-428e-a722-4249bbff4426)

**Comment by 2manslkh** [comment]
Where is the frontend for using the swap? Or how do we integrate with the protocol?
