### ISSUE TITLE
Get infra ready for users to claim airdropped tokens/NFTs

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#14985]
### Describe the feature request

We should set up infrastructure for users to claim tokens after genesis. This requires effort in frontend, backend, and smart contracts.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by adaki2004** [comment]
Part of it as token airdrop: https://github.com/taikoxyz/taiko-mono/issues/15026
