### ISSUE TITLE
Some dapps on https://taiko.xyz/ecosystem do not currently support Taiko test network, that is,  taiko network is not displayed as an option among the other networks they support.

### ISSUE THREAD

**Issue by Onoseanna** [taikoxyz/taiko-mono#14988]
### Describe the bug

Description of the bug here.

Some dapps on the taiko ecosystem website do not support Taiko test network. They neither show old versions of the network or the latest version of the network.

On  https://taiko.xyz/ecosystem these dapps are currently displayed as live on testnet but upon accessing the dapps, taiko test network was not found in some-----

### Steps to reproduce

Steps to reproduce here.

A solution would be a review on the dapps which are currently displayed on https://taiko.xyz/ecosystem.

Those dapps where taiko test network was not found can be labeled as
'' coming soon '' just like other dapps which are currently labeled as coming soon on the website. This would really help the community to understand which and what dapp to interact with.

### Additional context

Additional context here.

**Comment by Onoseanna** [comment]
@d1onys1us  I don't know if this can be worked on. What do you think?

**Comment by d1onys1us** [comment]
> @d1onys1us I don't know if this can be worked on. What do you think?

we should work on it, will take a look. thank you for pointing it out!

**Comment by 2manslkh** [comment]
Do you think you can do a review of the apps and add a A3 or A5 tag on each of the projects depending on the latest testnet they are on? @Onoseanna

**Comment by Onoseanna** [comment]
Ok I can. We work on it @2manslkh

**Comment by Onoseanna** [comment]
Previously when I submitted this bug, some of the dapps which were yet to integrate the current testnet network has integrated Taiko Jolnir testnet network.. this is is highly appreciated.

Few dapps which are yet to update to the current testnet version of the network are listed below with tags;

A3 represents taiko alpha-3 testnet.

A4 represents taiko alpha-4 testnet network

A0 means taiko test network not found.

1. Rai finance.........A3
  https://app.rai.finance/

2. Morkie................A4
https://www.morkie.xyz/

3. Kalki Swap.........A3
https://kalkiswap.org/

4. Pheasant network.....A0 https://pheasant.network/

5. Zero Swap.......A0 https://testdrive.zeroswap.io/
@2manslkh I did an update.

**Comment by d1onys1us** [comment]
thank you for your investgation @Onoseanna i did check pheasant network and zero swap and i see they are integrated with taiko jolnir. we are going to do an overhaul on our ecosystem page as well so we'll double check these again.

**Comment by Onoseanna** [comment]
Thank you @d1onys1us for checking it out. Recently more daaps are getting integrated. I don't know if it ok to request for a poap since the issue is now closed.
@d1onys1us is it ok for me to request for a contribution poap?
