### ISSUE TITLE
Add Hotpot to the ecosystem page

### ISSUE THREAD

**Issue by gabrielantonyxaviour** [taikoxyz/taiko-mono#15012]
### Title of your project

Hotpot

### Short (1-2 sentence) description of your project

Hotpot Protocol offers a toolkit for creating gamified Dapps, enabling builders to engage users with provably fair jackpots, airdrop raffle tickets, and build decentralized prediction markets on EVMs.

### Link to your project

https://github.com/Hotpot-protocol1

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://github.com/Hotpot-protocol1/hotpot-multichain-contracts#taiko-jolnir-testnet

### Upload a quality logo to your project

Live project website => [here](https://www.hotpot.gg/)

![hotpot](https://github.com/taikoxyz/taiko-mono/assets/79229998/b86f944f-fc3e-4722-b5aa-d108c1618a24)

**Comment by 2manslkh** [comment]
Please integrate the smart contracts with a frontend interface and state the integration plan/timeline. Thank you!
