### ISSUE TITLE
rhino.fi

### ISSUE THREAD

**Issue by Euclid-rhinofi** [taikoxyz/taiko-mono#15015]
### Title of your project

rhino.fi

### Short (1-2 sentence) description of your project

The lightning-fast secure bridge for seamless cross-chain transactions

### Link to your project

https://app.rhino.fi/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://explorer.jolnir.taiko.xyz/address/0xCAfA5b8B85FCc8d195d43E2B6f5F83245f5349D7

**Comment by 2manslkh** [comment]
Closing. Duplicate #15016. This one doesn't contain the logo
