### ISSUE TITLE
rhino.fi

### ISSUE THREAD

**Issue by Euclid-rhinofi** [taikoxyz/taiko-mono#15016]
### Title of your project

rhino.fi

### Short (1-2 sentence) description of your project

The lightning-fast secure bridge for seamless cross-chain transactions

### Link to your project

https://app.rhino.fi/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://explorer.jolnir.taiko.xyz/address/0xCAfA5b8B85FCc8d195d43E2B6f5F83245f5349D7

### Upload a quality logo to your project

![rhino fi-Primary-Logo (2)](https://github.com/taikoxyz/taiko-mono/assets/148785349/2eb6e49e-60c8-414a-b276-32a285bf5755)

**Comment by 2manslkh** [comment]
@Euclid-rhinofi  Could you provide a square logo? Thanks!

**Comment by Euclid-rhinofi** [comment]
![rhino fi-DVF-Token](https://github.com/taikoxyz/taiko-mono/assets/148785349/9bee4a0e-51f9-40fa-9ed9-c1e537659644)
