### ISSUE TITLE
Node Fails to Start After Updating to New Version - Suggestion for "Run a Taiko node" Guide

### ISSUE THREAD

**Issue by Lenn-e** [taikoxyz/taiko-mono#15014]
### Describe the feature request

After updating my Node to the new version, I encountered the following error:

`ERROR Dial ethclient error                     url=ws://l2_execution_engine:8546 error="dial tcp: lookup l2_execution_engine: i/o timeout"
`

I couldn't find any information related to this error in the troubleshooting guide. I also checked the Discord community and noticed that many others faced the same issue without a solution.

Suggested Solution:
After trying various solutions from the node troubleshooting guide and digging for somewhat related issues in discord, I found that running the following command resolved the issue:

`docker compose down -v
`

This command cleans up the old node, allowing the new one to run without errors. I suggest adding this as a hint to the "Run a Node" guide to help others who might encounter the same issue since it seems like it's encountered fairly often. In fact, by digging through discord I found a screenshot of this exact hint which I assume was present in an older version of the node running guide but got removed for some reason.

![image](https://github.com/taikoxyz/taiko-mono/assets/59662454/0fcbc6ea-55a2-42bb-b91c-b25bb24dc232)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by RogerLamTd** [comment]
@gitpoap-bot please give @Lenn-e a poap

**Comment by d1onys1us** [comment]
@gitpoap-bot please reward @Lenn-e
