### ISSUE TITLE
Add custom chain icons in walletconnect v3 once supported

### ISSUE THREAD

**Issue by KorbinianK** [taikoxyz/taiko-mono#15033]
### Describe the feature request

Update WC once custom chain icons are supported again. See https://github.com/taikoxyz/taiko-mono/pull/14999#issuecomment-1776588799

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
any update on this @KorbinianK ?

**Comment by KorbinianK** [comment]
> any update on this @KorbinianK ?

Looking into it as we speak. Draft PR (https://github.com/taikoxyz/taiko-mono/pull/15453) up, will continue tomorrow. Seems stable now and support everything we need.
