### ISSUE TITLE
Redundant Code in generateBridgeConfig and Unused Variable Declaration

### ISSUE THREAD

**Issue by ptchela** [taikoxyz/taiko-mono#15136]
I've noticed a couple of potential issues in the code that may require attention:

1. Redundant Code Execution: In the generateBridgeConfig function, the sourceFile.saveSync(); method is called twice consecutively. This may be unintentional and could lead to unnecessary operations or potential errors.
    Location: file name: packages/bridge-ui-v2/scripts/vite-plugins/generateBridgeConfig.ts
                   line numbers 62 and 65

2. Unused Variable Declaration: The variable configuredBridgesConfigFile is declared but then its value is immediately reassigned without any conditions. The initial declaration might be redundant and can be removed to clean up the code.
Location: file name: packages/bridge-ui-v2/scripts/vite-plugins/generateBridgeConfig.ts
                line number 28

Recommendation: Review the mentioned sections of the code to determine if these are genuine issues and take necessary corrective actions.

**Comment by KorbinianK** [comment]
Thanks for the feedback. As for 1. absolutely an oversight, not a critical one though as the plugin is only called once during the build.

2. I suppose you can just initialise the variable instead of just declaring it. 

Feel free to submit a PR to address these changes if you want!

**Comment by ptchela** [comment]
> Thanks for the feedback. As for 1. absolutely an oversight, not a critical one though as the plugin is only called once during the build.
> 
> 2. I suppose you can just initialise the variable instead of just declaring it.
> 
> Feel free to submit a PR to address these changes if you want!

Dear KorbinianK,

I hope this message finds you well. I am writing to express my interest in contributing to the [taikoxyz/taiko-mono] repository, specifically regarding the recent changes you mentioned where you said, "Feel free to submit a PR to address these changes if you want!"

I have prepared updates that I believe will add value to the project. However, I have encountered a hurdle with push permissions and currently do not have the access required to push my commits and create a pull request.

Could you please grant me push access or guide me on the proper procedure to get my contributions reviewed and possibly merged? I am eager to contribute and look forward to the possibility of collaborating on the project.

Thank you for considering my request. I am looking forward to your favorable response.

Warm regards,

Ptchela

**Comment by Cryptodelhi** [comment]
bridge

**Comment by ptchela** [comment]
> Thanks for the feedback. As for 1. absolutely an oversight, not a critical one though as the plugin is only called once during the build.
> 
> 2. I suppose you can just initialise the variable instead of just declaring it.
> 
> Feel free to submit a PR to address these changes if you want!

https://github.com/taikoxyz/taiko-mono/pull/15152
