### ISSUE TITLE
Documentation Command for Contract Verification Fails on Execution

### ISSUE THREAD

**Issue by paulallensuxs** [taikoxyz/taiko-mono#15133]
### Describe the bug

**Bug Description:**

The `forge create` command provided in the Foundry tab of the contract verification documentation triggers an error when executed. The error message suggests that the command syntax does not include all the required arguments, specifically the `<CONTRACT>` argument, which is crucial for the command to run successfully.

**Expected Result:**

The command provided in the documentation should be complete and correctly formatted, allowing users to execute it without modification to verify their contracts.

**Actual Result:**

Upon running the command, the user encounters the following error:

```
error: the following required arguments were not provided:
  <CONTRACT>

Usage: forge create --rpc-url <URL> --private-key <RAW_PRIVATE_KEY> --verify --verifier <VERIFIER> --verifier-url <VERIFIER_URL> <CONTRACT>

For more information, try '--help'.
```

This error indicates that the `<CONTRACT>` argument is missing from the command.

### Steps to reproduce

1. Visit the contract verification documentation page at `https://taiko.xyz/docs/guides/verify-a-contract`.
2. Navigate to the Foundry tab within the guide.
3. Copy the `forge create` command as provided in the documentation.
4. Run the command in a terminal.
5. Observe the resulting error which states that the `<CONTRACT>` argument was not provided.

### Additional context

This issue occurs on the Foundry tab of the contract verification guide and can lead to confusion and frustration among users attempting to verify their contracts.

**Comment by samui68400** [comment]
After testing the deployment of a contract via Foundry, I encounter an error when attempting to verify it following the guide. The error "ETHERSCAN_API_KEY must be set" persists even after correctly setting the Etherscan API key. I find that the guide lacks clarity and appears to require correction.

**Comment by samui68400** [comment]
I will further investigate the issue and offer to improve the guide if necessary.

**Comment by Chowart** [comment]
> ### Describe the bug
> **Bug Description:**
> 
> The `forge create` command provided in the Foundry tab of the contract verification documentation triggers an error when executed. The error message suggests that the command syntax does not include all the required arguments, specifically the `<CONTRACT>` argument, which is crucial for the command to run successfully.
> 
> **Expected Result:**
> 
> The command provided in the documentation should be complete and correctly formatted, allowing users to execute it without modification to verify their contracts.
> 
> **Actual Result:**
> 
> Upon running the command, the user encounters the following error:
> 
> ```
> error: the following required arguments were not provided:
>   <CONTRACT>
> 
> Usage: forge create --rpc-url <URL> --private-key <RAW_PRIVATE_KEY> --verify --verifier <VERIFIER> --verifier-url <VERIFIER_URL> <CONTRACT>
> 
> For more information, try '--help'.
> ```
> 
> This error indicates that the `<CONTRACT>` argument is missing from the command.
> 
> ### Steps to reproduce
> 1. Visit the contract verification documentation page at `https://taiko.xyz/docs/guides/verify-a-contract`.
> 2. Navigate to the Foundry tab within the guide.
> 3. Copy the `forge create` command as provided in the documentation.
> 4. Run the command in a terminal.
> 5. Observe the resulting error which states that the `<CONTRACT>` argument was not provided.
> 
> ### Additional context
> This issue occurs on the Foundry tab of the contract verification guide and can lead to confusion and frustration among users attempting to verify their contracts.

For example. contract file is MyContract.sol and the contract within it is named MyContract, the argument should be MyContract.sol:MyContract

**Comment by samui68400** [comment]
**I conducted various tests for a deployed contract, and here are the encountered errors:**

When using the command:

forge create --rpc-url https://rpc.jolnir.taiko.xyz --private-key XXXX src/Contract.sol:SimpleStorage --verify --verifier etherscan --verifier-url https://api.routescan.io/v2/network/testnet/evm/167007/etherscan

**I received the error: 'ETHERSCAN_API_KEY must be set.**

When using the command:

forge verify-contract 0xa52CA91A059ae854dC0856EA0D91b3C991EFa026 src/Contract.sol:SimpleStorage
Start verifying contract `0xa52CA91A059ae854dC0856EA0D91b3C991EFa026` deployed on mainnet

**I received the error: Etherscan could not detect the deployment.**

**Additionally, I tried by adding the smart contract's address:**

forge create --rpc-url https://rpc.jolnir.taiko.xyz --private-key XXXX --verify --verifier etherscan --verifier-url https://api.routescan.io/v2/network/testnet/evm/167007/etherscan 0xa52CA91A059ae854dC0856EA0D91b3C991EFa026

**This resulted in another error: 'Could not find artifact: 0xa52CA91A059ae854dC0856EA0D91b3C991EFa026**

**Comment by Chowart** [comment]
For the third command, if you're trying to verify an already deployed contract, the correct format should be something like:

`forge verify-contract --rpc-url https://rpc.jolnir.taiko.xyz --private-key XXXX --verifier etherscan --verifier-url https://api.routescan.io/v2/network/testnet/evm/167007/etherscan <ContractAddress> src/Contract.sol:SimpleStorage <ConstructorArguments>`

**Comment by samui68400** [comment]
Still not working for me.

**Comment by Ayomidemm** [comment]
Nice project

**Comment by Chaouchmehdi** [comment]
I cant join any roles

**Comment by yakinbisagroup** [comment]
need more friendly interface

**Comment by realenriko** [comment]
I also experience same try this
sudo -i
cd /bin/
rm forge
exit

**Comment by Gwaram455** [comment]
If contract verification is still not going, try switching from mobile phone to pc. I most cases, mobile phone devices tend to be erratic on deploying/ verifying contracts.

**Comment by Ash-code183** [comment]
need a detailed gyuide to sort this out

**Comment by Cryptmenic** [comment]
Has the issue been resolved? If not, I will do further investigation on it.

**Comment by johnDogen** [comment]
can't get it to work either

**Comment by odavidjeff** [comment]
I think the bridge interface can be simplified

**Comment by brentnab** [comment]
I also experience same try this
sudo -i
cd /bin/
rm forge
exit

**Comment by Ash-code183** [comment]
same tried the steps didnt work for me either

**Comment by iman136938** [comment]
keep up the good work
