### ISSUE TITLE
TPX_Perpetual_Dex

### ISSUE THREAD

**Issue by 0xkf** [taikoxyz/taiko-mono#15197]
### Title of your project

Taiko

### Short (1-2 sentence) description of your project

Perpetual Dex on Taiko

### Link to your project

https://tpx.fi/ 

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://github.com/tpxfi　

### Upload a quality logo to your project

[https://drive.google.com/file/d/1fcve7cxB4Thwxg0r71ypfDAtH19229A7/view?usp=sharing ](url)

**Comment by 2manslkh** [comment]
Will there be an actual product in the future?
