### ISSUE TITLE
Add InfStones Testnet Validator Node to ecosystem

### ISSUE THREAD

**Issue by adam-infstones** [taikoxyz/taiko-mono#15299]
### Title of your project

InfStones Testnet Validator Node

### Short (1-2 sentence) description of your project

InfStones has set up a secure Taiko testnet validator node. InfStones will support the Taiko community with infrastructure support. 

### Link to your project

https://infstones.com/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

0x4d4ea757E40825cf2307cd5a7175d0Af5059DB42

### Upload a quality logo to your project

[InfStones Logo-png.zip](https://github.com/taikoxyz/taiko-mono/files/13517183/InfStones.Logo-png.zip)

**Comment by 2manslkh** [comment]
Is this a public RPC? If it is, please provide the http/https rpc url

**Comment by davidtaikocha** [comment]
Closed due to inactive.
