### ISSUE TITLE
Add Chainsight to Taiko ecosystem page

### ISSUE THREAD

**Issue by xpriment626** [taikoxyz/taiko-mono#15319]
### Title of your project

Chainsight

### Short (1-2 sentence) description of your project

Modular oracles to enable dynamic DeFi across all EVM ecosystems.

### Link to your project

https://chainsight.network/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Here was the initial announcement with Taiko - https://x.com/Chainsight_/status/1725532058469212307?s=20 We will be transitioning to mainnet once our developer tooling (Chainsight CLI) reaches a stable v1.0.0 release. In the meantime, we will be working closely with the early Taiko DeFi ecosystem to design and test use cases.

### Upload a quality logo to your project

![Chainsight_Twitter_Icon](https://github.com/taikoxyz/taiko-mono/assets/92909049/a1ce92d0-e173-4ebe-9ec0-cdab94d94c41)

**Comment by 2manslkh** [comment]
https://beta.chainsight.network/explore/components/hug27-byaaa-aaaao-a2puq-cai

Not sure what the integration is here

@xpriment626

**Comment by 2manslkh** [comment]
What are the expected relay values? @xpriment626

**Comment by xpriment626** [comment]
> What are the expected relay values? @xpriment626

Chainsight is an Oracle Development Kit that lets developers extend oracles on the Chainsight network, 3rd party oracles, or create their own custom oracles. We piloted a deployment of volatility oracle on testnet. Our next steps for going to market is to collaborate with DeFi projects building on Taiko, for which I am already in contact with Ken and Jonathan from the ecosystem and grants team respectively.

**Comment by Cordeiro71** [comment]
Chainsight is a good project,  its a great idea!

**Comment by Craziefire** [comment]
I Will love to know how this chainsight project of ours will benefit the ecosystem of Taiko. @xpriment626

**Comment by xpriment626** [comment]
Chainsight is a modular oracle network focused primarily on enabling developers to create their own custom oracles for complex or exotic data not commonly available in existing oracle solutions like Chainlink and Pyth. The data feed I like to highlight when talking about Chainsight is Chainsight 20, an index feed that returns the value of the top 20 crypto assets and automatically rebalances itself. Here's an explainer article I wrote on it: https://medium.com/@Chainsight_Network/chainsight-20-crypto-index-now-live-106773283a25

In practice, this means developers can do the following such as (but not limited to):
- Swapping out the rebalance and weighting methodology
- Swapping out the assets entirely and tracking an index of their assets of choice
- Use Chainsight 20 oracle to create dynamic index products that are aware of market conditions and adjust accordingly in near-real-time
- Combine with additional data sources like Chainlink for redundancy

If you're keen to get more into the weeds of things, do feel free to reach out to me on telegram at: @e_childsplay and we can set up a discovery call or just talk more in-depth async.

cc: @Craziefire @2manslkh
