### ISSUE TITLE
Address may display domain name if acquired by user

### ISSUE THREAD

**Issue by amazon4479** [taikoxyz/taiko-mono#15356]
### Describe the feature request

If the user already bought a domain name it can be displayed at the wallet area instead of address if the user already bought a domain nane

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by namorh0215** [comment]
ok

**Comment by KorbinianK** [comment]
We may look into this once we upgrade to the new walletconnect v3. Right now this is not planned
