### ISSUE TITLE
Taiko liquidity pool bug

### ISSUE THREAD

**Issue by Iceyrim** [taikoxyz/taiko-mono#15366]
### Describe the bug

I had some troubles adding to the liquidity pool. I bridged some eth and horse from sepolia to Jolnir testnet which i tried pairing up for the pool but I experienced some difficulties. It failed many times before it was added successfully. I believe this shouldn’t be the case and should be looked into. Also the pool types are not clear and will be a challenge to new lpers- i suggest that the partitioning be made clear; so that those that wants to add a pair in equal ratio can easily do that while those who intend to add is different ratios (one pair more than the other) can too. For now it isn’t clear. Would be cool if a detail icon that explains some tags in the pool uI is added. All in essence to improve user experience.
Thanks and I appreciate the good work.

### Steps to reproduce

Steps to reproduce here.

### Additional context

1. Make pair addition to the pool to be more smooth and without unexpected failures
2. Add a detail icon which shows an explanation for the fee tiers and price ranging as this will improve user experience and knowledge as a whole while helping lpers efficiently manage fees and earnings.

**Comment by namorh0215** [comment]
added the [category.bug](https://github.com/taikoxyz/taiko-mono/labels/category.bug)
