### ISSUE TITLE
Taiko swap

### ISSUE THREAD

**Issue by Afurehub** [taikoxyz/taiko-mono#15364]
### Describe the bug

Description of the bug here.
There is apparently a problem adding liquidity pool on the taiko swap. Only eth is recognized. No token is recognized, hence all contract address imported to be paired with wth becomes invalid

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by jotajotabcn** [comment]
great job

**Comment by SakiAoiaoi** [comment]
It was so simple !

**Comment by bora41** [comment]
good

**Comment by namorh0215** [comment]
good job
