### ISSUE TITLE
FASTER TRADES BETWEEN JOLNIR AND SEPOLIA

### ISSUE THREAD

**Issue by MouseDoFluxo** [taikoxyz/taiko-mono#15379]
### Describe the feature request

Description of the feature request here.
I am starting to use this testnet but the amunt of delays to do simple transfers are killing me, could anyone tell if its just here or its global?

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.
I live in Brazil, dont know if it may be a problem or not. All the other test nets that i use to work with dont show up this issue,

**Comment by cyberhorsey** [comment]
jolnir to sepolia bridge requires all of the headers to sync between L1 and L2 in order to bridge the funds, there will be delays using this bridging methodology. in the future on mainnet there will be likely be yyhird party bridges that just use liquidity pools on both sides to bridge quicker.

**Comment by MouseDoFluxo** [comment]
great bro, thank you!
