### ISSUE TITLE
Adding Cookbook.dev to Taiko's ecosystem page

### ISSUE THREAD

**Issue by MikeDank** [taikoxyz/taiko-mono#15384]
### Title of your project

cookbook.dev

### Short (1-2 sentence) description of your project

Cookbook is an open-source smart contract registry where developers can find solidity primitives, libraries, and smart contracts for protocols across EVM-compatible blockchains that rely on the solidity programming language. 

### Link to your project

https://www.cookbook.dev/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://www.cookbook.dev/chains/Taiko

### Upload a quality logo to your project

<img width="256" alt="Logo - Updated - Black - 512x512" src="https://github.com/taikoxyz/taiko-mono/assets/55340820/3f4adca6-178b-4da0-bd92-f9e786fd77dc">

**Comment by Hinhsuconan** [comment]
Great

**Comment by ameeetgaikwad** [comment]
would like to help!

**Comment by d1onys1us** [comment]
added here: https://github.com/taikoxyz/website/pull/45/files

thanks!
