### ISSUE TITLE
ADDITION OF NEW TESTNET NETWORK

### ISSUE THREAD

**Issue by carrotdorcas** [taikoxyz/taiko-mono#15383]
### Describe the feature request

While testing out the Taiko bridge, I observed that cross-swap was possible on ONLY two networks;
Sepolia and Jolnir

I suggest the integration of Goerli network to the testnet. This will encourage new testers as there are alternative test networks.

### Describe alternatives you've considered

Addition of Goerli test network.

### Additional context

Additional context here.
![image](https://github.com/taikoxyz/taiko-mono/assets/78138128/0cbafc55-2299-49f4-80f3-f6ff05923c0c)

**Comment by cyberhorsey** [comment]
thanks for feedback, we will not be deploying the bridge code to additional Layer 1s for our test networks.
