### ISSUE TITLE
Hello, what do you think about translate documentation?

### ISSUE THREAD

**Issue by monleru** [taikoxyz/taiko-mono#15391]
### Describe the feature request

Hello, what do you think about translate documentation for another lanugages?

I can help you with it.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by Hinhsuconan** [comment]
Great sir. it's helpful

**Comment by Waiki96** [comment]
I propose Indonesian

**Comment by Hinhsuconan** [comment]
Great

**Comment by d1onys1us** [comment]
i think it's a good idea, we are evaluating some ways to do this now. i opened an issue in our website repo: https://github.com/taikoxyz/website/issues/44
