### ISSUE TITLE
Enhancement to Taiko Documentation

### ISSUE THREAD

**Issue by matthieukokabi** [taikoxyz/taiko-mono#15397]
### Describe the bug

Dear Taiko Maintainers,

I have been using Taiko for a while now and I’ve noticed that some sections of the documentation could benefit from further clarification to help new users. Specifically, the section on integrating with CI/CD pipelines. I've drafted a detailed guide that includes common configurations, troubleshooting tips, and examples from popular CI/CD platforms.

I believe this addition will be valuable to the community and I would love to contribute this to the Taiko documentation. Please find attached the markdown file with the proposed changes. I’m open to feedback and willing to collaborate further to refine this contribution.

Thank you for considering my input. Looking forward to the opportunity to contribute to such a remarkable project.

Best regards,

### Steps to reproduce

Dear Taiko Maintainers,

I have been using Taiko for a while now and I’ve noticed that some sections of the documentation could benefit from further clarification to help new users. Specifically, the section on integrating with CI/CD pipelines. I've drafted a detailed guide that includes common configurations, troubleshooting tips, and examples from popular CI/CD platforms.

I believe this addition will be valuable to the community and I would love to contribute this to the Taiko documentation. Please find attached the markdown file with the proposed changes. I’m open to feedback and willing to collaborate further to refine this contribution.

Thank you for considering my input. Looking forward to the opportunity to contribute to such a remarkable project.

Best regards,

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
There is no attached markdown. Have a look at our [Contributing Guidelines](https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md) for more information on how to contribute. Please understand that we can only accept PRs matching those criteria with a valid PR.

Feel free to attach a PR to this issue, where you provide your updates and suggestions. We will then review it.

**Comment by d1onys1us** [comment]
closing for now, but i do believe we should add developer docs (outside of the "user docs" which is on our website). if you have any suggestion, please feel free to open a PR with your suggestions. thanks.
