### ISSUE TITLE
Categorize dapps on the ecosystem page and filtering

### ISSUE THREAD

**Issue by mathiaszip** [taikoxyz/taiko-mono#15406]
### Describe the feature request

It appears that the ecosystem page on https://taiko.xyz/ecosystem showcases an extensive list of dapps, which is undoubtedly helpful for newcomers. However, to enhance user convenience and clarity, introducing a more organized categorization system could significantly improve the browsing experience. 

Presently, a visual aid in the form of a green box indicating "Live on testnet" is visible in the image. Implementing a color-coordinated system, perhaps with distinct boxes representing various dapp categories such as DEX, Liquid Staking, NFTs, and more, could provide users with immediate insights into each dapp's nature.
![018dc62cdcfc6c25933e0c89245eba86](https://github.com/taikoxyz/taiko-mono/assets/73193562/d91e1896-e84c-4abc-8811-13e6ede3c817)

Moreover, incorporating a user-friendly filtering mechanism at the top of the page would further streamline navigation. This feature would empower users to effortlessly sort through the listed dapps based on their preferred categories or types, enhancing their ability to find and explore specific dapps of interest.
![e090ecb53cdb27a81ace8cfab799784f](https://github.com/taikoxyz/taiko-mono/assets/73193562/9f35e2e2-82bb-41b0-a643-48ed0bab971d)

By integrating these improvements, the ecosystem page could transform into an intuitive hub, offering users a clearer understanding of each dapp's category while enabling efficient navigation through the diverse offerings available on the platform.

### Describe alternatives you've considered

Understanding the type of dapp available holds significant importance for users. While filtering might be of lesser priority, it ultimately rests on the developer's discretion, which I believe holds merit. Their perspective could provide valuable insights into optimizing the user experience. 🌟

**Comment by d1onys1us** [comment]
added this to our new website repo, closing as duplicate: https://github.com/taikoxyz/website/issues/43
