### ISSUE TITLE
Filtering projects on the ecosystem tab

### ISSUE THREAD

**Issue by Afonya081** [taikoxyz/taiko-mono#15409]
### Describe the feature request

To make it easier to understand the relationship to a certain category of projects added to the ecosystem, you can set filters to select categories. For example, DeFi, NFTs, LaunchPad, etc. You can also add links to the project itself, but to the preliminary page where there will be links to the application itself, social networks and the description of the project itself naturally. Sincerely.

**Comment by d1onys1us** [comment]
we are working on this, thanks.
