### ISSUE TITLE
Requesting more testnet bridge integration

### ISSUE THREAD

**Issue by mikeminer** [taikoxyz/taiko-mono#15411]
### Describe the feature request

on https://bridge.jolnir.taiko.xyz/ it is possible to bridge between Jolnir and Sepholia . For more adoption of the testnet i'm requesting to add also the possibility to bridge with Holesky , Ephemery and Goerli  testnets

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
i believe we are integrating with holesky on our next testnet but not 100% sure. but yes, jolnir is based on sepolia, you can bridge from sepolia into taiko jolnir.
