### ISSUE TITLE
Connection refused and server misbehaving

### ISSUE THREAD

**Issue by KallistaG** [taikoxyz/taiko-mono#15415]
### Describe the bug

There's an issue regarding of server misbehaving when I used docker to check logs
![image](https://github.com/taikoxyz/taiko-mono/assets/134775581/aedecc52-2fe3-4d71-93b3-990dac8f1d60)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
Plz ask here: https://github.com/taikoxyz/simple-taiko-node/issues
