### ISSUE TITLE
View your verified contract on Taikoscan link is not working

### ISSUE THREAD

**Issue by Elyaseeen** [taikoxyz/taiko-mono#15420]
### Describe the bug

I found an issue with the Taiko Block Explorer link https://taikoscan.network/ around Hardhat Contract verification guide and it should be updated or add a working link.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by davidtaikocha** [comment]
Plz use: https://explorer.jolnir.taiko.xyz/
