### ISSUE TITLE
feat(bridge): Clarification and Implementation for TODO in `ETHBridge.ts` regarding Dual Bridging

### ISSUE THREAD

**Issue by joaolago1113** [taikoxyz/taiko-mono#15427]
### Describe the feature request

While reviewing the code in `ETHBridge.ts` within the bridge contracts, I came across a `TODO` comment in the `_prepareTransaction` method of the `ETHBridge` class. The comment indicates a planned feature that would allow the contract to support bridging to both the sender's own address and a different recipient's address simultaneously:

```javascript
    // TODO: contract actually supports bridging to ourselves as well as
    //       to another address at the same time
```

Currently, when using a custom recipient different from the sender's address, the value is incorrectly set to zero. This led me to create a pull request (#15426) to address this issue. However, I am particularly interested in understanding the progress and plans regarding the implementation of the feature mentioned in the `TODO`.

Considering the potential impact and usefulness of this feature, I have also been exploring ways to extend the current contract to fully realize this functionality. Below is a conceptual proposal:

In LibBridgeSend.sol:
```solidity

    error B_INCORRECT_VALUE();
    error B_USER_IS_NULL();
    error B_WRONG_CHAIN_ID();
    error B_WRONG_TO_ADDRESS();
    error B_VALUES_CANNOT_BE_ZERO();

    /// @notice Sends a message to the Bridge with the details of the request.
    /// @dev This function takes custody of the specified funds, sending them to
    /// the EtherVault on Taiko or storing them on the Bridge for processing on
    /// the destination chain.
    /// @param state The current state of the Bridge.
    /// @param resolver The address resolver.
    /// @param message The message to be sent, including value and fee details.
    /// @return msgHash The hash of the sent message.
    function sendMessage(
        LibBridgeData.State storage state,
        AddressResolver resolver,
        IBridge.Message memory message
    )
        internal
        returns (bytes32 msgHash)
    {
        // Ensure the message user is not null.
        if (message.user == address(0)) {
            revert B_USER_IS_NULL();
        }

        // Check if the destination chain is enabled.
        (bool destChainEnabled, address destBridge) =
            isDestChainEnabled(resolver, message.destChainId);

        // Verify destination chain and to address.
        if (!destChainEnabled || message.destChainId == block.chainid) {
            revert B_WRONG_CHAIN_ID();
        }
        if (message.to == address(0) || message.to == destBridge) {
            revert B_WRONG_TO_ADDRESS();
        }
        
        // Ensure the sent value matches the expected amount.
        uint256 expectedAmount = message.value + message.recipientValue + message.fee;
        if (expectedAmount != msg.value) {
            revert B_INCORRECT_VALUE();
        }
        
        // Ensure that message.value and message.recipientValue are non-zero
        if (message.value == 0 && message.recipientValue == 0) {
           revert B_VALUES_CANNOT_BE_ZERO();
        }

        // On Taiko, send the expectedAmount to the EtherVault; otherwise, store
        // it on the Bridge.
        address ethVault = resolver.resolve("ether_vault", true);
        ethVault.sendEther(expectedAmount);

		
	    // Configure message details and send signal to indicate message
	    // sending.
	    message.id = state.nextMessageId++;
	    message.from = msg.sender;
	    message.srcChainId = block.chainid;
	    
	    address signalServiceAddress = resolver.resolve("signal_service", false);
 
        // If there is an amount to be sent to the recipient (message.recipientValue is greater than zero),
        // then handle the sending of the message to the recipient separately.
        if(message.recipientValue > 0){
        
	        state.nextMessageId++;

		    message.value = message.recipientValue;
		    
		    msgHash = _handleMessageSending(state, message, signalServiceAddress);
		    
		    message.to = msg.sender;
		    message.value = expectedAmount - message.recipientValue - message.fee;
		    
		    message.id++;
	    }
	    
	    // Handle the message sending for the remaining amount (either the total amount or the sender's portion).
        // This will be executed regardless of whether recipientValue is greater than zero.
	    msgHash = _handleMessageSending(state, message, signalServiceAddress);
    }


    /// @notice Handles the sending of a bridge message and emits an event.
    /// @param state The bridge state storage.
    /// @param message The message structure containing the details of the message to be sent.
    /// @param signalServiceAddress The address of the signal service.
    /// @return msgHash The hash of the message sent.
    /// @dev This function generates a message hash, sends a signal using the signal service, and emits a `MessageSent` event.
    function _handleMessageSending(
        LibBridgeData.State storage state,
        IBridge.Message memory message,
        address signalServiceAddress
    ) internal returns (bytes32) {

        bytes32 msgHash = message.hashMessage();
        ISignalService(signalServiceAddress).sendSignal(msgHash);
        emit LibBridgeData.MessageSent(msgHash, message);

        return msgHash;
    }
```

I would like to understand if this feature is still on track for development and how it aligns with the project's roadmap.
Thank you for your time and attention to this matter.

**Comment by giantfolarin** [comment]
Based on your proposal in LibBridgeSend.sol, it looks like you are attempting to enhance the functionality to support bridging to both the sender's own address and a different recipient's address simultaneously. The proposed changes involve checking if message.recipientValue is greater than zero, and if so, handling the sending of the message to the recipient separately.

It's important to consider potential edge cases, security implications, and thoroughly test the changes to ensure the integrity and security of the bridge contract.

As for alternatives, you might want to explore other ways to achieve the desired functionality, perhaps through a different design pattern or by leveraging existing features within the contract.

**Comment by joaolago1113** [comment]
> Based on your proposal in LibBridgeSend.sol, it looks like you are attempting to enhance the functionality to support bridging to both the sender's own address and a different recipient's address simultaneously. The proposed changes involve checking if message.recipientValue is greater than zero, and if so, handling the sending of the message to the recipient separately.
> 
> It's important to consider potential edge cases, security implications, and thoroughly test the changes to ensure the integrity and security of the bridge contract.
> 
> As for alternatives, you might want to explore other ways to achieve the desired functionality, perhaps through a different design pattern or by leveraging existing features within the contract.

Hello, are you part of the team? This reads like AI. 😂

**Comment by giantfolarin** [comment]
> > Based on your proposal in LibBridgeSend.sol, it looks like you are attempting to enhance the functionality to support bridging to both the sender's own address and a different recipient's address simultaneously. The proposed changes involve checking if message.recipientValue is greater than zero, and if so, handling the sending of the message to the recipient separately.
> > It's important to consider potential edge cases, security implications, and thoroughly test the changes to ensure the integrity and security of the bridge contract.
> > As for alternatives, you might want to explore other ways to achieve the desired functionality, perhaps through a different design pattern or by leveraging existing features within the contract.
> 
> Hello, are you part of the team? This reads like AI. 😂

lol! just suggesting what I think anyways

**Comment by KorbinianK** [comment]
@joaolago1113 I added the protocol team, they might be better at giving you insights to this feature. Fro

@giantfolarin I highly suggest to not add generic AI generated comments again. Feel free to add your own thoughts if they are of value.

**Comment by adaki2004** [comment]
@joaolago1113 Based on the fact that we do not have `EtherVault` your pseudo is a bit outdated.
Nonetheless thank you for your contribution. Feel free to adjust and work on that further, but please keep in mind the followings:
Please target this branch (https://github.com/taikoxyz/taiko-mono/pull/15316) with your code, because that is the one which is targeting (with small fixes) the branch which is locked for an ongoing audit.
Our rule of thumb now to not introduce any more (feature) changes into the protocol, which will also involve changes in the UI, hence it will delay our delviery (and affect out audit too), but in case it is a tiny modification, we can consider it, for sure.

**Comment by joaolago1113** [comment]
@adaki2004 I would love to test the alpha-6 branch. Could I get the new contract addresses for the bridge and others for it? Thanks a lot for your help on this!

**Comment by adaki2004** [comment]
> @adaki2004 I would love to test the alpha-6 branch. Could I get the new contract addresses for the bridge and others for it? Thanks a lot for your help on this!

Please observe the official channels for announcements! 
No public testnet is ongoing as A6 (yet). Expected soon - first half of Jan.
