### ISSUE TITLE
feat(protocol): Introduce Multi-Verifier for zk Proofs using SGX 🚀

### ISSUE THREAD

**Issue by RahulSinghRajput1** [taikoxyz/taiko-mono#15439]
### Describe the feature request

Describe the feature request.

Currently, zk proofs are verified using a smart contract. If there is a bug in the verifier smart contract, the zk proof is compromised, even if the zk proof itself remains intact.

To enhance security, we propose implementing a multi-verifier system. While multiple verification smart contracts can achieve this goal, an intriguing approach involves verifying the zk proof using SGX (Software Guard Extensions). This allows cost-effective verification of zk proofs since on-chain verification is typically expensive. The use of SGX enables leveraging the existing, audited zk proof verification code, minimizing any additional impact on the total cost.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context can be provided here.

**Comment by adaki2004** [comment]
Already existing issue: https://github.com/taikoxyz/taiko-mono/issues/15365
