### ISSUE TITLE
Strengthen golangci-lint check

### ISSUE THREAD

**Issue by mask-pp** [taikoxyz/taiko-mono#15487]
### Describe the feature request

Add more golangci-lint check rules, [reference link](https://golangci-lint.run/usage/configuration/).
such as: golint, misspell, govet, misspell, unparam

**Comment by Craziefire** [comment]
Okay will try to do that... still getting around GitHub not really an expert

**Comment by cyberhorsey** [comment]
> Okay will try to do that... still getting around GitHub not really an expert

I think it's better a team member handle this, as the linter change will require many code changes across all Golang packages.
