### ISSUE TITLE
feat(relayer): Separate HTTP API into its own subcommand

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#15497]
### Describe the feature request

 currently indexer sub ommand starts http server, this should be separated

**Comment by sttreaks** [comment]
Hi, I started working on this. :)

**Comment by cyberhorsey** [comment]
it has already been completed! sorry, this was assigned to me and should be marked as done.

**Comment by sttreaks** [comment]
> it has already been completed! sorry, this was assigned to me and should be marked as done.

Can you propose any other / related tickets to work on ?
