### ISSUE TITLE
bug(bridge-ui-v2):  katla - fonts black on mobile

### ISSUE THREAD

**Issue by hills4eva** [taikoxyz/taiko-mono#15505]
### Describe the bug

When using the bridge in mobile wallets the font color is black making the words unreadable 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
Hi, thanks for the report. Pleae provide more information such as device, OS version, wallet etc. So it is easier to reproduce.

**Comment by KorbinianK** [comment]
stale
