### ISSUE TITLE
Scan functionality issue

### ISSUE THREAD

**Issue by cherbert0123** [taikoxyz/taiko-mono#15508]
### Describe the bug

Scan function on Holesky not working. Currently, only able to manually find and bridge NFT's.

### Additional context

Here is some NFT's on Holeskey, which were not found using the scan and which I used the manual function to send

https://holesky.etherscan.io/tx/0x7eaca9aa2362d52bf59a224554a586c401b5ffc033ab8209e035b4f8608abd69

**Comment by KorbinianK** [comment]
We are currently not indexing Holesky, only Katla. This may change in the future but right now this is not a bug but intentional.
