### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by ashaqeela** [taikoxyz/taiko-mono#15501]
### Describe the bug

theres little UI bug in https://explorer.katla.taiko.xyz/ transcation count are not sync with actually transaction bc the transaction are through but "transaction" ui count it false

### Steps to reproduce

<img width="597" alt="Screenshot 2024-01-15 225647" src="https://github.com/taikoxyz/taiko-mono/assets/107167634/578301f8-88bd-451f-ac3b-47483c4c6490">

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
this is a delay in the Blockscout frontend, it has always been like this on previous testnets as well.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/issues/15501#issuecomment-1892943783
