### ISSUE TITLE
KATLA BRIDGE NFT

### ISSUE THREAD

**Issue by dangaoron** [taikoxyz/taiko-mono#15519]
### Describe the bug

When trying to scan the NFT it won't recognized, even after adding it to metamask, the manual adding of NFT doesn't recognize too.

![katla1](https://github.com/taikoxyz/taiko-mono/assets/77283537/198790ef-66cf-4ce5-b519-64248314c917)
![katla2](https://github.com/taikoxyz/taiko-mono/assets/77283537/39ecdd01-4c96-4eb9-baa8-dd39694029ca)

### Steps to reproduce

Steps to reproduce here.

### Additional context

The NFT is in KATLA network, created and deployed via Thirdweb in katla network.

**Comment by KorbinianK** [comment]
@dangaoron Please provide the NFT address (if you provided the sourcecode). Most likely the NFT does not follow the standards and has a non-number ID.

**Comment by dangaoron** [comment]
Here's the contract address of the NFT, it has a token id number assigned

0xbd3e9662F39cd6f030A91894FD8eB02b2529a90F

**Comment by dangaoron** [comment]
So I noticed it is working properly now, can both scan and add manually on both network holeysky and katla. tried it and bridged both from and to Kalta.  Great work! Should i close this issue or what? :) hoping i could get a contributor role or something for it :) again, great work for a quick fix!  👍
