### ISSUE TITLE
unable to swap on Taiko Katla testnet

### ISSUE THREAD

**Issue by cryptoqn** [taikoxyz/taiko-mono#15515]
### Describe the bug

Description of the bug here.Transactions getting failed.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.
![taikofeed](https://github.com/taikoxyz/taiko-mono/assets/73419650/cb01e7e3-82fc-4e30-9950-4939e2b5ecd6)

**Comment by KorbinianK** [comment]
Try a different RPC, see if that fixes it.

**Comment by KorbinianK** [comment]
stale
