### ISSUE TITLE
Need for providing more options for Faucet

### ISSUE THREAD

**Issue by Web3Node** [taikoxyz/taiko-mono#15517]
### Describe the feature request

The available Hollesky testnet faucet sources are becoming almost drained. Testnet users finding it difficult to receive. 
For now, the two only fuctional sources of  the Holesky testnet faucet are "Stakely", which is received through the  pasteof EOA wallet address and performing some social media task. The 2nd option left is through mining, which is more complicated to achieved. 

### Describe alternatives you've considered

There is a need for the removal of all the drained Holesky testnet faucets sources and/or make them functional.  
Another alternative is bringing in more faucet sources such as sepolia, with the ability to supply Holesky testnet faucet.

### Additional context

Additional context here.

**Comment by Engrcyber** [comment]
Getting hollesky Ethereum for the Taiko testnet has become a very big issue. But I was able to discover a web3 website that gives 0.1 hollesky eth per day, which should be enough to carryout testnet tasks. 

Website address is https://learnweb3.io/faucets/holesky/

All you have to do is create an account with the , input your eth address and solve the captcha. 0.1eth will automatically be sent to your wallet address. You can request for this every 24hr. I hope this helps a lot of user resolve the issue of unavailability of enough hollesky eth.

**Comment by safesuccess** [comment]
Thank you @Gwaram455  for bringing up this point. Atleast, i found a solution to getting faucet from this repo. Been struggling for the past 5 days. Thank you

**Comment by SultanRukmana** [comment]
When yhe faucet full and we need a few token testnet its very anyoying. That right need more option faucet

**Comment by Darlfas1** [comment]
Thanks so much for raising this vital point about the need for members of the community to be adequately provided with faucet.

**Comment by KorbinianK** [comment]
There are plenty of working Holesky faucets :) I am sure you will find one through either the docs, our discord or good old google.
