### ISSUE TITLE
Katla token bridge delay/error

### ISSUE THREAD

**Issue by revTrade** [taikoxyz/taiko-mono#15513]
### Describe the bug

I truly appreciate the diligent efforts of the developers in this advanced development. Prior to launching the mainnet, I encountered an error while bridging ETH from Holesky to Katla. The sent tokens were not received, despite the on-chain explorer indicating the success of the transaction.

### Additional context

Additional context here.
![Screenshot 2024-01-17 021416](https://github.com/taikoxyz/taiko-mono/assets/156843958/ff0790a1-1607-43e2-b559-e6fdbae0126b)
![Screenshot 2024-01-17 021435](https://github.com/taikoxyz/taiko-mono/assets/156843958/e4499200-a9db-459f-a846-c119ce409974)

**Comment by cyberhorsey** [comment]
That is the success transaction for sending the tokens, not for receiving them. There is currently a backlog for them to be claimed on the destination chain.
