### ISSUE TITLE
Taiko Alpha 6 LP invalid

### ISSUE THREAD

**Issue by Afurehub** [taikoxyz/taiko-mono#15518]
### Describe the bug

Swapping on https://swap.katla.taiko.xyz works well. However, adding liquidity to pool is invalid. I can't add liquidity to pool.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
Can you describe the steps to get to this point?

**Comment by krypTuknife** [comment]
was it too slow?
