### ISSUE TITLE
The exchange meeting failed on the Katla network, swap from ETH to USDC

### ISSUE THREAD

**Issue by yog2012** [taikoxyz/taiko-mono#15516]
#### Bug Description:
The exchange meeting failed on the Katla network, swap from ETH to USDC

#### Expected Result:
When there is enough ETH in the user account and USDC is exchanged from ETH, if the Gas setting is correct, it should be successful at once without any exceptions

#### Actual Result:
When the user chooses to input a sufficient number of ETH for exchange,The exchange meeting failed on the Katla network, swap from ETH to USDC

### Steps to reproduce

1.go to websit:https://swap.katla.taiko.xyz/#/swap
2.connect the okx wallet,and switch to Katla network
3.select your pay token:`eth`,select your receive token `usdc`.
input the eth quantity:`0.01`
4.then swap eth to usdc,wait for one minit

### Additional context

Wait for one minute and display “Swap failed”，**the screenshots as follow:**
![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/787082b2-fe7a-4df2-8e6e-599a3c74c922)

repeat the action,the same result

**Comment by yog2012** [comment]
and there is no transaction hash:

**Comment by yog2012** [comment]
and there is no transaction hash:

![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/71e781b1-94ec-47b4-bdd9-6c3aa6f42e75)

**Comment by shivam-V8** [comment]
Hey is anyone working on this issue? i checked and was able to face the same issue while Swapping ETH -> USDT.
Would love to contribute my part as well.
