### ISSUE TITLE
Mint test tokens:HORSE at Katla test net,but no one HORSE token is dispatch,and then the faucet show "This token is not mintable on this network"

### ISSUE THREAD

**Issue by yog2012** [taikoxyz/taiko-mono#15523]
### Describe the bug

goto the faucet page,mint  the "HORSE" token,mint ,but tip success,but no one HORSE is dispatch,and then the mint button is unavailabe

### Steps to reproduce

1.goto the faucet page
https://bridge.katla.taiko.xyz/faucet
2.select the "HORSE" token
3. mint

### Additional context

Additional context here.

![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/b1f7d2a7-1b44-487b-ba11-479a52c5c06b)

![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/dc7ffb8d-0495-4164-8f19-5eb49cb7c4d1)

no transations:
![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/96d6b828-bdb3-4477-aa47-3bb654734056)

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/issues/15523#issuecomment-1899936366

**Comment by yog2012** [comment]
> 1. You cannot mint HORSE on Katla, only Holesky
> 2. Your Transactions only show bridge transactions, go to the explorer or wallet to see your transactions

Roger，Thanks，Mybe it's my fault

**Comment by yog2012** [comment]
> 1. You cannot mint HORSE on Katla, only Holesky
> 2. Your Transactions only show bridge transactions, go to the explorer or wallet to see your transactions

Hey,bro,please check this:show "processing"
![image](https://github.com/taikoxyz/taiko-mono/assets/2180968/be39d661-70ec-4ae1-a6aa-6524ab277189)
