### ISSUE TITLE
Bridge for Katla to Holesky

### ISSUE THREAD

**Issue by invictusbtc** [taikoxyz/taiko-mono#15521]
### Describe the bug

The notice on the bridge website states that the transition to L1 will take approximately 24 hours. However, in reality, the transition takes much longer. For instance, it has been over 48 hours and the transition is still incomplete. Therefore, it is necessary to adjust the time interval of the transition.

Explorer - https://explorer.katla.taiko.xyz/tx/0x287866566f1025bd7d99eb39a79367c3e4a33d906f6b66c8fa5870d1a084a1f3

### Steps to reproduce

Transfer ETH from Katla to Holesky at bridge.katla.taiko.xyz

**Comment by MasterTi1** [comment]
I haven’t started part 6 yet, but overall the testnet is going smoothly without any problems

**Comment by Nomad0x87** [comment]
I agree! Overall the chain is going smoothly!

**Comment by Ash-code183** [comment]
NFT bridging in still an issue, it takes alot of time for protocol to read any nft contract and approve it

**Comment by KorbinianK** [comment]
Bridging L2 -> L1 will take ~24hs and that is by design for this testnet. In the beginning there were some sync issues that caused this delay to be longer, transactions still stuck from last week will eventually get picked up.
