### ISSUE TITLE
Bridging of Holesky to Katla

### ISSUE THREAD

**Issue by Em3rzone** [taikoxyz/taiko-mono#15526]
### Describe the bug

The time for bridging from Holesky to Katla took over 24hours and that takes a lot of time.

### Steps to reproduce

It is needed to adjust the time interval of the transition

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
May be due to a large number of relayer requests. We will increase the bandwidth in the future for mainnet 🙏

**Comment by davidtaikocha** [comment]
Resolved: https://github.com/taikoxyz/taiko-mono/issues/15541#issuecomment-1902790320
