### ISSUE TITLE
I FOUND A SOLUTION TO LACK OF HOLLESKY ETHEREUM FOR TAIKO TESTNET 

### ISSUE THREAD

**Issue by Engrcyber** [taikoxyz/taiko-mono#15527]
Navigating through the Taiko discord community, I found out many testnet users are finding it hard to acquire hollesky eth to carryout testnet tasks. I decided to seek for a long lasting solution to this.

SOLUTION
 I was able to come across a website that only requires you to sign up with either wallet, discord or email (recommend), the  authenticate with your guthub. It allows you to claim 0.1 hollesky eth every 24hr time frame, which should be more than enough to carryout the Taiko Katla tesnet. Kindly check the link attached below for website link 
https://learnweb3.io/faucets/holesky

**Comment by 2manslkh** [comment]
Do highlight this to the community in discord!
