### ISSUE TITLE
Asset value comparison.

### ISSUE THREAD

**Issue by k1yz5r** [taikoxyz/taiko-mono#15535]
### Describe the feature request

In a world of decentralization, the importance of simplicity and easy use of a protocol or application is a huge key toward mass adoption. I will suggest adding asset value to the bridge protocol features so that when users are trying to use the bridge, they can easily input assets and equally see the asset value in USD. FOR EXAMPLE: "A start-up investor trying to use the bridge feature to bridge his ETH, just inputing the asset value (ETH) 0.01, such user should be able to view the exact comparison value of asset... this will be a useful feature because most crypto assets are volatile in nature.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

![Screenshot (231)](https://github.com/taikoxyz/taiko-mono/assets/87627821/ed829ceb-ed2a-4ef6-8463-bfa232232eb6)

**Comment by KorbinianK** [comment]
Your wallet will likely show you the transaction cost in your local currency or whatever you configured. As we neither detect the user's location nor know their preferred fiat currency, this is not a feature currently on the roadmap.
