### ISSUE TITLE
NFT Bridge problem 

### ISSUE THREAD

**Issue by DrippyDripss** [taikoxyz/taiko-mono#15532]
### Describe the bug

Description of the bug here. Well i was trying to bridge the NFT and i have 500$ worth testnet and the fee was only 178$ but i tried with aggressive gass fee and paid more but it still keep failling and i am unable to bridge my both NFT 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here. 
![Screenshot_2024-01-19-23-55-30-577_com kiwibrowser browser](https://github.com/taikoxyz/taiko-mono/assets/156595933/161dc0da-fdfd-4dd0-97d2-a563b7cf8f91)

**Comment by mailmeanwar** [comment]
Failex

**Comment by KorbinianK** [comment]
You most likely created or are using a collection from NFTs2Me

If you're experiencing problems with bridging your NFT created on NFTs2Me, you may need to adjust the collection settings. Follow these steps:

1. Go to your collection settings on NFTs2Me.
2. Change the 'Max Per Owner' setting to 0.
3. Remint your NFT with the new settings.

**Comment by web3farmer247** [comment]
try refreshing your browser

**Comment by KorbinianK** [comment]
Stale
