### ISSUE TITLE
DELAY SWAPPING

### ISSUE THREAD

**Issue by Dannyviktor** [taikoxyz/taiko-mono#15534]
### Describe the bug

Trying to swap my ETH on Taiko to Horse but delayed for more than 6hrs.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by RazaTheChallenger** [comment]
Ensure you have sufficient ETH in your Taiko wallet to cover the swap and transaction fees.
Verify that the liquidity pool for the ETH-Horse pair has enough liquidity to handle your swap amount.
Check if there are any ongoing network issues that might be affecting Taiko swaps.

**Comment by Cryptmenic** [comment]
I think holesky network is slow. Even claiming faucet has been failing. I think more patches need to be done to resolve this issue.

**Comment by rajatj86** [comment]
you can try it now it take less time
