### ISSUE TITLE
Stately holesky testnet issue

### ISSUE THREAD

**Issue by Akontee2** [taikoxyz/taiko-mono#15533]
### Describe the bug

Tried to claim faucet for more than 10 times already with none working out for me

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
There is a big demand right now. Please wait a bit or ask nicely in the discord community if someone can send you some.

**Comment by Akontee2** [comment]
Alright
