### ISSUE TITLE
BUG SCAN NFT (HOLESKY TO KATLA)

### ISSUE THREAD

**Issue by arraylasted** [taikoxyz/taiko-mono#15539]
### Describe the bug

found the Bug for scan NFT who just can adding them manually, actually need auto just simple click on scan..like on the katla L2 it work normally...
![WhatsApp Image 2024-01-20 at 23 33 20](https://github.com/taikoxyz/taiko-mono/assets/54189453/779285e1-8a7a-4dd9-8cd6-b6089590bc17)

### Steps to reproduce

need a fiture scan fix.. not just adding them normally 

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
We are currently not indexing Holesky, only Katla. This may change in the future but right now this is not a bug but intentional.
