### ISSUE TITLE
HOLESKY BRIDGED TO KATLA, MANUAL CLAIM ONLY?

### ISSUE THREAD

**Issue by philip0529** [taikoxyz/taiko-mono#15541]
### HOLESKY TO KATLA BRIDGE

I bridged an ETH from Holesky going to Katla, thinking that it will be automatically claimed by the "RELAYER," and week has passed still not been claimed. 
### MANUAL CLAIM
Instead, I borrow an ETH in Katla network from a person in discord just to claim manually the ETH Katla that I bridged a week ago.

### WHO ARE THE RELAYER?

How long does it take for the RELAYER to claim such bridged for us without waiting longer?

**Comment by Hothit1** [comment]
I got the same problems but the Ethereum arrived after 1 day. 
would suggest to add a line to the bridge interface to let people know that they might need to wait for relayer or they can claim by themself if they've already have Eth on Katla.

**Comment by cyberhorsey** [comment]
there was an issue with the relayer processors, it should be resolved now and the backlog is being processed. thank you for the issue!
