### ISSUE TITLE
Failed transactions 

### ISSUE THREAD

**Issue by rose987** [taikoxyz/taiko-mono#15552]
### Describe the bug

Description of the bug transactions mainly consists with horse to other assets getting failed 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
In order to help you we need more information.

**Comment by rose987** [comment]
TTtok token from katla to holesky sometimes getting failed

**Comment by KorbinianK** [comment]
> TTtok token from katla to holesky sometimes getting failed

Please provide details such as transaction hash and the type of error you are getting. We will look into it

**Comment by KorbinianK** [comment]
stale
