### ISSUE TITLE
Add liquidity 

### ISSUE THREAD

**Issue by rose987** [taikoxyz/taiko-mono#15557]
### Describe the bug

Description of the bug here why horse - eth pair showing out of order while adding liquidity.. i am not able to add . Some other pairs r also showing out of order 

### Steps to reproduce

Steps to reproduce here.
![Screenshot_2024-01-24-09-30-38-75_d4b821f22c36211daa9077338f9854d0](https://github.com/taikoxyz/taiko-mono/assets/41636498/3cef0e25-324f-496f-9671-3a550c1203af)

### Additional context

Additional context here.

**Comment by 2manslkh** [comment]
It seems that someone bought your tokens within your provided liquidity range. The LP is working as expected 👍
