### ISSUE TITLE
Taiko Bridge wrong amount of eth

### ISSUE THREAD

**Issue by Netonedim** [taikoxyz/taiko-mono#15579]
### Describe the bug

While using bridge from Holesky to Katla, there i see two different eth amounts from my metamask eth. Especially the 2.d amount was a bit strange but after i clicked the max it showed -(negative) amount of eth.
![Taikoya1](https://github.com/taikoxyz/taiko-mono/assets/116693284/5af9b646-3cb2-4004-903c-c59863abc7ca)

0x6cB562eDe1273A4bf554d2D2E273a6110e2F3c5B is the metamask adress i used

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
Duplicate https://github.com/taikoxyz/taiko-mono/issues/15507
