### ISSUE TITLE
NFT Bridging not working 

### ISSUE THREAD

**Issue by Chinaice07** [taikoxyz/taiko-mono#15571]
### Describe the bug

When trying to bridge NFT from Holesky to Katla it all goes through the approval of the NFT but when the  
transaction history was checked it didn't go and a button beside it was written to 'Retry' the transaction but it gave an error message after approving transaction. The 'Release' button appeared after that and when clicked initially it brought up a transaction to approve but the tx fail after and on subsequent trails it didn't bring up a transaction to approve just an error message. The NFT is still with the 0x91bc040cABBB29A5A9520a47d575D3dda6EE4F05 contract address and not been bridged to Katla and i cannot get the  NFT back to Holesky. Many other in the discord server has complained of similar issue so not just me.
Also the bridge does not automatically detect NFT, the scan button does not work. When adding the NFT manually it most times takes time to detect the Token ID.
![Screenshot_20240125-033534](https://github.com/taikoxyz/taiko-mono/assets/144505390/023453c6-584e-4b7b-b646-71e0fe6865b8)
![Screenshot_20240125-034550](https://github.com/taikoxyz/taiko-mono/assets/144505390/8652074c-3316-4a15-9362-e2f9bb2bdabf)
![Screenshot_20240125-034618](https://github.com/taikoxyz/taiko-mono/assets/144505390/1a0f0eba-a819-4bee-8c7f-700c022142db)

### Steps to reproduce

1. Go to https://bridge.katla.taiko.xyz and connect Metamask Wallet
2. Click the three lines (Menu) at the top right corner
3. Click the NFT
4. Click bridge
5. Scan for NFT on Holesky (won't bring any result) or add the NFT contract manually
6. Click continue and Approve NFT
7. Then Click Bridge 
8. Check transaction history after the transaction complete successfully; the bridge was not successful bridged to Katla just left the wallet to the contract and now a retry button is shown beside it
9. Click 'Retry'
10. When/if the transaction fails a 'Release' button appears, click it

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@Chinaice07 thanks for the report. Regarding the release failing: We are looking into that. There seems to be an issue when generating the necessary proofs on UI side in order to release it.

As to NFTs not being detected on Holesky via scanning: This is expected as we are not indexing all Holeskys transactions currently. This may change, and will for sure for the main net, but right now only Katla NFT transactions are indexed to find contracts.

**Comment by Netonedim** [comment]
I had created a collection on holesky https://stellar-royal-clowns-club.testnet.nfts2.me/ 
, i succesfully bridged it,
 you can mint and try again with one of this nft
, i had no problem
you can see successful tx of nft bridging here https://holesky.etherscan.io/tx/0x913b30fbda5279cb0cb493dd604e8a1c3f3d8e832ce62324ed3bb9a8ff22039c

**Comment by KorbinianK** [comment]
stale
