### ISSUE TITLE
Bridge for Katla to Holesky

### ISSUE THREAD

**Issue by invictusbtc** [taikoxyz/taiko-mono#15586]
### Describe the bug

Information for reflection:
One transaction is delayed. It has been 11 days.
Not claimed - "An invalid proof was provided for this action"
I think it's a bug!!!

https://explorer.katla.taiko.xyz/tx/0x544ee36142e07c7f7d0d79c66932cf486525c2e8ec36604da3a52ec487182617

![2024-01-27_09-41-52](https://github.com/taikoxyz/taiko-mono/assets/108835149/fe021894-0b90-4c6d-8750-f87b281131f6)
![2024-01-27_09-35-12](https://github.com/taikoxyz/taiko-mono/assets/108835149/d0b364a2-2d9a-49c9-8c65-44ca9282e34c)

**Comment by invictusbtc** [comment]
I think it's a bug.

**Comment by invictusbtc** [comment]
It has been 15 days, indicating a potential bug.

https://explorer.katla.taiko.xyz/tx/0x544ee36142e07c7f7d0d79c66932cf486525c2e8ec36604da3a52ec487182617

![2024-01-31_22-13-27](https://github.com/taikoxyz/taiko-mono/assets/108835149/ea268311-8560-4cd2-b4b5-e95ca7edce13)
![2024-01-31_22-12-35](https://github.com/taikoxyz/taiko-mono/assets/108835149/d736cb64-ab34-483b-958f-37f548a70a96)

**Comment by KorbinianK** [comment]
@invictusbtc We are aware of this and an update for the relayer will launch soon. Please be patient a little bit longer :)

**Comment by invictusbtc** [comment]
@KorbinianK Ok, just give me the POAP :)

**Comment by invictusbtc** [comment]
why did you close the issue when it's still pending?!

![2024-02-06_16-23-31](https://github.com/taikoxyz/taiko-mono/assets/108835149/4bd37497-69fd-4e89-9496-f843d4e5e473)
