### ISSUE TITLE
Fix: Correct IP Format in .env.sample Endpoints

### ISSUE THREAD

**Issue by papadritta** [taikoxyz/taiko-mono#15583]
### Describe the bug

The .env.sample file currently contains an incorrectly formatted IP address, http:/192.168.1.15:8545, which is missing a forward slash. This format could potentially lead to connection issues for new users attempting to connect to the archive node using these endpoint examples. The correct format should be http://192.168.1.15:8545.

### Steps to reproduce

1. Open the .env.sample file in the project repository.
2. Observe the format of the IP address under the relevant endpoint section.
3. Note the missing forward slash in the http:// part of the IP address.

### Additional context

Correcting this format is crucial for ensuring that new users do not encounter connectivity issues due to a typographical error in the example configurations.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/simple-taiko-node/pull/170
