### ISSUE TITLE
Unauthorized Access to Pool Details

### ISSUE THREAD

**Issue by kowcik** [taikoxyz/taiko-mono#15592]
### Describe the bug

Currently, in the Taiko project, there is a security concern where users have the ability to view all details of pools created by other users by traversing the URL with random pool IDs. This issue allows unauthorized access to sensitive information, compromising the privacy and security of the platform.

To ensure the confidentiality and integrity of users' pool data, it is crucial to address this security vulnerability at the earliest stage of pool exploration. Implementing appropriate access controls and authorization mechanisms during the initial step of pool discovery is recommended. This will restrict users from viewing details of pools they have not created, mitigating the risk of potential threats and unauthorized data exposure.

By addressing this issue and enforcing strict access restrictions, Taiko can enhance security measures, protect user privacy, and establish a more secure environment for pool management and interaction

### Steps to reproduce

Prerequisite: User has to be aware of the remove liquidity URL and this is possible when you remove liquidity for your own pool 
Ex; https://swap.katla.taiko.xyz/#/remove/

1. Add a random number to the url. example 92250
2. Click on remove liquidity button

### Additional context

In the below image the pool# 91696is not owned by me 

Image 1: 
![Screenshot 2024-01-28 165633](https://github.com/taikoxyz/taiko-mono/assets/53010941/747e02e4-815f-4a13-8cea-91b0ae734f45)
Image 2:

**Comment by kowcik** [comment]
Image 2: 
![Uploading Screenshot 2024-01-28 165750.png…]()

**Comment by Gbanks2230** [comment]
Nice observation

**Comment by kowcik** [comment]
Will i be eligible for role ??
