### ISSUE TITLE
Taiko faucet page does not work when accessed through the faucet link(https://bridge.katla.taiko.xyz/faucet) directly . 

### ISSUE THREAD

**Issue by awinash21** [taikoxyz/taiko-mono#15595]
### Describe the bug

Description of the bug here :

The Taiko faucet page behaves differently and faucet does not work when accessed directly through this link https://bridge.katla.taiko.xyz/faucet . It works normally when we click the main url https://bridge.katla.taiko.xyz and then click on faucet . It throws an unrelated error when accessed through the /faucet url which already has /faucet in the path. 

<img width="1439" alt="faucet_bug_when_directly_access_faucet_url" src="https://github.com/taikoxyz/taiko-mono/assets/42409242/b6174e3c-55c9-4d41-b5b4-d873dea5a312">

### Steps to reproduce

Steps to reproduce here:

1. Go to https://bridge.katla.taiko.xyz/faucet url and connect to site 
2. Select Horse token 
3. On selecting Horse token it always throws an error saying Destination Chain must be selected which is incorrect error messaging .

**Comment by KorbinianK** [comment]
Thanks for the report, the fix is already waiting for deployment!
