### ISSUE TITLE
No Bug 

### ISSUE THREAD

**Issue by Yashneem12** [taikoxyz/taiko-mono#15615]
### Describe the bug

I am Using Taiko Since 6 month, Bridge 100 Times On Testnet, always Working Smoothly 

But Thire Are Some Bug On Claim Horse Foucet

Thanks 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by MacBuk7** [comment]
yes, Are Some Bug On Claim Horse Foucet

**Comment by KorbinianK** [comment]
@Yashneem12 @MacBuk7 Please provide more details such as screenshots so we can look into it. Thank you!

**Comment by KorbinianK** [comment]
stale

**Comment by Yashneem12** [comment]
Sorry Sir For Late Reply


We Used More Time And It worked Properly

Thanks Sir 🙏
