### ISSUE TITLE
Failed when creating the new pool and adding liquidity 

### ISSUE THREAD

**Issue by rajatj86** [taikoxyz/taiko-mono#15614]
### Describe the bug

Description of the bug here.When i try to create a pair of horse and ttko its failed dont know the reason 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by rajatj86** [comment]
is there any way to get the TTKok without SGX machine i want to try with it to add liquidity

**Comment by rajatj86** [comment]
does any one know how to get TTKok ?

**Comment by Harshal9900** [comment]
facing same issue multiple time , cant add luqudity

**Comment by Harshal9900** [comment]
> does any one know how to get TTKok ?

yes , just perform the node and ingage or ingage with github
