### ISSUE TITLE
Bridge | Allowance error

### ISSUE THREAD

**Issue by Azazel020** [taikoxyz/taiko-mono#15621]
### Describe the bug

Bridge gives an unknow error when transfering Horse >> Katla

### Steps to reproduce

1) Go to https://bridge.katla.taiko.xyz/

2) transfer Horse > Katla network

### Additional context

Additional context here.
![Taiko error](https://github.com/taikoxyz/taiko-mono/assets/44430967/697d1299-58da-4457-a10d-6418fe2763ec)

**Comment by Azazel020** [comment]
I just changed the qty from 5 > 10 and after that I could sign the message and bridge the Horse.

FYI

**Comment by KorbinianK** [comment]
@Azazel020 thanks for the information, a fix is on the way.
