### ISSUE TITLE
Txns are getting dropped on Katla Testnet

### ISSUE THREAD

**Issue by maggicutie** [taikoxyz/taiko-mono#15626]
### Describe the bug

Txns are getting dropped on Katla Testnet, they are not getting through as the interface is simply unable to launch he wallet provider & showing error.

<img width="931" alt="taiko error" src="https://github.com/taikoxyz/taiko-mono/assets/135960615/095a1f49-f7d8-45f9-99db-71d78f96da2e">

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by maggicutie** [comment]
<img width="936" alt="Screenshot_11" src="https://github.com/taikoxyz/taiko-mono/assets/135960615/1a884b33-6f64-4aeb-b50e-77b70c5b94d8">

**Comment by rajatj86** [comment]
Due to heavy load on rpc i think it happen with me also and i try it on low traffic

**Comment by KorbinianK** [comment]
@maggicutie can you share the NFT address and your wallet address? Was it an NFT you previously bridged or is it the first time?

**Comment by elpheno08** [comment]
Edit processing fee on custom
