### ISSUE TITLE
docs(website):Add the Taiko node construction procedure for beginners.

### ISSUE THREAD

**Issue by araokaman** [taikoxyz/taiko-mono#15625]
### Describe the feature request

As one example, the current construction guide describes using the nano command to open a text editor and set the value of the endpoint portion, as shown in the attachment.

![image](https://github.com/taikoxyz/taiko-mono/assets/75957857/a22f7c1c-7204-4d94-a762-81147043bd4d)

However, beginners in node construction are not accustomed to using text editors such as nano, and they are confused.
They also have trouble finding the appropriate line among multiple lines, so we would like to recommend a simpler procedure using replace.

### Describe alternatives you've considered

We propose to replace the target character using the sed command.

The following command is used in the above endpoint configuration.
※{} part is replaced by the user
`sed -e "s|L1_ENDPOINT_HTTP=|L1_ENDPOINT_HTTP={Use http}|" -e "s|L1_ENDPOINT_WS=|L1_ENDPOINT_WS={Use websockets}|" .env > .env `

This eliminates the need for tedious editing in a text editor.

### Additional context

The above procedure can also be diverted to enable Proposer and Prover.

**Comment by rajatj86** [comment]
i want to run the holesky node on my VPS do u have codes to run on VPS?

**Comment by araokaman** [comment]
> i want to run the holesky node on my VPS do u have codes to run on VPS?

Instructions for building the Holesky node can be found in the official guide.
If you are building on a VPS, simply follow these steps on the VPS.
https://docs.taiko.xyz/guides/run-a-holesky-node/

**Comment by araokaman** [comment]
Hello.

Thank you for your response. I am glad you even made a pull request.

So I don't have to create a pull request on my end for this case, right? Am I still eligible to receive GitPOAP as a contributor?

**Comment by Harshal9900** [comment]
facing the error while runnning node, showing dispatch error , i dont know what the glitch but its randering multiple times

**Comment by jay3183** [comment]
I would like to help with this problem
