### ISSUE TITLE
Guild Taiko Error

### ISSUE THREAD

**Issue by BCrative4** [taikoxyz/taiko-mono#15637]
### Describe the bug

Error
Must be verified for this action. Please refresh the page, and verify

ID: 7a4def4a-cc68-4a62-b754-393b6ffd835c

### Steps to reproduce

Can't join Guild Taiko Still Error, i try refresh/reconnect account guild still error

### Additional context

An unknown error occurred
Check the console for more details

![report](https://github.com/taikoxyz/taiko-mono/assets/80142059/e35335cc-d574-4801-9dc4-04eb20195871)

**Comment by KorbinianK** [comment]
Unrelated to this repository.
