### ISSUE TITLE
Problem adding NFT to Katla L2 wallet

### ISSUE THREAD

**Issue by TWINEAGLE-23** [taikoxyz/taiko-mono#15649]
### Describe the bug

Katla does not accept the contract address when importing NFT to L2 wallet. Instead, it accepts the Bridge contract address. Isn't there something strange here?
<img width="1352" alt="Ekran Resmi 2024-02-02 12 49 37" src="https://github.com/taikoxyz/taiko-mono/assets/111805595/3edc6e83-4523-44b9-8f2a-b9164629ad7d">
<img width="1306" alt="Ekran Resmi 2024-02-02 13 03 48" src="https://github.com/taikoxyz/taiko-mono/assets/111805595/a3f34a28-f64f-43d0-8b32-ea4a92678d93">

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@TWINEAGLE-23 the wallet you are referring to looks like MetaMask. If there is an issue with it, it's not in our hands
