### ISSUE TITLE
Add "Wallet Health" Feature

### ISSUE THREAD

**Issue by antonhidayatulloh** [taikoxyz/taiko-mono#15653]
### Describe the feature request

The rise of wallets is subject to drain because they interact with malicious tokens and the web. With the "Wallet Health" feature for scanning wallet addresses it will be very helpful for bridge users.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
I don't think it is within the responsibility of taiko to measure the "health" of a wallet. Where would you even get started? Who decides what is a malicious token? What about dusting attacks on wallets? Who maintains such a list? 

Not planned. If you are uncertain about your wallets security, create a new one and only interact with contracts and dapps you 100% trust.
