### ISSUE TITLE
NFT Minting issue

### ISSUE THREAD

**Issue by Gaddafi1969** [taikoxyz/taiko-mono#15652]
### Describe the bug

problem in changing the network when minting the NFT in this website [mint.morkie.xyz/taiko](https://t.co/jYoRYAUIh6)

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
Not related to this repository. Contact the respective project or team that provides the NFT, which is not taiko.
