### ISSUE TITLE
Unable to Find Marketplace for Prover Endpoints

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/taiko-mono#15654]
### Describe the feature request

I am encountering difficulties in locating the marketplace mentioned in the documentation for obtaining prover endpoints. The documentation suggests obtaining a prover from the marketplace capable of generating SGX and ZK-EVM proofs. However, I am unable to find the specified marketplace.
<img width="1558" alt="Capture d’écran 2024-02-04 à 08 46 04" src="https://github.com/taikoxyz/taiko-mono/assets/107585158/432f0aa6-6fd1-4ff5-a233-0c77d54dd984">

### Describe alternatives you've considered

Consider creating a dedicated page with a list of prover endpoints for easy reference. Additionally, include details on verifying the successful submission of a block proposal.

### Additional context

The documentation mentions the necessity of having a prover from the marketplace that can generate both SGX and ZK-EVM proofs. Unfortunately, the location or details of this marketplace are not provided in the documentation.

**Comment by CrCollecter** [comment]
tomorrow

**Comment by d1onys1us** [comment]
we have added it now here: https://docs.taiko.xyz/resources/prover-marketplace/

we will update this to include a submission form and healthcheck for the prover endpoints. you can follow that issue here: https://github.com/taikoxyz/docs/issues/41

**Comment by samui68400** [comment]
thank you for the update
