### ISSUE TITLE
Dark mode feature

### ISSUE THREAD

**Issue by DenyBsa** [taikoxyz/taiko-mono#15650]
### Describe the feature request

When I use dark mode on your website its pretty difficult to see the gas fee or additional informations below its all dark + dark mode = not so good for users

### Describe alternatives you've considered

You can change color and make it lighter then its gonna be very good for users while using Taiko website

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
If you are referring to the bridge, you can simply switch to light mode.
