### ISSUE TITLE
Bridge NFT

### ISSUE THREAD

**Issue by AriyanJoy3595** [taikoxyz/taiko-mono#15663]
### Describe the bug

Bridge NFT is not working and transaction was failing 

### Steps to reproduce

Please fix this issue ASAP

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@AriyanJoy3595 without any details we cannot help you. Transaction hash, screenshots etc. and we will look into this. There is a reason the issue template has those sections. Please understand that we will close this issue if no further information have been provided within the next couple of days.

**Comment by d1onys1us** [comment]
closing as stale.
