### ISSUE TITLE
cant connect my wallet to https://bridge.katla.taiko.xyz/faucet

### ISSUE THREAD

**Issue by Zackwulff** [taikoxyz/taiko-mono#15660]
### Describe the bug

it seems like the site is down

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@Zackwulff The bridge UI is online and connecting the wallet works. Please share more info, such as screenshots and error messages, otherwise we cannot help you.

**Comment by KorbinianK** [comment]
stale
