### ISSUE TITLE
ERROR UI bug for completed transaction

### ISSUE THREAD

**Issue by Obmini** [taikoxyz/taiko-mono#15664]
### Describe the bug

Bug is visible when you make a transaction/confirmation for token. This error abou Transaction only on UI, but on explorer this transaction are already gone. Looks like they provide details about previous transaction or something ogne wrong.
![Знімок екрана 2024-02-06 003652](https://github.com/taikoxyz/taiko-mono/assets/96210636/6f398ec8-25a0-4871-8039-40c3c5c45675)

### Steps to reproduce

Steps to reproduce here.

Chrome version 121.0.6167.140. Adblock on.
1. Choose token - HORSE 20 jetons)
2.Start to Bridge and Send transaction
![1](https://github.com/taikoxyz/taiko-mono/assets/96210636/89d938b4-29c5-473a-81a9-a1dfc3713f4f)

3. You will see Process transaction
4. After few seconds - transaction failed tad
![2](https://github.com/taikoxyz/taiko-mono/assets/96210636/4c3120fd-c006-4645-8dc1-e05c3b02856b)

5. If you refresh page once - it show balance from previous transaction, which failed more older
![3](https://github.com/taikoxyz/taiko-mono/assets/96210636/2cf25435-04f6-4feb-85e6-cda8222eb240)

6. If you refresh page second time - it shows actual balance
![4](https://github.com/taikoxyz/taiko-mono/assets/96210636/54a284cc-79a8-4a5c-82ed-4e7e04d6b1e6)

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@Obmini I looked into this, this is because it actually times out waiting for the transaction hash. Currently there is a lot of traffic on the network, so it takes a long time, causing this error to appear.

We will improve this, and display the correct message.

**Comment by rajatj86** [comment]
i got the same error but when i try at low traffic time it doesn't come you can try it

**Comment by DeanMojo** [comment]
Got the same error

**Comment by shivam-V8** [comment]
@KorbinianK would love to contribute on it, can you please guide me through the repository?
