### ISSUE TITLE
Bridge Claim ETH Katla to Holesky

### ISSUE THREAD

**Issue by BCrative4** [taikoxyz/taiko-mono#15673]
### Describe the bug

Error claim after bridge, pay high gas fee and still error

### Steps to reproduce

Claim ETH after bridge from katla to holesky
![katla](https://github.com/taikoxyz/taiko-mono/assets/80142059/b4f3e3b8-2315-4b8b-a3cf-4269d26b5f4e)
![katla 2](https://github.com/taikoxyz/taiko-mono/assets/80142059/7c364eee-d3a8-43ec-8cec-5081857b75aa)
![katla 3](https://github.com/taikoxyz/taiko-mono/assets/80142059/1bf3c847-0f3e-4379-a773-23940736a16b)

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@BCrative4  please share a screenshot of the developer console output as well as wallet address.

For chrome:
https://developer.chrome.com/docs/devtools/open

**Comment by BCrative4** [comment]
but, this is error from smart contract sir

Pada Rab, 7 Feb 2024 pukul 23.23 Korbinian ***@***.***>
menulis:

**Comment by KorbinianK** [comment]
@BCrative4 The error in the UI is very unspecific, the console output might help narrow it down. With your wallet address I can look into the transactions. Without any of these information I am unable to help you.

**Comment by d1onys1us** [comment]
closing as stale, please re-open with more details such as wallet address if still running into problems.
