### ISSUE TITLE
Transactions not seamless with CryptoRumble and slow

### ISSUE THREAD

**Issue by zactian7205** [taikoxyz/taiko-mono#15670]
### Describe the bug

When a transaction (e.g. starting a game) goes through, CryptoRumble does not react accordingly. More often than not, transactions are slower compared to other chains, and sometimes TXID error popup shows.

<img width="749" alt="Screenshot at Feb 07 08-39-53" src="https://github.com/taikoxyz/taiko-mono/assets/79579052/b9962bbd-c902-4c85-ac34-df0ce5bdd603">

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
@zactian7205 This repository is not associated with crypto rumble. Please reach out to their team.
