### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by nheoshikuyanhemo** [taikoxyz/taiko-mono#15674]
### Describe the bug

Transaction failed When eth bridges, especially when claiming eth taiko

### Steps to reproduce

Transaction failed 

### Additional context

Transaction failed

**Comment by KorbinianK** [comment]
@nheoshikuyanhemo Thank you for your report. Without any further details we cannot help you. 

Please provide transaction hash, screenshots etc. and we will look into this. There is a reason the issue template has those sections you should fill in. Please understand that we will close this issue if no further information have been provided within the next couple of days. Thank you.

**Comment by d1onys1us** [comment]
closing, please re-open with more details if necessary.
