### ISSUE TITLE
When will we receive the TTKok tokens?

### ISSUE THREAD

**Issue by szefo8181** [taikoxyz/taiko-mono#15684]
### Describe the bug

Does anyone from Teemu's team have any information? When will the TTKOk tokens be distributed?

To participate in the network as a Prover, we had to purchase stronger servers, which incurs costs of $400 per month. Practically, when I purchased the server three weeks ago to submit the form and provide the necessary data, we still haven't received any tokens!

The information could have been released when the testnet was ready for deployment by individual users. As a result, we incur costs of $400 per month, and the server remains unused. Can someone from Teemu's team provide us with any information regarding this matter?

I'll just add that I'm currently working on the Holeskey and Taiko nodes as RPC, and that's all. These services could also be run on weaker machines, and the Prover and Proporser is turned off.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by nicocil04** [comment]
Any news about that ?

**Comment by d1onys1us** [comment]
@szefo8181 the google form received too many inquiries for us to be able to handle manually as we needed to register the public key manually and give back an ID to include in the SGX instance.

we are actively working on a self-service onchain registration for SGX. will provide more details as soon as they come.
