### ISSUE TITLE
Demora no envio dos tokens na ponte.

### ISSUE THREAD

**Issue by Fam76** [taikoxyz/taiko-mono#15690]
### Describe the bug

Boa Tarde a todos da equipe.
Fiz ontem a ponte entre a rede Holesky e a rede Katla só que não consigo reinvindicar os tokens de teste pelo fato de que consta Saldo insuficiente para reivindicar a si mesmo. Aguarde até que o retransmissor reivindique você automaticamente. Só que já vai fazer quase 24hrs. Contribui com todas as outras fases de Taiko e quero muito contribuir com essa também. Grato pela atenção

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
translate to english next time please. we had a bug in our relayer, should be cleared soon, thanks.
