### ISSUE TITLE
Bridge NFT issues

### ISSUE THREAD

**Issue by Grootoshi** [taikoxyz/taiko-mono#15714]
### Describe the bug

Bridging nft doesnt automatically recognise nfts in wallet, have to manually enter information,

even then, the individual numbers are not clear when bridging back

### Steps to reproduce

please see above

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
We are only scanning for nfts on Katla, not holesky. Not a bug. This will most likely change for Mainnet.

**Comment by Grootoshi** [comment]
The scanning on Katla was not working
