### ISSUE TITLE
Bridge for Katla to Holesky (BUG)

### ISSUE THREAD

**Issue by invictusbtc** [taikoxyz/taiko-mono#15729]
### Describe the bug

Information for reflection:

One transaction is delayed. It has been 11 days.
Not claimed - "An invalid proof was provided for this action"
IT'S A BAG.!!!

Explorer - https://explorer.katla.taiko.xyz/tx/0x544ee36142e07c7f7d0d79c66932cf486525c2e8ec36604da3a52ec487182617

![2024-02-10_16-57-26](https://github.com/taikoxyz/taiko-mono/assets/108835149/c64c10cb-0724-405c-9ba9-ad2eabef0c0c)
![2024-02-10_16-55-57](https://github.com/taikoxyz/taiko-mono/assets/108835149/db8e5ca7-3710-499c-9d22-de65a844430a)

### Steps to reproduce

Transfer ETH from Katla to Holesky at bridge.katla.taiko.xyz

**Comment by KorbinianK** [comment]
Your transaction has been claimed already and you have received your funds on Holesky. It just doesn't display the correct status in the UI yet, but that will come with a fix very soon.

**Comment by jemy9900** [comment]
facing this issue.. bridge stuck and swapping getting too much time

**Comment by jemy9900** [comment]
wallet address :- 0xD9C53DeE28dF57BB75BB18e31DcaB5f16650C1Da

**Comment by Harshal9900** [comment]
taking too much time for bridge and lastly getting error while bridging

**Comment by shivam-V8** [comment]
@Harshal9900 Can you add more about the transaction where you're facing this issue

**Comment by KorbinianK** [comment]
> > Your transaction has been claimed already and you have received your funds on Holesky. It just doesn't display the correct status in the UI yet, but that will come with a fix very soon.
> 
> No, it's not true! The ETH test tokens never arrived on Holesky! Yes, the transaction was confirmed on the Katla chain, but no tokens were received on the Holesky chain. That's why I'm saying it's a BUG!!! I don't really care about this issue. 81 ETH more or less, it doesn't matter! I was just sharing that I found a BAG ;)

@cyberhorsey in case you want to follow up here

**Comment by KorbinianK** [comment]
@jemy9900 Which transaction "is stuck"? Are you getting the same "Invalid proof" error message? If so, for which one

**Comment by KorbinianK** [comment]
stale

**Comment by invictusbtc** [comment]
1 month
https://explorer.katla.taiko.xyz/tx/0x544ee36142e07c7f7d0d79c66932cf486525c2e8ec36604da3a52ec487182617
5 days
https://explorer.katla.taiko.xyz/tx/0x7f75d2a4f4f9f5319d22064724c4efa02d19be8c0fa9f5bf188a01f112de524f
