### ISSUE TITLE
update API reference documentation with katla testnet endpoints

### ISSUE THREAD

**Issue by paulallensuxs** [taikoxyz/taiko-mono#15749]
### Describe the bug

The current API reference documentation for the Event Indexer API and Bridge Relayer API contain outdated links that reference the Jolnir testnet. As the new Katla testnet is now available, it is necessary to update these links.

The specific changes needed are as follows:
- Update the Event Indexer API link in `https://eventindexer-swagger.taiko.xyz/` from `eventindexer.jolnir.taiko.xyz` to `eventindexer.katla.taiko.xyz`.
- Update the Bridge Relayer API link in `https://relayer-swagger.taiko.xyz/` from `relayer.jolnir.taiko.xyz` to `relayer.katla.taiko.xyz`.

### Steps to reproduce

Steps to Reproduce:
1. Visit https://docs.taiko.xyz/api-reference/event-indexer-api/
2. Check the link provided for the Event Indexer API.
3. Visit https://docs.taiko.xyz/api-reference/bridge-relayer-api/
4. Check the link provided for the Bridge Relayer API.

**Comment by kaksv** [comment]
Can I take this on?

**Comment by kaksv** [comment]
I also think the spcific APIs to change are in another repository.Because I have cloned the repo of the docs but the indexers are not part of this documentation

**Comment by shivam-V8** [comment]
Seems like this issue is already resolved.

**Comment by maverickOA** [comment]
good one

**Comment by benx12345** [comment]
Nice, already solved

**Comment by edgardevil895** [comment]
you would need to locate the relevant documentation files in your code repository, make the necessary changes, and then submit a pull request or follow your team’s process for updating documentation.

**Comment by sachbeta** [comment]
One of best
