### ISSUE TITLE
Contract Deploy Bug

### ISSUE THREAD

**Issue by gLNnN7** [taikoxyz/taiko-mono#15794]
### Describe the bug

Hi guys,

Ive made a request to deploy  ERC1155 tokens, but the transactions doesnt complete or fail they just kept "in line".

On the attachments you'll be able to see, if i click to go to explorer, it says 404 not found
![t1](https://github.com/taikoxyz/taiko-mono/assets/160059370/6c9be425-ccff-4ed6-9795-c5be5d4db9b5)
![t2](https://github.com/taikoxyz/taiko-mono/assets/160059370/954992c1-54d7-4eab-a35a-fdfe845593c2)
![t3](https://github.com/taikoxyz/taiko-mono/assets/160059370/f0b3d367-fe85-4e8d-b9da-d5bbb5d06893)

i think its blocking new transactions on my wallet, because not even swap is working here, ive also tried to cancel it paying more gas, but it didnt work.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by gLNnN7** [comment]
my wallet is 0x57461C55611Ac00811aE4f8114f740A4A283F2a3

**Comment by KorbinianK** [comment]
@gLNnN7 try resetting your nonce in metamask

**Comment by jemy9900** [comment]
0xD9C53DeE28dF57BB75BB18e31DcaB5f16650C1Da , i also face the same issue

**Comment by jemy9900** [comment]
hope devs will check my issue

**Comment by jemy9900** [comment]
taiko team will reach me soon i am damn sure

**Comment by gLNnN7** [comment]
everything is fine around here guys, checked this morning and the transactions were gone.

Only 3 left, but i speed up the gas and it finished.

Thanks for the attention and sorry for the bad english.

$TAIKO to the mooonnn!!

**Comment by KorbinianK** [comment]
resolved
