### ISSUE TITLE
GitHub on Galxe

### ISSUE THREAD

**Issue by whallet445** [taikoxyz/taiko-mono#15804]
### Describe the feature request

I think that the last task on galxe needs to be linked to GitHub. But it's probably hard to do. And do it as the main criterion or bonus for nft. It will be possible to cancel a lot of bots at once. 
If we had done that, we would have had more people contributing.
Thanks

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
Closing, not related to this repository. Feel free to discuss campaigns on discord.
