### ISSUE TITLE
adding one style to the swap page

### ISSUE THREAD

**Issue by oneofthenfts** [taikoxyz/taiko-mono#15808]
### Describe the feature request

add this style on https://swap.katla.taiko.xyz/#/swap
this style makes the text visible when hovering over the pending button

```
.dZSKRu:hover, .dZSKRu:focus {
    color: black;
    border: 1px solid rgb(249, 249, 249);
    background-color: rgb(255, 239, 255);
}
```

![Screenshot from 2024-02-15 14-25-49](https://github.com/taikoxyz/taiko-mono/assets/149963982/dd1fab66-4c53-4c30-b4b3-326de36c59eb)
![Screenshot from 2024-02-15 14-25-35](https://github.com/taikoxyz/taiko-mono/assets/149963982/f06b130b-466a-42e9-a2a4-4966f60633fe)
![Screenshot from 2024-02-15 14-25-26](https://github.com/taikoxyz/taiko-mono/assets/149963982/17b46a63-5e19-49d4-beba-ebccbc6c729e)

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by shivam-V8** [comment]
This `. dZSKRu ` class is not there in the css styling in the https://swap.katla.taiko.xyz/ .

**Comment by KorbinianK** [comment]
The uniswap interface is a different repository :) Feel free to create a new issue, or even provide a PR.

**Comment by oneofthenfts** [comment]
> The uniswap interface is a different repository :) Feel free to create a new issue, or even provide a PR.

I’m not promoting anyone, I just wanted to add some style since you haven’t done it yourself for a long time. but if the items on the swap page are not the responsibility of the Taiko repository then you are right, I should not have created this thread in this place

**Comment by oneofthenfts** [comment]
this style can be reassigned, although in a few days the mainnet will probably change the design completely, so most likely this is not relevant for the current situation
