### ISSUE TITLE
Claim results for the HOLSKEY to Taiko bridge failed

### ISSUE THREAD

**Issue by nheoshikuyanhemo** [taikoxyz/taiko-mono#15875]
### Describe the bug

Description of the bug here.Claim results for the HOLSKEY to Taiko bridge failed

Tx: 0x22ac303f40a60997ada5ee8603e3e9e367bbb5caf835cb65eaede0bd3af23794

![Screenshot_20240216-224846](https://github.com/taikoxyz/taiko-mono/assets/32210699/c867789c-4645-4d46-bedd-291d7e2565bb)

### Steps to reproduce

Steps to reproduce here.
![Screenshot_20240216-224846](https://github.com/taikoxyz/taiko-mono/assets/32210699/5bd00c90-9cba-4f99-8d84-9d806f802d0e)

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
The transaction has been claimed and could not be claimed manually again -> B_STATUS_MISMATCH
