### ISSUE TITLE
Language selection not working

### ISSUE THREAD

**Issue by top7** [taikoxyz/taiko-mono#15870]
### Describe the bug

Language selection does not seem to work on this page https://swap.katla.taiko.xyz/#/swap?lng=fr-FR

### Steps to reproduce

Steps to reproduce here.
![Capture d’écran du 2024-02-16 15-59-04](https://github.com/taikoxyz/taiko-mono/assets/18647267/e5f84dcb-7d4c-406e-8ab4-4b904ad5824a)

### Additional context

Additional context here.
Chrome Browser

**Comment by Hothit1** [comment]
isn't that the only supported language ?

**Comment by KorbinianK** [comment]
Right now there is no multi language support for any of our applications.
