### ISSUE TITLE
Add [PROJECT_NAME] to the ecosystem page

### ISSUE THREAD

**Issue by Arrefamm** [taikoxyz/taiko-mono#15871]
### Title of your project

tko

### Short (1-2 sentence) description of your project

tko

### Link to your project

https://explorer.katla.taiko.xyz/tx/0x490604bb042da182651925b92afb9f551c20c629e0296e93473b89f8e52a85f5

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

live

### Upload a quality logo to your project

how to get grant?

**Comment by d1onys1us** [comment]
reported for spam.
