### ISSUE TITLE
Need to update prover market place endpoint in the docs

### ISSUE THREAD

**Issue by Azeemniazi** [taikoxyz/taiko-mono#15876]
### Describe the bug

The current endpoint reference for the prover marketplace is outdated and not working anymore, it is necessary to update to a new link in the documentations
Link to documentation: https://docs.taiko.xyz/resources/prover-marketplace
issue to handle: http://taiko-a6-prover.zkpool.io:9876/

### Steps to reproduce

Replace the prover market place link
From: http://taiko-a6-prover.zkpool.io:9876/
To: http://taiko-a6-prover.zkpool.io/  **(Or any new working endpoint url as per updated by ZKPool)**

**Comment by arularmstrong** [comment]
I have raised the PR for the above https://github.com/taikoxyz/docs/pull/53

**Comment by Azeemniazi** [comment]
> I have raised the PR for the above [taikoxyz/docs#53](https://github.com/taikoxyz/docs/pull/53)

Do mention when it gets accepted so i can close the issue

**Comment by arularmstrong** [comment]
The PR is merged to main, changes are visible now.
<img width="518" alt="Screenshot 2024-02-17 at 7 25 12 PM" src="https://github.com/taikoxyz/taiko-mono/assets/33225342/c762b22c-cb95-4c28-8b6b-4e9ea7b9fc1c">
