### ISSUE TITLE
Pending transactions , speed up doesn't work , it is stuck

### ISSUE THREAD

**Issue by Aste75** [taikoxyz/taiko-mono#15880]
### Describe the bug

After doing some swaps and depositing liquidity,  transactions won't go through and seems to be stuck in a loop even if the speed up gas fee 10% or aggressive is selected.  

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
This is related to whatever wallet you are using. Try resetting your nonce, e.g. on metamask or just wait until the first transactions actually have been picked up before sending multiple new ones.

**Comment by Aste75** [comment]
MM wallet.  Same issues already occured on Taiko testnet but never this long.  I will try to reset the nonce.

**Comment by arularmstrong** [comment]
Is the previous transaction dropped after the 10% speed up?

**Comment by Aste75** [comment]
I managed to solve the problem.

Increase 10% didn't work at all.

However the cancel option worked 💪 

Made a few new swaps and they went through.
