### ISSUE TITLE
Liquidity Pool Pair Order Issue

### ISSUE THREAD

**Issue by gilead12** [taikoxyz/taiko-mono#15897]
### Describe the bug

When attempting to add liquidity to the Horse - ETH pair, and possibly other pairs, the order of the pairs appears to be incorrect, preventing successful liquidity addition. The pairs are not displayed in the expected order.

### Steps to reproduce

1. Navigate to the liquidity pool section.
2. Select the "Horse - ETH" pair.
3. Attempt to add liquidity to the selected pair.
4. Observe that the pair order seems to be out of place.

**Additional context:**

This issue may also be present in other pairs within the liquidity pool. Screenshots illustrating the problem and any error messages encountered during the process would be helpful in diagnosing and resolving the issue.

![Screenshot 2024-02-18 094528](https://github.com/taikoxyz/taiko-mono/assets/40698486/07db0922-58a5-4f80-80d1-18638eae6596)

**Comment by KorbinianK** [comment]
Please look at the uniswap v3 documentation to see what "out of range" means.
