### ISSUE TITLE
Withdraw 12 days

### ISSUE THREAD

**Issue by xadro23** [taikoxyz/taiko-mono#15892]
### Describe the bug

Description of the bug here.
I have withdraw taiko kelta to Heskey this go 12 days, please faster about withdraw 

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by KorbinianK** [comment]
Feel free to reopen the issue when you can provide more information such as wallet address, which transaction etc. Fill out the template as detailed as possible.
