### ISSUE TITLE
LP on taiko ? 

### ISSUE THREAD

**Issue by Hinataweb3** [taikoxyz/taiko-mono#15895]
### Describe the feature request

Guys i participated on many testnet of taiko did plenty of features like swaps bridges mint nft deploy contract but i had never the chance to try lp on it its something i use a lot in my web3 journey to lend and borrow ! it would be wonderfull to do it thanks guys :D 

### Describe alternatives you've considered

Collaborate with a lp already present on some L2

**Comment by KorbinianK** [comment]
Feel free to use the swap at https://swap.katla.taiko.xyz and provide liquidity
