### ISSUE TITLE
Enhance Explorer to Support Domain Names in Search and Transaction Results

### ISSUE THREAD

**Issue by arularmstrong** [taikoxyz/taiko-mono#15890]
### Describe the feature request

In addition to adding support for domain name lookup in the search bar, it's crucial to enhance the explorer to display linked domain names in search and transaction results for existing users. Currently, the explorer only provides information related to addresses, which may not fully represent users' activities on the blockchain. By including linked domain names in search and transaction results, users can easily identify relevant information associated with their domains, providing a more comprehensive view of their blockchain interactions.

### Describe alternatives you've considered

Another alternative approach could involve implementing a dedicated "My Domains" section within the explorer interface. This section would allow users to manage and view their linked domain names directly within the explorer platform. By integrating this functionality into the explorer, users can conveniently access information about their domains without the need for external tools or services. Additionally, this approach promotes a cohesive user experience by centralizing domain management within the explorer interface, thereby enhancing user engagement

### Additional context

By displaying linked domain names in search and transaction results, users can quickly identify their domain-related activities on the blockchain, such as transactions involving their domains or interactions with other users' domains. This feature would enhance the usability and utility of the explorer, making it a more valuable tool for users who are actively engaged in managing domain names on the blockchain.
### View on Address Details
<img width="841" alt="Screenshot 2024-02-17 at 1 07 59 PM" src="https://github.com/taikoxyz/taiko-mono/assets/33225342/94dd4ffd-9aad-4312-ac9c-030abe3d3258">

### View on Transaction Details
<img width="1171" alt="Screenshot 2024-02-17 at 1 08 50 PM" src="https://github.com/taikoxyz/taiko-mono/assets/33225342/b54e3ae4-a9fd-4905-a7fd-1bb49b7a6ddf">

### View on Searchbar
<img width="1177" alt="Screenshot 2024-02-17 at 1 15 00 PM" src="https://github.com/taikoxyz/taiko-mono/assets/33225342/218d4eba-d024-49c5-a5ce-3a3862b1d881">

**Comment by KorbinianK** [comment]
Currently not planned before Mainnet as we might use a different explorer altogether.
