### ISSUE TITLE
Errors while creating taiko

### ISSUE THREAD

**Issue by 0xmustey** [taikoxyz/taiko-mono#15907]
### Title of your project

Taiko 

### Short (1-2 sentence) description of your project

Taiko node

### Link to your project

Taiko.xyz

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Testnet

**Comment by KorbinianK** [comment]
spam
