### ISSUE TITLE
Reduce noise and bot traffic in taiko-mono

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#15904]
### Describe the feature request

taiko-mono has way too much bot traffic. I have manually reported some of these accounts that clearly spam (like "asfdasdfasd" with a brand new github account).

we should come up with a multi-step plan to:
- reduce spam issues
- reduce maintainer burden for closing these spam issues.

a short list of items:
- [x] code_of_conduct.md
- [x] updating issue_template to make it more difficult to create an issue, at least acknowledge something **in bold**, you will be reported for spam if it's a spam issue
- ai bot to recognize spam issues
- automatically close stale issues

**Comment by Harshal9900** [comment]
bro i didnt face any problem with sound or anything, kindly reach hospital

**Comment by ladysnazzy** [comment]
> bro i didnt face any problem with sound or anything, kindly reach hospital

there was no need to be rude
