### ISSUE TITLE
Ensure Consistent Emission of Amounts Matching Token Length

### ISSUE THREAD

**Issue by Simplydmo** [taikoxyz/taiko-mono#15913]
### Describe the feature request

The current implementation within taiko.xyz may result in inconsistencies regarding the emitted amounts within the **TokenReceived** event, particularly concerning **ERC721 tokens**. To address this, the proposed solution involves aligning the emitted amounts with the length of **tokenIds**, ensuring clarity and consistency during token transfers.

### Describe alternatives you've considered

1. Modifying the TokenReceived event to emit fixed amounts for ERC721 tokens, irrespective of the tokenIds' length.
2. Implementing additional validation mechanisms to ensure uniformity in emitted amounts across different token types.
3. Introducing explicit documentation highlighting the expected behavior of emitted amounts within the TokenReceived event for various token scenarios.

**Comment by KorbinianK** [comment]
Reported for spam.
