### ISSUE TITLE
Cryptorumble Transaction Error

### ISSUE THREAD

**Issue by ohmursyd** [taikoxyz/taiko-mono#15918]
### Describe the bug

Testnet is not stable when make any transaction in cryptorumble

Its quite often when playing the game inlcude
1. Open box
2. Upgrade hero
3. Start Game

![Screenshot 2024-02-19 135105](https://github.com/taikoxyz/taiko-mono/assets/87795534/212e7980-3232-4d08-bca2-95cecf1822fe)

(https://test.zypher.game/CryptoRumble/)

### Steps to reproduce

Maybe make the testnet faster will make the traffic not stuck

**Comment by ariesbalweell** [comment]
Either because transactions are busy or the network is not yet perfect because it takes a lot of time and syncing is slow

**Comment by KorbinianK** [comment]
Reach out to the crypto rumble team, we are not responsible for their dapp.
