### ISSUE TITLE
Swap on Phone doesn't Work on Phone 

### ISSUE THREAD

**Issue by BAKA3130** [taikoxyz/taiko-mono#15915]
### Describe the bug

I Tried swapping from ETH to WETH but the transaction was stuck for hors and when i checkked my transacion history nothing was shown i can attach a video for proof hope this helps the devs 

https://github.com/taikoxyz/taiko-mono/assets/160452538/294cf828-492b-474f-8c2f-ff7cdbe5946d

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by odavidjeff** [comment]
From your video, I can see swapping from WETH to ETH, not the other way around. Plus can you try using a Web3 Browser like MIses, I'm sure you should be able to complete the transaction.

**Comment by KorbinianK** [comment]
This seems to be a wallet issue on your end, not an issue with the swap. Just wrapped ETH on katla myself on Metamask mobile, works just fine.
