### ISSUE TITLE
Include prover address information in SGX proof.

### ISSUE THREAD

**Issue by hugo-blue** [taikoxyz/taiko-mono#15919]
### Describe the feature request

As we, ZKPool team, test the SGX prover in Taiko A6 testnet, we find that the current SGX proof lacks any information related to the prover's address, which could allow others to steal the proof.

### Describe alternatives you've considered

Include prover address information in SGX proof.

### Additional context

Additional context here.

**Comment by adaki2004** [comment]
> ### Describe the feature request
> 
> As we, ZKPool team, test the SGX prover in Taiko A6 testnet, we find that the current SGX proof lacks any information related to the prover's address, which could allow others to steal the proof.
> ### Describe alternatives you've considered
> 
> Include prover address information in SGX proof.
> ### Additional context
> 
> Additional context here.

Thanks Hugo, it is already fixed with the new version ! `prover` is incorporated in the hash to be signed.
