### ISSUE TITLE
Reset to Default Wallet Address for Recipient Address

### ISSUE THREAD

**Issue by shak58** [taikoxyz/taiko-mono#15925]
### Describe the feature request

To enhance the user experience in the Taiko Bridge UI, I propose the implementation of a "Reset" button in the recipient address modal. This feature would allow users to effortlessly revert the recipient address back to their default wallet address with a single click, rather than manually deleting the input or re-entering the default address.

### Describe alternatives you've considered

An alternative would be to keep the current functionality, where users must manually enter their default address to reset it. However, this is less user-friendly and can be cumbersome, particularly for users on mobile devices or those who transact frequently.

### Additional context

Presently, users need to manually clear the recipient address field and re-enter their sender address to reset it. 

![Clear Custom Address](https://github.com/taikoxyz/taiko-mono/assets/150069539/c0759f26-7447-4db5-b12c-2f0849a877f9)

**Comment by cryptoholder963** [comment]
very usufull
