### ISSUE TITLE
Users cannot change wallet on https://bridge.katla.taiko.xyz/

### ISSUE THREAD

**Issue by duykhangxz** [taikoxyz/taiko-mono#15920]
### Describe the feature request

When I first access to the website to mint HORSE token, I connected my Phantom wallet by accident, when I had to connect my Metamask wallet instead. Unfortunately, the pop-up keep showing up and there's no button to close it; therefore, I cannot disconnect it and change to my Metamask Wallet. 

I suggest that you guys can easily add the option "connect to another wallet" in the pop-up so that users like me can change to another wallet

![image](https://github.com/taikoxyz/taiko-mono/assets/160480611/984d0f1a-9eb8-4a1a-9de3-74cb6268ae9d)

### Describe alternatives you've considered

- Delete the web cookies so that I will
- Have to open the website on a different browser to connect to another wallet

### Additional context

Additional context here.

**Comment by consolexyz** [comment]
can i take on this ?
