### ISSUE TITLE
Taiko doc doesn't open on background when an external link is clicked

### ISSUE THREAD

**Issue by uwaifo18** [taikoxyz/taiko-mono#15938]
### Describe the bug

I was using the project developer doc for step's on how to deploy a smart contract on taiko, on my Android device, I tapped a link on the doc that was supposed to take me to remix , but instead of opening the link in a new tab or window, the doc itself closed and I lost my progress. I expected the doc to stay open in the background and the link to open in a new tab or window. This is very frustrating and inconvenient, as I have to reopen the doc by leaving the site which I am to make I tutorial on.

### Steps to reproduce

you might want to change the code to open it in a new tab or window instead. You can use the target attribute of the <a> tag to specify where to open the document. For example, <a href="document.pdf" target="_blank">Open document</a> will open the document in a new tab or window.

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Kolsdam** [comment]
I would like to work on this

**Comment by d1onys1us** [comment]
fixed https://github.com/taikoxyz/docs/pull/87
