### ISSUE TITLE
Slow and Failed transactions experienced by users on the Taiko Katla Testnet Network

### ISSUE THREAD

**Issue by Chidiebere2001** [taikoxyz/taiko-mono#15955]
### Describe the bug

There's a bug issue experienced by users (Including Myself) on the Taiko Katla Testnet Network resulting to failed and slow transactions experienced by users. Of recent, there have been influx of users complaining of failed and slow transactions on the Network.

Attached are images of some users complaining on the Discord server
![WhatsApp Image 2024-02-20 at 07 26 56](https://github.com/taikoxyz/taiko-mono/assets/90405296/b74347ca-ee88-40a0-9695-9f6430f269e1)
![WhatsApp Image 2024-02-20 at 07 38 39](https://github.com/taikoxyz/taiko-mono/assets/90405296/4f2d1ffe-a7bf-47b6-a19d-f07522217041)
![Uploading WhatsApp Image 2024-02-20 at 07.31.16.jpeg…]()
![Uploading WhatsApp Image 2024-02-20 at 07.31.16 (1).jpeg…]()

  

### Steps to reproduce

1. Identify and Reproduce the Bug:
    --- Understand the specific circumstances or conditions that trigger the slow transactions.
    --- Reproduce the issue in a controlled environment to isolate its root cause.

2. Monitor and Gather Data: 
    --- Implement monitoring tools to collect real-time data on transactions processing times, resources utilization and system performance.

3. Communicate Transparently to Community:
   ---  Keep users informed about the issue and assure them that Team is working on a resolution. This will keep them abreast.

4. Isolate and Rollback:
      --- Isolate the buggy code or feature causing the slowdown.
      --- Consider rolling back to a stable version of the software until a fix is ready.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
We are not responsible for the crypto rumble game. Reach out to their team please.

**Comment by Chidiebere2001** [comment]
> We are not responsible for the crypto rumble game. Reach out to their team please.

Look at the highlighted messages in the images. Those are users complaining of Slow transactions/Failed transactions in Taiko Katla Testnet. Not related to Crypto Rumble Games.
