### ISSUE TITLE
Delayed and Failed  Transactions on the Katla Testnet Network 

### ISSUE THREAD

**Issue by Chidiebere2001** [taikoxyz/taiko-mono#15960]
### Describe the bug

There's a bug issue experienced by users (Including Myself) on the Taiko Katla Testnet Network resulting to failed and slow transactions experienced by users. Of recent, there have been influx of users complaining of failed and slow transactions on the Network.
Attached are images of some users complaining on the Discord server with users complaint highlighted.
NB: This is not related to Crypto Rumble Game.

![IMG-20240220-WA0009](https://github.com/taikoxyz/taiko-mono/assets/90405296/bf1ab1fd-7de4-417c-bba9-6cf9ba8286c7)

![IMG-20240220-WA0012](https://github.com/taikoxyz/taiko-mono/assets/90405296/752f1da4-259b-4bdb-88b0-b42639390973)
![IMG-20240220-WA0010](https://github.com/taikoxyz/taiko-mono/assets/90405296/6cf98893-1d34-42a8-8eea-f9df978ffa59)

### Steps to reproduce

1. Understand the Bug Report:
   - Review the bug report or user complaints to understand the specific circumstances leading to transaction delays and failures.

2. Set Up a Testing Environment:
   - Create a controlled testing environment that mirrors the production environment as closely as possible.

 3. Identify the Version:
   - Identify the software version (e.g., blockchain node software, smart contracts) in which the bug was reported.

 4. Review Configuration:
   - Ensure that the configurations in your testing environment match those in the reported environment.

 5. Use Sample Data:
   - Create or use sample data that is representative of the data causing delays and failures.

 6. Prepare Test Cases:
   - Develop specific test cases that simulate the conditions triggering the bug. Consider different scenarios and edge cases.
   
 7.  Execute Test Cases:
   -  Execute the prepared test cases systematically, following the steps outlined in   each case.

8.   Monitor Logs:
    - Monitor logs, metrics, and any relevant debugging information during the test execution.
    -  Look for error messages, warnings, or unexpected behavior in the system logs.
        

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Last warning before getting banned. If you have actual transactions that are affected, post those. Not a bunch of Screenshots and chat-gpt generated text.
