### ISSUE TITLE
Requesting socials and whitepaper details

### ISSUE THREAD

**Issue by mortshack** [taikoxyz/taiko-mono#15975]
### Describe the feature request

De
![Screenshot_2024-02-21-18-01-26-42_d4b821f22c36211daa9077338f9854d0](https://github.com/taikoxyz/taiko-mono/assets/85753452/5354c687-0ee2-477f-bf97-0923a6b72f10)
scription of the feature request here under this section...
This would help many new users that are facing issues....:/

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Imohkings** [comment]
The interface is user friendly with a unique design. The loading time for the page is fast so it's convenient to save task time

**Comment by KorbinianK** [comment]
@mortshack we might add more links in a future version, right now it's not planned.

@Imohkings while we appreciate your feedback, please don't comment spam unless you want to get banned. Issues are meant for valuable discussion on a specific issue, feel free to share your thoughts on discord.
