### ISSUE TITLE
Stuck Transaction: ETH Faucet from Katla to Holesky Delayed for Over 48 Hours

### ISSUE THREAD

**Issue by Fazleiw** [taikoxyz/taiko-mono#15983]
### Describe the bug

It seems there's an issue with a transaction on Taiko's network that's stuck in the "processing" stage for longer than expected. Before Taiko's mainnet launch, it's crucial to address such issues to ensure smooth operations. The transaction link provided indicates that it's still marked as "processing," which isn't typical. This delay could be due to updates on the chain or network. It's important to investigate and resolve this promptly to prevent any potential impact on Taiko's functionality.

https://explorer.katla.taiko.xyz/tx/0xe9f8b1c6d094935a084a76b248b144d81fa5f0158d175d71f8b07115265f5c7c?tab=index

![Screenshot 2024-02-22 111911](https://github.com/taikoxyz/taiko-mono/assets/156914529/2cc2ac0f-3e20-41a3-b5a5-b7aa17e2ea3f)

before you ask, this is official bridging website

### Steps to reproduce

Here are the steps to reproduce
![Screenshot 2024-02-22 112100](https://github.com/taikoxyz/taiko-mono/assets/156914529/bf9c9a7e-0b8c-40a5-a688-afdc5bf37475)
 the issue:

Perform ten bridging transactions between Holesky and Katla.
During these transactions, ensure that five of them involve larger funds, such as 15 ETH.
Allow these transactions to enter the "processing" stage.
Despite waiting for more than 24 hours, you will not receive the ETH for these transactions.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by my5216** [comment]
too long..

**Comment by Fazleiw** [comment]
agree
