### ISSUE TITLE
Transaction stuck on bridge 

### ISSUE THREAD

**Issue by rameez1372** [taikoxyz/taiko-mono#15989]
### Describe the bug

Stuck transaction on swap bridge and add liquidity on katla testnet 

### Steps to reproduce

Please fix this transaction stuck issue

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Swap and bridge are two different dapps. Please reopen the issue and and add proper details such as tx hash etc.
