### ISSUE TITLE
Mobile not supported 

### ISSUE THREAD

**Issue by raju1372** [taikoxyz/taiko-mono#15988]
### Describe the bug

Swap does not working on mobile devices 

### Steps to reproduce

Please allow us to swap on mobile devices 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Swap works on mobile Metamask. Without any further information, this ticket will be closed. Please look up on how to report a bug properly.
