### ISSUE TITLE
Add support for other layer2 network bridge 

### ISSUE THREAD

**Issue by rameez1372** [taikoxyz/taiko-mono#15992]
### Describe the bug

Please add support for other layer2 network for bridge 

### Steps to reproduce

Great project 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Reported for spam now. Please don't open issues when you have nothing worth contributing.

**Comment by rameez1372** [comment]
No more spam sorry sir
