### ISSUE TITLE
POAP Utility and Taiko Galxe Leaderbord Ranking Tiers.

### ISSUE THREAD

**Issue by pr1museth** [taikoxyz/taiko-mono#15994]
### Describe the feature request

**Good Morning my lovely Taiko! 💗**

I think team need to find solution for POAPs because a lot of questions from the early birds and it would be nice to implement the Tiers system on Taiko Galxe leaderbord to reward early ones and most dedicative users that have started contribution since the beginning. 

![Taiko](https://github.com/taikoxyz/taiko-mono/assets/121545087/63611c79-bd61-4d50-b566-1cfaace816b3)

For my opinion Taiko team can make the NFTs on Taiko Alpha-6 Testnet and transfer it to eligible ~100k for POAP wallets. 
At the same time lauch the campaign on Galxe that would give 1000-2000 points for NFT/POAP holders, it'd be the great bonus for early contributors. 

![poap](https://github.com/taikoxyz/taiko-mono/assets/121545087/d361ab9f-1663-4b51-bd78-fecc6dfc69fa)

After the finishing all quests on Galxe we can implement the **"Taiko Rollup Tiers"** that would give the special position depending on the rank on the Galxe leaderboard. And here's some examples of the tiers:

- _Tier 1. Taiko Master [1-1000 leaderboard]_ 
- _Tier 2. Taiko Captain [1001-10000 leaderboard]_
- _Tier 3. Taiko Star [10001- 50000 leaderboard]_
- _Tier 4. Taiko Novice [50001- ∞ leaderboard >2500 points atleast]_

![tiers](https://github.com/taikoxyz/taiko-mono/assets/121545087/ce2bca2e-88ca-4ec5-b9a7-21de35dbc847)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Etsoy** [comment]
its ok)

**Comment by KorbinianK** [comment]
There is plenty of evidence of who did what, since we are using a blockchain after all. So creating more POAPs just to make it visual will currently take away from developer resources focusing on more important tasks. But rest assure, we have exciting things coming up this year to keep people engaded!
