### ISSUE TITLE
Please allow us to collect poap

### ISSUE THREAD

**Issue by rameez1372** [taikoxyz/taiko-mono#15993]
### Describe the feature request

I want to know how to claim alpha testnet 1 participation poap still waiting for link

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
https://www.gitpoap.io/gp/686
https://www.gitpoap.io/gp/893
