### ISSUE TITLE
Add upgrade to node

### ISSUE THREAD

**Issue by rameez1372** [taikoxyz/taiko-mono#15991]
### Describe the feature request

I want to suggest team on upgrading node sometimes node doesn't ping or working it get some error 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to reopen the issue in the correct repository and provide proper details on the errors, otherwise it is considered spam
