### ISSUE TITLE
Getting HOLESKY faucet is quite hard

### ISSUE THREAD

**Issue by olaaa55** [taikoxyz/taiko-mono#16000]
### Describe the bug

I have been unable to access the Holesky faucet since the start of the testnet  which has slowed down my testing till date. I expected that the taiko holesky faucet should be easy to access but that has not happened and i didn't want to do wallet to wallet transfer.

### Steps to reproduce

1. Create a Holesky faucet link exclusive to Taiko users.
2. faucet that can dispense as much holesky as possible
3. Easy to access link to  faucet
4. A faucet drip that can accommodate as much users as possible

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
We are not providing a holesky faucet
