### ISSUE TITLE
Estimated Time Frame For  (Bridge) Transaction on website 

### ISSUE THREAD

**Issue by saucekey** [taikoxyz/taiko-mono#16015]
### Describe the feature request

Transactions should be for a given time period. And the problem is that there is no estimated time frame for bridge transaction . Feature such as an estimated time frame for transactions on the taiko website  be it for native bridge should entail the amount of time that a transaction will take, which can be identified and used by users. Primary or immediate time frames are actionable right now and are of interest to day-users and high-frequency users. Below is an attachment

![taiko attachment](https://github.com/taikoxyz/taiko-mono/assets/130064048/deaa74c9-6c57-4dba-a870-c38638c65f4d)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Vtalike** [comment]
> ### Describe the feature request
> 
> Transactions should be for a given time period. And the problem is that there is no estimated time frame for bridge transaction . Feature such as an estimated time frame for transactions on the taiko website  be it for native bridge should entail the amount of time that a transaction will take, which can be identified and used by users. Primary or immediate time frames are actionable right now and are of interest to day-users and high-frequency users. Below is a pictorial instance.
> 
> ![IMG_5683](https://github.com/taikoxyz/taiko-mono/assets/130064048/63663ed8-ba8b-4237-b5aa-d3dc74a9e147)
> 
> 
> 
> ### Spam policy
> 
> - [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Viktor110** [comment]
> ### Describe the feature request
> 
> Transactions should be for a given time period. And the problem is that there is no estimated time frame for bridge transaction . Feature such as an estimated time frame for transactions on the taiko website  be it for native bridge should entail the amount of time that a transaction will take, which can be identified and used by users. Primary or immediate time frames are actionable right now and are of interest to day-users and high-frequency users. Below is a pictorial instance.
> 
> ![IMG_5683](https://github.com/taikoxyz/taiko-mono/assets/130064048/63663ed8-ba8b-4237-b5aa-d3dc74a9e147)
> 
> 
> 
> ### Spam policy
> 
> - [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@Viktor110 @Vtalike reported for spam. Enjoy your account bans. 🫡
