### ISSUE TITLE
Blockscout smart-contract verification error

### ISSUE THREAD

**Issue by unchase** [taikoxyz/taiko-mono#16010]
### Describe the bug

The following error occurs when attempting to verify upgradable proxy smart-contract using command:

```
npx hardhat verify --network taiko_katla 0x46874eDd92d5A33216fe2e151759Ead76Ff43747
```
![image](https://github.com/taikoxyz/taiko-mono/assets/29679226/c592522e-3dba-46a3-bd1d-218cf6e77b20)

> hardhat-verify found one or more errors during the verification process:
>
> Etherscan:
> Etherscan API call failed with status 400, response: {"message":"Unknown action","result":null,"status":"0"}

### Steps to reproduce

1. Create a simple upgradable proxy smart-contract
2. Create a `hardhat.config.js` file:

```js
const { task } = require("hardhat/config");

require("dotenv").config();

require("@nomicfoundation/hardhat-toolbox");
require("@nomicfoundation/hardhat-verify");
require("@openzeppelin/hardhat-upgrades");

task("deploy", "Deploy contract").setAction(async () => {
  const deploy = require("./scripts/deploy");
  await deploy();
});

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  defaultNetwork: "taiko_katla",
  solidity: {
    version: "0.8.21",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
      viaIR: true,
    },
  },
  networks: {
    taiko_katla: {
      chainId: 167008,
      url: "https://rpc.katla.taiko.xyz",
      accounts: [process.env.PRIVATE_KEY],
      gasMultiplier: 1,
    },
  },
  etherscan: {
    apiKey: {
      taiko_katla: process.env.TAIKO_API_KEY,
    },
    customChains: [
      {
        network: "taiko_katla",
        chainId: 167008,
        urls: {
          apiURL: "https://blockscoutapi.katla.taiko.xyz/api",
          browserURL: "https://explorer.katla.taiko.xyz",
        },
      },
    ],
  },
  sourcify: {
    enabled: false
  }
};

```

P.S. I have tried specifying different options in **customChains** in **apiURL**: `https://explorer.katla.taiko.xyz/api`, `https://explorer.katla.taiko.xyz/api` (as specified [here](https://blockscoutapi.katla.taiko.xyz/api-docs)), but they return other errors:

![image](https://github.com/taikoxyz/taiko-mono/assets/29679226/eda838b3-77ad-4c6b-992c-277a097a359d)
![image](https://github.com/taikoxyz/taiko-mono/assets/29679226/1f9e7aa3-9c8e-49cb-86b4-0f067a3c1af2)

P.P.S. There is no solution to this problem for hardhat in the [documentation](https://docs.taiko.xyz/guides/verify-a-contract/) either.

3. Publish the smart-contract with command `npx hardhat deploy`
4. Run the verification command `npx hardhat verify --network taiko_katla 0x46874eDd92d5A33216fe2e151759Ead76Ff43747`

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@unchase We are aware of several issues with our current explorer, especially regarding contract verification.

But stay tuned, **something is coming very soon** ;) 

For now we will not update blockscout unfortunately
