### ISSUE TITLE
Need For Mintable Token in Katla Faucet

### ISSUE THREAD

**Issue by SuccessAyo** [taikoxyz/taiko-mono#16022]
### Describe the feature request

The HOSRE token is the only option on both Katla testnet and Holesky testnet faucet as seen in https://bridge.katla.taiko.xyz/faucet/, but it is not mintable on the Katla testnet. 

Proposed solution:
Provision of a mintable token on Katla testnet faucet on the website.
![Screenshot (77)](https://github.com/taikoxyz/taiko-mono/assets/85240438/d4642a6f-b539-4a4e-94a5-b26dc9a242c9)
![Screenshot (78)](https://github.com/taikoxyz/taiko-mono/assets/85240438/273343cc-39eb-461b-94e1-1a9ab3672be4)

 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Not a bug, HORSE is only mintable on Holesky.

**Comment by SuccessAyo** [comment]
Beautiful! Now I totally get it, I can see what needs a bit of correction.
