### ISSUE TITLE
Please document the command to assist with STN installation in the Docs

### ISSUE THREAD

**Issue by zen21090** [taikoxyz/taiko-mono#16034]
### Describe the feature request

https://docs.taiko.xyz/guides/run-a-taiko-node/
I have confirmed that many individuals are encountering library errors in the '2. Install a Taiko node' section.
In most cases, the issue can be resolved with the following command, so documenting it in the Docs can assist beginners.
```
sudo apt-get update
sudo apt-get install build-essential
```

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by d1onys1us** [comment]
thank you, i opened the issue in the appropriate repo (https://github.com/d1onys1us/stn/issues/154) so i will close it here. this is because cargo tries to build the binary.

i will change the default installation method, add a cargo binary install, and add this step for linux users. 🥂
