### ISSUE TITLE
Request for more details in "Recieve tokens" guide in docs

### ISSUE THREAD

**Issue by SuccessAyo** [taikoxyz/taiko-mono#16050]
### Describe the feature request

Using the official guide https://docs.taiko.xyz/guides/receive-tokens/, the fact that the dummy token (HORSE) can only be requested on Holesky testnet is not but should be documented, please I suggest that it be documented for better clarity. 
Also kindly document it that HORSE tokens can only be minted once on the holesky testnet and indicate the amount of tokens that will be received e.g "user will receive 50 HORSE testnet tokens from the faucet". This will aid better clarity and less questions about faucet on the community platform. Thank you always ❤️. 
![Screenshot_20240224_101305_Chrome](https://github.com/taikoxyz/taiko-mono/assets/85240438/64b7a179-3b45-4e1a-b9ff-8de224739c1a)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
I don't think that amount of information is necessary or helpful. You get direct feedback on the faucet page and the amount doesn't really matter to be honest, as it has no worth.
