### ISSUE TITLE
Bridge to Katla for Holesky

### ISSUE THREAD

**Issue by invictusbtc** [taikoxyz/taiko-mono#16065]
### Describe the bug

Information for reflection:

Two transaction is delayed. 1 - It has been 1 month. 2 - It has been 5 days.
IT'S A BAG.!!!

Explorer 1 (81 ETH) - https://explorer.katla.taiko.xyz/tx/0x544ee36142e07c7f7d0d79c66932cf486525c2e8ec36604da3a52ec487182617
Explorer 2 (790 ETH) - https://explorer.katla.taiko.xyz/tx/0x7f75d2a4f4f9f5319d22064724c4efa02d19be8c0fa9f5bf188a01f112de524f

![2024-02-25_17-27-50](https://github.com/taikoxyz/taiko-mono/assets/108835149/ea1899ca-f156-4805-9a22-06f451543a10)

**Comment by cornrol** [comment]
It should be Network glitch due to inflow of transactions

**Comment by invictusbtc** [comment]
@cornrol maybe, but that doesn't change the fact that my ETH is stuck somewhere in the chain :) 
I've been waiting for one of the transactions to complete for over a month, and I've been waiting for the second transaction for five days now :)

**Comment by Storm2100** [comment]
made same transaction by bridging from Holesky to Katla and also
back from katla to holesky, took long but transaction went through, All transaction showed success on the explorer
Check your processes again

**Comment by Nishakjesse** [comment]
the inflow volume  is probably the issue here,strange but the contract has been exected though

**Comment by cyberhorsey** [comment]
> @cornrol maybe, but that doesn't change the fact that my ETH is stuck somewhere in the chain :) I've been waiting for one of the transactions to complete for over a month, and I've been waiting for the second transaction for five days now :)

I'll take a look today.

**Comment by cyberhorsey** [comment]
https://holesky.etherscan.io/tx/0x5722ce61856a9ef417bcd3a14958a4cf1bc68aced4f78ff3ec812bba96a0edbc

This is the transaction on Holesky for your first transaction of 81 ETH, with the exact fee of `0.0010076517954` being paid, is it not? I believe the "processable" is just a UI bug here.  It was processed 24 days ago.
    
I will look into your other transaction later today.
