### ISSUE TITLE
Connect wallet to tko.chat

### ISSUE THREAD

**Issue by Gitgit2501** [taikoxyz/taiko-mono#16073]
### Describe the bug

Metamask wallet will not connect to tko.chat social media site. Loops round telling me to disconnect and refresh before failing to connect again. Have tried hard refresh and cleared cache. COnnect is fine on other Taiko dApps.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
They their own repository and is not directly associated with Taiko. Please contact them directly.
