### ISSUE TITLE
NFT Image Not showing

### ISSUE THREAD

**Issue by Leighzhl** [taikoxyz/taiko-mono#16087]
### Describe the bug

Description of the bug here.

NFT image for bridging is not showing.

![Screenshot 2024-02-27 092728](https://github.com/taikoxyz/taiko-mono/assets/72096376/a061632c-a316-45b3-bb69-8ed35056fa66)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Please provide more details such as the (verified) NFT contract and expected image url?

**Comment by mu3io1** [comment]
Network problem

**Comment by Leighzhl** [comment]
Oh, I didn't know that you have to verify the contract first in order to see it. I'm sorry.

**Comment by KorbinianK** [comment]
@Leighzhl I saw it's the crypto rumble NFTs. It seems they do not follow the expected standard for metadata but without seeing how code, we don't know for sure.
Feel free to reach out to them and inquire more info on their metadata standard.

**Comment by KorbinianK** [comment]
Stale
