### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by nas333** [taikoxyz/taiko-mono#16084]
### Describe the bug

There is a typo on guild . see attached 
![typo guild](https://github.com/taikoxyz/taiko-mono/assets/119011893/76bfd073-1f1b-4260-a3e0-55fb6b55cd57)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by samui68400** [comment]
twitter API is not working I guess

**Comment by KorbinianK** [comment]
We are not responsible for the Guild codebase.

**Comment by nas333** [comment]
> We are not responsible for the Guild codebase.

i though it would be good to let you guys know and whilst you are not responsible this definitely looks bad because taiko is involved in this in an indirect way. If its  all good for you , then fine by me
