### ISSUE TITLE
Taiko Katla Testnet 24H Delay

### ISSUE THREAD

**Issue by AbduAlexander** [taikoxyz/taiko-mono#16083]
### Describe the feature request

Taiko Katla Testnet need to speed up the whole bridging process on L1 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
This is a security feature by design. However by the time of mainnet this delay may be different.
