### ISSUE TITLE
A payment like type of dapp using zk technology

### ISSUE THREAD

**Issue by Badlordazekage** [taikoxyz/taiko-mono#16082]
### Describe the feature request

There is this project, zebec. What it does is that it offers real time payment of employees by employers per hour rather than waiting till the end of the month thus one gets paid for the exact time worked for. It is a feature I think would work best with zk technology and i suggest if possible such a feature could be incorporated into the taiko ecosystem would give an added real world-crypto utility. You can check out the aforementioned project for more information and see if it would be something you may want to incorporate into taiko.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to let them know to apply to our ecosystem.
