### ISSUE TITLE
Reset button for Wallet Address Address ?

### ISSUE THREAD

**Issue by coinoneri** [taikoxyz/taiko-mono#16086]
### Describe the feature request

**Describe the feature request**
To enhance the user experience in the Taiko Bridge UI, I propose the implementation of a "Reset" button in the recipient address modal. This feature would allow users to effortlessly revert the recipient address back to their default wallet address with a single click, rather than manually deleting the input or re-entering the default address.

**Describe alternatives you've considered**
An alternative would be to keep the current functionality, where users must manually enter their default address to reset it. However, this is less user-friendly and can be cumbersome, particularly for users on mobile devices or those who transact frequently.

**Additional context**
Presently, users need to manually clear the recipient address field and re-enter their sender address to reset it.

![Ekran görüntüsü 2024-02-27 042620](https://github.com/taikoxyz/taiko-mono/assets/149978211/d348ceaa-1038-432b-b00f-2890304e3f59)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
duplicate #15925
