### ISSUE TITLE
Nft bridging on Taiko Bridge.

### ISSUE THREAD

**Issue by Areus11** [taikoxyz/taiko-mono#16089]
### Describe the bug

nft bridging takes more than usual, in some cases took more than 24 hours.

### Steps to reproduce

Suggested solutions:

•Enable parallel processing of transactions to handle multiple transfers simultaneously, increasing overall throughput and reducing transaction times.
•Implement off-chain solutions like state channels or sidechains to handle transactions off the main blockchain, reducing congestion and speeding up the bridging process.
•Continuously test and optimize the bridging process to identify bottlenecks, address performance issues, and enhance overall speed and efficiency.
•Implement caching mechanisms to store frequently accessed data and reduce the need for repeated queries, speeding up transaction processing.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Delays depend on the load on the network. We are looking into some reports
