### ISSUE TITLE
Add estimation time arrive when bridging

### ISSUE THREAD

**Issue by Sucimaru** [taikoxyz/taiko-mono#16088]
### Describe the feature request

Please add an estimation time when the token will arrive on other chain while bridging

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by saucekey** [comment]
kindly check what the feature  requested few days ago

**Comment by Sucimaru** [comment]
> kindly check what the feature requested few days ago

My bad, sorry
