### ISSUE TITLE
Dev Competiton 

### ISSUE THREAD

**Issue by smolmike** [taikoxyz/taiko-mono#16091]
### Describe the feature request

Due to the recent success of Blast L2 I think a Taiko dev comp would be a really great way to bring developers over to Taiko. over 3k teams entered over 1k projects in less then a few months. this type of influx of dev talent can quicky foster a community and builders. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by vanhoan88** [comment]
thanks sir

**Comment by KorbinianK** [comment]
https://code4rena.com/audits/2024-03-taiko
