### ISSUE TITLE
faucet on taiko.katla.bridge is just work for once.

### ISSUE THREAD

**Issue by thexcorsim** [taikoxyz/taiko-mono#16094]
### Describe the feature request

I think it would be more exciting if the faucet on taiko.katla.bridge is work more than once, it will make user more easy to find horse token rather than to find in another site for another faucet, add more quantity for the faucet.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
50 Horse are plenty.

**Comment by thexcorsim** [comment]
Thanks for attention.

Pada Sel, 27 Feb 2024 15:54, Korbinian ***@***.***> menulis:
