### ISSUE TITLE
Crypto Rumble - Zypher Game

### ISSUE THREAD

**Issue by officialsirvic** [taikoxyz/taiko-mono#16104]
### Describe the bug

While playing the crypto rumble zypher game using the AI assistance, it gets stuck at some point and has no more moves until assisted manually. I expect that the AI assistance should know the appropriate moves to make to avoid getting stuck.

Also, the game is a bit sluggish in loading and wallet pop-up.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by snarl91** [comment]
Yes I encountered the same a few times and the game lags during loading and for Metamask snaps.

**Comment by KorbinianK** [comment]
Please contact crypto rumble. We are not responsible for their game

**Comment by officialsirvic** [comment]
> Please contact crypto rumble. We are not responsible for their game

Okay, just thought I should raise the issue.
