### ISSUE TITLE
Integrate Polaris EVM Berachain to Taiko L2

### ISSUE THREAD

**Issue by AnangSyah321** [taikoxyz/taiko-mono#16102]
### Describe the feature request

I think it will be grate to integrate the Polaris EVM Berachain to Taiko, and the Berachain still in testnet to. Maybe can make some feature with the team to enable the bridge or swap from Taiko Katla to Berachain Artio.
https://github.com/AnangSyah321/Polaris-Berachain

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to apply properly if you are part of the team.
