### ISSUE TITLE
Would be great if we can see more testnet opportunities on the site including perps and all

### ISSUE THREAD

**Issue by Avinash26-sinner** [taikoxyz/taiko-mono#16100]
### Describe the feature request

Description of the feature request here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Sheunzy** [comment]
Yes...more testnet task and the bridging to katla or holesky seems little lagging please

**Comment by VinhSiuCiu** [comment]
Great ! The project runs very smoothly and is easy to use. Congratulations on the successful Project

**Comment by KorbinianK** [comment]
Stop spamming if you want to keep your accounts. Use discord for discussions.
