### ISSUE TITLE
GitPOAP for 2024

### ISSUE THREAD

**Issue by helpmeyou** [taikoxyz/taiko-mono#16114]
### Describe the feature request

Hey, i want to request another POAP for 2024. There are 2 POAP's already for 2022 and 2023. Why should we not have one more for 2024? 

Regardsly.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
It's in the works.
