### ISSUE TITLE
Transaction speed

### ISSUE THREAD

**Issue by Onoshab** [taikoxyz/taiko-mono#16116]
### Describe the feature request

We can make transaction faster by writing a code that allows anyone bridging higher amount experience faster speed while others with lower amount can follow .

Also doing a refund can help secure more transaction on taiko as Eth gas is always on the high side. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by doglex1** [comment]
transaction time was slow when I made a transaction from Taiko Kalta to Holesky

**Comment by thekera404** [comment]
transaction time was slow when I made a transaction from Taiko Kalta to Holesky

**Comment by saucekey** [comment]
well what i would like to is that a time frame for transaction should be added, so we can get to know the amount of time each transaction is going to take

**Comment by ApexApe82** [comment]
It took me a few days to bridge the Horse token from Holesky to Taiko. It kept giving me errors in the transaction

**Comment by bulentgym** [comment]
we don't know code writing

**Comment by swiftereum** [comment]
bridging took a longer time and reducing the time involved would be of help for users

**Comment by zlb0907** [comment]
bridging took a longer time

**Comment by Kalomes** [comment]
use higher gas and transactions will be faster. For example i use 155 and bridge takes minute or two
