### ISSUE TITLE
delayed transaction

### ISSUE THREAD

**Issue by JekSepar0** [taikoxyz/taiko-mono#16119]
### Describe the bug

bridge is delayed, The large number of transactions piled up on the network causes the bridge process to take a long time

### Steps to reproduce

use vpn if it doesn't work, it might speed up the transaction

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
VPN certainly does not speed up the transactions lol

**Comment by JekSepar0** [comment]
> VPN certainly does not speed up the transactions lol

helps speed up transaction approval
