### ISSUE TITLE
NFT Bridging from Katla to Holesky does not work.

### ISSUE THREAD

**Issue by Aste75** [taikoxyz/taiko-mono#16113]
### Describe the bug

Appoving works then Bridging does not. It seems to go through but after a little time an message error pops up and the transaction fails.

btw I managed to bridge ntf from Holesdky to Katla.  

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@Aste75 Can you share your wallet address and the error you are getting?

**Comment by seclib** [comment]
Je pense que comme c'est en testnet et que c'est super farmer en ce moment... Et bien y a du ralentissement.

**Comment by Aste75** [comment]
> @Aste75 Can you share your wallet address and the error you are getting?

I was using MM and switched to Rabby in order to see if I see the same "Unkwown Error" that pops up. 

It bridged the NFT smoothly. No error NOTHING !

I don't know why it does not work properly with MM. Clean cache but still unsucessful.  I truly believed it was an issue with the Testnet but it is NOT.

That's all I can report. ty
