### ISSUE TITLE
Transaction record

### ISSUE THREAD

**Issue by adachan1111** [taikoxyz/taiko-mono#16125]
### Describe the feature request

I suggest to have a transaction record to download from taiko website as so many people doesnt how to check thru website. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Your source of truth will be the explorer or wallet.
