### ISSUE TITLE
Add Taiko to Layerzero And LOG-X 

### ISSUE THREAD

**Issue by Armaniblaq500** [taikoxyz/taiko-mono#16123]
### Describe the feature request

I really want to see a collab between Taiko and layerzero, would be thrilling to see a collab with log-x cause log-x trading is smooth and not hard to understand, I can choose to make spot or futures trade easily from LOG-X , Imagine having to interact with taiko mainnet contracts and making blockchain interactions easily on log-x and easily switch to another chain. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to reach out to them
