### ISSUE TITLE
can't mint token horse

### ISSUE THREAD

**Issue by suripm33** [taikoxyz/taiko-mono#16121]
### Describe the bug

can't mint token horse. i just ones mint since a feb month ago. why cant mint again until now?

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
You can only mint 50 HORSE tokens once.
