### ISSUE TITLE
marketing suggestion 

### ISSUE THREAD

**Issue by junkawaa** [taikoxyz/taiko-mono#16127]
### Describe the feature request

Taiko is the same name from the game of japan taiko drums, we need to attract such game people to use our chain.
it is a small market but we can explore Japan market. They are much acceptable crypto in asia so far. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Guess why one of our emojis is the drum ;) We are well aware of this! Thanks for your suggestion though.
