### ISSUE TITLE
NFT bridging from Kalta to Holesky

### ISSUE THREAD

**Issue by kaissoft** [taikoxyz/taiko-mono#16135]
### Describe the bug

improve the transaction time of nft bridging 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by kaissoft** [comment]
lets go taiko

**Comment by KorbinianK** [comment]
Reported for spamming
