### ISSUE TITLE
Blockchain Education 

### ISSUE THREAD

**Issue by Hermxeeh** [taikoxyz/taiko-mono#16133]
### Describe the feature request

What are blockchain bridges?

Blockchain Bridge, also known as network bridges or cross-chain bridges, are a tool designed to solve the challenge of interoperability between blockchains. Bridges have become a necessary component of the blockchain industry because, as it stands, blockchains operate in silos and cannot communicate with one another.

For example, users cannot use bitcoin ([BTC](https://www.coindesk.com/price/bitcoin/)) on the Ethereum blockchain or ether ([ETH](https://www.coindesk.com/price/ethereum/)) on the Bitcoin blockchain. So if one user (let’s call him Billy) who holds all his funds in BTC wants to pay another user (let’s call her Ethel) for an item but Ethel only accepts ETH, Billy hits a wall. He can’t send BTC directly to Ethel. He can take extra steps to buy ETH or trade a portion of his BTC for ETH, but BTC cannot be sent directly to Ethel. This can be seen as a major disadvantage in comparison to fiat currencies and credit cards, which can be used across several providers.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Thank you.

**Comment by Zuwa181** [comment]
Thanks you sir
