### ISSUE TITLE
Add Taiko to Layer3 Quest

### ISSUE THREAD

**Issue by olaideabimbola** [taikoxyz/taiko-mono#16132]
### Describe the feature request

Include Taiko in the Layer3 quest lineup.
Layer3, is a rising website that can hosts graphical, pictorial, and educational quests aimed at enhancing users' comprehension of a project. Adding Taiko to this will boost Taiko visibility and help users to understand more about the project.

Website: https://layer3.xyz/quests

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to either contact the team or if you are part of the team, formulate a proper application.
