### ISSUE TITLE
GAS FEE TRANSPARENCY AND ADJUSTMENT

### ISSUE THREAD

**Issue by SSILVQH** [taikoxyz/taiko-mono#16136]
### Describe the feature request

On the swap network (https://swap.katla.taiko.xyz/#/swap?chain=taiko-katla), I think there should be an innovation where users/investors can see their gas fee amount about to be used before clicking on the swap button and so there can be a need for adjustments to suite the users and to know the exact amount of gas fee to be kept in our balances to avoid transaction error or transaction failed. Thank you this is my contribution to the incredible taiko ecosystem .

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by SSILVQH** [comment]
I would be happy if this is consider as team is tremendously doing a great job kudos.

**Comment by anas777-dev** [comment]
Biaya gas terlalu mahal

**Comment by KorbinianK** [comment]
It's the uniswap interface. Feel free to suggest that to them. Currently not planned to change anything reg. functionality

**Comment by SSILVQH** [comment]
nice !
