### ISSUE TITLE
Relayer Withdraw option

### ISSUE THREAD

**Issue by olaideabimbola** [taikoxyz/taiko-mono#16131]
### Describe the feature request

Relayers will be an anonymous nodes that can perform transactions on user's behalf with extra security. This can be helpful during a bridging and withdrawing process.

In the withdrawal process, there will be an on/off switch feature which is the Relayer, which will act as anonymous nodes executing transactions on your behalf to enhance security.

For example when a user decides to withdraw fund to a new wallet (and the wallet has a zero balance to cover gas fee), the Relayer can handle the transaction for the user. It will only covers the gas fees but also retains an equivalent amount from user's withdrawn assets.

Essentially, the Relayer takes care of the transaction, including gas fee coverage, while withholding an equivalent token value if a user is transferring to a new wallet address without native gas tokens to cover fees.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Relayers are already in place and can claim for users if the claim is profitable.
