### ISSUE TITLE
Feature Enhancement: Integrate ENS Support

### ISSUE THREAD

**Issue by osiris0007** [taikoxyz/taiko-mono#16140]
### Describe the feature request

Since taiko is aiming to scale Ethereum in a manner that emulates it as closely as possible, technologically and ideologically, i believe it would an amazing idea to integrate one of Ethereum’s most successful features: ENS domains. 

Problem Statement:
The Ethereum Name Service (ENS) simplifies the process of interacting with Ethereum addresses by allowing users to associate human-readable names with their wallet addresses.
Integrating ENS support aligns very well with taiko’s vision of emulating Ethereum as closely as possible with a feature that will enhance user experience and adoption at the same time. 
Proposal:
Add native ENS resolution capabilities to Taiko.
Users can interact with ENS names directly within taiko’s ecosystem.
Implement features like ENS name lookup, address resolution, and reverse resolution.
Benefits:
Seamless interaction with ENS names.
Ease of access and enhanced user experience.
Aligns with Ethereum’s ecosystem.
Enhanced adoption because of the high popularity ,adoption and integration of ENS domains within Ethereum’s ecosystem.
Implementation Steps:
Research existing ENS libraries or APIs. 
Integrate ENS resolution into Taiko’s functionality.
Lookup the possibility of introducing ENS subdomains ( ex : osiris.tko.ens) as main domain name on the taiko network by collaborating with ENS ( similar to what Uniswap did recently and brought significant attention to their wallet and dapp) 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by zlb0907** [comment]
cool
