### ISSUE TITLE
Integrate into Rabby wallet

### ISSUE THREAD

**Issue by Hecksflakes** [taikoxyz/taiko-mono#16141]
### Describe the feature request

Basically to have Taiko testnet network and eventually the mainnet  integrated into Rabby wallet.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by d1onys1us** [comment]
this should be opened in rabby, not here.
