### ISSUE TITLE
Adding transaction Timer for Users

### ISSUE THREAD

**Issue by Abasetop** [taikoxyz/taiko-mono#16159]
### Describe the feature request

Since Taiko is scaling Ethereum, making users feel a better user experience is one of the main objectives. So I'll recommend adding a transaction Timer for each transaction so users get to know when the transaction is completing.

That way users will like it more and also feel relaxed.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by saucekey** [comment]
pls do note that this feature has been requested already
