### ISSUE TITLE
Error encountered while trying to Bridge NFT

### ISSUE THREAD

**Issue by Abasetop** [taikoxyz/taiko-mono#16158]
### Describe the bug

First of all, I'll say a big Thanks for the awesome user experience.

While trying to Bridge NFT from Katla to Holesky Network, I encountered an error that made the transaction unsuccessful and I kept trying several times but same issue.

I've attached a screenshot of the error message at the top right corner.

![Screenshot_2024-02-28-05-10-07-823_site mises browser](https://github.com/taikoxyz/taiko-mono/assets/53538642/2f2ecb5a-866d-4022-a8d8-782288ab5c0d)

### Steps to reproduce

N/A

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Abasetop** [comment]
> have you check wallet account [explorer katla](https://explorer.katla.taiko.xyz/address)

Yes, the wallet was connected successfully

**Comment by KorbinianK** [comment]
@Abasetop please provide your wallet and nft contract addresses. 

Can you open the browser dev console (F12 on chrome) and copy the the error from there?

**Comment by slashyanyan** [comment]
您可以打开浏览器开发控制台（chrome 上的 F12）并从那里复制错误吗？
