### ISSUE TITLE
Taiko Bridge

### ISSUE THREAD

**Issue by HighMarcus** [taikoxyz/taiko-mono#16169]
### Describe the bug

I noticed the tokens don't show the balance we hold until after so many refreshs

### Steps to reproduce

Probably a nice upgrade on the website will fix it

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by rmemacula** [comment]
Me too. Its buggy

**Comment by Yegola** [comment]
Me too, is is very buggy

**Comment by KorbinianK** [comment]
Please re-open this issue when you can provide proper details, screenshots etc. Without that there is no way of knowing what you mean, sorry.
