### ISSUE TITLE
Adding time frame of bridging

### ISSUE THREAD

**Issue by Boamahcyrus** [taikoxyz/taiko-mono#16179]
### Describe the feature request

I suggest that time frame for bridging token should be indicates for users to see before we start it. It helps users to see what is expected before we enter to bridge. Like what is shown in the document below
![Screenshot_20240228_234053_Gallery](https://github.com/taikoxyz/taiko-mono/assets/79230363/56e5066b-b5b9-431e-9045-9f0db9823071)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Duplicate
