### ISSUE TITLE
Price feeds swap V3

### ISSUE THREAD

**Issue by Lenoons** [taikoxyz/taiko-mono#16175]
### Describe the bug

The price feed been for some trading pair on Taiko tesnet are not accurate as the TTKOK USDC or ETH USDC
Could be oracle problem. I dont really know just wanted the team knows if it's normal or not 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Probably due to low liquidity. Wrong repo and low prion right now.
