### ISSUE TITLE
Issue to obtain the test token

### ISSUE THREAD

**Issue by cathychann1113** [taikoxyz/taiko-mono#16173]
### Describe the feature request

I have suggestion that use another test token, as so many contributor they dont obtain the token for testing, etc. 
the best way is to have another type token. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by rmemacula** [comment]
I agree

**Comment by O-k-i-k-i** [comment]
true

**Comment by KorbinianK** [comment]
Thousands of users are doing it successfully. So no.
