### ISSUE TITLE
Integrating Taiko in chainIDE and Witnet Oracle

### ISSUE THREAD

**Issue by Padom2020** [taikoxyz/taiko-mono#16171]
### Describe the feature request

This is to request Taiko be integrated into ChainIDE, a multichain IDE that can enable me, as a developer, to easily deploy contracts, verify them, and interact with them. I can assist in kickstarting the process by discussing it with the team behind ChainIDE, as I personally know some people who work there. Also, I wanted a price feed for my project, which I am working on deploying on Taiko. Since I am already using Witnet Oracle, I can personally facilitate fast integration on Witnet if given the approval to proceed.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Fee free to contact them to integrate taiko, not the other way around.
