### ISSUE TITLE
Issue with Network Transition Modal When Connecting Wallet

### ISSUE THREAD

**Issue by otaviobraaga** [taikoxyz/taiko-mono#16172]
### Describe the bug

**Issue with Network Transition Modal When Connecting Wallet**

Description:
When attempting to connect the wallet using Taiko UI, I observed an issue related to the network transition modal. The bug prevents automatic switching to the Holesky or Katla networks. I conducted tests with the BSC and ETHEREUM networks, and encountered a "Switch Declined" error. Additionally, the wallet does not even open to allow manual switching.

Typically, network switching is only possible when manually registered on the provider. However, this approach may be insecure for less experienced users. I would recommend automating the network registration directly within the Taiko UI interface, making the process safer and more user-friendly for all users.

**I assume the expected result is :**
The network transition modal should allow automatic switching from current network to the Holesky or Katla networks when connecting the wallet. Additionally, the wallet should open normally to allow manual switching if necessary.

Environment tested:

Platform: [Windows 11 23H2]
Browser: [Brave v 1.63.162, Edge v122.0.2365.52 ]

The issue only occurs when manually registered on the provider, which can be unsafe for inexperienced users. Automating the network registration within the Taiko UI interface would be advisable.

### Steps to reproduce

Access the Taiko UI interface.

1 -  Attempt to connect the wallet.
2 - Observe the network transition modal.
3 - Try to switch to the Holesky or Katla networks.
4 - Notice that the switch is prevented, and a "Switch Declined" error is displayed.
5 - Attempt to perform manual switching, but observe that the wallet does not allow it.
![brave_6YKINSy37R](https://github.com/taikoxyz/taiko-mono/assets/107889885/3bb63fe5-4303-46d0-8593-9a509cd1ee4e)

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by mrhyu** [comment]
True
