### ISSUE TITLE
Bridge Uniting and Single Portal 

### ISSUE THREAD

**Issue by bradmelias** [taikoxyz/taiko-mono#16181]
### Describe the feature request

unite all the bridges and tokens all on one page, with chain switcher showing tokens held on each chain. Maybe tie in the tasks from thhe guild and links to galxe etc. This gives users one simple portal with a user friendly UI to not only track progress but view the various capabilities and other features to test before full launch

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Farmers be lazy.
