### ISSUE TITLE
Error when trying to provide liquidity

### ISSUE THREAD

**Issue by canter1** [taikoxyz/taiko-mono#16187]
### Describe the bug

it says the liquidity i provided is out of range 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by ainozz** [comment]
Review the Requirements: Take a look at the specific requirements or guidelines provided by the platform or system. They usually specify the acceptable range of liquidity that can be provided.

Adjust Your Input: Check the amount of liquidity you provided and ensure that it falls within the specified range. If it's too high or too low, consider adjusting it accordingly.

**Comment by markokharchenko** [comment]
the same)
