### ISSUE TITLE
Create a Taiko and Solana Link 

### ISSUE THREAD

**Issue by flokeyyy** [taikoxyz/taiko-mono#16182]
### Describe the feature request

Not many L2s can interact directly with Solana in terms of bridge connections especially not ones that are tokenless would be cool to see a bridge with taiko and Solana to move funds across might also open up the Solana community for us 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
No.
