### ISSUE TITLE
Takes longer period to bridge. 

### ISSUE THREAD

**Issue by justubongj** [taikoxyz/taiko-mono#16197]
### Describe the bug

The transaction completes after more than 24 hours, not sure why people do not have a problem with this.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
duplicate
