### ISSUE TITLE
BUG IN DAPP TAIKO

### ISSUE THREAD

**Issue by 0xZaccube** [taikoxyz/taiko-mono#16227]
### Describe the bug

in Profile Showing Pending Transaction, But when im clicking show nothing

pict 1 Before , pict 2 After

![Cuplikan layar 2024-03-02 040958](https://github.com/taikoxyz/taiko-mono/assets/161220129/4f0217e2-ad83-407f-9ed3-d247e000e832)
![Cuplikan layar 2024-03-02 040944](https://github.com/taikoxyz/taiko-mono/assets/161220129/07b8d563-1ee0-4e09-b964-bc4c36d2ed39)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by 0xZaccube** [comment]
![Uploading Cuplikan layar 2024-03-02 041420.png…]()

**Comment by 0xZaccube** [comment]
still bug

**Comment by KorbinianK** [comment]
Please fill out the bug template correctly, without more information we cannot help you. Feel free to reach out on discord.
