### ISSUE TITLE
ISSUE WITH NFT BRIDGING TASK

### ISSUE THREAD

**Issue by Lilgypsie123** [taikoxyz/taiko-mono#16234]
### Describe the bug

The testnet task which requires the bridging of self created and deployed  nft has been a hassle as the deployed nft address does not seem efficient after bridging  . The nft when bridged , develops a sort of error letting it to relinquish its initial  contract address and being nearly impossible to transfer back to it's initial chain of deployment.

### Steps to reproduce

Create nft and deploy,  Bridge nft from holesky to katla and bridge back .  Check the contract address . 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@Lilgypsie123  Please provide examples with addresses.
When you bridge the NFT back to its original chain it has the identical contract address

**Comment by mhaseeb911** [comment]
Yes he is saying true.I have the same issue 
0xf5FE12ed40b0d2B3e1E1DcEB7cB52F523E13AC0b
