### ISSUE TITLE
HOLESKY FAUCET BUG

### ISSUE THREAD

**Issue by Billbante** [taikoxyz/taiko-mono#16249]
### Describe the bug

Kindly note that the holesky faucet is not working for some users.
There is IP restriction during claim process.

NOTE: No VPN was used during this process.

See attached for error message.
<img width="638" alt="holesky faucet" src="https://github.com/taikoxyz/taiko-mono/assets/137031385/03c9ffe0-cf24-4ad6-83d4-8cacf968bc4f">

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
We are not responsible for faucets.
