### ISSUE TITLE
Adding the Inscriptions Technology

### ISSUE THREAD

**Issue by volzook** [taikoxyz/taiko-mono#16253]
### Describe the feature request

I think it would be fun to combine all the best from the Inscriptions and add something new to Taiko so that the NFTs on it will be special in the future - not like on other blockchains. I would like a similar system based on the Runes protocol, Trac.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by sankriscrypto** [comment]
Good News ...NFTs Taiko will be special in the future

**Comment by Akaribajoga** [comment]
Thus could be an a special contribute cause the inscription will help taiko nft in the near future
