### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by hitunesmix** [taikoxyz/taiko-mono#16250]
### Describe the bug

slow in deployment

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by hitunesmix** [comment]
no comment

**Comment by KorbinianK** [comment]
@hitunesmix reported for spam
