### ISSUE TITLE
Galxe passport and gitcoin passport requirement to recieve reward in the ongoing campaign

### ISSUE THREAD

**Issue by olaunjex1** [taikoxyz/taiko-mono#16254]
### Describe the feature request

It's quite obvious and a common thing in crypto space where by some user try to game a project reward by creating multiple account. It makes honest user receive little or nothing for their honest work. I believe if you make use of both galxe and gitcoin as requirement to recieve reward, it will reduce sybillor to someone extent. Kindly  consider this so that honest user could recieve a deserving reward at for their effort in prompting the project (taiko)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Lil00404** [comment]
Good idea, at least galxe passport because gitcoin passport more hard to obtain.
I know some friends who used the same wallet for many years and have trouble to reach 20 points on gitcoin passport

**Comment by KorbinianK** [comment]
We are well aware of the situation :)
