### ISSUE TITLE
Faucet issue

### ISSUE THREAD

**Issue by hkanekici** [taikoxyz/taiko-mono#16265]
### Describe the feature request

I cannot mint the Horse coin on the Katla net. Is there any way to make it possible? thanks

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by atlanticgg** [comment]
You can swap your Katla **ETH** to **HORSE** using https://swap.katla.taiko.xyz/#/swap

**Comment by KorbinianK** [comment]
@hkanekici can you share the error you see? Also provide the wallet address
