### ISSUE TITLE
transactions issue

### ISSUE THREAD

**Issue by NorthOmerica** [taikoxyz/taiko-mono#16266]
### Describe the feature request

i cannot see my transactions 
![taiko2](https://github.com/taikoxyz/taiko-mono/assets/148994696/52959306-f567-4c83-a6a1-0d60a95bcb33)
![taiko1](https://github.com/taikoxyz/taiko-mono/assets/148994696/2faf9427-5519-4eaa-95b0-d2d28f6a9d70)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Transaction section only shows bridge transactions. You'll find it on the explorer
