### ISSUE TITLE
https://swap.katla.taiko.xyz/#/swap    Bug Report

### ISSUE THREAD

**Issue by mrtrdl** [taikoxyz/taiko-mono#16261]
### Describe the bug

Error Details:

How It Occurs Step by Step:

[Connect Taiko Katla]
[signed]
[Taiko Katla to Seoılia]
Expected Behavior:
[Performing transactions on the Taiko Katla network.]

Received Error Message:
[It is consistently attempting to transition from the Taiko Katla network to the Sepolia network. Even when confirmed, it still tries to move from the Sepolia network to the Taiko Katla network. The operation is not stable.]

What steps can I take to resolve this issue, or what additional information do you need from me to address it?
[taiko swap.pdf](https://github.com/taikoxyz/taiko-mono/files/14470733/taiko.swap.pdf)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
We do not support sepolia but holesky. That's why.
