### ISSUE TITLE
Taiko docs don't open.

### ISSUE THREAD

**Issue by atlanticgg** [taikoxyz/taiko-mono#16269]
### Describe the bug

When you're trying to run a "begin the journey" campaign on the Guild and you try to complete tasks related to Taiko docs ( "Visit our Receiving Tokens Guide" and "Visit the Bridging Tokens Guide" ), they simply do not open ( the link works, but the site still won't open ). Anyway the task in the Guild is counted, which is strange, because I simply cannot get acquainted with the information I need to complete subsequent tasks.

### Steps to reproduce

**1.** Go to https://guild.xyz/taiko/begin-the-journey
**2**. Try to visit any of both taiko docs links troughthis campaign ( **https://docs.taiko.xyz/guides/receive-tokens/** or **https://docs.taiko.xyz/guides/bridge-tokens/** )

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Must be a problem with your system or browser. They open fine for thousands of other users.
