### ISSUE TITLE
 The issues with the pool :)

### ISSUE THREAD

**Issue by hkanekici** [taikoxyz/taiko-mono#16267]
### Describe the feature request

The automatic setting of product values is not working properly when creating a pool on https://swap.katla.taiko.xyz/. Due to this issue, I am unable to create a pool. It would be nice if automatic value assignment could be implemented.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by ngworld2020** [comment]
hım haklısınız bende aynı sorunu yaşadım :)
