### ISSUE TITLE
level=error component=activeQueryTracker msg="Failed to create directory for logging active queries“

### ISSUE THREAD

**Issue by shilohma** [taikoxyz/taiko-mono#16270]
### Describe the bug

Description of the bug here.
I encountered this problem when running node, is it a bug?
aiko_client_prover_relayer-1  | [INFO  wait] --------------------------------------------------------
taiko_client_prover_relayer-1  | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
taiko_client_prover_relayer-1  | [INFO  wait] --------------------------------------------------------
taiko_client_prover_relayer-1  | Required flags "l1.proverPrivKey, prover.capacity" not set
prometheus-1                   | ts=2024-03-03T04:24:30.865Z caller=query_logger.go:115 level=error component=activeQueryTracker msg="Failed to create directory for logging active queries"
prometheus-1                   | ts=2024-03-03T04:24:30.865Z caller=query_logger.go:93 level=error component=activeQueryTracker msg="Error opening query log file" 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Please reach out in the correct discord channel.

**Comment by shilohma** [comment]
ok, ths
