### ISSUE TITLE
Analysis in details of to claim horse nft

### ISSUE THREAD

**Issue by Eazibigz** [taikoxyz/taiko-mono#16273]
### Describe the feature request

Description of the feature I cannot mint the Horse coin on the Katla net. Is there any way to make it possible? thanks here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
You probably already minted it in the past. Share your wallet address and the error you see.
