### ISSUE TITLE
colour mode

### ISSUE THREAD

**Issue by JoshAbi2** [taikoxyz/taiko-mono#16277]
### Describe the feature request

it would be amazing if you can add a dark mode option to the platform. white light bothers some people, that's why mobile devices have an option for Dark Mode

### Spam policy

- [ ] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Mychaell** [comment]
There's an option to toggle both light and dark modes on the bridge site if that's what you're referring to:

**On mobile: 👇🏽** 

https://github.com/taikoxyz/taiko-mono/assets/59489349/7e6ea18c-74bf-4513-8603-63b5a6668f3c


**On Desktop 👇🏽:**

https://github.com/taikoxyz/taiko-mono/assets/59489349/cb98015a-4078-40f6-9719-7cff04b14e45

**Comment by JoshAbi2** [comment]
ooh, I'm just seeing this. thank you

**Comment by pnoken** [comment]
Guess this issue can be closed now
