### ISSUE TITLE
Multi signature for outgoing transactions

### ISSUE THREAD

**Issue by Gbanks2230** [taikoxyz/taiko-mono#16275]
### Describe the feature request

Description of the feature request here.

with the increase in hacks and wallet drain, one of the best safety measures to keep this in check knowing fully well that it cannot be avoided but can be prevented is a Feature of Multi signature for outgoing transactions. The team can develop a contract for this which users will be confident enough to use since it is developed by the team itself. It doesn’t have to be deployed on the Ecosystem but it can be a contract deployed separately which users will have the option to add or use . This will help to prevent future hacks and also we would like to see TAIKO self custodian wallet in the future. Im sure the team have a lot of plan for us so GOODLUCK

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by shazib2023** [comment]
so what should be done?
