### ISSUE TITLE
Error report:  NFT cannot be bridged from Katla to Holesky

### ISSUE THREAD

**Issue by hijonehi** [taikoxyz/taiko-mono#16284]
### Describe the bug

If an NFT is originally created on Katla chain, it cannot be bridged to Holesky chain.  The Bridge-APP keeps saying: Unknown error--An unexpected error has occurred. Please try again.
If an NFT is bridged from Holesky to Katla, then it can be bridged back to Holesky successfully.

### Steps to reproduce

Create an NFT on Katla chain on nfts2.me or thirdweb.com. Claim it. Try to bridge the NFT to Holesky. It can be approved  but fail to  be bridged.
![7741-1](https://github.com/taikoxyz/taiko-mono/assets/61875854/5f8fbd58-0e23-4c4b-927e-fb1b3d3ba59c)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Reach on on discord, this is due to the NFT generator not following the standard.
