### ISSUE TITLE
Adding Transaction Time 

### ISSUE THREAD

**Issue by yungtoba** [taikoxyz/taiko-mono#16280]
### Describe the feature request

It would also be cool to add how long each transaction would take when bridging assets. I dropped a sample of how it would look like on Taiko Bridge. 

![Transaction time](https://github.com/taikoxyz/taiko-mono/assets/28141326/e81002a0-e275-4517-a05a-e3fd401eb2de)

![Transaction time](https://github.com/taikoxyz/taiko-mono/assets/28141326/a85b0914-03ac-48e7-a584-0acb07c1cf06)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Duplicate
