### ISSUE TITLE
ADD ADDITIONAL SUPPORT FOR OTHER EVM WALLETS (OKX, RABBY, BITGET, IMTOKEN, COINBASE)

### ISSUE THREAD

**Issue by Mitosis1** [taikoxyz/taiko-mono#16285]
### Describe the feature request

There are many EVM compactible wallets and many users have migrated onto other newer wallets such as Okx, Rabby, Bitget, Imtoken and Coinbase just to mention a few. One of the bottlenecks to the use of dapps is the unavailability or lack of support for the different wallets web3 users use.  Currently, Taiko Katla only supports a few EVM compactible wallets(as indicated in the screenshot below).
By adding support for multiple wallets, use of dapps on Taiko will be easy and adoption almost instantaneous
![Taiko Katla](https://github.com/taikoxyz/taiko-mono/assets/32782176/fd7377ba-d7ac-4cd6-a1d6-3319ef098025)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Emefa1** [comment]
This is a loudable idea. I am looking forward to Devs implementing these suggestions to make Taiko chain more user friendly

**Comment by Fishbone11** [comment]
I kept wondering when extra wallet support would be added too. I personally use Okx wallet so I would be happy to see this wallet supported on Taiko chain. Good work @Mitosis1

**Comment by Augustinogh** [comment]
Great idea.

**Comment by KorbinianK** [comment]
Our bridge supports all wallets via walletconnect. Swap is just a test and does not reflect Mainnet
