### ISSUE TITLE
NFT

### ISSUE THREAD

**Issue by unal4828** [taikoxyz/taiko-mono#16297]
### Describe the feature request

HORSE NFT BRIDGE CANNOT BE DONE ON THE KATLA NETWORK.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
No details provided. Reach out on discord.
