### ISSUE TITLE
feat(protocol): implementing Transaction Expiry Time During on swap/bridge dAPP

### ISSUE THREAD

**Issue by 007sucre** [taikoxyz/taiko-mono#16291]
### Describe the feature request

Transactions may fail due to various reasons such as network congestion, insufficient gas fees, or simply due to market volatility causing price changes before the transaction is confirmed. To address this issue and enhance user experience, I propose the implementation of transaction expiry time as a feature on swap/bridge dAPP so as to minimizes the risk of failed transactions and potential losses due to market fluctuations or network issues.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
An interesting feature request. I think we may consider it after this current protocol is battle tested. Internally we decided not to add new features until the mainnet is launched.

**Comment by 007sucre** [comment]
Great idea, would be proud to see it implemented in the future then.
