### ISSUE TITLE
BRIDGED NFT doesnt show on the Hoelsky chain when i try to check it 

### ISSUE THREAD

**Issue by Oziehkika** [taikoxyz/taiko-mono#16299]
![Screenshot 2024-03-04 035702](https://github.com/taikoxyz/taiko-mono/assets/91777688/091746af-e9b6-4c5f-8b02-b06ea0f25db5)

Bridged an nft from Katla to Hoelsky but when i ty to check and bridge it backt to Katla it doesnt show in the wallet. could this be a bug?

**Comment by KorbinianK** [comment]
We are only indexing NFTs on Katla not holesky. You need to manually import the new bridged contract address. Reach out on discord for further help if needed.

**Comment by Oziehkika** [comment]
okay thank you
