### ISSUE TITLE
User Interface: NFT Bridge - Token ID

### ISSUE THREAD

**Issue by dankenneth23** [taikoxyz/taiko-mono#16298]
### Describe the feature request

please remove the feature on taiko nft bridge that makes token ID increases/decreases when you do mouse scroll inside the token id field. it can triggered by accident when scrolling at the bottom of the page after the input of nft token id. 

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by sarvarbekabdupattoyev** [comment]
So cool

**Comment by Msasifrank** [comment]
I thought this was cause by my PC beeing old, I decided to  end my test for the next day

**Comment by dantaik** [comment]
@KorbinianK could you please verify if this is still an UX issue?

**Comment by KorbinianK** [comment]
Can't replicate this on chromium browsers or firebox
