### ISSUE TITLE
Update FAQs page

### ISSUE THREAD

**Issue by faust21k** [taikoxyz/taiko-mono#16302]
### Describe the feature request

I quite often come across the question of where to get a ETH on the Taiko Katla network to test the Taiko ecosystem. I think it would be nice to update the FAQs page in Taiko docs ( https://docs.taiko.xyz/resources/faqs/ ) and get the answer to this question there. it might look like:

### **How do I get a ETH on the Taiko Katla network?**
You can use the official [Taiko bridge](https://bridge.katla.taiko.xyz/) to send your ETH from the Holesky network to the Taiko Katla network.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to create a PR to add this section!

**Comment by faust21k** [comment]
> Feel free to create a PR to add this section!

ready sir
https://github.com/taikoxyz/docs/pull/75
