### ISSUE TITLE
Cannot switch to Holesky unless RPC is added manually

### ISSUE THREAD

**Issue by fiatsendme** [taikoxyz/taiko-mono#16308]
### Describe the bug

In the bridge section (https://bridge.katla.taiko.xyz/) user cannot automatically add rpc in metamask unless manually added. 
![image](https://github.com/taikoxyz/taiko-mono/assets/64193869/3c48fd78-eae0-4fd4-8429-de651c1bf9b4)

### Steps to reproduce

- Visit https://bridge.katla.taiko.xyz/
- Connect wallet
- Select Holesky

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by reimon50** [comment]
Add Holesky first to be able to switch without error

**Comment by fiatsendme** [comment]
How do I claim my GitPOAP?

**Comment by fiatsendme** [comment]
@KorbinianK please when is my gitPOAP going to be invoked?

**Comment by fiatsendme** [comment]
@dantaik I am wondering why my gitPOAP hasn't been issued yet? Anyone to reply me?
