### ISSUE TITLE
Add Light and Dark Mode Toggle for Katla Taiko  Swap

### ISSUE THREAD

**Issue by sarvarbekabdupattoyev** [taikoxyz/taiko-mono#16306]
### Describe the feature request

This issue proposes the implementation of a toggle switch to allow users to switch between light and dark mode for the Taiko Katla swap interface.

Benefits:

Improved user experience and preference customization.
Enhanced accessibility for users with visual impairments.
Implementation Details:

Use a toggle component from the existing UI library.
Implement state management to track the selected mode.
Update styles dynamically based on the chosen mode.
Optionally, persist the user's preference across sessions (using local storage or a database with appropriate security measures).
Testing:

Thoroughly test across browsers, devices, and screen sizes.
Ensure accessibility compliance and user-friendliness.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by cancan1972** [comment]
Use a toggle component from the existing UI library.
Implement state management to track the selected mode.
Update styles dynamically based on the chosen mode.

**Comment by KorbinianK** [comment]
There is a toggle in the settings:
<img width="389" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/5267230/aa27f5dd-3a40-49e6-a9ce-9804590a70c9">
