### ISSUE TITLE
Integrate Taiko to Transak at Mainnet

### ISSUE THREAD

**Issue by InnoOkeke** [taikoxyz/taiko-mono#16310]
### Describe the feature request

Transak is a developer integration toolkit that enables app developers to onboard users to buy/sell crypto in any blockchain app, website or web plugin.

With Taiko integrated to Transak, It'll allow Users of Apps purchase crypto on Taiko blockchains across several nations with ease. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to open an application to the ecosystem if you are are a representative of Transak. But then do it in the website repository.
If not, reach out to them to do it.
