### ISSUE TITLE
bridge timer

### ISSUE THREAD

**Issue by swiftereum** [taikoxyz/taiko-mono#16317]
### Describe the feature request

The average time for bridging of testnet Eth to Katla should be indicated. the bridge was very fast but adding a timeframe of completion will show users the average bridge time compared to others

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Duplicate
