### ISSUE TITLE
ADD LIQUIDITY POOL TO TAIKO KATLA

### ISSUE THREAD

**Issue by Italeo8** [taikoxyz/taiko-mono#16332]
### Describe the feature request

Taiko katla is good, but still missing the full flexibility of being the best dapp, love the themes. I think  you guys should add a liquidity pool to this.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Use the swap?

**Comment by Italeo8** [comment]
Yes I have, and it is working smoothly.

**Comment by Italeo8** [comment]
> Use the swap?

Yes I have and it's working smoothly.
