### ISSUE TITLE
nft bridge 

### ISSUE THREAD

**Issue by imranmahmudshoiball** [taikoxyz/taiko-mono#16337]
### Describe the feature request

Need nft bridge function.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
<img width="1182" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/5267230/032a4d56-159a-4cbd-b860-8bad5ae723da">
