### ISSUE TITLE
POOLS bugs when trying to create a new position

### ISSUE THREAD

**Issue by ace36gaming** [taikoxyz/taiko-mono#16336]
### Describe the bug

Found a Bug on the Pools when trying to add a new pool eg. ETH / HORSE after clicking "EDIT" for fee tier  and choosing one of them ( I tried all different fees %) then I when on to type the 2 amount for ETH n HORSE once you type one the other one disappear and the you type one on the bottom and type an amount on top it said " PREVIEW" then "ADD" and it freeze on there the transaction will not go thought 

### Steps to reproduce

what i have found as a way around is to select the "percentage fee tier"  then click where it said "FULL RANGE" after that it will let you type the amount on the bottom and the other asset automatically fill and match the amounts. everything goes smoothly after with the transaction and i was able to add liquidity to the pools

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by ace36gaming** [comment]
sorry didn't provide the website here it is just in case:    https://swap.katla.taiko.xyz/#/pools

**Comment by loboespartano** [comment]
A mi tambien me da error al armar una pool ETH/HORSE.t https://alpha.izumi.finance/trade/add-liquidity
![Captura de pantalla 2024-03-11 205827](https://github.com/taikoxyz/taiko-mono/assets/116645245/0b0cd50c-4292-4849-b005-90f56cba2927)

**Comment by dantaik** [comment]
We are using Uniswap protocol, if there is a bug, could you please file a report to Uniswap's repo?

**Comment by dantaik** [comment]
@2manslkh could you verify if this is a frontend issue?

**Comment by 2manslkh** [comment]
Not an issue
