### ISSUE TITLE
Not available Eth balance on the katla Taiko bridge

### ISSUE THREAD

**Issue by Neotravolta** [taikoxyz/taiko-mono#16349]
### Describe the bug

Description of the bug here
Trying to bridge Eth from Katla to Holesky chain, after connecting my wallet all i get is NA balance of which I have some Eth on Katla chain

### Steps to reproduce

Steps to reproduce here.
Just connect wallet to the Katla Taiko bridge evem after disconnecting wallet and connecting again issue still persist 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Neotravolta** [comment]
![IMG-20240307-WA0020](https://github.com/taikoxyz/taiko-mono/assets/142179013/c86863e0-43bd-46e7-9163-8b5fc2c8ba92)

**Comment by mgasageorge** [comment]
Completwd

**Comment by KorbinianK** [comment]
Duplicate, fixed already and coming in the next release
