### ISSUE TITLE
NFT transaction failure from Katla testnet

### ISSUE THREAD

**Issue by rajmehta26** [taikoxyz/taiko-mono#16354]
### Describe the bug

Transactions from katla testnet to holskey keep failing 
![image](https://github.com/taikoxyz/taiko-mono/assets/152624212/897c56b5-bfda-4341-91f2-8bdbed240727)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
@rajmehta26 Probably one of those nft2me collections am I right? reach out on discord, those contracts don't follow the NFT standard correctly.

**Comment by rajmehta26** [comment]
No, apparently its every nft that I am transacting, shows failure

Best regards,

Raj Mehta
