### ISSUE TITLE
I can't  swap HORSE to Eth, but transactions are not completed ,

### ISSUE THREAD

**Issue by Msasifrank** [taikoxyz/taiko-mono#16366]
### Describe the bug

Description of the bug here.
When you swap Ether to Horse there is no Issue, the issue comes into play when you  swap Horse to Ether , Transaction will be pending forever ,   or Fail.   Is theres any one who has experienced this?  

Swaping horse to ether only work by swapping  horse to usdt ,then Usdt to  ether.

### Steps to reproduce

Steps to reproduce here.

1.Swap ether to Horse,
2. Swap Horse to ether. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by eribertomota** [comment]
At this moment, eth->horse is not working for me. Transactions are pending forever or failing.

**Comment by Msasifrank** [comment]
I wonder why is this happening , try swaping horse to USDT ,then to Eth

**Comment by laumeng** [comment]
i have the same problem

**Comment by laumeng** [comment]
have you solve it ?

**Comment by Msasifrank** [comment]
Yes ,by going around
