### ISSUE TITLE
Adding Filter Feature in Ecosystem Page

### ISSUE THREAD

**Issue by 0xZaccube** [taikoxyz/taiko-mono#16365]
### Describe the feature request

Description of the feature request here.

Previously, I would like to argue, maybe not everyone understands about ecosystems [ https://taiko.xyz/ecosystem ] , to make things easier, what if gave them a filter like:

NFTs
WEB3
A.I
Wallets

etc.

So in the future, people can use filters to make it easier to browse the Taiko ecosystem according to their interests.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
We're already working on something :) Stay tuned!
