### ISSUE TITLE
Enchanced CLI Tools

### ISSUE THREAD

**Issue by jay3183** [taikoxyz/taiko-mono#16369]
### Describe the feature request

Enchanced CLI commands that allow us developers to interact with smart contracts on Katla or taiko mainnet. CLI commands that allow devs to call methods on smart contracts that are deployed on mainnet or testnet, fetch information from the taiko blockchain etc, start an interactive REPL connected to a node maybe from a taiko CLI ?

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
@d1onys1us what do you think of this request?

**Comment by d1onys1us** [comment]
I don't think these would be good to develop as a Taiko specific feature. I think something more generic for Ethereum can be good, but much of this is already covered with [cast](https://book.getfoundry.sh/cast/), [anvil](https://book.getfoundry.sh/anvil/) and [chisel](https://book.getfoundry.sh/chisel/).

For example, devs can fork Katla with anvil: `anvil --fork-url https://rpc.katla.taiko.xyz`. 

Will close this issue for now. Thanks!

**Comment by jay3183** [comment]
So am I not eligible for a POAP ?
