### ISSUE TITLE
Minor mistapes

### ISSUE THREAD

**Issue by goluboiar** [taikoxyz/taiko-mono#16388]
### Describe the bug

file: packages/branding/README.md

Now:
{code}
**Files**
Look inside of this package for some common files you can use. Otherwise, please resort to the [Figma](https://www.figma.com/file/qVALIk5srW9nvOJwl6NF6F/Taiko-Brand-Guidelines-(External)).

**Colors**
Our primary hex color is #E81899. For the full color palette and further details, please resort to the [Figma](https://www.figma.com/file/qVALIk5srW9nvOJwl6NF6F/Taiko-Brand-Guidelines-(External)).
{code}

Mistape: reSort --> rePort.

### Steps to reproduce

# open file packages/branding/README.md
# find "resort"

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
"Resort to" is grammatically correct, albeit the wrong word in this context. But so is report.

**Comment by goluboiar** [comment]
Gm!
mb "refer to"?
