### ISSUE TITLE
Bugs in Zypher Games games from Taiko Testnet

### ISSUE THREAD

**Issue by Oji2601** [taikoxyz/taiko-mono#16385]
### Describe the bug

After I tested Taiko Galxe: Discover, Challenge & Play: Journey Through Learning & Fun on Taiko's A6 Testnet, when entering the stage to try the Zypher game there are some bugs or maybe there is still a lack of performance on the game or the Taiko Katla network.

 Here are the things I found: 
1. When making a transaction to buy NFT that will be used in the game, it takes a very long time and in the end you can't buy it. Even though my own internet network is good and can be used on other websites. 
2. When I got the NFT, when I wanted to use it I couldn't get into the game and had to refresh continuously until I could enter and it took a long time. Previously I checked on the Katla block that the NFT had entered my wallet.
3. When I finished facing the boss in the first game, when I wanted to claim the prize, sometimes there was still an error. And so on until the 3rd boss level. 

In conclusion, maybe Zypher Games and Taiko can improve this, such as speeding up the transaction process and minimizing the occurrence of errors in the game that should not even exist. In this way, visitors to the game, especially the Taiko community who run the game testnet, can be satisfied and happy with the progress of the game and Taiko itself. Maybe that's all the issues or bugs I can convey, hopefully it's useful and can be used as a consideration for the project so it can be even better. Thank you :) 

### Steps to reproduce

Maybe there are several steps to improve the game in my opinion: 
1. Improve the quality of the game by repairing damaged facilities/errors or bugs that occur. 
2. Taiko is trying to communicate with the game to make it even better in the future.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Please reach out to Zypher games directly.
