### ISSUE TITLE
taiko testnet interactions

### ISSUE THREAD

**Issue by clw14758** [taikoxyz/taiko-mono#16382]
### Describe the bug

Some problems with taiko testnet interactions.
![360截图17081102426864](https://github.com/taikoxyz/taiko-mono/assets/92667340/603a65fb-5796-4384-80d9-c3e1bf3fc5df)
![360截图184307079898121](https://github.com/taikoxyz/taiko-mono/assets/92667340/0e53e09b-b268-4740-9eab-43a433c1011a)
An unknown error occurs during bridge processing

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Without details we cannot help you. Feel free to reach out on discord.
