### ISSUE TITLE
Enhancing User Experience: Introducing a Popup to Clarify Local Routing Functionality on the Swap Page

### ISSUE THREAD

**Issue by courage-ugwuanyi** [taikoxyz/taiko-mono#16383]
### Describe the feature request

On the swap page https://swap.katla.taiko.xyz/#/swap when the `cog` icon is clicked, a modal pop-up displays two functionalities namely, `Local routing` and `Max slippage`. The `Max slippage` has a `question mark in a circle`, which when hovered, shows a pop-up, explaining some details to the user and giving information about their actions. On the other hand, the `Local routing` functionality neither has a `question mark in a circle` associated with it that gives any information to the user, nor does it render any visible effect on the page when it is toggled on or off.

**Suggested Feature Addition:**

I have attached photos showing my suggestion of adding an `info icon` to the `Local routing` functionality to help users understand what the feature does and how it can impact their transactions. This improves user experience.

![Taiko - UI improvement-1](https://github.com/taikoxyz/taiko-mono/assets/130373788/8c690189-2be7-451f-8052-1e6bf548a771)

![Taiko - UI improvement-2](https://github.com/taikoxyz/taiko-mono/assets/130373788/b56b1732-1c50-42c3-857e-6ee1b353d741)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
https://github.com/Uniswap/interface/issues/7289
