### ISSUE TITLE
swap.katla.taiko.xyz Flagged as Malicious 

### ISSUE THREAD

**Issue by Sampxon** [taikoxyz/taiko-mono#16395]
### Describe the bug

I am a user raising an issue on GitHub regarding swap.katla.taiko.xyz The website has been flagged for malicious activity, and I kindly request the attention of Taiko development team to investigate and resolve the issue promptly. Your collaboration and timely communication are appreciated. Thank you.

I understand that addressing such concerns requires time and effort, but I believe that the timely resolution of this issue is crucial to maintaining the integrity of the Taiko ecosystem. As a user, I am eager to receive updates on the progress made and any actions taken to mitigate the reported malicious activity.
![Image 11-03-2024 at 14 39](https://github.com/taikoxyz/taiko-mono/assets/110123509/3d522e65-418a-4ba7-9cf2-ed927944ce4a)

### Steps to reproduce

Steps to reproduce here.
Visit swap.katla.taiko.xyz with MalwareBytes or any other powerful web antivirus turned on 
Access is blocked and Said screenshot attached as image is seen

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by brontesmarpaung** [comment]
you can learn from docs

**Comment by dantaik** [comment]
I think it's OK to have such warning :D
