### ISSUE TITLE
Contribution Recognition for Taiko Team - Assistance with GITPOAP 2024 Minting #16392

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/taiko-mono#16396]
Hello Taiko Team,

**I am reaching out regarding a previous issue, #16392, which was mistakenly closed.** 
I intended to provide **additional information and evidence of my contribution to Taiko Geth.**

Unfortunately, the issue was closed before I could supply the necessary details. 

I would like to rectify this and request a GitPOAP for my contribution. Here are the specific details :

Issue Raised: [#160](https://github.com/taikoxyz/taiko-geth/issues/160)
Pull Request: [#162](https://github.com/taikoxyz/taiko-geth/pull/162)

**Discord Confirmation: @davidtaikocha has confirmed on Discord that I will be included in the new GitPOAP when it is created.**

**I understand from the documentation that opening a meaningful issue is also eligible for a GitPOAP. I believe my contribution through the issue and subsequent pull request aligns with the requirements.**

I kindly request that a GitPOAP be awarded to me for this contribution. I would greatly appreciate it if you could manually invoke the GitHub bot to send the GitPOAP.

I have also made additional contributions to the Taiko project, including a merged pull request on taiko/website

Thank you very much for your attention to this matter. 
I look forward to receiving the GitPOAP and continuing to contribute to Taiko 

Screenshots 

<img width="1059" alt="poap" src="https://github.com/taikoxyz/taiko-mono/assets/107585158/f5718973-9021-411a-a02f-b67db36fa1da">
<img width="1869" alt="discord discussion" src="https://github.com/taikoxyz/taiko-mono/assets/107585158/08b38e7a-08e9-47a8-85e1-23fd640d364c">
<img width="982" alt="noir sur blanc" src="https://github.com/taikoxyz/taiko-mono/assets/107585158/abe954ce-e6e4-42ce-94b7-2963464c5808">
in the future.

**Comment by samui68400** [comment]
any news? thanks for your answer

**Comment by nikola4888** [comment]
Hopefully you'll receive a response soon!

**Comment by samui68400** [comment]
are you part of the team?

**Comment by nikola4888** [comment]
> are you part of the team?

No i'm just a community member

**Comment by RizalHF23** [comment]
i am excited to be part of Taiko team

**Comment by d1onys1us** [comment]
@gitpoap-bot can you please award a poap to @samui68400

**Comment by d1onys1us** [comment]
yay it worked. thx @samui68400

**Comment by samui68400** [comment]
This is just a first step for me, I'm going to continue to do my utmost to learn and help the community and the project. Thanks
