### ISSUE TITLE
Problem with gas in metamask 

### ISSUE THREAD

**Issue by m3shm** [taikoxyz/taiko-mono#16400]
### Describe the bug

As i see In metamask the gas is 0.00000000001 Eth and no order ho through

but everything is perfect in rabby wallet 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by canter1** [comment]
edit the gas fees using the advance fee settings on your metamask to
max base fee 0.11
priority fee to 0.1
gas limit to 157000

**Comment by dantaik** [comment]
With the upcoming testnet, the min base-fee is 1gwei, this shall "fix" some UX issues with metamask. 

I'll close this issue for now.
