### ISSUE TITLE
fail to add liquidity

### ISSUE THREAD

**Issue by VeeruNFT** [taikoxyz/taiko-mono#16407]
### Describe the bug

I'm trying to add liquidity with my zeal wallet but its not adding up i don't know why Its showing error saying insufficient funds but i have the test funds in my wallet and also i have added the taiko katla network twice but still error is there . Any way to rectify this error?? thanks

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by vonyue** [comment]
Is the zeal wallet fully compatible with the taiko katla network?

**Comment by 2manslkh** [comment]
yes
