### ISSUE TITLE
Share Router for Taiko Dex & Official Badge from Taiko Ecosystem

### ISSUE THREAD

**Issue by zerosecxz** [taikoxyz/taiko-mono#16418]
### Describe the feature request

- Please Share Router Taiko Dex ( i cant find on docs ) it will help project owner for deploying liq from smartcontract
- Add submission Token Feature ( for avoid scam project )

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
@zerosecxz could you elaborate these two feature requests?
