### ISSUE TITLE
responsive of the design for the mainwebsite

### ISSUE THREAD

**Issue by joshares** [taikoxyz/taiko-mono#16416]
### Describe the feature request

the frontend developer needs to align the footer properly, it looks slightly aligned to the left, and this makes the design of the website looks like its been done by amateurs. the "@2024 taiko labs" statement at the end is suppose to be directly under the developers section in the footer if the footer was aligned properly. A big project like this should not have those little design errors. the solution is easy and its something I can do it minutes.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by joshares** [comment]
the developer should , flex the footer section and use justify-between. this will accurately flex the footersection, so it doesnt look aligned to the left on bigscreens

**Comment by d1onys1us** [comment]
If you are familiar with how to do the change can you please open a PR in taikoxyz/website? I will close this for now because we have a new design underway.

In the meantime, feel free to open a PR, thx.
