### ISSUE TITLE
Minor mistape

### ISSUE THREAD

**Issue by dnd84** [taikoxyz/taiko-mono#16410]
### Describe the bug

Describe the bug
The testnet task which requires the bridging of self created and deployed nft has been a hassle as the deployed nft address does not seem efficient after bridging . The nft when bridged , develops a sort of error letting it to relinquish its initial contract address and being nearly impossible to transfer back to it's initial chain of deployment.

Steps to reproduce
Create nft and deploy, Bridge nft from holesky to katla and bridge back . Check the contract address .

Spam policy
 I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Copy paste of an identical issue including the policy... Reported for spam.
