### ISSUE TITLE
Bridge USDT From L2 to L1

### ISSUE THREAD

**Issue by senjaparades** [taikoxyz/taiko-mono#16415]
### Describe the feature request

maybe can add bridge more coin like USDT from L2 to L1

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by NewAlf** [comment]
This is testnet. Not all tokens are available. Can only bridge ETH and HORSE from Holesky to Katla network.

**Comment by dantaik** [comment]
@KorbinianK for our mainnet launch, do we have a list of verified tokens already?

**Comment by rona582** [comment]
When mainnet
