### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by tonycody** [taikoxyz/taiko-mono#16421]
### Describe the feature request

Suggest support for multiple national languages, not just English. For example: China

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Our bridge already supports it under the hood, we may add more languages after the main net launch.

**Comment by dantaik** [comment]
Close it for now.
