### ISSUE TITLE
transaction problem

### ISSUE THREAD

**Issue by abin1212** [taikoxyz/taiko-mono#16423]
### Describe the bug

i am facing a problem in transaction  on Taiko x Blazpay: Mint, Stake and Play task 

### Steps to reproduce

![Screenshot (165)](https://github.com/taikoxyz/taiko-mono/assets/56836728/66043266-66cc-4d80-96a7-f10d7e30f199)
![Screenshot (164)](https://github.com/taikoxyz/taiko-mono/assets/56836728/bebf7d55-467c-4abf-bed2-14de45d4b75e)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by emjoe1** [comment]
Blazpay mentioned having some issues with the website on their discord channel yesterday but the quest is working smoothly now. Be sure to equally stake after minting.

**Comment by mgasageorge** [comment]
The problem is all about even mint is not working for now hope the team will work on it soon

**Comment by KorbinianK** [comment]
Reach out to blazpay or our discord for general support.
