### ISSUE TITLE
Wallet conect 

### ISSUE THREAD

**Issue by henriquestrong** [taikoxyz/taiko-mono#16426]
### Describe the bug

Description of the bug here.implement conect wallet for cell phones
because we all use cell phones more than computers

### Steps to reproduce

implement conect wallet for cell phones
because we all use cell phones more than computers

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Walletconnect works on the phone, only Metamask is disabled due to a bug. You can open it directly inside the Metamask App on your phone if you want to use it.

https://github.com/WalletConnect/web3modal/issues/1981
