### ISSUE TITLE
Swap failed on UNI clone

### ISSUE THREAD

**Issue by mthoma112288** [taikoxyz/taiko-mono#16434]
### Describe the bug

I am unable to complete a swap on the UNI clone on Taiko Katla 

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Reach out on discord for general support and please provide details.
