### ISSUE TITLE
Blazpay mint 

### ISSUE THREAD

**Issue by mgasageorge** [taikoxyz/taiko-mono#16433]
### Describe the bug

The blazpay mint i tried to do the mint not working, the transactions don but the mint not don and completely successful, it doesn't show the mint ,and I have just to registered on blazpay not working too  this time I have tried for 5 times to mint nothing I got hope the team will fix this soon thank you!
![Screenshot_20240313-174336](https://github.com/taikoxyz/taiko-mono/assets/160029785/64a67534-f36c-4de4-ac91-2ac315e6d90c)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.
![Screenshot_20240313-184314](https://github.com/taikoxyz/taiko-mono/assets/160029785/a5ac1727-bcfc-44cd-9ae6-d36a126b17da)
![Screenshot_20240313-184347](https://github.com/taikoxyz/taiko-mono/assets/160029785/c77532a2-f784-4547-80f3-71d99704af17)
![Screenshot_20240313-184413](https://github.com/taikoxyz/taiko-mono/assets/160029785/d7e3b060-9ea8-4cb5-bc7d-6d1aaf960766)

**Comment by mgasageorge** [comment]
Hope the team will work immediately on it soon regards!!!

**Comment by KorbinianK** [comment]
Reach out to blazpay or our discord.
