### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by solpret** [taikoxyz/taiko-mono#16448]
### Describe the bug

Description of the bug here.when try to make a transaction sometimes our transaction deelay so long almost a day and thats cant faster or rejected

### Steps to reproduce

Steps to reproduce here.make a transaction swap from eth to horse or other tokens

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by solpret** [comment]
when making a transaction, I said the transaction was pending for quite a long time, I tried swapping from eth to horse, and I couldn't speed it up or cancel it.

**Comment by KorbinianK** [comment]
Reach out on discord for general support.
