### ISSUE TITLE
Adds dencun / cancun info in Taiko Katla L2 Testnet

### ISSUE THREAD

**Issue by canyelo** [taikoxyz/taiko-mono#16442]
### Describe the feature request

- How much impact did the Ethereum Dencun update have on gas on the Taiko testnet?
- When Taiko enters the Mainnet , how will the gas be selected correctly regarding supply?

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
These are great questions for our community calls, feel free to ask them there. This is not a discussion forum.
