### ISSUE TITLE
Add multisig wallet

### ISSUE THREAD

**Issue by canyelo** [taikoxyz/taiko-mono#16454]
### Describe the feature request

Security for Ethereum and other layers 2 required
To protect Ethereum Validators and users using nodes on Taiko, a multi-signature  is required in the wallet, because, - A multi-signature wallet is a digital wallet that requires at least two private keys to log in and complete a transaction. Transaction here means sending a digital asset such as cryptocurrency. We can compare a multisig wallet, also called multisig, to a secret safe that requires two keys to unlock.

I think this feature fits perfectly with "Taiko's Approach to Multi-Proofs technology"

The multi-proofs approach can hedge the risk of bugs and vulnerabilities in client implementation and proving systems.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
You are free to use whatever wallet you want, also a multisig, there are some good ones available e.g. Safe. I don't see the relevancy of this issue.
