### ISSUE TITLE
Slow Transaction 

### ISSUE THREAD

**Issue by buddymarilyn** [taikoxyz/taiko-mono#16450]
### Describe the bug

on the Testnet, most transactions of mine are pending

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Subhashis62** [comment]
Verified project

**Comment by Subhashis62** [comment]
Guild joined is too difficult
