### ISSUE TITLE
Gas estimation

### ISSUE THREAD

**Issue by Hhaybel** [taikoxyz/taiko-mono#16451]
### Describe the bug

<img width="932" alt="taiko" src="https://github.com/taikoxyz/taiko-mono/assets/125997945/bf07648f-a480-4fef-aa2d-29b97b0d0db8">
Katla2 is unable to estimate gas fee ehen trying to mint the taiko entry pass

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
This is an issue with Blazpay, not Taiko. Reach out to them please
