### ISSUE TITLE
gwei in katla network too low in metamask

### ISSUE THREAD

**Issue by umyams** [taikoxyz/taiko-mono#16455]
### Describe the bug

gwei in katla network is too low in metamask wallet so the transaction cannot be executed

i change gwei to 1 and working perfectly

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by ProfParadox123** [comment]
If the gas price (measured in Gwei) is too low, your transaction may not be confirmed by the network. You can try increasing the gas price in MetaMask to speed up the transaction. Here's how you can do it:

1. Open MetaMask and go to your wallet.
2. Find the pending transaction that is stuck.
3. Click on the transaction to expand it.
4. Look for the "Edit" or "Speed Up" button (the wording may vary).
5. Increase the gas price (in Gwei) to a higher value.
6. Confirm the change and resubmit the transaction.

Keep in mind that setting a higher gas price means you'll pay more for the transaction, but it should help it get processed faster.

**Comment by dantaik** [comment]
@KorbinianK the current v1.1.0 protocol release ensures the min L1 base fee is close to 1gwei (slightly smaller), so in the bridge UI, you can make changes to use 1gwei as the minimal basefee.

**Comment by xiaoshazhou** [comment]
yes i think it is very clear that the current protocol works well

**Comment by KorbinianK** [comment]
resolved with upcoming testnet
