### ISSUE TITLE
BRIDGING FROM HOLESKY TO KATLA AND BACK

### ISSUE THREAD

**Issue by webcoded** [taikoxyz/taiko-mono#16452]
### Describe the bug

The bridging from holesky takes a lot of time if one has no katla to claim while bridging from katla back to holesky doesn't work..it keeps failing after pending for a certain amount of time

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Mkhastroh** [comment]
Contracts deployment too technical for non devs
