### ISSUE TITLE
Pagination Bug: Incorrect Forward Arrow Displayed Beyond Last Page

### ISSUE THREAD

**Issue by courage-ugw** [taikoxyz/taiko-mono#16469]
### Describe the bug

When navigating through transaction records spanning only two pages (using my case as an example), the `forward` `>` arrow button erroneously appears after the second page when I input a number greater than 2 in the page input field. Apart from the forward arrow button being displayed, I am also able to increment the page number with the forward button, even though there are no more data to display.

### Steps to reproduce

1. Navigate to the transaction records page: https://bridge.katla.taiko.xyz/transactions 
2. Make transactions to so that your transaction records spans 2 pages.
3. Observe the presence of pagination controls, including  forward `>` arrow button, when on the second page.
4. Input a number greater than 2 into the page input field.
5. Note the appearance of the forward `>` arrow button, despite no additional data beyond the second page.

**Expected Behavior:**
On the second page, the forward or next arrow button should be hidden, indicating that there are no more pages to navigate to.
Inputting a number greater than the total number of pages should not trigger the display of the forward arrow button, as there are no additional pages beyond the last page. **See the yellow box**

**Actual Behavior:**
1. On the second page, the forward or next arrow button incorrectly appears.
2. Inputting a number greater than 2 in the page input field causes the forward or next arrow button to display, leading to an incorrect perception of additional pages. **See the blue box and blue arrow**

**Additional Information:**

Browser/Environment: Chrome Version 122.0.6261.129
Operating System: Windows 11

![pagination_error-expected](https://github.com/taikoxyz/taiko-mono/assets/134559563/10c703dd-d143-4e88-8983-443f54f47574)

![pagination_error-1](https://github.com/taikoxyz/taiko-mono/assets/134559563/6a5d720c-d5e0-4468-beac-2de98a139939)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by ProfParadox123** [comment]
Is the issue solved ?

**Comment by courage-ugwuanyi** [comment]
This PR fixes the bug: https://github.com/taikoxyz/taiko-mono/pull/16475
