### ISSUE TITLE
Transactions remain pending on metamask 

### ISSUE THREAD

**Issue by Junaid1018** [taikoxyz/taiko-mono#16467]
### Describe the bug

Description of the bug here. Transactions for Eth remain pending on Taiko Katla for several days , even after increasing gas transactions are still pending. This happens for both while bridging and swapping

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by 2manslkh** [comment]
Network is congested and we are working to increase the bandwidth of the chain 💪

**Comment by Junaid1018** [comment]
I Used rabby wallet and the transactions were confirmed withing seconds
