### ISSUE TITLE
Priority fee API

### ISSUE THREAD

**Issue by adaki2004** [taikoxyz/taiko-mono#16471]
### Describe the feature request

Currently we face an issue (on L2!) that transactions might not go through due to the fact that metamask (and not necessarily metamask only!!) does not return the correct priority fee for Katla -> It "suggests" 0, but in reality, our block producers revenue is the priority fee, so it is totally understandable if proposers are not willing to pick up such transactions. (Transactions without priority fee could still go through, if there are no other tip-paying transactions to prioritize. )

As a reference for Ethereum it looks like this:
![kép](https://github.com/taikoxyz/taiko-mono/assets/51912515/d6aa4e7a-0310-4217-b816-05584351b064)

While on Katla it looks (i dont know if always, but lot of the times when i checked) like this - with 0 priority fee:
![kép](https://github.com/taikoxyz/taiko-mono/assets/51912515/c97b6856-2fa2-442e-9131-4c6c17949469)

Last Friday Blazpay experienced the "stuck transactions issue" for a while, where the mods helped figuring out how to properly send through the transactions, by increasing the priority fee manually.

For us - since we have the bridge dApp-, sometimes is also a headache (when user wants to bridge from L2 to L1), for the aforementioned reasons.

Would be good to:
- Educated people and dApp developers that this is the case (!) - maybe a "note" section on our webpage somewhere
- Calculate the average tip payed over the last 24h / transaction and use it with metamask (when ppl using our Bridge)
- Possibly expose that API to other dApp so they could use the info as well

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by cyberhorsey** [comment]
fyi wallets are likely just calling this rpc method which is returning 0 for us I would assume.

https://www.quicknode.com/docs/ethereum/eth_maxPriorityFeePerGas

**Comment by adaki2004** [comment]
> fyi wallets are likely just calling this rpc method which is returning 0 for us I would assume.
> 
> https://www.quicknode.com/docs/ethereum/eth_maxPriorityFeePerGas

Then, node shall get the correct value (i guess) from that DB, would solve problem. Maybe dont need 24/h averaging but last 30mins - 1 hour is more helpful. cc @xiaodino

**Comment by dantaik** [comment]
I had a call with the blocknative team. They have a solution (current [available](https://www.blocknative.com/gas-estimator) for Ethereum). If we have enough data, blocknative can use their AI algo to build a gas-estimator for us.

**Comment by adaki2004** [comment]
> I had a call with the blocknative team. They have a solution (current [available](https://www.blocknative.com/gas-estimator) for Ethereum). If we have enough data, blocknative can use their AI algo to build a gas-estimator for us.

Well, it is OK, but we cannot lose and wait for them. We need a solution well before mainnet otherwise we will be flooded with these kind of things, and it will be a horror-story.
https://github.com/taikoxyz/taiko-mono/issues/16400#issuecomment-2009213871

I urge to solve this issue (this or that way) and create a proper implementation behind the `eth_maxPriorityFeePerGas` as Jeff pointed out.

**Comment by cyberhorsey** [comment]
> I had a call with the blocknative team. They have a solution (current [available](https://www.blocknative.com/gas-estimator) for Ethereum). If we have enough data, blocknative can use their AI algo to build a gas-estimator for us.

Interested to hear what amount of data they need and if it can be built and deployed for our next testnet prior to mainnet, which should be a requirement for a solution.

**Comment by dantaik** [comment]
FYI, protocol v1.1.0 now ensures the minimal base fee is close to (slightly smaller than )1gwei.
