### ISSUE TITLE
Portuguese tab for Discord users 

### ISSUE THREAD

**Issue by giulliacosta** [taikoxyz/taiko-mono#16473]
### Describe the feature request

I feel that the community could have a Portuguese tab for the Brazilian users. Sometimes it difficult for most of us to get on with th messages of the General tab, as we have to keep translating it to a better understanding. 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Marcelinompb** [comment]
Nice one, I'm brazilian as well, it would be nice to have a Community for us

**Comment by KorbinianK** [comment]
This repository is not related to our discord. Please reach out there
