### ISSUE TITLE
Fix all typos in one go

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#16488]
### Describe the feature request

We don't want to accept hundreds of small typo PRs, instead we'd like to fix everything in one go, and then continue to prevent typos with our CICD.

We have a CICD job in [typos.yml](https://github.com/taikoxyz/taiko-mono/blob/main/.github/workflows/typos.yml) which does this. However, in order to integrate the job quickly, we decided to ignore a bunch of files, which you can see here in [_typos.toml](https://github.com/taikoxyz/taiko-mono/blob/main/_typos.toml).

This issue is super easy! What you have to do is this:

1. [Install typos](https://github.com/crate-ci/typos/tree/master?tab=readme-ov-file)
2. Start removing all things from the [_typos.toml](https://github.com/taikoxyz/taiko-mono/blob/main/_typos.toml#L3), except keep the ones where we won't care about typos. These are: `CHANGELOG.md`, `automata-attestation`, and `third-party`. Everything else we should remove!
3. After removing those (I would recommend removing one at a time), use the `typos` cli tool you installed, to find the typos, review them carefully, and then apply the fixes. The tool should apply them automatically, by the way!

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by d1onys1us** [comment]
hello @momodaka as you said you are interested in contributing, i will assign you to this issue. if you have any questions please feel free to leave them here, otherwise we'll review the PR once it's ready. thanks a bunch! 🍻

**Comment by ariesjia** [comment]
> hello @momodaka as you said you are interested in contributing, i will assign you to this issue. if you have any questions please feel free to leave them here, otherwise we'll review the PR once it's ready. thanks a bunch! 🍻

I can take this issue.

**Comment by momodaka** [comment]
> hello @momodaka as you said you are interested in contributing, i will assign you to this issue. if you have any questions please feel free to leave them here, otherwise we'll review the PR once it's ready. thanks a bunch! 🍻

Let me do it 🍻

**Comment by d1onys1us** [comment]
thank you @ariesjia for your commitment. @momodaka asked first however on another PR.

if there is a particular field / area of work you are interested in, I can try to come up with another issue. thanks

**Comment by d89don** [comment]
I can correct capitalization, punctuation, and grammar throughout the documentation. Also, I can clarify wording for better understanding and standardize formatting for consistency if desired. Fixing typos is nice but there are also other issues with the docs I've noticed. I have experience with writing technical documentation in my private GitHub environment.

**Comment by Doclulu38** [comment]
Nice proposal

**Comment by JordanChipley** [comment]
This is overall a solid copy

**Comment by nikola4888** [comment]
Wagmi!

**Comment by dhamo9900** [comment]
wen token launch ?/

**Comment by adaki2004** [comment]
> wen token launch ?/

https://twitter.com/wenwencoin

**Comment by d1onys1us** [comment]
> Hi @d1onys1us, If there is more to be done as a "good first issue" I'm available to help

what kind of stuff do you like to work on or want to do? that will help narrow things down. thankx
