### ISSUE TITLE
bug on node

### ISSUE THREAD

**Issue by bigdreams006** [taikoxyz/taiko-mono#16482]
### Describe the bug

Description of the bug here. node refusing to load
![node](https://github.com/taikoxyz/taiko-mono/assets/131692196/d57ca0b5-f539-407a-b618-71550e3d6dae)

### Steps to reproduce

Steps to reproduce here.
chech and update syntax 

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by bigdreams006** [comment]
This is becoming a rule now. Everytime the node is syncing, it syncs to a point, where it says that it has fully synced, and then it stays there. It doesn't sync any more blocks, taiko_client_driver-1          | ERROR[03-19|09:01:15.688] Block batch iterator callback error      error="failed to check whether iterator.current cursor has been reorged: context deadline exceeded" many  get this error constantly
It used to dissapear after a restart, and now it doesnt
Or is the docker method not supported anymore?

**Comment by dantaik** [comment]
Migrated to https://github.com/taikoxyz/taiko-geth/issues/206
