### ISSUE TITLE
Difficulty Connecting Wallet and Persistent Staking Failures with Taiko Stone NFT on Blazpay Partnership

### ISSUE THREAD

**Issue by cyrilcrypy** [taikoxyz/taiko-mono#16495]
### Describe the bug

Description:
I've encountered multiple issues while attempting to mint and stake the Taiko Stone NFT as part of the recent Blazpay partnership initiative. Initially, the process was hindered due to difficulties in connecting my wallet. After overcoming the connection issue, my attempts to stake the NFT consistently failed, preventing me from participating in the staking benefits.

### Steps to reproduce

Steps to reproduce here.
1. Navigate to the Taiko x Blazpay NFT staking page.
2. Click on "Connect Wallet" to integrate with [Specify Wallet Type - e.g., MetaMask, TrustWallet, etc.].
3. After multiple attempts, the wallet connects.
4. Mint the Taiko Stone NFT successfully.
5. Proceed to stake the minted NFT.
6. Encounter an error leading to a failure in the staking process.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
This is either an issue for blazpay our our discord.
