### ISSUE TITLE
Keep the input value

### ISSUE THREAD

**Issue by datznt** [taikoxyz/taiko-mono#16499]
### Describe the feature request

Please keep the value of the amount when choosing a different token.
For example: Default is ETH then enter value 1. Switch to HORSE and keep the value 1

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
No
