### ISSUE TITLE
Verifying Faucets 

### ISSUE THREAD

**Issue by JordanChipley** [taikoxyz/taiko-mono#16497]
### Describe the bug

Sometimes when its the mid day rush on the block chain sometimes the faucet won't claim. So, I figured out that if you slash the gewi by 25% it will still go through on the blockchain. This will help every save exchange fees later on

### Steps to reproduce

Just reduce the gas by 25%

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
On mainnet the faucet will go away. I think I'll close this issue as we will probably not going to change anything for now. Thanks for the suggestioin.
