### ISSUE TITLE
https://taiko.xyz/ecosystem deploys only deployed app after mainnet launch.

### ISSUE THREAD

**Issue by jayblitz** [taikoxyz/taiko-mono#16508]
### Describe the feature request

Please update the ecosystem dapps. Some of the listed apps are not yet deployed on Taiko. Its will be easier for Users to differentiate which dApps are deployed and which ones aren't by just adding a deployed on Taiko or Live on Taiko tag.

If it is too much of an ask, let's automate it so that once a project selects **Yes** on this file ( https://github.com/taikoxyz/website/issues/new?assignees=&labels=category.enhancement%2Cstatus.needs-triage&projects=&template=add_project.yml ) it will be updated on the Ecosystem dashboard as Live on testnet
<img width="265" alt="Screenshot 2024-03-23 075951" src="https://github.com/taikoxyz/taiko-mono/assets/134429752/bcd31613-7553-4119-900c-c446d877e541">

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
Taiko has had multiple network, if we have to tag each app on our ecosystem page, then there will be multiple tags. 

A better approach in my opinion is after a few month post mainnet, we clean up the ecosystem page and keep only deployed apps.
