### ISSUE TITLE
Bridging

### ISSUE THREAD

**Issue by Fernweh1720** [taikoxyz/taiko-mono#16504]
### Describe the feature request

While bridging the process & claim time is so high if possible to improve.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
Initially we have a larger delay to mitigate potential security issues. We have plan to gradually change the value to smaller values.
