### ISSUE TITLE
Explorer link to a 'Processing' NFT bridge transaction fails

### ISSUE THREAD

**Issue by terminals** [taikoxyz/taiko-mono#16524]
### Describe the bug

When clicking 'View Details' on a pending L2 > L1 NFT bridge transaction, the explorer link that a user is sent to fails. 

The URL a user is sent to looks like this: https://katla.taikoscan.network/%20/tx/0x6c9837815f46d0b7861f9b5f3bb14529b38ea3f60a6af4d424300d90482ab279

Instead it should look like this without the '%20/' in the link above: https://katla.taikoscan.network/tx/0x6c9837815f46d0b7861f9b5f3bb14529b38ea3f60a6af4d424300d90482ab279

It looks like there's a whitespace being added somewhere in the construction of the link - could potentially be getting introduced from either the original JSON config before the base64 encoding process or during the process of decoding/validating against the schema as it doesn't include steps to trim or sanitize the URL strings?

### Steps to reproduce

1. Bridge an NFT from Katla to Holesky
2. While the bridge transfer is in process, visit the 'Transactions' page and click the 'View Details' link for the NFT that was bridged
3. The linked page will display as 'Not Found: the page you are trying to access does not exist'
4. The URL will have '%20/' erroneously included in the URL, which when removed will send the user to the correct explorer link

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by terminals** [comment]
Think I found the culprit: https://github.com/taikoxyz/taiko-mono/blob/main/packages/bridge-ui/scripts/exportJsonToEnv.js

Looks like configuredChains is intentionally excluded from the whitespace trimming run on the rest of the config json files:

```
    if (filename !== 'configuredChains') {
      base64Content = base64Content.replace(/\s+/g, '');
    }
```

**Comment by terminals** [comment]
For reference, here's what I get when inspecting locally - note the space after the katla block explorer: <img width="680" alt="Screenshot 2024-03-25 at 6 07 06 pm" src="https://github.com/taikoxyz/taiko-mono/assets/3211957/38795361-f086-499c-b947-cb1a60a2bd16">

**Comment by KorbinianK** [comment]
Thanks for raising this and the investigation, I'll fix the whitespace in the env!
