### ISSUE TITLE
NfT BRIDGE

### ISSUE THREAD

**Issue by UMARAHMAD4** [taikoxyz/taiko-mono#16521]
### Describe the feature request

THE NFT BRIDGE SUPPOSED TO BE ABLE TO DETECT NFTS ON THE WALLETS WITHOUT FILLING MANUALLY

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
It only detects them on Katla
