### ISSUE TITLE
Taiko Contribution

### ISSUE THREAD

**Issue by canyelo** [taikoxyz/taiko-mono#16553]
### Describe the feature request

I hope this message finds you well. I am reaching out regarding my contributions to the Taiko project throughout  and 2024. I have been an active member of the community, dedicating time and effort to various aspects of the project. I was active in the Taiko discord channel and helped newbies with their problems

I also proposed my ideas and problems on github, which would help improve performance in taiko and, in general, improve our taiko community  = 

![Скриншот 28-03-2024 183611](https://github.com/taikoxyz/taiko-mono/assets/132910894/29085456-b2f2-4c66-8a32-148fd51bc811)
![Скриншот 28-03-2024 183654](https://github.com/taikoxyz/taiko-mono/assets/132910894/b39b7b2c-ae08-492c-ae10-396f92437726)

And I would be grateful to reward me with GitPoap " Taiko Contributor 2024 "
My contribution has been a source of pride for me, and I am willing to continue to support the Taiko project in any way possible. Your help in resolving this issue will mean a lot to me.
I hope @KorbinianK  will answer my request

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
You did not contribute to this repository. You posted a question that does not belong on github and proposed a "feature" that makes no sense, as you can use any wallet you want anyway (I also answered that in the issue). 

Those do not make you a contributor or eligible for any POAPs.
