### ISSUE TITLE
changing the name of the NFT bridge buttons

### ISSUE THREAD

**Issue by oneofthenfts** [taikoxyz/taiko-mono#16562]
give a name to the first button on the NFT **Review** bridge

![image (1)](https://github.com/taikoxyz/taiko-mono/assets/149963982/8d412be4-b8f8-40a3-ab74-cc2e0c3340cf)

because that’s the name of the tab that appears when this button is pressed, this can be seen in the screenshot

but at the moment this button is called **Continue**
![image](https://github.com/taikoxyz/taiko-mono/assets/149963982/a87096e5-5688-45a7-a327-0d6444839db2)

it turns out we have two **Continue** buttons

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
There is nothing wrong with the naming of the buttons.

**Comment by oneofthenfts** [comment]
> There is nothing wrong with the naming of the buttons.

when you click on a button called **continue** and find yourself on a page called **review**, is that correct?
ok then closed, I agree if you like it that way and will go to the mainnet with such buttons, good luck

**Comment by oneofthenfts** [comment]
but if you change the names of these buttons on the mainnet even though you are now saying that there is nothing wrong with them, then you will turn out to be an even bigger amateur than I think at the moment

**Comment by oneofthenfts** [comment]
@KorbinianK according to your logic, you can write almost any word on all buttons, for example continue, and it doesn’t matter what the name of the tab you find yourself on is when you click on this button. this is very funny. I imagine, for example, X or Facebook or whatever, where all the buttons say continue and people like you checked it and said that everything is fine and there is nothing wrong with it lol

**Comment by oneofthenfts** [comment]
did you even understand this post? what buttons am I talking about?

**Comment by oneofthenfts** [comment]
this button is not correct because it leads to the review tab

![Screenshot from 2024-03-29 20-36-21](https://github.com/taikoxyz/taiko-mono/assets/149963982/c833f90d-362d-4d16-9469-6dc2d9c4cdea)

this button is correct because it leads to the bridge completion tab and is clicked to confirm that the review is correct

![Screenshot from 2024-03-29 20-36-52](https://github.com/taikoxyz/taiko-mono/assets/149963982/43a9bcce-cb3a-43fb-8afe-41cbdcbd3937)

but if you focus only on text, then these buttons are no different for you, you understand this, they simply have no meaning other than spam clicks

but if you don’t understand this, then I won’t convince you anymore, I don’t care about your project then, for me, those who simply cannot understand such basic things are not those whom I can consider a good company
