### ISSUE TITLE
Balance showing error (Holeksy)

### ISSUE THREAD

**Issue by wajanda** [taikoxyz/taiko-mono#16586]
### Describe the feature request

![11](https://github.com/taikoxyz/taiko-mono/assets/132693306/14d66168-5dd5-46a8-8441-6a260dc2e058)

When I have some balannce ETH on my wallet. but it shows N/A as my balance in the bridge

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Maxounft82** [comment]
Ce probleme d'affichage est courant pas que sur Taiko en général en rafraichissant la page le solde ETH de votre portefeuille s'affichera.

**Comment by KorbinianK** [comment]
Fixed in the next testnet release
