### ISSUE TITLE
allow contracts to read L2's parent block timestamp

### ISSUE THREAD

**Issue by godofweb** [taikoxyz/taiko-mono#16581]
### Describe the feature request

this feature it may be very useful to incentivize block proposers for liveness.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by dantaik** [comment]
Done here already. https://github.com/taikoxyz/taiko-mono/pull/16425
