### ISSUE TITLE
docs: Update link in how_taiko_proves_blocks.md

### ISSUE THREAD

**Issue by alexanderblv** [taikoxyz/taiko-mono#16597]
### Describe the feature request

(https://github.com/taikoxyz/taiko-mono/blob/39d4be6e003d5e1c9d182dbaa76c54abe09a6112/packages/protocol/docs/how_taiko_proves_blocks.md?plain=1#L109)

Line 109, the data is outdated. A big update has been released. Here is a new link:
(https://docs.soliditylang.org/en/v0.8.25/units-and-global-variables.html)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by amis13** [comment]
jep x2

**Comment by amis13** [comment]
done: https://github.com/taikoxyz/taiko-mono/pull/16643

**Comment by saeed1212-dot** [comment]
hujkhjk

**Comment by inuyasha1060** [comment]
よくわからない
