### ISSUE TITLE
docs: update link in tokenomics-whitepaper.tex

### ISSUE THREAD

**Issue by alexanderblv** [taikoxyz/taiko-mono#16598]
### Describe the feature request

https://github.com/taikoxyz/taiko-mono/blob/39d4be6e003d5e1c9d182dbaa76c54abe09a6112/packages/protocol/docs/tokenomics-whitepaper.tex#L55)

Line 55, the data is outdated. A big update has been released. Here is a new link: https://docs.soliditylang.org/en/v0.8.25/

For some reason I can't create a Pull Request and because of this I have to create Issue

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by amis13** [comment]
jep

**Comment by amis13** [comment]
done: https://github.com/taikoxyz/taiko-mono/pull/16643

**Comment by alexanderblv** [comment]
I'm sorry for the question, but I won't get GitPOAP or Contibutor in Taiko for this issue and for #16597?

**Comment by alexanderblv** [comment]
Hey! @d1onys1us @JBScaled @dantaik
Still waiting for your teply!

**Comment by king-Alex-d-great** [comment]
Is this completed?

**Comment by alexanderblv** [comment]
> Is this completed?

The problem is solved, but I do not know if I am included in the Contributors list

**Comment by adaki2004** [comment]
> > Is this completed?
> 
> The problem is solved, but I do not know if I am included in the Contributors list

For opening an issue, you will not get any contribution badge or so. It needs to be a PR merged into our repo to be eligible.

**Comment by kobeism** [comment]
Good stuff

**Comment by alexanderblv** [comment]
> > > Is this completed?
> > 
> > 
> > The problem is solved, but I do not know if I am included in the Contributors list
> 
> For opening an issue, you will not get any contribution badge or so. It needs to be a PR merged into our repo to be eligible.

This will be done in the near future. @amis13  wrote that my issue is satisfied.
https://github.com/taikoxyz/taiko-mono/issues/16598#issuecomment-2036231239

**Comment by mans2030** [comment]
looking good guys

**Comment by alexanderblv** [comment]
@d1onys1us @dantaik @davidtaikocha  hey! 
This and https://github.com/taikoxyz/taiko-mono/issues/16598 PRs merged into repo in https://github.com/taikoxyz/taiko-mono/pull/16876. According to https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md I have to get the Contributor role and GitPOAP2024. I see no one has received GitPOAP or Contributor for merge https://github.com/taikoxyz/taiko-mono/pull/16876
Think it's some kind of mistake that we didn't get it.

**Comment by d1onys1us** [comment]
@gitpoap-bot award @alexanderblv
