### ISSUE TITLE
Remove password values from non-test source-files

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#16653]
### Describe the bug

Currently there are the following (at least) passward hardcoded in our source file. I think we should try our best to remove them:

<img width="546" alt="Screenshot 2024-04-05 at 09 08 09" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/cfa33c71-c999-4d07-bca0-aaf7428e1987">
<img width="593" alt="Screenshot 2024-04-05 at 09 08 19" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/bc88cf19-2403-4ac7-8f32-84a8a865a227">
<img width="645" alt="Screenshot 2024-04-05 at 09 08 23" src="https://github.com/taikoxyz/taiko-mono/assets/99078276/f758b521-e637-4d9b-9c02-9fdbd12a4560">

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by cyberhorsey** [comment]
this has been completed
