### ISSUE TITLE
Dynamic roadmap update

### ISSUE THREAD

**Issue by anglosax770** [taikoxyz/taiko-mono#16682]
### Describe the feature request

Dynamically update the roadmap visualised on the website so interested visitors can track the project progress by approximate dates or at least with visual actual stages.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by farshad004** [comment]
good improve

**Comment by Fortune-rust** [comment]
This is needed in order to be able to plan ahead and be able to track ones activity done and ones remaining.
