### ISSUE TITLE
chore(repo): decoding the expression

### ISSUE THREAD

**Issue by potiore** [taikoxyz/taiko-mono#16748]
https://github.com/taikoxyz/taiko-mono/blob/e992ec902583c9f726bf915c6fd7b00289977460/packages/relayer/processor/processor.go#L207

"rn" is short for "right now", which means "now", it might be better to use the full form for clarity.

**Comment by VinhSiuCiu** [comment]
Great ! Thanks

**Comment by mans2030** [comment]
looking good guys

**Comment by Itscryptogambler** [comment]
That's the right way keep it going

**Comment by cyberhorsey** [comment]
Jesus Christ

**Comment by d1onys1us** [comment]
@gitpoap-bot award @potiore
