### ISSUE TITLE
chore (repo): typos in taikoxyz / taiko-mono

### ISSUE THREAD

**Issue by alexanderblv** [taikoxyz/taiko-mono#16761]
https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/eventindexer/stat.go#L15

dependent -> dependent (correct spelling of the word).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/relayer/event.go#L21

and it's success -> and its success ("it's" is an abbreviation of "it is", and "its" is a possessive pronoun).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/bridge-ui/src/stores/modal.ts#L3

We make this global because we need to be able to -> This is made global because we need to be able to (clarifying sentence introduction).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/bridge-ui/src/components/Button/Button.svelte#L35

Remember, with Tailwind's classes you cannot use string interpolation -> Remember, with Tailwind's classes, you cannot use string interpolation (a comma has been added to separate the subject and predicate).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/relayer/pkg/proof/block_header.go#L13

blockHeader fetches block via rpc, then converts an ethereum block to the BlockHeader type that LibBridgeData -> blockHeader fetches a block via RPC, then converts it to the BlockHeader type that LibBridgeData (added the missing preposition phrase "a block").

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/relayer/processor/estimate_gas.go#L16

estimateGas estimates the gas for a ProcessMessage call. it will add a gasPaddingAmt -> estimateGas estimates the gas for a ProcessMessage call. It will add a gasPaddingAmt (fixed an error in capitalization of "it").

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/relayer/processor/is_profitable.go#L13

isProfitable determines whether a message is profitable or not. It should -> isProfitable determines whether a message is profitable or not. It should (the sentence is correct)

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/blobstorage/pkg/metrics/metrics.go#L15

Serve starts the metrics server on the given address, will be closed when the given -> Serve starts the metrics server on the given address and will be closed when the given (the sentence separator has been changed for better connectivity).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/bridge-ui/src/components/Bridge/TokenAmountInput.svelte#L180

There is no reason to show any error/warning message if we are computing the balance -> There is no reason to show any error/warning message if we are computing the balance (the sentence is correct).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/protocol/utils/generate_genesis/erc20.ts#L11

deployERC20 generates a L2 genesis alloc of an ERC-20 contract, -> deployERC20 generates an L2 genesis allocation of an ERC-20 contract, (fixed an error in the sentence structure).

https://github.com/taikoxyz/taiko-mono/blob/e6f576e09a0d0bcf79666ef2d92787d49a5086fa/packages/eventindexer/disperser/disperser.go#L21

Disperser is a subcommand which is intended to be run on an interval, like a cronjob, to parse the indexed data from the database, and generate time series data that can easily be displayed via charting libraries. -> Disperser is a subcommand intended to be run at intervals, like a cronjob, to parse indexed data from the database and generate time series data that can be easily displayed via charting libraries. (optimized the offer for better readability and connectivity).

**Comment by soandwhat** [comment]
Thanks! I'll fix it now

**Comment by d1onys1us** [comment]
see my reply here: https://github.com/taikoxyz/taiko-mono/pull/16774#issuecomment-2071147233
