### ISSUE TITLE
We need an easy way to fund Holesky & Katla faucet

### ISSUE THREAD

**Issue by Fortune-rust** [taikoxyz/taiko-mono#16775]
### Describe the feature request

Lack of faucet most times create frustration for us who interact with the testnet more often.

Please this is of genuine concern and would love you guys to look into it, since it id the last testnet.

Thank You!

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by jeanjacquessabberlatz** [comment]
Lack of faucet most times create frustration for us who interact with the testnet more often.

Please this is of genuine concern and would love you guys to look into it, since it id the last testnet.

Thank You!

**Comment by KorbinianK** [comment]
There are several faucets available and they work just fine. Sometimes there is a big demand and you may need to wait a bit, but we have no influence on faucets.
