### ISSUE TITLE
Bridge BUG - Token type and balance display errors

### ISSUE THREAD

**Issue by SW-Heart** [taikoxyz/taiko-mono#16822]
### Describe the bug

Overview: After switching networks, the displayed token type and balance do not update.

### Steps to reproduce

Details:
Issue presentation:
When I use the bridge to transfer HORSE tokens on the Holesky network, the balance is displayed as 50.
<img width="616" alt="image (2)" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/57aa16c7-ffdb-497d-8366-f4b278d45740">
Next, I switched to the Katla network, and the quantity of HORSE tokens still displays as 50, although the actual value is not this number.
<img width="556" alt="image (3)" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/7da4a3df-25e9-45cd-9265-907e50519978">
Now, even if I open the token list and click on HORSE again to try to refresh the balance, it does not work.
<img width="573" alt="image (4)" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/41319507-333b-48cf-8614-8fcc75ad79fc">
Ultimately, only when I first click on another token, such as ETH, and then click on HORSE in the second step, does the balance display correctly. The correct balance is shown in the following image.
<img width="632" alt="image (5)" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/be88e0d2-74e4-42ae-9e01-45886ba65491">
The balance display issue has been ongoing. The first time was when switching wallets did not refresh the balance, which seems to have been resolved now. The second time involves switching networks not refreshing token types and balances. It appears that token types are now refreshing, but the balance still displays incorrectly. Please review and resolve this issue.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Thanks for reporting this, it is already fixed in the next testnet version.
