### ISSUE TITLE
Unable to send ERC20 Token From Hekla to Holesky

### ISSUE THREAD

**Issue by iSatbir** [taikoxyz/taiko-mono#16847]
### Describe the bug

There is an error while attempting to Bridge Horse token from Hekla to Holesky.
It throws an error:

> **Failed to send
> There was an issue attempting to send ERC20 token.**

See the attached screenshot.
![Error Sending ERC20 Token](https://github.com/taikoxyz/taiko-mono/assets/130428158/1b0b84d2-5d26-4979-95b1-fd8c92dc998b)

### Steps to reproduce

Mint Horse Token on Holesky Network.
Bridge to Hekla Network.
Bridge Back to Holesky from Hekla and it'll throw this error.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by camille3567** [comment]
This problem still exists
<img width="1208" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/167544632/87040ec2-bf98-4071-b73d-4dbfb3b0e847">
