### ISSUE TITLE
Running a Taiko node docs

### ISSUE THREAD

**Issue by brachsterX** [taikoxyz/taiko-mono#16857]
### Describe the bug

[Documentation](https://docs.taiko.xyz/guides/run-a-taiko-node/) commands needs update.

1.
![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/61cfd133-bc4c-4c62-b06d-2b5a9e4c1d8c)
Command should be `docker compose --profile l2_execution_engine up -d`

2. 
![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/cdbede9c-9eda-4083-945b-59f057fbe024)
Result should be chainId as 0x28c61 (167009)

3. Running a Proposer docs
![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/c4aebab9-0e03-46c4-8c66-dcbca6a1ca80)

Command should be `docker compose --profile proposer up -d`. There is an extra dash on "-up".

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by brachsterX** [comment]
wen poap @RogerLamTd (:

**Comment by RogerLamTd** [comment]
@gitpoap-bot please give @brachsterX a poap
