### ISSUE TITLE
Pending Transaction Filing

### ISSUE THREAD

**Issue by gweyzaguilar** [taikoxyz/taiko-mono#16859]
### Describe the bug

Swap is not working. Pending transaction filling-up, speed up several times already the recent transaction in the history but still not working to be completed.

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by SuccessAyo** [comment]
Currently experiencing this issue on katla, tried bridging ETH to Holesky about an hour ago but it remains "pending" 
![Screenshot (99)](https://github.com/taikoxyz/taiko-mono/assets/85240438/02c59549-08e6-4f26-a562-bd2cb97c9969)

**Comment by gweyzaguilar** [comment]
![Screenshot_20240427_165856](https://github.com/taikoxyz/taiko-mono/assets/79240644/7fccb8ec-e516-4909-affe-efbccc28c9df)

More than 24 hrs now, Hekla swap is still pending.
