### ISSUE TITLE
typo in explorer url

### ISSUE THREAD

**Issue by Ghonghito** [taikoxyz/taiko-mono#16851]
### Describe the bug

When transaction is completed and clicking on "View on explorer" its redirects to explorer.**helka**.taiko.xyz instead of explorer.**hekla**.taiko.xyz
![1](https://github.com/taikoxyz/taiko-mono/assets/73051326/dc1f607b-2fe1-4934-9382-7daf44b7919a)

### Steps to reproduce

just swap or add liqudity

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Wrong repo, but has been fixed already. :) Thanks for noticing
