### ISSUE TITLE
deceptive site alert/ taiko hekla

### ISSUE THREAD

**Issue by lizyld** [taikoxyz/taiko-mono#16855]
### Describe the bug

this keeps showing might be error.,

![440561109_7115727475204067_5833836317282835240_n](https://github.com/taikoxyz/taiko-mono/assets/89774577/a921a27e-b959-4407-83bb-80315df610aa)

on the new page

### Steps to reproduce

Steps to reproduce here.
need to check if the site is legit

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
I don't know what app or plugin this is, it's not from us

**Comment by lizyld** [comment]
ok... thank for update
