### ISSUE TITLE
The bridge transaction from hekla to holsky is lost 

### ISSUE THREAD

**Issue by nheoshikuyanhemo** [taikoxyz/taiko-mono#16852]
### Describe the bug

The bridge transaction from Hekla to Holsky was lost before being claimed,
![Screenshot_20240425-184235_Mises](https://github.com/taikoxyz/taiko-mono/assets/32210699/74b74e6c-f561-4ab3-baff-c2fd1120b0e2)

Hash transactions:
0x908e33378ccff1a9a143a58572cb9719cf76a33b638f6a979e08e0cd835571d9

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by nheoshikuyanhemo** [comment]
Transaction 
0x908e33378ccff1a9a143a58572cb9719cf76a33b638f6a979e08e0cd835571d9

**Comment by ibuyshite** [comment]
it's normal .. it takes 2-3 min to update if it is lost
there was no need to open an issue bout this 

just reload after 10 min it will appear

**Comment by nheoshikuyanhemo** [comment]
This transaction has been going on for more than a week

Pada Kam, 25 Apr 2024 19:52, RB ***@***.***> menulis:

**Comment by Lucifer123232** [comment]
working fine right now.
try to update the fees to aggressive and speedup the transaction

**Comment by Lucifer123232** [comment]
same for me too. the transaction is successful but it's not yet updated on holsky

**Comment by KorbinianK** [comment]
@nheoshikuyanhemo 

You bridged 5 days before Hekla publicly launched and the relayer was not working at this point. 

It would require some manual effort to recover your funds and we more important priorities. Frankly, this was your own fault, do not interact with dapps when you don't know whether they are fully working or not. 

This is a testnet, consider it a "lesson learned" as no real funds were lost.

**Comment by nheoshikuyanhemo** [comment]
Oke No problem, I'm just testing, I got the hekla chain before it went
public, but it's already on chainlist.org . So I used it

Pada Jum, 26 Apr 2024 17:03, Korbinian ***@***.***> menulis:
