### ISSUE TITLE
Bridge from Ketla to Holesky 

### ISSUE THREAD

**Issue by Neotravolta** [taikoxyz/taiko-mono#16853]
### Describe the bug

Description of the bug here.
Bridging from Hekla to Holesky keep failing but from Holesky to Hekla is very successful 

### Steps to reproduce

Steps to reproduce here.
Just connect your wallet to bridge, switch network from Holesky to Hekla, them try to bridge 
![Screenshot_20240425_140632_Mises](https://github.com/taikoxyz/taiko-mono/assets/142179013/419598d7-a893-4c4f-a585-71176d57a912)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Has been fixed,try again
