### ISSUE TITLE
Adding liquidty

### ISSUE THREAD

**Issue by rona582** [taikoxyz/taiko-mono#16866]
### Describe the bug

Description of the bug here.everytime i choose usdc and eth i cant enter the amount that i want to create pools

### Steps to reproduce

Steps to reproduce here.make it faster sometime cant see the balance

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Jerrystarknet** [comment]
Currently, adding liquidity provides transaction fail error. Would be great to work on this also.

**Comment by Fortune-rust** [comment]
yes please
i faced the same issue, adding of liquidity seems to be an issue.
I can't seem to place a figure on both the eth & usdc space simultaneously.
