### ISSUE TITLE
Node error

### ISSUE THREAD

**Issue by SW-Heart** [taikoxyz/taiko-mono#16863]
### Describe the bug

When I run the new Hekla testnet, I encounter this error every time I synchronize to the latest block: 
`taiko_client_driver-1 | ERROR[04-26|04:40:21.716] Block batch iterator callback error error="failed to decode tx list: beacon client not found"`. 
Restarting the node allows synchronization to the latest block before the error occurs again, and then the blocks no longer update, but transactions keep accumulating. Previously, everything was running smoothly with Katla and blocks were being produced, but with Hekla, this error persists. Many people have encountered the same issue.

### Steps to reproduce

Start or restart the node, initially everything is normal.
<img width="1469" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/ff70dfe5-667e-4f72-8f0a-85dea9f5e4c7">
When syncing to the latest block, an error occurs
<img width="1234" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/5631fc1a-23c3-4d19-a1b9-55789926d06c">
Blocks no longer update, but transactions continue to accumulate.
<img width="1465" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/c76e9fd9-6ff6-4b66-94ce-0c6e6a25a21e">
Since I've seen over a dozen people encountering this issue, it seems not to be a coincidence. Please investigate whether it might be a problem with the project's code
I have tried both self-hosted RPCs and public, paid RPCs, but the problem remains unresolved.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Is `L1_BEACON_HTTP` a valid value in `.env`?

**Comment by SW-Heart** [comment]
<img width="848" alt="image" src="https://github.com/taikoxyz/taiko-mono/assets/39661597/a88fe80d-0a40-453d-abcb-ef3ab4f2e94b">
**Required if you are running a driver or prover, but not proposer.**
This shows that the proposer does not need L1_BEACON_HTTP

**Comment by davidtaikocha** [comment]
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/39661597/325855603-a88fe80d-0a40-453d-abcb-ef3ab4f2e94b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMDg4MDgsIm5iZiI6MTcxNDEwODUwOCwicGF0aCI6Ii8zOTY2MTU5Ny8zMjU4NTU2MDMtYTg4ZmU4MGQtMGE0MC00NTNkLWFiY2ItZWYzYWI0ZjJlOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDA1MTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZWFiN2YzMDg5ZWZhNmRmMDdlMGY0YTg2NTY2MjZhMGIzYWFkYTMzZjU0MDdjZTc1NmI1MTIxYzRjYzBlMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EhVrZnCp5mONa040HAE_Gp92x7aZJm8XzVttKgyzHjM"> **Required if you are running a driver or prover, but not proposer.** This shows that the proposer does not need L1_BEACON_HTTP

Actually `L1_BEACON_HTTP` is required for all, sorry for the wrong comment.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/simple-taiko-node/pull/213
