### ISSUE TITLE
Bridging  Assets  Not Confirming

### ISSUE THREAD

**Issue by zipzap13** [taikoxyz/taiko-mono#16861]
### Describe the bug

I bridge eth testnet from holesky to hekla,it consumes a lot of time  but it does not proceed to confirming steps.   It will always load in processing but not in the state of confirming.I hope this will be address . This is a serious issue.
![sadasd](https://github.com/taikoxyz/taiko-mono/assets/110014418/9136d574-cbf6-4297-b34c-73c8d2f59549)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
The network is under heavy load, it's normal that it takes a while. We will work on a timeout notification to make it clearer. Just check your wallet, your transaction is pending and after a while goes through.

**Comment by rona582** [comment]
I try to add lid pool but everytime put usdc and eth eth are not showing
