### ISSUE TITLE
Hekla Testnet Dashboard

### ISSUE THREAD

**Issue by OverflowDev** [taikoxyz/taiko-mono#16875]
### Describe the feature request

Create an interactive and user-friendly dashboard for the Hekla testnet, providing real-time insights into network performance, protocol updates, and ecosystem health. This dashboard will allow users to monitor key metrics such as block issuance rates, gas usage, protocol improvements, and reported issues. Users can also suggest features, report bugs, and engage with the Taiko community directly through the dashboard interface. This dashboard will enhance user experience, facilitate network monitoring, and foster community engagement within the Taiko(Hekla) testnet ecosystem

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Status page is here: https://explorer.hekla.taiko.xyz/stats
