### ISSUE TITLE
Introduce a hub for users on major protocols

### ISSUE THREAD

**Issue by energybee** [taikoxyz/taiko-mono#16873]
### Describe the feature request

An avenue for users to connect and address ongoing on-chain issues live.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Stop spamming useless requests if you want to keep your account.
