### ISSUE TITLE
node is error not syncing

### ISSUE THREAD

**Issue by lizyld** [taikoxyz/taiko-mono#16880]
### Describe the bug

When I run the new Hekla testnet, I encounter this error every time I synchronize to the latest block:
always not found.
Restarting the node allows synchronization to the latest block before the error occurs again, and then the blocks no longer update, but transactions keep accumulating everything was running smoothly with previous node and blocks were being produced, but with Hekla, this error cant make. i hope you post this on

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
@lizyld please provide screenshots/logs

**Comment by RogerLamTd** [comment]
closing as stale, please reopen if there are still issues @lizyld
