### ISSUE TITLE
Failed to deploy l1 contracts

### ISSUE THREAD

**Issue by mask-pp** [taikoxyz/taiko-mono#16898]
### Describe the bug

Use `taiko-mono@1d5b04cac37e87fd9bdf4ac15488c8c4ef0cb141`,  and run `forge script script/DeployOnL1.s.sol:DeployOnL1 ...` script and then appear revert:
![image](https://github.com/taikoxyz/taiko-mono/assets/32827930/c7ee2c54-c101-4a40-9008-76c66b61da44)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by mask-pp** [comment]
It reverts in this function `_authorizePause`:
![image](https://github.com/taikoxyz/taiko-mono/assets/32827930/55f1bf0b-24fb-41ce-a6c3-f49636a91c65)

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/16897
