### ISSUE TITLE
TEKLA BRIDGE NOT RESPONDING

### ISSUE THREAD

**Issue by tizzyvegas** [taikoxyz/taiko-mono#16895]
### Describe the bug

The bridging website would say  bridge  site is not active

### Steps to reproduce

but if you click on the bridge from the drop down it will load

### Spam policy

- [x] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
What's Tekla? We only have Hekla and Katla

**Comment by wealthpos1** [comment]
This is True, it only shows the HORSE token, and it will later say Horse token is not available, what I did was bridge from Holesky to Tekla, you can try that.

**Comment by KorbinianK** [comment]
There is no Tekla... If you claimed your horse they are in your wallet.
