### ISSUE TITLE
Gas/Transaction Fee Optimization

### ISSUE THREAD

**Issue by Jerrystarknet** [taikoxyz/taiko-mono#16905]
### Describe the feature request

Since we are deployed on Testnet, most of us won't be necessarily concerned about the Transaction fees. Approving spending limit cost about $0.3 and swapping cost $1.5 while providing LP cost $2.99. These quotes were taken while ETH GWEI was at 3. 
The introduction of BLOBS have drastically reduced Transaction cost on all L2s and will be a major setback if we deploy on mainnet with this fees.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by rchoudhary99** [comment]
I also have the same bt later it will bhi auto fixed

**Comment by Fortune-rust** [comment]
I agree with this too.
