### ISSUE TITLE
SWAP FUNCTION ERROR.

### ISSUE THREAD

**Issue by wealthpos1** [taikoxyz/taiko-mono#16901]
### Describe the bug

The swap function only works for WETH and USDC the rest are reporting failed transaction.

### Steps to reproduce

![Screenshot (30)](https://github.com/taikoxyz/taiko-mono/assets/107282829/272cbb34-5e1a-4a6e-af9d-0dbbf851421f)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by maguro899** [comment]
ok i can  provide to this repository if yuo can assigne to me please . 
thanks

**Comment by Jerrystarknet** [comment]
Yes, this issue is still pending. Hope it gets fixed soon
