### ISSUE TITLE
Tons of ETH

### ISSUE THREAD

**Issue by gr8collector** [taikoxyz/taiko-mono#16923]
### Describe the bug

This happened on Tekla.   i did a swap into ETH last month, not sure what token i used.   But it gave me the best returns i have gotten.   Wished it were on mainnet and we would be golden.   I remember that i was thinking of receiveing around 1 ETH but instead got 2200++ ETH.   I think the pools were messed up at the time.  Hope it was fixed as economy would be messed up if not.

### Steps to reproduce

i will try and look for the transaction on my wallet and update here if i manage to find it

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
It's a testnet where nothing has any value, so the pools are also just tonplay around. The swap contracts are 100% uniswap, so you can assume there are no bugs.
