### ISSUE TITLE
Inconsistency Between MetaMask Transaction Status and Blockchain Explorer Confirmation

### ISSUE THREAD

**Issue by fzkvn** [taikoxyz/taiko-mono#16936]
### Describe the bug

Hello,

I've encountered a significant issue where there is a discrepancy between the transaction status as reported by Metamask and the actual confirmation status on the blockchain explorer. This inconsistency could potentially lead to users submitting duplicate transactions, under the assumption that their initial transaction failed, based on Metamask's status report.

**Issue Details:**
- Metamask indicates that the transaction has "Failed."
- However, the blockchain explorer shows the transaction as "Successful" with confirmation by 231 blocks.

**Potential Impact:**
- Users who do not cross-verify the transaction status on a blockchain explorer might attempt to resend the transaction, assuming it has failed as per Metamask's/Other Wallet indication.
- This could result in unintended duplicate transactions, leading to unnecessary network congestion and potential loss of funds due to double spending on fees.

**Transaction Information:**
- Transaction Hash: `0x1e1500c7c103b2e58d877760e1bde9bde96dfe429220de86a6a221a39d6510c`
- Metamask Status: Failed
- Blockchain Explorer Status: Success, Confirmed by 231 blocks
- Block: 66042
- Timestamp: April 30, 2024, 05:13:00 PM +7 UTC

I am including a screenshot for your reference. It is crucial to address this issue to prevent user confusion and to ensure that the Metamask interface accurately reflects the true status of transactions on the blockchain.

Thank you for looking into this matter.
![Screenshot 2024-04-30 185106](https://github.com/taikoxyz/taiko-mono/assets/167605036/ab0b0aff-78ed-4762-809c-18bfd62f46c2)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Could you share the link of this page? looks like the transaction hash is not on chain, guess its reorged by a L1 reorg.

**Comment by valerivakar** [comment]
Could you share the link of this page? looks like the transaction hash is not on chain, guess its reorged by a L2 reorg

**Comment by fzkvn** [comment]
> Could you share the link of this page? looks like the transaction hash is not on chain, guess its reorged by a L2 reorg

https://blockscoutapi.hekla.taiko.xyz/tx/0x1e1500e7c103b2e6d877f60e1bde9bde96dfef429220ed6a6a6a221a39d6510c
