### ISSUE TITLE
Inability to simultaneously add liquidity between the $eth and $usdc space.

### ISSUE THREAD

**Issue by Fortune-rust** [taikoxyz/taiko-mono#16942]
### Describe the bug

In the add liquidity feature, i cannot seem to place the amount of the 2 pairs which i would love to add as liquidity. If i decide to set one so it can run the other, it still gives me an empty space on the other liquidity.

### Steps to reproduce

1. I should be able to set the price at which i want to add as liquidity.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Sammy244** [comment]
I verify that this issue is not a spam or scam

**Comment by 2manslkh** [comment]
Can you provide more details on the range of liquidity you are adding?
