### ISSUE TITLE
Taiko themed memory game which encompasses drumming, dancing , memory and rhythm pattern sequences.

### ISSUE THREAD

**Issue by UKBurger** [taikoxyz/taiko-mono#16954]
### Describe the feature request

**A** great project to integrate with Taiko network could be a multiplayer Taiko battle game. Players could challenge each other in rhythmic duels, showcasing their drumming skills and competing for high scores. It would be a thrilling and interactive experience! 🥁🔥

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Feel free to start developing and maybe apply in the next grands round.

**Comment by UKBurger** [comment]
Okay I will get to it , btw when is the taiko mainnet happening, a fixed
date I meant

**Comment by Olajpow** [comment]
When is the mainnet
