### ISSUE TITLE
Hekla To Holeskey Nft Bridge Failed 

### ISSUE THREAD

**Issue by Goodluckigweze** [taikoxyz/taiko-mono#16957]
### Describe the bug

Description of the bug here. [I don't know if I will classify this as a technical issue, so today I tried bridging the blazepay x taiko nft I minted from the galxe task from hekla to holeskey testnet, but it did not go through. Received a transaction failed error message and I have enough funds on hekla chain to cover for the gas fee.

After the transaction failed, I switched the chain to holeskey, to bridge the new year nft i minted from mercl nft's page on katla 
testnet, which i bridged back then to holeskey testnet and the transaction failed. And for the record I already changed the RPC several times to know if it is an RPC issue but the transaction still did not go through.

So now I don't know if the error message bug and glitches am getting is from my end. I guess that's for the team to find out and get back to me. I will be anticipating your response, guess it's a technical problem after all.]

### Steps to reproduce

Steps to reproduce here.
Since it is a technical issue, it's all upto the team. I already explained every tiny details above

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Please provide relevant asdresses and transactions

**Comment by KorbinianK** [comment]
stale
