### ISSUE TITLE
Fee calculation

### ISSUE THREAD

**Issue by brachsterX** [taikoxyz/taiko-mono#16962]
### Describe the bug

Running the node overnight, is this normal for the fees to exponentially increase like this after not being able to propose a block?
I'm only running a proposer.

![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/bec139d2-44b4-4ce7-bf5a-d3a2111c3db3)

### Steps to reproduce

Some set .env values:
```
BLOCK_PROPOSAL_FEE=10
MAX_TIER_FEE_BUMPS=5
TX_GAS_LIMIT=3000000 (default value that came with simple-taiko-node)
```
### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Fixed by https://github.com/taikoxyz/taiko-client/pull/788 , plz restart `simple-taiko-node` and give another try, thanks for the report :)

**Comment by brachsterX** [comment]
Thanks @davidtaikocha wen poap (:
