### ISSUE TITLE
Taiko socialfi

### ISSUE THREAD

**Issue by Camari-usha** [taikoxyz/taiko-mono#16965]
### Describe the feature request

1. Description of the feature request here. A socialfi app that suppports the chain{taiko} and help create equality and chance for people who are looking to create visibility and commjnity for themselves and their project but targeting only users of a particular chain {e.g Fantasy top, farcaster etc}. 
2. Just like every other chain rigth now, it has become a fact that having a socialfi helps to retain users and i feel it should not be overlooked y the taiko team

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
That is not a feature, but a new app.
