### ISSUE TITLE
Bridge Behavior

### ISSUE THREAD

**Issue by brachsterX** [taikoxyz/taiko-mono#16982]
### Describe the bug

Is this behavior intentional when bridging?

On https://bridge.hekla.taiko.xyz/transactions - the status reports Pending (screenshot taken after 15mins of tx being approved)

![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/a351ba29-ed48-4dd4-ac84-a05e1b170f19)

However on explorer, the transaction reports Success. 

![image](https://github.com/taikoxyz/taiko-mono/assets/97795503/ef72bd08-4bff-4890-9abb-da98e7eb3d5f)

transaction: https://hekla.taikoscan.network/tx/0x233e30b4e021712e88987616ebce1f38131e900601257a32680795301851c5cf

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
The bridging process consists of two steps. One transaction on the source chain and one the destination chain.

The explorer shows you only the source one.

Once the message has been relayed to the destination chain, the status changes to "claim". You can then claim yourself or the relayer claims for you. The different statuses are explained behind the (?) icon.
