### ISSUE TITLE
chore: update version link in go.mod

### ISSUE THREAD

**Issue by 1uckyjack** [taikoxyz/taiko-mono#17017]
https://github.com/taikoxyz/taiko-mono/blob/5bff52f6d830dddaee16a3959f71feba2355043c/go.mod#L34

The data is outdated, a new version `v2` has been released. The correct link will look like: `gopkg.in/go-playground/assert.v2 v2.2.0`

**Comment by mask-pp** [comment]
Thanks for the reminder, We can update dependence by using the command `go mod tidy`.

**Comment by mask-pp** [comment]
Also, recommend using "github.com/stretchr/testify".
