### ISSUE TITLE
doc: typo in PR #17039

### ISSUE THREAD

**Issue by yourela** [taikoxyz/taiko-mono#17042]
https://github.com/taikoxyz/taiko-mono/pull/17039/files
Typo in line 53
I have reviewed this PR and most likely there is a typo here, it should be `TaikoRequestProofBody`
![image](https://github.com/taikoxyz/taiko-mono/assets/163650682/231b2eb6-0985-4f8b-9e91-2cb9da68e5ae)

**Comment by YoGhurt111** [comment]
Sorry for the late reply.
Raiko is our multi-proofs system. 
For more information, you can see https://github.com/taikoxyz/raiko.
