### ISSUE TITLE
Bridge the eth from holesky to hekla , but no reflection....

### ISSUE THREAD

**Issue by jamescjw** [taikoxyz/taiko-mono#17085]
### Describe the bug

Bridge the eth from holesky to hekla , but no reflection....

### Steps to reproduce

1. using bridge 
2. holesky to hekla
![image](https://github.com/taikoxyz/taiko-mono/assets/50795515/72b582c5-6f0d-42d2-bb24-f8151176ce54)
3. processing a long time, no tx in taikoscan 
![image](https://github.com/taikoxyz/taiko-mono/assets/50795515/3ad4d38c-56ec-4fe1-822c-acf9991f1616)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
You are bridging from Holesky to Hekla. So the bridge transaction shows up on Holesky.
