### ISSUE TITLE
docs:Make the link to the guide correct

### ISSUE THREAD

**Issue by dev1lon** [taikoxyz/taiko-mono#17113]
## Website:https://bridge.hekla.taiko.xyz/

When you click on the **_guide_**, I get to the start page of [docs.taiko ](https://docs.taiko.xyz/start-here/getting-started/)
![1](https://github.com/taikoxyz/taiko-mono/assets/90638030/3457bfe7-bcc5-42ed-a0f0-d4f2a89fc39c)
### But I would like, when you click on a guide, to immediately go to the [page with the guide](https://docs.taiko.xyz/guides/set-up-your-wallet/) and not look for it in the list on the left
![image](https://github.com/taikoxyz/taiko-mono/assets/90638030/5bff415c-10a0-47e2-a0fb-8b56a89a9e5f)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by KorbinianK** [comment]
Thanks for the suggestion.
