### ISSUE TITLE
Open External Links in a New Tab

### ISSUE THREAD

**Issue by Kolsdam** [taikoxyz/taiko-mono#17180]
### Describe the feature request

Description of the feature request here.
Looking through the [Receive token Guide](https://docs-mxctb0to5-taikoxyz.vercel.app/guides/receive-tokens/) and i wanted to navigate to the Bridge which is an external link but it just opens in that same tab instead of openning in a new tab.

You can fix this by using `target="_blank" rel="noopener noreferrer"` this also prevents tabnabbing
The rel attribute sets the relationship between the current page and the linked URL. Setting it to noopener noreferrer is to prevent a type of phishing known as [tabnabbing](https://en.wikipedia.org/wiki/Tabnabbing).

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by tambora07** [comment]
Good jog is taiko

**Comment by AlfeuAlves** [comment]
Good job is taiko

**Comment by Doclulu38** [comment]
good job

**Comment by RogerLamTd** [comment]
breaks user expectation, closing as not intended
