### ISSUE TITLE
ubnormal slashing failing to prove

### ISSUE THREAD

**Issue by Akh111** [taikoxyz/taiko-mono#17198]
### Describe the bug

tokens are slashing and failing to prove getting error (attached image). if i restart raiko and prover then one time it will prove then start to get the errors. discussed in discord mods requested to rise the issue in hear. 
![Screenshot from 2024-05-08 18-37-55](https://github.com/taikoxyz/simple-taiko-node/assets/83766426/3d3270c2-5eeb-44a2-96ee-77112105a36b)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by YoGhurt111** [comment]
Fixed by https://github.com/taikoxyz/taiko-mono/pull/17268

**Comment by YoGhurt111** [comment]
Thanks for your feedback!
