### ISSUE TITLE
How to solve problem: ERROR Latest filled block is not available

### ISSUE THREAD

**Issue by Darclindy** [taikoxyz/taiko-mono#17263]
### Describe the feature request

My node's block height is 0, and docker's logs show that:
ERROR simple-taiko-node-l2_execution_engine-1    | ERROR[05-08|15:05:27.230] Latest filled block is not available.
I don't kown the cause is from my .env config or my server's config.
please give some suggests!

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by mask-pp** [comment]
`Latest filled block is not available.` this error log is not an issue, just cased by repeat calling `forkchoiceupdate`. And this scene already reduced by this [PR](https://github.com/taikoxyz/taiko-mono/pull/17281).
