### ISSUE TITLE
Failed to clean stale beacon headers     err="filled header below beacon header tail: 45987 < 67388"

### ISSUE THREAD

**Issue by lucajj3** [taikoxyz/taiko-mono#17262]
### Describe the bug

Failed to clean stale beacon headers.

I don't think there is a solution at the moment other than having to rebuild the docker

### Steps to reproduce

1) If node isnt sync and stopped node ( i have editeded .env too), 
2) run node 
you may have this error:
 Beacon backfilling failed                err="syncing canceled (requested)"
 ERROR Failed to clean stale beacon headers     err="filled header below beacon header tail: 45987 < 67392"

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by mask-pp** [comment]
Same with this [issue](https://github.com/taikoxyz/taiko-mono/issues/17263).
