### ISSUE TITLE
RPC didn't work 

### ISSUE THREAD

**Issue by imranmahmudshoiball** [taikoxyz/taiko-mono#17305]
### Describe the bug

RPC didn't work in brave browser wallet.

### Steps to reproduce

Need to compatible RPC for all browser wallet.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by mask-pp** [comment]
Can you show more error messages?
