### ISSUE TITLE
Error when deploying smart contract

### ISSUE THREAD

**Issue by Diddy-bit** [taikoxyz/taiko-mono#17307]
### Describe the bug

When deploying smart contract in mintpad.co for Taiko Hekla blockchain, it is showing as failed transaction in Metamask, but when checking transaction details in https://blockscoutapi.hekla.taiko.xyz/tx/, it's Confirmed.

![mintpad_metamask_error](https://github.com/taikoxyz/taiko-mono/assets/70631203/f52402d4-315a-41e4-929e-d8590ec4e5cd)

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by hernan-gil** [comment]
I can't see the transaction in the explorer. It appears to be down or permanently changed url. Can you please put the trx Id in order to review it?

**Comment by davidtaikocha** [comment]
Whats the hekla RPC endpoint u were using?

**Comment by Diddy-bit** [comment]
https://blockscoutapi.hekla.taiko.xyz/tx/0x335f041ed331c10c2bf7543819bc3664fede79a3f0de1b252dc6f5cdcd6cc146

**Comment by Diddy-bit** [comment]
https://taiko-hekla.blockpi.network/v1/rpc/public
