### ISSUE TITLE
transaction taking to long

### ISSUE THREAD

**Issue by paulo8888** [taikoxyz/taiko-mono#17345]
### Describe the bug

gas fee not substantial for time it takes for transaction to go through during busy hours.

### Steps to reproduce

increase gas fee to speed up transaction time.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
which RPC endpoint are u using?
