### ISSUE TITLE
Steps Appear Incomplete After Register your wallet Process on Trailblazers Website

### ISSUE THREAD

**Issue by ordinaryfok** [taikoxyz/taiko-mono#17353]
### Describe the bug

After completing the 3rd step process on the Trailblazers website, the first and second steps (connecting your Twitter account and completing Pink & Share) still appear as incomplete. Attached is the screenshot.
 
 ![Taikobug](https://github.com/taikoxyz/taiko-mono/assets/145860601/223fd1b1-133d-41bf-8f70-14cfde8b2b51)

### Steps to reproduce

Need to Investigate by a Website Developer

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Panoptikym** [comment]
"
