### ISSUE TITLE
bridge relayer did not pick up a message

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#17466]
### Describe the bug

I sent two messages from L1 to L2, the first one got picked up by the relayer so it shows up in the UI, but the second one did not.

tx1: https://etherscan.io/tx/0x77c61b3dfb0d226181e5a69ff0d611a4bec832b6e08fda691f6765ad25fcf163
tx2: https://etherscan.io/tx/0x12c12ef08bdf7ee87bf6c10fa3cefd32ad132590682dd3ca636badb34907bd08

### Steps to reproduce

The message's to address is `0x08c82ab90f86BF8d98440b96754a67411D656130`, which is not a vault.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by cyberhorsey** [comment]
Will take a look.
