### ISSUE TITLE
High Gas Fees Issues: Write Contract Burn on TaikoScan.

### ISSUE THREAD

**Issue by Kafiirr** [taikoxyz/taiko-mono#17706]
### Describe the bug

I encountered an issue on TaikoScan where performing a Write Contract burn (NFTs) transaction incurs significantly high gas fees compared to other transactions. Ideally, I expected the gas fees to be consistent or similar across different types of transactions.
![Screenshot 2024-06-29 134024](https://github.com/taikoxyz/taiko-mono/assets/124496288/372f7fd2-b631-41ba-930e-1a84f9ae6173)

### Steps to reproduce

1. Open [`TaikoScan`](https://taikoscan.io)
- Find a smart contract that has been verified and supports burning
- Connect wallet > ``Contract`` section > ``Write Contract`` > ``Burn`` > Executing the transaction.

2. Compare the gas cost incurred for a burn transaction with other types of transactions on the platform.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by Panoptikym** [comment]
у мене таке саме

**Comment by davidtaikocha** [comment]
Its just because this execution will be reverted.
