### ISSUE TITLE
Katla still Active on Debank chainlist

### ISSUE THREAD

**Issue by spachib** [taikoxyz/taiko-mono#17761]
### Describe the bug

Katla is still active on Debank repo, https://github.com/DeBankDeFi/chains/blob/ea18ef50394f53afc6819d015f8cb626ec6b30df/_data/chains/eip155-167008.json#L4

This information is used as an authority by various dapps

Need to switch to `active` to `deprecated`

### Steps to reproduce

Steps to reproduce here.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by swarna1101** [comment]
created the PR here: https://github.com/ethereum-lists/chains/pull/5445

**Comment by swarna1101** [comment]
this is fixed and merged to main
