### ISSUE TITLE
Add Token Transfer Functionality to ERC20 Contract

### ISSUE THREAD

**Issue by Rifkichrl** [taikoxyz/taiko-mono#17771]
### Describe the feature request

We aim to introduce a token transfer function into our existing ERC20 contract within this project. This function will enable users to securely transfer tokens between accounts.

Steps
Implement the transfer function in the existing ERC20 contract.
Ensure tests cover various transfer scenarios, including successful and unsuccessful transfers.
Document using NatSpec format to explain usage guidelines and considerations.
Additional Information:

Please refer to the coding standards and documentation guidelines in the project's README before starting implementation.
Feel free to ask any questions or clarifications regarding this issue.

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
spam
