### ISSUE TITLE
add ETH to withdrawToAdmin function

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/taiko-mono#17784]
### Describe the feature request

Hello
I've been testing new proxy functions and sent few ETH along with TAIKO o the proxy address. If I'm not mistaken there is no function to withdraw ETH from contract. would be great to add it
Thanks

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/17800
