### ISSUE TITLE
Separate function as "claimableBondOf"

### ISSUE THREAD

**Issue by StoneMac65** [taikoxyz/taiko-mono#17856]
### Describe the feature request

Correct me if I'm wrong please but as I noticed "bondBalanceOf" function on Taiko L1 contract returns total amount of bonds for that address. Including verified and unverified balance. Would be great to query only claimable balance in separate function

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by X0Jhepz** [comment]
This setup ensures that each address can only claim up to its total balance and keeps track of how much has already been claimed.

**Comment by dantaik** [comment]
The `bondBalanceOf` function returns the currently claimable amount of TAIKO bond for a given address. This balance represents the portion of the bond that the address can withdraw immediately.

The total bond balance for an address can be known by checking all previous `depositBond` function calls.

**Comment by StoneMac65** [comment]
> The `bondBalanceOf` function returns the currently claimable amount of TAIKO bond for a given address. This balance represents the portion of the bond that the address can withdraw immediately.
> 
> The total bond balance for an address can be known by checking all previous `depositBond` function calls.

Noted. Thanks
