### ISSUE TITLE
feat(docs-site): Cookbook Onboard: AI Assistant

### ISSUE THREAD

**Issue by ClockRide** [taikoxyz/taiko-mono#17862]
### Describe the feature request

The AI assistant and co-pilot is trained on all existing Taiko resources (source code, docs website, etc) and is available as a standalone modal, embeddable as a button on any page (recommended for technical docs). It answers developer questions about building projects on Taiko, acting as an enhanced and streamlined technical documentation search tool as well as a Solidity coding co-pilot.

Ask Cookbook AI could also access context from thousands of data sources indexed by Cookbook.dev in addition to Taiko-specific data sources, providing the best blockchain developer-focused answers of any chatbot on the market. Cookbook will assist in the tuning and calibration of the AI assistant to ensure the highest answer quality.

## Preview
https://docsbot-demo-git-taiko-cookbookdev.vercel.app/

![image](https://github.com/user-attachments/assets/c9d4e4af-2f52-41bb-8cdc-73820a9645f5)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by RogerLamTd** [comment]
closing as not intended, after testing the functionality is essentially the same as a simple search and we have no control over updates in the model. Maybe as a developer tool, feel free to open a different issue & PR!
