### ISSUE TITLE
Remove deployments from taiko-mono repo homepage

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#17958]
### Describe the feature request

I would recommend unchecking "deployments". I do not think it is necessary because this is a monorepo, which represents several different deployments. These deployments are also no longer relevant as we do not deploy with the GitHub app integration anymore. See here:

<img width="762" alt="Screenshot 2024-08-20 025155" src="https://github.com/user-attachments/assets/2d5fc0e7-1f87-4783-8b79-08bd38385fd8">

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by d1onys1us** [comment]
cc @dantaik

**Comment by dantaik** [comment]
<img width="637" alt="Screenshot 2024-08-22 at 19 58 08" src="https://github.com/user-attachments/assets/8c2f05db-0dad-42fc-914e-8e869194eb0f">

This is what it is. The Deployment is unchecked.

**Comment by d1onys1us** [comment]
> <img alt="Screenshot 2024-08-22 at 19 58 08" width="637" src="https://private-user-images.githubusercontent.com/99078276/360420044-8c2f05db-0dad-42fc-914e-8e869194eb0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzk4MjAsIm5iZiI6MTcyNDM3OTUyMCwicGF0aCI6Ii85OTA3ODI3Ni8zNjA0MjAwNDQtOGMyZjA1ZGItMGRhZC00MmZjLTkxNGUtOGU4NjkxOTRlYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAyMTg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhM2ZkNTVlMTVmYzk4YWEyNzkzYzg0NmEzNDdlMTA5MmVkMGNjOGVkMWU1ZmI3NDUxYWUyODRkY2M3NzUyN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cW3E3rFPKFsOaMmtXpGuCJxfKEK_yzF4GH5yapFzlSQ">
> This is what it is. The Deployment is unchecked.

that is strange. and you selected "save changes" yeah?

**Comment by d1onys1us** [comment]
Looks like my browser cached it, checked in incognito and LGTM. Thanks!
