### ISSUE TITLE
run gen_bindings.sh fail with error `../protocol/out/TaikoL1.sol/TaikoL1.json: No such file or directory`

### ISSUE THREAD

**Issue by ping-ke** [taikoxyz/taiko-mono#18011]
### Describe the bug

I am a dev, and I am working on updating L1 contracts and taiko-client to try to integrate ethstorage and taiko chain.
I updated the L1 Contracts and want to generate go-binding code, but when I run `./gen_bindings.sh` to generate code, 
I got the error "`../protocol/out/TaikoL1.sol/TaikoL1.json: No such file or directory`". So where can I get/generate the json file?

### Steps to reproduce

steps:
1. `cd taiko-client/scripts`
2. `./gen_bindings.sh`

got this error:
![image](https://github.com/user-attachments/assets/f3ce7998-1cd2-4137-963b-0f4571961efc)

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by davidtaikocha** [comment]
Could you try deleting `protocol/out` dir and then give another try?

**Comment by mask-pp** [comment]
The [github action file](https://github.com/taikoxyz/taiko-mono/blob/main/.github/actions/install-pnpm-dependencies/action.yml) can be used as reference.
