### ISSUE TITLE
taiko-client compile failed on macOS after upgrade macOS to Sequoia(15.0)

### ISSUE THREAD

**Issue by cpucorecore** [taikoxyz/taiko-mono#18168]
### Describe the bug
# env
golang:
```bash
➜  taiko-mono git:(docs-site-v1.12.0) ✗ go version
go version go1.22.7 darwin/amd64
```
os: osx with version Sequoia(15.0)
```bash
➜  taiko-mono git:(docs-site-v1.12.0) ✗ uname -a
Darwin MacBook-Pro.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:30 PDT 2024; root:xnu-11215.1.10~2/RELEASE_X86_64 x86_64
```

➜  taiko-client git:(docs-site-v1.12.0) make build
go: downloading github.com/taikoxyz/taiko-geth v1.5.1-0.20240808041410-882a6cd3294c
go: downloading golang.org/x/term v0.22.0

...

# github.com/supranational/blst/bindings/go
/var/folders/rd/m8gg8hzs66b1ccvvr730799h0000gn/T/cgo_assembly-1b44db.s:1473:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/rd/m8gg8hzs66b1ccvvr730799h0000gn/T/cgo_assembly-1b44db.s:6556:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/rd/m8gg8hzs66b1ccvvr730799h0000gn/T/cgo_assembly-1b44db.s:6674:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/rd/m8gg8hzs66b1ccvvr730799h0000gn/T/cgo_assembly-1b44db.s:6810:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8
^
/var/folders/rd/m8gg8hzs66b1ccvvr730799h0000gn/T/cgo_assembly-1b44db.s:6946:1: error: invalid CFI advance_loc expression
.cfi_adjust_cfa_offset 8

### Steps to reproduce

Steps to reproduce here.

**Comment by davidtaikocha** [comment]
We still need to use `go < 1.23` to compile the project atm.

**Comment by cpucorecore** [comment]
sudo rm -rf /Library/Developer/CommandLineTools

then reinstall CommandLineTools can fix it
