### ISSUE TITLE
In Trailblzer S2, few wallets are getting 1K points on voting for .1 gwei and few are getting 500 points for same or more gwei

### ISSUE THREAD

**Issue by cryptosumit01** [taikoxyz/taiko-mono#18439]
### Describe the bug

See an example profiles 

This wallet getting 1k points whenever he does ruby voting.
https://trailblazers.taiko.xyz/profile/0x31f0953a4470c95a9f1E61c6236Abde17e658eDB 
https://taikoscan.io/tx/0x9cedbc3df7652978ea9984c854823dc67ba7d6fc9a53389be8430a2efcd34235

See below user getting 500 points even using more gwei.
https://trailblazers.taiko.xyz/profile/0x61B1260576840Af6769770E8FCBc025d71573A1A 
https://taikoscan.io/tx/0xb61658a35497399935a179feee0e556b9c24575fc765a3c7df408e1e4e1cd45b

### Steps to reproduce

Steps to reproduce here.

**Comment by bennettyong** [comment]
Fix deployed to account for different transaction types. Now both getting similar points.
