### ISSUE TITLE
Review SC - Trailblazers : 0xa20a8856e00F5ad024a55A663F06DCc419FFc4d5

### ISSUE THREAD

**Issue by quentingosset** [taikoxyz/taiko-mono#18574]
### Describe the bug

Because it seems that nobody on the discord is able to give me the contact of a developer of the smart contract of the Trailblazers season 2.
So, i report here that there is a problem in the smart contract (0xa20a8856e00F5ad024a55A663F06DCc419FFc4d5) a lot of users try to mint S2 badge but the Smart contract revert the transaction.

As the smart contract is not published, can you review and update it?

### Steps to reproduce

We don't know exacctly the pattern but people can't mint and some can mint.

**Comment by KorbinianK** [comment]
Wrong repo. Please keep trailblazer discussions on discord. The issue is being worked at, as stated many times.
