### ISSUE TITLE
feat(protocol): allow a prover to auction for right to prove a block exclusively

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#258]
The idea is to allow a prover to auction for the right to prove a block exclusively with the following exceptions:

- if another prover submits the proof really early, e.g., earily than ½ of avgProofTime, it is still allowed.
- if this current auction winner failed to submit a valid proof before a deadline (1.25 * aveProofTime), then anyone can submit proofs.

The auction shall also be limited to a small window, e.g., ¼ * avgProofTime.

**Comment by dantaik** [comment]
I'm closing the PR and mark this feature as low priority. One reason not to offer this feature is that we need to test our core protocol logics thoroughly before we add more features.

**Comment by d1onys1us** [comment]
is this still a good-first-issue? i don't think so, so i think we should remove the label. cc @cyberhorsey
