### ISSUE TITLE
Update Ethereum org website with Taiko under ZK-Rollup page

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#268]
Let's add our project here https://ethereum.org/en/developers/docs/scaling/zk-rollups/#zkevm-projects

**Comment by d1onys1us** [comment]
https://github.com/ethereum/ethereum-org-website/pull/8607

**Comment by dantaik** [comment]
@d1onys1us it seems your preview PR got closed without merging, could you please try again?

**Comment by d1onys1us** [comment]
> @d1onys1us it seems your preview PR got closed without merging, could you please try again?

yeah, i will add it to this iteration to try again.

**Comment by seunbayo** [comment]
@d1onys1us  can I take this one up?

**Comment by d1onys1us** [comment]
> @d1onys1us  can I take this one up? I am also a contributor on eth website

That would be AWESOME. Actually, I tried before, but got rejected. If you want to make a draft PR there and send me the branch, I'll help give it a peer review before we open it for review by the eth-org maintainers.

I was thinking we can do a little community service to help entice the PR approval. By community service I mean, also cleanup some of the page's ZK-Rollup terms in terms of consistency (capitalization, etc.) and perhaps a few more small things, to make the page more educational.

But yes, all yours! Just ping me for the peer review. This one will help a lot for visibility.

**Comment by seunbayo** [comment]
I think from what I have seen so far from the maintainers (They really don't want your to touch other people's work except if there is a clear error)

So I will push the PR and have them Review (when merged, then we can do the community service after)

**Comment by d1onys1us** [comment]
> I think from what I have seen so far from the maintainers (They really don't want your to touch other people's work except if there is a clear error)
> 
> 
> 
> So I will push the PR and have them Review (when merged, then we can do the community service after)

Okay, thank you. But still send along the draft PR, if you don't mind, so I can give the document a review. Because we did try to open a PR twice there already.

**Comment by d1onys1us** [comment]
merged into ethereum-org zk rollups page 🚀
