### ISSUE TITLE
feat(docs): add documentation on how to generate a private key

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/taiko-mono#2730]
### Describe the feature request

There are a lot of questions about how to generate a private key for this documentation: https://taiko.xyz/docs/alpha-1-testnet/deploy-a-contract#steps

Let's add some steps on how to do it. There are two decent ways to do this, I would highly suggest to use a dummy account and not the private key of an account that has any real funds. 

You can create a dummy account keypair manually with openssl (something like this https://gist.github.com/miguelmota/3793b160992b4ea0b616497b8e5aee2f) , or you can just create an account with metamask and export the private key. 

We should keep in mind that not everyone has metamask. Perhaps we can even suggest usage of a useless private key if they don't care about the contract deployer (however doing this means that address will not show up when we scan the network for the POAP). 

### Describe alternatives you've considered

None

### Additional context

None

**Comment by dantaik** [comment]
Can we simple add a few links to third party tutorials regarding how to create Ethereum private keys/accounts, such as this one https://piyopiyo.medium.com/how-to-generate-ethereum-private-key-and-address-in-local-offline-environment-90294308593c

**Comment by SqpuHkS** [comment]
**Tutorial for extracting private key from seed phrase**
