### ISSUE TITLE
bug(bridge-ui): Max features not working properly

### ISSUE THREAD

**Issue by jcbm123143** [taikoxyz/taiko-mono#2743]
### Describe the bug

Max features not working

### Steps to reproduce

1) Go to https://bridge.a1.taiko.xyz/
2) Bridge ETH A1 to TAIKO A1
3) Click Max Features

Max features not working

![image](https://user-images.githubusercontent.com/22148449/210022370-fa79a166-ab13-4038-9cde-43039febc99c.png)

### Additional context

Wallet used for testnet
0x5D9D12C6D996cce9B6B4AaDD8D3d4F81B0465e8d

**Comment by d1onys1us** [comment]
cc @shadab-taiko

**Comment by dantaik** [comment]
We can also make sure the max value only displays 4 digits after "."
