### ISSUE TITLE
feat(bridge-ui): add copy popup message

### ISSUE THREAD

**Issue by jcbm123143** [taikoxyz/taiko-mono#2757]
### Describe the feature request

Copy Address - popup message "COPIED"

### Describe alternatives you've considered

A popup message should be placed so that the user can immediately see that they have copied their wallet address

![image](https://user-images.githubusercontent.com/22148449/210023191-6ada4c78-3bec-4028-852c-2b83b9ecae0b.png)

**Comment by WormydogDOTeth** [comment]
Do you want to use the existing success message 

ie: 
<img width="876" alt="Screen Shot 2023-01-01 at 11 26 20 PM" src="https://user-images.githubusercontent.com/120331945/210195073-59721d04-8050-446a-b416-0542d843e950.png">

**Comment by shadab-taiko** [comment]
Addressed in #7076
