### ISSUE TITLE
# Friction log

### ISSUE THREAD

**Issue by seijin88** [taikoxyz/taiko-mono#2924]
# Friction log
- dont see any bugs on bridging from ETH A-1 to taiko A-1
- i like simple UI its much more efficient

# there is no other notes
https://l1explorer.a1.taiko.xyz/tx/0x904796db19754bc496bda23474bfacb7e53cbb87bfe2b6a0f4ec7b913e5e19bb

_Originally posted by @seijin88 in https://github.com/taikoxyz/taiko-mono/discussions/2923_

**Comment by dantaik** [comment]
What are we talking about here?

**Comment by shadab-taiko** [comment]
Closing this since there's no actionable issue here.
