### ISSUE TITLE
feat(bridge): Add Failed state for Bridge and `releaseTokens` method on TokenVault

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#355]
If invokeMessageCall fails, we should add a new state, `FAILED`, for the message on the destination chain bridge. And then we should add a `releaseTokens` method on the TokenVault for source chain which takes a merkle proof of the `releaseTokens` on the destination chain that the signal has message status = `3` (aka: `FAILED`).

**Comment by dantaik** [comment]
FAILED status was added in PR https://github.com/taikoxyz/taiko-mono/pull/356 but the releaseTokens is not part of it.

**Comment by dantaik** [comment]
After this is done, we should create an feature request issue for @shadab-taiko .

**Comment by dantaik** [comment]
https://github.com/taikoxyz/taiko-mono/pull/13004 is another step before releaseToken can be implemented.
