### ISSUE TITLE
chore(protocol): replace Uint512.sol with a MIT licensed library

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#359]
### Describe the feature request

We want all our code to be MIT-licensed, but we have this [Uint512.sol](https://github.com/taikoxyz/taiko-mono/blob/main/packages/protocol/contracts/thirdparty/LibUint512.sol) under GPL license. It will be great if someone can reimplement this library under MIT. 

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
https://github.com/taikoxyz/taiko-mono/pull/341 

I have already refactored this library in above PR
