### ISSUE TITLE
docs(protocol): remove internal variables and functions'

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#401]
### Describe the feature request

In the current smart contract documentation, for example https://taiko.xyz/docs/reference/smart-contracts/L2/TaikoL2, we need to remove private and internal state variables and functions:

- `__gap`
- `_checkPublicInputs `
- `_hashPublicInputs `

**Comment by 1xDeFi** [comment]
I tried to remove it from some of the pages. 
If I'm doing it right, let me know to fix the rest of the pages. 

https://github.com/taikoxyz/taiko-mono/pull/419
https://github.com/taikoxyz/taiko-mono/pull/418
https://github.com/taikoxyz/taiko-mono/pull/417
https://github.com/taikoxyz/taiko-mono/pull/416
https://github.com/taikoxyz/taiko-mono/pull/415

**Comment by d1onys1us** [comment]
> I tried to remove it from some of the pages. If I'm doing it right, let me know to fix the rest of the pages.
> 
> #419 #418 #417 #416 #415

left a comment on one of them

**Comment by dantaik** [comment]
When we change the source code, these docs will be auto-generated again, then we need to manually remove these internal vars again, don't we? @d1onys1us

**Comment by d1onys1us** [comment]
> When we change the source code, these docs will be auto-generated again, then we need to manually remove these internal vars again, don't we? @d1onys1us

yes, that's right. there is a way we can actually fix this. i will give it a shot today.

**Comment by d1onys1us** [comment]
> > When we change the source code, these docs will be auto-generated again, then we need to manually remove these internal vars again, don't we? @d1onys1us
> 
> yes, that's right. there is a way we can actually fix this. i will give it a shot today.

now this is done here: https://github.com/taikoxyz/taiko-mono/pull/490
