### ISSUE TITLE
feat(protocol): expose delay for block verification with view function

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#421]
### Describe the feature request

Description of the feature request here.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Not sure what exactly you want to expose, but happy to take a look at your PR, @cyberhorsey .

**Comment by cyberhorsey** [comment]
This is something to allow bridge UI to say "Taiko L2 => L1 transaction can be expected in roughly {time}", by exposing the avgProofDelay for a block.
