### ISSUE TITLE
feat(bridge-ui): display delay for L2 to L1 bridge processing to user, check headersync event before showing claim button

### ISSUE THREAD

**Issue by cyberhorsey** [taikoxyz/taiko-mono#423]
### Describe the feature request

Description of the feature request here.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by Fher01** [comment]
I am not a tech guy but I am trying to learn as much as possible. Congratulations to the team. You are doing a great job. Keep building I'll help to the project in any possible way That I can.

**Comment by davidtaikocha** [comment]
https://github.com/taikoxyz/taiko-mono/issues/189 🤔
