### ISSUE TITLE
feat(bridge-ui): allow ERC20 and Ether to be transferred in one message/transaction.

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#433]
### Describe the feature request

The bridge contracts support such a feature, it will be cool that users can do this to reduce cost. A similar feature may also be possible for NFTs.

This feature is a low priority.

**Comment by 1xDeFi** [comment]
You mean users can bridge multiple token/NFT in one transaction? 

In this case, we can add a simple + button next to the token that we wish to transfer, and when the user clicks on it, another row is added.

These are the swap samples that can be changed for the bridge. 

Single

![123](https://user-images.githubusercontent.com/90858998/207895007-4b64f9d2-bacc-4d0d-b238-42aa55a97f64.png)

Multi 

![43](https://user-images.githubusercontent.com/90858998/207895196-69b05989-be80-420c-863b-af17b547d8ff.png)

**Comment by dantaik** [comment]
Not really. You can bridge some Ether alone with another ERC20 or NFT. But you cannot bridge more than one ERC20 or NFT in one transaction. Ether is special.

**Comment by dantaik** [comment]
I review the code of EtherVault and ERC20Vault, it seems that the contracts don't support such a feature yet -- EtherVault and ERC20Vault needs to merge into one Vault to achieve my goal of *bridge multiple assets via one tx*. Lets demote this feature.

**Comment by 1xDeFi** [comment]
Is it possible to bridge multi-tokens by swapping them into a stablecoin, then bridging them, and swapping back into the multi-tokens on destination chain?

**Comment by dantaik** [comment]
The default bridge from Taiko shall be as simple as possible not to compete with third party bridges who may offer such features.

**Comment by dantaik** [comment]
I'm closing this issue for now, please feel free to reopen if you hope to continue the conversation.
