### ISSUE TITLE
Feat(Bridge UI): a better layout to show claimable claimed cross-chain transactions

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#434]
### Describe the feature request

The current bridge UI, as many other third-party bridge UIs, are high inspired by Uniswap. 

<img width="1542" alt="Screenshot 2022-12-14 at 14 29 55" src="https://user-images.githubusercontent.com/99078276/207523177-8445d3c3-0e31-44e6-a07d-dab8afaccd38.png">

However, there is a big difference between the UX of Uniswap and our Bridge. Each Uniswap user action is atomic -- a swap will either succeed or fail. Users don't need to see previous swap history on Uniswap as there is no actionable interactions for failed or succeeded swaps.

Bridge UX is different, it has two parts, the send-over part (on the source chain) and the claiming part (on the dest chain). For failed claims, users can try (multiple times) claiming if it keeps failing.  Therefore **being able to see unclaimed/claimable messages is very essential part of the UI**, we should not hide these claimable messages in the drop down, we should make it more explicit.  My idea is to have two tables/lists: one for the claimable items, one for recent claimed items, as show below:

<img width="847" alt="Screenshot 2022-12-14 at 14 42 34" src="https://user-images.githubusercontent.com/99078276/207524966-aab22c90-6a81-4d47-a0e7-fd07da36ed99.png">

In the claimed items, we should at least include the URL to the actual claiming transaction. Users will really care about how their funds are received on the destination chain.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by 1xDeFi** [comment]
For mobile can be something like this: 
![Bridge UI - Mobile](https://user-images.githubusercontent.com/90858998/207890773-d8cafe4b-89a1-4680-8bf1-5ee682b4897f.png)

**Comment by shadab-taiko** [comment]
Taken care of in https://github.com/taikoxyz/taiko-mono/pull/411 with the form and transactions in separate tabs.
