### ISSUE TITLE
feat(bridge UI): improve the input field on firefox

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#449]
### Describe the feature request

Firefox displays an input stepper that doesn't match te page in my opinion
Firefox: ![image](https://user-images.githubusercontent.com/60930264/208173200-486c6c48-9d2f-4cfe-a6f0-b2bfec93282b.png)
Chrome:![image](https://user-images.githubusercontent.com/60930264/208173285-6e7af452-2455-4f8e-9226-a6161b4a41aa.png)

So maybe getting rid of the stepper is the best apprach, since it's not really useful 

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
cc @shadab-taiko

**Comment by dantaik** [comment]
Shadab, please check out these links

- https://stackoverflow.com/questions/23372903/hide-up-down-arrow-buttons-spinner-in-input-number-firefox-29
- https://stackoverflow.com/questions/33749896/hide-html5-input-type-number-arrow-with-a-css-class

**Comment by shadab-taiko** [comment]
> Shadab, please check out these links
> 
> * https://stackoverflow.com/questions/23372903/hide-up-down-arrow-buttons-spinner-in-input-number-firefox-29
> * https://stackoverflow.com/questions/33749896/hide-html5-input-type-number-arrow-with-a-css-class

@dantaik its already fixed in #6248 . Will close this issue once that PR is merged.
