### ISSUE TITLE
test(bridge): change integration test from fixture() pattern to before/beforeEach blocks

### ISSUE THREAD

**Issue by RogerLamTd** [taikoxyz/taiko-mono#452]
Why?

**Comment by cyberhorsey** [comment]
@dantaik think you added "Why?" comment by editing Roger.

This is something @davidtaikocha requested.

**Comment by davidtaikocha** [comment]
yah, to remove some duplicated trivial code. i think this issue can be closed now since its already merged?

**Comment by dantaik** [comment]
I'm not sure we should remove fixture, I quite like it :)

**Comment by RogerLamTd** [comment]
> I'm not sure we should remove fixture, I quite like it :)

We can leave the integration test as is then? Most of the unit test files have already been altered
