### ISSUE TITLE
[Bug] Bridge form doesn't enable button after wallet connection

### ISSUE THREAD

**Issue by leppaludi** [taikoxyz/taiko-mono#470]
### Describe the bug

If you first type in an amount and then connect wallet, the "Bridge" button isn't enabled unless you type in a new amount.

### Steps to reproduce

1) Open https://bridge.a1.taiko.xyz/
2) Type in ETH amount 0.1
3) Connect wallet
4) Button will be disabled
5) Append a "0" after 0.1
6) The button will be enabled

**Comment by cyberhorsey** [comment]
This has been fixed :)
