### ISSUE TITLE
fix(bridge-ui): History tx in the web not show up

### ISSUE THREAD

**Issue by mdhs01** [taikoxyz/taiko-mono#4772]
### Describe the bug

Trying to bridge $HORSE Ethereum A1 to Taiko A1, Notification for this tx was succesfull but i cant see history tx in the web.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
Could you please provide your bridge transaction hash?

**Comment by dantaik** [comment]
I believe we have an issue for this - loading data from relayer.

**Comment by cyberhorsey** [comment]
This has been resolved.
