### ISSUE TITLE
fix(bridge-ui): bridge error, transaction still pending

### ISSUE THREAD

**Issue by Azis94** [taikoxyz/taiko-mono#546]
### Describe the bug

My bridge from taiko to A1 ethereum is still pending from yesterday, but my eth its already in my A1 eth I don't know how to explain but yesterday im try to bridge 5 eth from taiko to A1 eth and that's it's happen you can see in my pic
![Screenshot_2022-12-28-03-34-23-653_com kiwibrowser browser](https://user-images.githubusercontent.com/74254937/209714867-bbc5e090-c819-4529-a6eb-102c3e961ac5.jpg)
![Screenshot_2022-12-28-03-34-47-931_com kiwibrowser browser](https://user-images.githubusercontent.com/74254937/209714876-9c841c93-158d-4904-b6d6-3b136fc66d30.jpg)
![Screenshot_2022-12-28-03-40-50-636_com kiwibrowser browser](https://user-images.githubusercontent.com/74254937/209714993-81253493-f27c-447e-b646-06fcab8d758e.jpg)
https://l2explorer.a1.taiko.xyz/tx/0xfceed506f97a3636487710e277905be83f15bf3908bda972280d8186c91ef4da

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
For this kind of bug reports, we really need the bridge transaction hash!

**Comment by Azis94** [comment]
> verify

https://l2explorer.a1.taiko.xyz/tx/0xfceed506f97a3636487710e277905be83f15bf3908bda972280d8186c91ef4da 
This my tx sir

**Comment by davidtaikocha** [comment]
> > verify
> 
> https://l2explorer.a1.taiko.xyz/tx/0xfceed506f97a3636487710e277905be83f15bf3908bda972280d8186c91ef4da This my tx sir

We can't find this transaction (at least with a pending status) in the block explorer, looks like ur local metamask didn't managed to send the transaction to the node through RPC successfully?

**Comment by Azis94** [comment]
How i can send you video from this becouse i don't understand how to explain? 
This error tx make my another bridge still pending thats is big problem for me

**Comment by Azis94** [comment]
![Uploading Screenshot_2023-01-03-13-15-24-207_com.kiwibrowser.browser.jpg…]()

**Comment by Azis94** [comment]
![Screenshot_2023-01-03-13-15-24-207_com kiwibrowser browser](https://user-images.githubusercontent.com/74254937/210303752-2328c113-1c62-403b-8264-e6208c15c5aa.jpg)

**Comment by davidtaikocha** [comment]
after looking at ur screenshot, maybe this is what u actually need :) https://medium.com/kogecoin/how-to-unstick-stuck-transactions-in-metamask-b23228a0a429#:~:text=Click%20on%20the%20Advanced%20section,Phew!
