### ISSUE TITLE
feat(bridge-ui): rework HORSE faucet

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#634]
### Describe the feature request

It's currently not user friendly to request HORSE. 
I'd suggest changing the icon so it looks less like a filter, changing the button text to 'Request HORSE' and align the button left.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

![Bridge Image](https://user-images.githubusercontent.com/60930264/209726045-7af551d7-e8b4-4c48-8a4c-2e0501d7cc1f.png)

**Comment by d1onys1us** [comment]
cc @shadab-taiko

**Comment by dantaik** [comment]
I actually prefer the current layout TBH.

**Comment by shadab-taiko** [comment]
I too prefer the current layout. Will check if there are icons that look more relevant. Closing this issue.
