### ISSUE TITLE
feat(docs): add dev documentation on Taiko specific APIs

### ISSUE THREAD

**Issue by Brechtpd** [taikoxyz/taiko-mono#6996]
### Describe the feature request

Taiko exposes some important data in its L1 (L2 block hashes, block status,...) and L2 (L2 block hashes,...) smart contracts. Document these so developers know how to use them.

Also document how to use these to build bridges.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
I don't think there are much to be added besides the comments in [this PR](https://github.com/taikoxyz/taiko-mono/pull/13137).
