### ISSUE TITLE
fix(bridge-ui): bunch of notifications pop-up

### ISSUE THREAD

**Issue by 6aBoBHa** [taikoxyz/taiko-mono#7029]
### Describe the bug

on the bridge site, when i use "claim" (just one time i click on it and approve) - a bunch of notifications pop-up, is it normal?
![image](https://user-images.githubusercontent.com/117993204/210386376-4409d1b4-37d0-4ecb-a069-896496c084fb.png)

### Steps to reproduce

use 'claim' button on the transactions tab

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
cc @shadab-taiko
