### ISSUE TITLE
feat: split Signal service as an independent contract from Bridge

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#7558]
### Describe the feature request

Shall we extract an  `ISignal` contract from the Bridge contract so third-party bridges can use it easily without understanding our Bridge at all? 

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by dantaik** [comment]
@davidtaikocha @cyberhorsey @RogerLamTd please join the discussion.

**Comment by davidtaikocha** [comment]
agreed, to implement their own bridges, what developers only need to care about is this cross chain signal's interface.
