### ISSUE TITLE
Some issues have been on the way

### ISSUE THREAD

**Issue by QustomQure** [taikoxyz/taiko-mono#7591]
### Discussed in https://github.com/orgs/taikoxyz/discussions/7590

<div type='discussions-op-text'>

<sup>Originally posted by **QustomQure** January  4, 2023</sup>
# Friction log
- Some transactions(specifically bridge from L2 to L1) missing in action and forever pending. And their links to txn explorer leading to: 
      "Sorry, We are unable to locate this transaction Hash" screen.
https://l2explorer.a1.taiko.xyz/tx/0x496da155553fd19ce8a0c88f8f76cc1e0383baa9c347ca92f7740232172fc9b0
https://l2explorer.a1.taiko.xyz/tx/0xce9e58312d6675b6247ca4ec14364ff5560570f0e78cd7a368071ae3e3e09274
https://l2explorer.a1.taiko.xyz/tx/0xe0973049fb7b42f374dcdb2a6051f9ba116dd0875ae2cac0b7c9c3daa90121f3
https://l2explorer.a1.taiko.xyz/tx/0x80a3422593c5fd841e447868a9bb9ce5351dc877042f0517e7d8e671edf47085
![2023-01-04_08-40-59](https://user-images.githubusercontent.com/43998465/210491518-90b2d0fc-93ba-4fc7-a987-10e52e1f6951.png)
- I have issues with claiming HORSE on L2 Taiko A1
- I can't just disconnect wallet from app, it stays connected

# Other notes
- You should definitely show which one transactions is in the pending list. Now it is not clear</div>

**Comment by QustomQure** [comment]
0x28f7052caaC00a4491D2422d5449ac897110165c wallet
And i have another wallet where i do not have this issues. This is looking suspicious for me... 
![2023-01-04_08-55-38](https://user-images.githubusercontent.com/43998465/210493021-98ec2837-4527-4a9c-a1d4-13c893bad2ab.png)

0xb8BEB983FCd14929668235e0CB252e1FB4216507 Second wallet

**Comment by 0xShard** [comment]
I have not experienced this problem

**Comment by cyberhorsey** [comment]
This is a Metamask issue. You need to go to settings and can click Reset Account to wipe your Queued transactions.
