### ISSUE TITLE
fix: The two bridge tabs should have the same width 

### ISSUE THREAD

**Issue by dantaik** [taikoxyz/taiko-mono#7730]
### Describe the bug

When there is no transaction, the outer line (light grey) shall have the same width as the other tab's.

<img width="332" alt="Screenshot 2023-01-03 at 12 01 21" src="https://user-images.githubusercontent.com/99078276/210521524-ac25b25e-c94a-4c91-bea2-4b97ba704891.png">

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by AzatSaaryan** [comment]
that's how it should be

**Comment by stomik95** [comment]
> that's how it should be

maybe
