### ISSUE TITLE
fix(bridge-ui): .default.env are empty

### ISSUE THREAD

**Issue by wolfderechter** [taikoxyz/taiko-mono#8198]
### Describe the bug

The .default.env file variables are empty and result in a failure to run the svelte app luckily someone on discord posted an example.

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
@shadab-taiko i don't think any of our .env values are confidential. so we can just paste it. let's follow the same convention at simple-taiko-node: https://github.com/taikoxyz/simple-taiko-node/blob/main/.env.sample

we can use these values, they are public:
```
VITE_NODE_ENV=dev
VITE_L1_RPC_URL="https://l1rpc.a1.taiko.xyz/"
VITE_L2_RPC_URL="https://l2rpc.a1.taiko.xyz/"
VITE_RELAYER_URL="http://localhost:4102/"
VITE_TEST_ERC20_ADDRESS_MAINNET="0x3E3a3416DbCc5cb4448B6b171fF15f9Da35Ab72d"
VITE_MAINNET_CHAIN_ID=31338
VITE_TAIKO_CHAIN_ID=167003
VITE_MAINNET_CHAIN_NAME="Ethereum A1"
VITE_TAIKO_CHAIN_NAME="Taiko A1"
VITE_TAIKO_TOKEN_VAULT_ADDRESS="0x0000777700000000000000000000000000000002"
VITE_MAINNET_TOKEN_VAULT_ADDRESS="0xD0dfd5baCf160B97C8eE3ecb463F18c08673160c"
VITE_TAIKO_HEADER_SYNC_ADDRESS="0x0000777700000000000000000000000000000001"
VITE_MAINNET_HEADER_SYNC_ADDRESS="0x7B3AF414448ba906f02a1CA307C56c4ADFF27ce7"
VITE_MAINNET_BRIDGE_ADDRESS="0x3612E284D763f42f5E4CB72B1602b23DAEC3cA60"
VITE_TAIKO_BRIDGE_ADDRESS="0x0000777700000000000000000000000000000004"
```

**Comment by shadab-taiko** [comment]
@d1onys1us right now all the values are public so we don't have any issues but ideally it would be better to set it up in a way that we can also have confidential values. For now we can move forward with mentioning these in the default.env file as in the mentioned PR.

Another issue we might have though is that these values do keep on changing so I am wondering whether it would be better to add a page in the docs for this and we link to it from bridge-ui README?

**Comment by cyberhorsey** [comment]
@shadab-taiko as this is a frontend repo it is highly likely to ever contain confidential values as those values could be extracted from the web app in the console regardless of how confidentially we insert them. Anything confidential would be done through a backend service, so the .default.env should be fine as a permanent solution.

Going forward perhaps .default.snaefaelssjokul.env and .default.mainnet.env, etc, might be a good idea?

**Comment by shadab-taiko** [comment]
@cyberhorsey I was speaking in terms of a general practice to be applied to this, other and future repositories for handling environment variables.

**Comment by shadab-taiko** [comment]
+1 on adding comments to .default.env.

**Comment by shadab-taiko** [comment]
Created an issue to track adding comments https://github.com/taikoxyz/taiko-mono/issues/12391. Closing this now.
