### ISSUE TITLE
fix(bridge-ui): make sure wallet connection persists on page reloads

### ISSUE THREAD

**Issue by Nurzhas1** [taikoxyz/taiko-mono#839]
### Describe the feature request

A wallet connection is required whenever the bridge page is reloaded.
Keeping a connected wallet would be more user friendly-friendly.

### Describe alternatives you've considered

Description of the alternatives you've considered here.

### Additional context

Additional context here.

**Comment by d1onys1us** [comment]
cc @shadab-taiko . feel free to self-assign and close.

**Comment by Nurzhas1** [comment]
@d1onys1us Does the issue I created qualify for the poap?

**Comment by dantaik** [comment]
We should persist the connection.

**Comment by WormydogDOTeth** [comment]
> We should persist the connection.

When you say persist the connection, can you clarify what data we would persist
