### ISSUE TITLE
Bug with claiming

### ISSUE THREAD

**Issue by Kraken133** [taikoxyz/taiko-mono#8978]
### Describe the bug

The transaction window shows that I can claim, but nothing happens when I click. Only transactions are added to the queue

<img width="691" alt="Снимок экрана 2023-01-05 в 14 12 25" src="https://user-images.githubusercontent.com/102407107/210778349-ee21ccda-e0c7-45e0-948c-50e61ec484eb.png">

<img width="346" alt="Снимок экрана 2023-01-05 в 14 12 36" src="https://user-images.githubusercontent.com/102407107/210778353-2b500ef7-41cf-42f5-8dad-d0624174b0c3.png">

After a while, I managed to claim

### Steps to reproduce

Steps to reproduce here.

### Additional context

Additional context here.

**Comment by cyberhorsey** [comment]
Network was slow this day because of larger than expected transaction count. Issue is resolved now!
