### ISSUE TITLE
[Protocol] Bench statistics of ECDSA circuit.

### ISSUE THREAD

**Issue by smtmfft** [taikoxyz/taiko-mono#90]
The benchmark stat of the current open src ECDSA lib is:
prover generation: 29.5s
verification time: ~60ms
memory usage: ~7.5G

As the proof generation could be parallelized, if we can optimize it to maybe <15s and have an aggregation circuit to collect tens of TXs in maybe ~30s. We could use sig proof to protect the MEV of our L2. So that our protocol design could be better, and our assumption #84 might change accordingly.

Let's tracking future data here.

**Comment by dantaik** [comment]
is 29.5s per tx?

**Comment by d1onys1us** [comment]
closing as stale, please re-open if needed
