### ISSUE TITLE
Ability to change the color scheme of the interfacefeat: INSERT_DESCRIPTIVE_TITLE

### ISSUE THREAD

**Issue by Osmorad** [taikoxyz/taiko-mono#9147]
### Describe the feature request

I use Google Chrome on Windows 10, I have the problem that the interface of the site (bridge) is very dark, I can not see the letters!

I propose to add a change in the appearance of the interface to (light and dark)

### Describe alternatives you've considered

An alternative solution if you change the color of the letters on the site (the bridge) to white

### Additional context

![image](https://user-images.githubusercontent.com/81820551/210801725-276df033-2253-4c1c-a024-4d0c5a08d536.png)

I attached a screenshot, where I indicated (with a red stripe) the place where the letters are not visible

**Comment by shadab-taiko** [comment]
Thanks @Osmorad for pointing this out. Would you be able to share if you have any chrome extension installed which might be interfering with the styles?

**Comment by Osmorad** [comment]
> Thanks @Osmorad for pointing this out. Would you be able to share if you have any chrome extension installed which might be interfering with the styles?

![image](https://user-images.githubusercontent.com/81820551/211139754-536474b4-5fb7-4825-a7e4-c565f47c30d5.png)
I only have these extensions installed

Another question, why I could not claim 2023 Taiko Contributor GitPOAP?

**Comment by shadab-taiko** [comment]
@Osmorad Thanks for sharing this. Will push a fix soon which should solve these issues.

Regarding the POAP, I don't have any information on that. Maybe @d1onys1us can help answer this.

**Comment by d1onys1us** [comment]
> > Thanks @Osmorad for pointing this out. Would you be able to share if you have any chrome extension installed which might be interfering with the styles?
> 
> ![image](https://user-images.githubusercontent.com/81820551/211139754-536474b4-5fb7-4825-a7e4-c565f47c30d5.png) I only have these extensions installed
> 
> Another question, why I could not claim 2023 Taiko Contributor GitPOAP?

hello @Osmorad , in order to receive a 2023 Taiko Contributor GitPOAP, please refer to [CONTRIBUTING.md#claim-a-taiko-contributor-gitpoap](https://github.com/taikoxyz/taiko-mono/blob/main/CONTRIBUTING.md#claim-a-taiko-contributor-gitpoap)
